### ISSUE TITLE
Error when concat int and string

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-lang#17797] opened 2019-08-15 12:43 UTC
**Description:**
This is what I want to print: (1)
code: `"("+(i+1)+") "`

Error: 
`error: .::main.bal:79:25: operator '+' not defined for 'string' and 'int'`

**Affected Versions:**
1.0.0-alpha

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by rdhananjaya** [comment] 2019-08-15 14:16
Ballerina does not provide automatic conversion between int and string.
We need to use toString() method to achieve the int to string conversion.

**Comment by gigara** [comment] 2019-08-16 04:44
toString() method is not working for my scenario.
```
//not working
int j = 0;
io:println("No" + (j+1).toString());
```
This gives the following error
`error: .::main.bal:10:22: invalid token '.'`

```
//not working
int j = 0;
io:println("No" + (j+1));
```
`error: .::main.bal:10:12: operator '+' not defined for 'string' and 'int'
`

But it works here.
```
//this works
int j = 0;
io:println("No" + j.toString());
```

**Comment by Shan1024** [comment] 2019-08-29 03:37
Invoking a method on braced expression is not supported in Ballerina yet. That is why `(j + 1).toString()` not working.

So as you have done in the last example, the value should be assigned to a variable, then should call the `.toString()` method.

Example code to achieve your requirements - 

```ballerina
int j = i + 1;
io:println("("+ j.toString() + ") ");
```

**Comment by MaryamZi** [comment] 2019-10-12 10:16
Closing since the original issue is not a bug, and the improvement to support invocations on braced expressions is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/18298.

**Closed by MaryamZi** 2019-10-12 10:16 UTC
Labels: Area/Language, BetaTesting, Resolution/Not a bug
