### ISSUE TITLE
High CPU usage takes place when invoking Java interop function

### ISSUE THREAD

**Issue by MadhurangaWije** [ballerina-platform/ballerina-lang#29221] opened 2021-03-15 16:58 UTC
**Description:**
When creating an application with ballerina GitHub connector's webhook, the application fails to run in an environment with 1GB memory and 1CPU.

**Steps to reproduce:**
Tested by running a sample application in a ballerina docker image(`kanishkaw/application-env-ballerina:swan-lake-alpha2`) limiting to 1024MB memory and 1CPU, and it failed. The corresponding remote functions do not get executed, and in the GitHub dashboard, it shows as a timeout error. The application gets hangup, none of the other functions are working and the server doesn't even respond to normal requests. But when the same application run with 1024MB and 2CPU, it worked.

Therefore it seems, high CPU usage takes place when invoking the Java interop function inside the GitHub connector.

**Affected Versions:**
Ballerina Swan Lake Alpha2

**OS, DB, other environment details and versions:**
Ballerina Swan Lake Alpha2 - patched with ballerina websub module changes

GitHub Connector Code: https://github.com/MadhurangaWije/module-ballerinax-github/tree/feature/websub-alpha2

Sample service used for testing: https://github.com/MadhurangaWije/github-con-test

**Comment by warunalakshitha** [comment] 2021-08-30 12:26
There is no much information for conclude that above issue is causing due to java interops. By design, we just call the interop java function during codegen. 

Can you please provide more information like structure of the java interop function and also whether this is reproducible with latest ballerina swan lake versions.

**Comment by warunalakshitha** [comment] 2021-09-01 04:57
As per the offline chat with @MadhurangaWije this issue was not reproducible with latest connector code and seems to be fixed. I am closing this issue. Please reopen if you have further queries on this.

**Closed by warunalakshitha** 2021-09-01 04:57 UTC
Labels: Type/Bug, Team/jBallerina, Points/2
