### ISSUE TITLE
Showing an error with `$missingNode$_0` when using multiple mapping match patterns

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#29854] opened 2021-04-06 06:23 UTC
**Description:**
$title

**Steps to reproduce:**

```ballerina
function func() {
    any|error v = {x1: 1, b: true};

    match v {
        {x1:1, b: true} | {x1} => {
            
        }
    }
}
```

This gives 
```
ERROR [two.bal:(5:30,5:30)] missing colon token
ERROR [two.bal:(5:30,5:30)] missing identifier
ERROR [two.bal:(5:30,5:30)] variable '$missingNode$_0' should be declared as constant
error: compilation contains errors
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdulmina** [comment] 2021-04-06 06:32
@lochana-chathura this is a known issue right?. Do we have an issue for that?

**Comment by lochana-chathura** [comment] 2021-04-06 06:35
Duplicate of #29168

**Closed by lochana-chathura** 2021-04-06 06:35 UTC
Labels: Area/Parser, Priority/Blocker, Team/CompilerFE, Type/Bug
