### ISSUE TITLE
Using transactional expr inside xml-template-expr crashes the compiler

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#33078] opened 2021-10-05 15:05 UTC
Consider the following code

```
public function main() {
    xml z = xml `<A>${xml `<B>${transactional}</B>`}</A>`;
}
```

Compiling the above code, gives the following exception

```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.getInternalTransactionModuleInvokableSymbol(TransactionDesugar.java:669)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7412)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTransactionalExpr.accept(BLangTransactionalExpr.java:38)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8160)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7061)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:72)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8160)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8200)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6383)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6327)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:117)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8160)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7196)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLTextLiteral.accept(BLangXMLTextLiteral.java:52)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8160)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8200)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7158)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLElementLiteral.accept(BLangXMLElementLiteral.java:111)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8160)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8200)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7158)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangXMLElementLiteral.accept(BLangXMLElementLiteral.java:111)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8160)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1392)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8135)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1524)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8135)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8176)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8186)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1287)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8135)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1332)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8135)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8193)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:808)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8135)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:455)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:234)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:412)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:345)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:183)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:53)
```

**Comment by MaryamZi** [comment] 2022-03-03 03:39
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/33087

**Closed by MaryamZi** 2022-03-03 03:39 UTC
Labels: Type/Bug, Status/Duplicate, Team/CompilerFE, Area/Desugar, Lang/Transactions, Crash, Lang/Expressions/XmlTemplate, Reason/Other
