### ISSUE TITLE
Runtime exception: java.lang.NoClassDefFoundError: ballerina/test/0/$configurationMapper

### ISSUE THREAD

**Issue by janihur** [ballerina-platform/ballerina-lang#34949] opened 2022-02-04 12:37 UTC
**Description:**

I ported a smallish code base from Swan Lake Beta 4 to Swan Lake 2201.0.0. The code can be found from https://bitbucket.org/janihur/advent-of-code/src/master/ballerina/aoc21/

The code crashes run-time with exception:

```
java.lang.NoClassDefFoundError: ballerina/test/0/$configurationMapper
```

**Steps to reproduce:**

Clone repo: https://bitbucket.org/janihur/advent-of-code/src/master/

```
$ cd ballerina/aoc21
aoc21$ bal --version
Ballerina 2201.0.0 (Swan Lake)
Language specification 2022R1
Update Tool 1.3.9

$ bal clean
Successfully deleted '/media/sf_src/other/advent-of-code/ballerina/aoc21/target'.
$ bal build --offline
Compiling source
	jani/aoc21:0.1.0

Generating executable
	target/bin/aoc21.jar

Dumping build time information
	target/build-time.json
	timestamp : 0
	offline : true
	compile : false
	projectLoadDuration : 0
	packageResolutionDuration : 570
	packageCompilationDuration : 864
	codeGenDuration : 1049
	emitArtifactDuration : 812
	testingExecutionDuration : 0
	totalDuration : 1643977569702

$ java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

$ java -jar target/bin/aoc21.jar --day 1
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-02-04 14:27:21,090] SEVERE {b7a.log.crash} - ballerina/test/0/$configurationMapper 
java.lang.NoClassDefFoundError: ballerina/test/0/$configurationMapper
	at jani.aoc21.0.$configurationMapper.$configureInit(Unknown Source)
	at jani.aoc21.0.$_init.main(aoc21)
Caused by: java.lang.ClassNotFoundException: ballerina.test.0.$configurationMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more 
```

**Affected Versions:**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

**Comment by Ibaqu** [comment] 2022-02-08 05:25
@janihur Theres a section of code in the main files that is using a `ballerina/test` import. Normally the test modulet is meant to be exclusively used in the `tests` folder. This is an oversight on our part as importing the tests in any other folder should return an appropriate error. 

I commented out the part of code in the main.bal file that did the assertions and ran the following :

```bash
user@aquib:~/Documents/workspace/projects/advent-of-code/ballerina/aoc21$ bal run -- --day 2 --part 1
Compiling source
        user/aoc21:0.1.0

Running executable

(day 2)(part 1)(answer 1488669)
```

This is the part commented out

```
function puzzleRun(
     PuzzleId puzzleId
    ,int[] expected
    ,function(int[]) returns record { int? part1; int? part2; } runner
) {
    var answers = runner(puzzleId.parts);

    if answers.part1 is int {
        io:println(string`(day ${puzzleId.day})(part 1)(answer ${<int>answers.part1})`);
        // test:assertEquals(answers.part1, expected[0], string`Wrong answer to part 1`);
    }

    if answers.part2 is int {
        io:println(string`(day ${puzzleId.day})(part 2)(answer ${<int>answers.part2})`);
        // test:assertEquals(answers.part2, expected[1], string`Wrong answer to part 2`);
    }
}
```

What I suspect is happening is that the test related classes are not getting packed into the runnable jar which is why it throws this error.

**Comment by pramodya1994** [comment] 2022-02-08 08:44
@janihur Currently we are fixing this issue and it will be released as an update soon.

By the time as a workaround, you can remove `dumpBuildTime` from `Ballerina.toml` and build the project and then run it.

**Comment by manuranga** [comment] 2022-04-30 04:21
This was fixed in nBalleina, but now I am getting 
`java.lang.NoClassDefFoundError: ballerina/os/1/os` is this the same, regression or a new issue?

**Closed** 2022-05-04 10:38 UTC
Labels: Type/Bug, Priority/Blocker, Team/DevTools, Points/2, Area/ProjectAPI

**Comment by azinneera** [comment] 2022-05-27 07:58
**Root cause:**
Some dependencies are getting added with `testOnly` scope though they are in the `default` scope. This is due a bug in the package resolution.
