### ISSUE TITLE
"Compilation failed due to an unhandled exception" caused by java.lang.NullPointerException while compiling valid code.

### ISSUE THREAD

**Issue by spencerwi** [ballerina-platform/ballerina-lang#34193] opened 2021-12-07 15:55 UTC
**Description:**

While attempting to compile and run [this code](https://github.com/spencerwi/AdventOfCode2021/blob/558e0e699a6c0476c67008b3fef277d31bcdd77d/day7/main.bal) via `bal run`, the Ballerina compiler crashes with the following error message:

```
Compiling source
        vscode/day7:0.1.0
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2021-12-07 15:48:29,617] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:443)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:401)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:268)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:416)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:353)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:80)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:191)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [day7:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
``` 

**Steps to reproduce:**

1. Launch a codespace from [this repo at this branch+commit](https://github.com/spencerwi/AdventOfCode2021/tree/558e0e699a6c0476c67008b3fef277d31bcdd77d) (just click the "Code" dropdown and select "New Codespace").
2. Once the new codespace launches, run `cd day7` to enter the directory of the Ballerina project that exhibits the issue
3. Run `bal run`
4. Observe that the compiler crashes with the above error message.  

**Affected Versions:**
- Swan Lake Beta4 (docker image not yet available to test Beta5) 

**OS, DB, other environment details and versions:**

Running from CLI in [this Swan Lake Beta4 docker container](https://hub.docker.com/layers/ballerina/ballerina-devcontainer/slbeta4/images/sha256-d450b06cd4a45bcf43ab3947d2f17b621da1db3a10e87ab0339a6c7688385c88?context=explore)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gabilang** [comment] 2021-12-09 05:55
This issue can be reproduced with the following code:
```
type Func function(int i) returns int;

public function main() {
    Func func = foo;
    int[] a = from int j in 0 ... 5 select func(j);
}

function foo(int i) returns int {
    return 1;
}
```

**Comment by gabilang** [comment] 2021-12-23 07:30
This issue is caused by a missing case of closures for function pointers. In `QuaryDesugar.java`, closures for function pointers are not marked properly.

**Comment by hasithaa** [comment] 2021-12-23 07:32
@gabilang Can you check this issue with this PR https://github.com/ballerina-platform/ballerina-lang/pull/31589

**Comment by gabilang** [comment] 2021-12-23 10:19
> @gabilang Can you check this issue with this PR #31589

Checked with that PR, the issue is still there.

**Comment by warunalakshitha** [comment] 2022-01-03 07:52
Since this need to be fixed in QueryDEsugar moved to CompilerFE.

**Comment by pcnfernando** [comment] 2022-07-01 06:54
Until the issue is fixed as a workaround; you can explicitly call the method directly.

```ballerina
import ballerina/io;
import ballerina/regex;

function fixedCost(int[] crabs, int targetPosition) returns int {
    return int:sum(...(
        from int crab in crabs
        select int:abs(crab - targetPosition)
    ));
}

// The problem describes a situation where each step
//  costs "itself" in gas -- so step 1 costs 1 gas,
//  step 2 costs 2 gas, etc, and you add them together.
// So to move 3 steps, it costs 1 + 2 + 3 = 6 gas.
// As it turns out, this "factorial but with addition"
//  has a name: the binomial coefficient (thanks, Pascal!)
//  and is calculated as (n * (n+1))/2
function binomialCost(int[] crabs, int targetPosition) returns int {
    return int:sum(...(
        from int crab in crabs
        let int stepsToMove = int:abs(crab - targetPosition)
        select (stepsToMove * (stepsToMove + 1))/2
    ));
}

// type CostFunction function(int[] crabs, int targetPosition) returns int;

function solve(boolean isFixedCost, int[] crabs) returns int {
    int[] workingCopy = crabs.clone(); // so that Part A doesn't affect Part B
    int highestPosition = int:max(0, ...workingCopy);
    return int:min(int:SIGNED32_MAX_VALUE, ...(
        from int position in 0...highestPosition
        select isFixedCost ? fixedCost(workingCopy, position) : binomialCost(workingCopy, position)
    ));
}

public function main() {
    string input = "1,2,3";
    int[] crabs = 
        from string component in regex:split(input, ",")
        where component.trim().length() > 0
        select checkpanic int:fromString(component);
    
    io:println("Part A: ", solve(true, crabs));
    io:println("Part B: ", solve(false, crabs));
}
```

**Comment by KavinduZoysa** [comment] 2023-03-02 10:42
Closing this for now, and we will take this one later on.

**Closed by KavinduZoysa** 2023-03-02 10:42 UTC
Labels: Type/Bug, Team/CompilerFE, Lang/Expressions/Query
