### ISSUE TITLE
testerina test cases along with transactions are throwing NPE

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#26972] opened 2020-11-17 05:50 UTC
**Description:**
```
[2020-11-17 11:17:38,767] SEVERE {b7a.log.crash} - java.lang.NullPointerException 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: java.lang.NullPointerException
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:123)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:567)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: java.lang.NullPointerException
	at io.ballerina.runtime.internal.values.MapValueImpl.populateInitialValue(MapValueImpl.java:290)
	at ballerina.sql.0_5_2.$value$ConnectionPool.ConnectionPool$gen$$0046$0060init$0062(connection-pool.bal:34)
	at ballerina.sql.0_5_2.$typedesc$ConnectionPool.instantiate(connection-pool.bal)
	at ballerina.sql.0_5_2.sql.$gen$ballerina$0047sql$00580$00465$00462$0046$0060init$00622(sql:303)
	at ballerina.sql.0_5_2.sql.$gen$ballerina$0047sql$00580$00465$00462$0046$0060init$00621(sql:29)
	at ballerina.sql.0_5_2.sql.$gen$$0046$0060testinit$0062(sql:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:107)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:498)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
```
**Steps to reproduce:**
Build module-ballerina-sql after enabling transaction testcases

**Comment by gimantha** [comment] 2020-11-17 06:03
Here is the minimal code, which causes the issue.

 ```ballerina
import ballerina/test;

 @test:BeforeGroups {
 	value: ["transaction"]
 }
 function initTransactionContainer() {
 }

 @test:AfterGroups {
 	value: ["transaction"]
 }
 function cleanTransactionContainer() {
 }

 @test:Config {
     groups: ["transaction"]
 }
 function testLocalTransaction() {

     transaction {
         var x = commit;
     }
 }
```

Then the exception thrown is,

```ballerina
[2020-11-17 10:17:24,080] SEVERE {b7a.log.crash} - java.lang.NullPointerException 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: java.lang.NullPointerException
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:123)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:567)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: java.lang.NullPointerException
	at io.ballerina.runtime.internal.MapUtils.handleMapStore(MapUtils.java:48)
	at ballerina.sql.0_5_2.sql.$gen$$0046$0060testinit$0062(sql:2)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:107)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:498)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Ibaqu** [comment] 2020-11-17 11:19
We were able to reproduce the null pointer issue for the `local-transaction-test` in `module-ballerina-sql`. 

On debugging the `CodeGenerator` class, it was found that the required import `ballerinai/transaction` did not seem to get passed to the test suite. 

The `generate()` takes a testablePackage.symbol as a parameter which does not include the `ballerinai/transaction import, even though it is included in the package during BIRGen. 

Here, index 7 is the required import. 
![Screenshot 2020-11-17 at 16 25 53](https://user-images.githubusercontent.com/43578935/99383825-72e9fa80-28f4-11eb-9eaf-a250fb357b28.png)

However, this is not included in the `testablePackage.symbol.imports
![unnamed](https://user-images.githubusercontent.com/43578935/99383869-885f2480-28f4-11eb-8ef5-e51e391866c2.png)

**Comment by gimantha** [comment] 2020-11-17 16:44
@Ibaqu I got the required import passed into the testpackage's symbol's import list, but still I am getting this NPE.

**Comment by gimantha** [comment] 2020-11-18 15:43
This is not caused by testerina, but due to missing transitive imports of transactions internal module. Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/26999

**Closed by gimantha** 2020-11-18 15:43 UTC
Labels: Component/Testerina, Priority/Blocker, Team/TestFramework
