### ISSUE TITLE
Compilation error while running the Ballerina app in Choreo

### ISSUE THREAD

**Issue by LahiruSammika95** [ballerina-platform/ballerina-lang#37285] opened 2022-08-06 06:23 UTC
When I try to run, service.bal which inside a Choreo managed ballerina project, I get this error regularly.

Ballerina version: Ballerina 2201.1.1 (Swan Lake Update 1)

    ballerina: Oh no, something really went wrong. Bad. Sad.
    
    We appreciate it if you can report the code that broke Ballerina in
    https://github.com/ballerina-platform/ballerina-lang/issues with the
    log you get below and your sample code.
    
    We thank you for helping make us better.
    
    [2022-08-06 06:13:56,159] SEVERE {b7a.log.crash} - Failed to write library: /config/workspace/target/cache/lahiru123/police_check_api/0.1.0/java11/lahiru123-police_check_api-0.1.0.jar 
    java.lang.RuntimeException: Failed to write library: /config/workspace/target/cache/lahiru123/police_check_api/0.1.0/java11/lahiru123-police_check_api-0.1.0.jar
            at io.ballerina.projects.repos.FileSystemCache.cachePlatformSpecificLibrary(FileSystemCache.java:117)
            at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:316)
            at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:473)
            at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
            at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
            at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
            at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
            at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
            at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
            at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
            at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
            at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
            at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
            at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
            at java.base/java.util.Optional.ifPresent(Optional.java:183)
            at io.ballerina.cli.launcher.Main.main(Main.java:51)
    Caused by: java.io.FileNotFoundException: /config/workspace/target/cache/lahiru123/police_check_api/0.1.0/java11/lahiru123-police_check_api-0.1.0.jar (No such file or directory)
            at java.base/java.io.FileOutputStream.open0(Native Method)
            at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
            at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
            at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2451)
            at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:3325)
            at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:3289)
            at org.apache.commons.io.FileUtils.writeByteArrayToFile(FileUtils.java:3272)
            at io.ballerina.projects.repos.FileSystemCache.cachePlatformSpecificLibrary(FileSystemCache.java:114)
            ... 15 more

**Comment by Nadeeshan96** [comment] 2022-09-06 12:17
@LahiruSammika95 Here the stack trace says the issue was caused because the jar had not been created. It may be due to an error occurred before this step. There should be another stack trace before getting this one. Are there any other issues when you are compiling the code? Can you please add that stack trace as well?

And also can we reproduce this locally?

**Comment by warunalakshitha** [comment] 2022-09-29 15:46
We are closing this issue since we assume this was due to some corrupted caching issue. We need more information to further analysis of the issue. Please reopen this if you observe the same error again with all error stack traces.

**Closed by warunalakshitha** 2022-09-29 15:46 UTC
Labels: Type/Bug, Team/jBallerina, Reason/Other
