### ISSUE TITLE
Enhancement - Unresolved Reference 

### ISSUE THREAD

**Issue by NGimhana** [ballerina-platform/ballerina-lang#9632] opened 2018-07-13 08:43 UTC
**Description:**
Unresolved Reference for common packages like HTTP, IO in IntelliJ IDEA Editor. But the code compiles and running smoothly. Need some Indication enhancement of the style of the code base.

**Affected Versions:**
Ballerina 0.976.1-SNAPSHOT

**OS, DB, other environment details and versions:**
UBUNTU 16.04 x64

**Comment by NGimhana** [comment] 2018-07-18 08:41
Yes. I have set. The code runs as expected. The issue is, not identifying the Packages imported.
 
![scr](https://user-images.githubusercontent.com/25481892/42870023-4fa0609c-8a94-11e8-82ae-4ea45d7ce06a.png)

**Comment by Shan1024** [comment] 2018-07-18 08:56
@NGimhana - Seems like the project is not a Ballerina project. Can you try after creating a ballerina project?

**Comment by NGimhana** [comment] 2018-07-18 10:38
The problem remains even after Initiating as a Ballerina Project module.

![scr](https://user-images.githubusercontent.com/25481892/42876512-86505768-8aa4-11e8-98f9-8183ec98118f.png)

**Comment by NipunaRanasinghe** [comment] 2018-07-18 10:56
@NGimhana - what is the plugin version you are using? Can you please check with the [latest ballerina release](https://ballerina.io/downloads/) and [IntelliJ Plugin 0.980.0](https://plugins.jetbrains.com/plugin/9520-ballerina) since you are using a previsous SNAPSHOT version?

**Comment by Shan1024** [comment] 2018-07-18 11:10
I think the issue is in the Ballerina pack you are using which is `Ballerina 0.976.1-SNAPSHOT`. In that pack, the ballerina sources were not shipped due to some changes. This issue was fixed in the Ballerina 0.980.0 version. So please use Ballerina 0.980.0 version for development.

**Closed by Shan1024** 2018-07-18 11:10 UTC
Labels: Component/intellij plugin, Type/Improvement

**Comment by NGimhana** [comment] 2018-07-18 11:17
The Latest releases resolve the Issue. But I opened this Issue as there was 0.976.1-SNAPSHOT public downloadable and no compatible IntelliJ plugin available at that time. Now all are updated. :-)
