### ISSUE TITLE
Add deprecation information into apidocs

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#21927] opened 2020-03-18 09:13 UTC
**Description:**
Need to add the deprecation information into apidocs.

**Steps to reproduce:**
Generate apidocs for a module which contains a deprecated construct.

**Affected Versions:**
1.2.0

**Comment by hevayo** [comment] 2020-03-23 10:51
Duplicate of 21725

**Closed by hevayo** 2020-03-23 10:51 UTC
Labels: Area/Tooling, Component/Docerina
