### ISSUE TITLE
[Bug]: NPE in join clause

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#38384] opened 2022-10-25 07:59 UTC
### Description

Following code gives NPE

```
import ballerina/io;

type User record {|
    readonly int id;
    string name;
|};

type Login record {|
    int userId;
    string time;
|};

public function main() {
    table<User> key(id) users = table [
        {id: 1234, name: "Keith"},
        {id: 6789, name: "Anne"}
    ];

    Login[] logins = [
        {userId: 6789, time: "20:10:23"},
        {userId: 1234, time: "10:30:02"},
        {userId: 3987, time: "12:05:00"}
    ];

    string[] loginLog = from var login in logins
                        outer join var user in users
                        on login.userId equals user.id
                        select user.name + ":" + login.time;

    io:println(loginLog);
}

```

Stacktrace
```
Compiling source
        outer_join_clause.bal

Running executable

[2022-10-25 13:23:12,585] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at outer_join_clause.$streamLambda$_4(outer_join_clause.bal:31)
        at outer_join_clause.$streamLambda$_4$lambda4$(outer_join_clause.bal:31)
        at ballerina.lang$0046query.0.$value$_SelectFunction.process(types.bal:623)
        at ballerina.lang$0046query.0.$value$_SelectFunction.call(types.bal)
        at ballerina.lang$0046query.0.types.$gen$$anon$method$delegate$_StreamFunction$0046process$0(types.bal:91)
        at ballerina.lang$0046query.0.$value$_StreamPipeline.$gen$$anon$method$delegate$_StreamFunction$0046process$0$lambda0$(types.bal)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:569)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:303)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:270)
        at java.base/java.lang.Thread.run(Thread.java:834)
 
error: java.lang.NullPointerException
        at outer_join_clause:$streamLambda$_4(outer_join_clause.bal:31)
           ballerina.lang.query.0._SelectFunction:process(types.bal:623)
           ballerina.lang.query.0:$anon$method$delegate$_StreamFunction.process$0(types.bal:91)
```

### Related area

-> Compilation

**Comment by pcnfernando** [comment] 2022-11-03 07:38
This should be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/38232. @ushirask please verify

**Comment by ushirask** [comment] 2022-11-03 07:59
Duplicate of #34897 
#38232 will solve the NPE issue, however the above code segment will not be correct since we'd have to use `select user?.name + ":" + login.time` and we cannot concatenate `string` and `string?` and will have to be handled accordingly.

**Comment by ushirask** [comment] 2022-11-03 08:00
Duplicate of #34897

**Closed** 2022-11-08 09:21 UTC
Labels: Type/Bug, Status/Duplicate, Team/CompilerFE, Reason/Invalid, needTriage, userCategory/Compilation
