### ISSUE TITLE
The design is not loaded in the edit mode of all samples

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8050] opened 2018-04-25 13:46 UTC
**Description:**
![5](https://user-images.githubusercontent.com/1845370/39249402-396098fc-48bc-11e8-8dd5-ca4ab9e612bb.png)

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Chromium Browser - Version 51.0.2704.79 Ubuntu 15.10 (64-bit)

**Comment by rasika** [comment] 2018-04-26 04:05
Can you verify this with the latest? Tested in beta18-SNAPSHOT and working fine.

<img width="1440" alt="screen shot 2018-04-26 at 9 29 48 am" src="https://user-images.githubusercontent.com/1448489/39285273-27a8ad88-4935-11e8-8f27-6a78e01a4f45.png">

**Comment by rasika** [comment] 2018-05-09 09:20
Marking as "Closed" since cannot reproduce in the latest.

**Closed by rasika** 2018-05-09 09:20 UTC
Labels: L1/L2 for May, Priority/Highest, component/Composer
