### ISSUE TITLE
Code suggestion does not work for parameters in functions

### ISSUE THREAD

**Issue by Anoukh** [ballerina-platform/ballerina-lang#13510] opened 2019-02-07 09:23 UTC
**Description:**
Code suggestion does not work for parameters in normal functions. It works for public functions only

```ballerina
function someName(string name) {  // string type did not get suggested
    
}
```
VSCode Version: 1.31.0
Date: 2019-02-06T08:51:24.856Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-43-generic

**Comment by nadeeshaan** [comment] 2019-03-13 08:52
Duplicate of #13787

**Closed by nadeeshaan** 2019-03-13 08:52 UTC
Labels: Component/LanguageServer, Component/VScode plugin, Type/Bug
