### ISSUE TITLE
Need to Change the Template Design of API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#25896] opened 2020-04-03 14:07 UTC
**Description:**
API Doc page organization/alignments need to be improved. Currently, API Docs are loaded on iframes and it leads to many issues. One is the empty bar on the side as shown below and another can be [1].

<img width="1680" alt="Screenshot 2020-04-03 at 19 36 02" src="https://user-images.githubusercontent.com/11707273/78369212-76897500-75e2-11ea-823e-66bcc2ede85a.png">

<img width="1680" alt="Screenshot 2020-04-03 at 19 45 16 2" src="https://user-images.githubusercontent.com/11707273/78370273-11368380-75e4-11ea-8886-9e80972d9b07.png">

What we have currently is an implementation done for offline viewing. We can make API Docs landing page a Home page and improve its design template.

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/368

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/ballerina-platform/ballerina-dev-website/issues/355

**Comment by shehan360** [comment] 2021-01-12 05:25
Closing as the issue is resolved.

**Closed by shehan360** 2021-01-12 05:25 UTC
Labels: Component/Docerina, Team/DevTools
