### ISSUE TITLE
Code completion fails for @kubernetes:Service annotation 

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-platform/ballerina-lang#9179] opened 2018-06-20 16:02 UTC
**Description:**
There is no code completion for @kubernetes:Service annotation (before endpoint)

**Steps to reproduce:**
See code sample: https://github.com/ballerina-guides/ballerina-demo/blob/master/5_demo_kubernetes.bal

**Affected Versions:**
0.975

**OS, DB, other environment details and versions:**
Mac OS, latest VS Code

**Related Issues (optional):**

**Suggested Labels (optional):**
Category/Language Server

**Suggested Assignees (optional):**
Joseph

**Comment by nadeeshaan** [comment] 2018-06-24 14:03
Duplicate of #8932. Hence closing the issue

**Closed by nadeeshaan** 2018-06-24 14:03 UTC
Labels: Type/Bug, component/LanguageServer
