### ISSUE TITLE
Deprecation error throws in full expression rather than actual type

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#24335] opened 2020-06-18 18:09 UTC
**Description:**

This is reflected in Deprecation BBE. Check the error messages for line 78 and line 81.

```Logtalks
warning: .::deprecation.bal:35:5: usage of construct 'Address' is deprecated
warning: .::deprecation.bal:39:22: usage of construct 'LKA' is deprecated
warning: .::deprecation.bal:65:76: usage of construct 'Person' is deprecated
warning: .::deprecation.bal:68:5: usage of construct 'Person' is deprecated
warning: .::deprecation.bal:78:5: usage of construct 'Person' is deprecated
warning: .::deprecation.bal:78:16: usage of construct 'createPerson(Jane, Doe, Castro Street, Mountain View, USA)' is deprecated
warning: .::deprecation.bal:81:16: usage of construct 'p.getFullName()' is deprecated
```

Refer to PR: https://github.com/ballerina-platform/ballerina-distribution/pull/577
Changes introduced by this PR needs to be amended after the proper fix.

**Steps to reproduce:**
Please run Deprecation BBE in new parser.

**Affected Versions:**
jBallerina 2.0.0-Preview1-M6

**OS, DB, other environment details and versions:**
macOS Cataline

**Suggested Labels (optional):**
Area/Language,Type/Bug

**Comment by praneesha** [comment] 2021-06-12 14:20
Closing since this BBE is removed now.

**Comment by MaryamZi** [comment] 2021-06-12 14:58
Reopening this since it is a compiler issue.

The string representation of the expression is still used (slbeta1).

Reproducible with

```ballerina
@deprecated
function foo(int i, string s) {

}

public function main() {
    foo(1, "hello");
}
```

```cmd
Compiling source
        test.bal
WARNING [test.bal:(7:5,7:20)] usage of construct 'foo(1, hello)' is deprecated
```

**Comment by hasithaa** [comment] 2022-03-24 04:53
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35286

**Closed by hasithaa** 2022-03-24 04:53 UTC
Labels: Type/Improvement, Team/CompilerFE, Area/Diagnostics, Points/1, SwanLakeDump, Area/AST
