### ISSUE TITLE
Issue in nested type definitions

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#12963] opened 2019-01-03 04:43 UTC
**Description:**
```ballerina
import ballerina/io;

type T object { public string g = ""; };

type T2 T;

public function main() {
    object { public string g = ""; } o = new;
    T2 t2 = o;
    io:println(t2);
}
```

This gives the following compilation error.

```
incompatible types: expected 'T', found '$anonType$0'
```

**Comment by MaryamZi** [comment] 2019-04-01 09:43
This is due to anonymous objects always being `public`. 

When the type definitions are marked public, the expected behaviour is observed.

```ballerina
import ballerina/io;

public type T object { public string g = ""; };

public type T2 T;

public function main() {
    object { public string g = ""; } o = new;
    T2 t2 = o;
    io:println(t2);
}
```

```cmd
$ ballerina run test.bal
{g:""}
```

Closing this issue since object equivalency for anonymous vs public objects is tracked with https://github.com/ballerina-platform/ballerina-lang/issues/10480.

**Closed by MaryamZi** 2019-04-01 09:43 UTC
Labels: Component/Compiler, Type/Bug
