### ISSUE TITLE
NPE throws in BIROptimizer when there is a foreach inside query syntax

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#34557] opened 2022-01-07 06:48 UTC
**Description:**
When we try to build the following sample code, 

```
public function main() returns error? {
    string[] fruits = ["apple orange banana", "orange apple banana", "banana", "apple", "orange"];

    map<int> count = {};
    var _ = check from string fruit in fruits.toStream()
            do {
                string[] tokens = regex:split(fruit, "\\s+");
                foreach string token in tokens {
                    if token != "" {
                        int? frequency = count[token];
                        count[token] = frequency is int ? frequency + 1 : 1;
                    }
                }
            };
    io:println(count);
}
```
Get following NPE at BIROptimizer,

```
[2022-01-07 12:16:09,469] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:443)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:401)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:269)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:452)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:389)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:249)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)

```

**Steps to reproduce:**
Build the above sample code.

**Affected Versions:**
slbeta6

**Comment by warunalakshitha** [comment] 2022-01-10 15:15
This seems to be duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/34193

**Comment by pcnfernando** [comment] 2022-07-01 05:30
This seems to be due to a closure resolving issue. Will try to prioritize this in the upcoming sprints.
As a workaround, you can use a temp variable.

```ballerina
import ballerina/regex;
import ballerina/io;
public function main() returns error? {
    string[] fruits = ["apple orange banana", "orange apple banana", "banana", "apple", "orange"];

    map<int> count = {};
    var _ = check from string fruit in fruits.toStream()
            do {
                string[] tokens = regex:split(fruit, "\\s+");
                map<int> tempCount = count;
                foreach string token in tokens {
                    if token != "" {
                        int? frequency = tempCount[token];
                        tempCount[token] = frequency is int ? frequency + 1 : 1;
                    }
                }
                count = tempCount;
            };
    io:println(count);
}
```

**Closed** 2022-08-08 09:29 UTC
Labels: Type/Bug, Team/CompilerFE, Area/BIR, Lang/Actions/Query
