### ISSUE TITLE
Micro gateway gives the correct response for invalid JWT access token

### ISSUE THREAD

**Issue by Varuni-Punchihewa** [ballerina-platform/ballerina-lang#11479] opened 2018-11-19 07:04 UTC
**Description:**
Microgateway gives out the correct response even after when you change the last letter of the verify signature section in the generated JWT.

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5UQXhabU14TkRNeVpEZzNNVFUxWkdNME16RXpPREpoWldJNE5ETmxaRFUxT0dGa05qRmlNUSJ9.eyJhdWQiOiJodHRwOlwvXC9vcmcud3NvMi5hcGltZ3RcL2dhdGV3YXkiLCJzdWIiOiJhZG1pbiIsImFwcGxpY2F0aW9uIjp7ImlkIjo0LCJuYW1lIjoiTW9ja0FwcCIsInRpZXIiOiJVbmxpbWl0ZWQiLCJvd25lciI6ImFkbWluIn0sInNjb3BlIjoiYW1fYXBwbGljYXRpb25fc2NvcGUgZGVmYXVsdCIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImtleXR5cGUiOiJQUk9EVUNUSU9OIiwic3Vic2NyaWJlZEFQSXMiOlt7Im5hbWUiOiJNb2NrQVBJIiwiY29udGV4dCI6IlwvbW9ja2FwaVwvMS4wLjAiLCJ2ZXJzaW9uIjoiMS4wLjAiLCJwdWJsaXNoZXIiOiJhZG1pbiIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQiLCJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIn0seyJuYW1lIjoiTW9ja1NlY3VyZUFQSSIsImNvbnRleHQiOiJcL21vY2tzZWN1cmVhcGlcLzEuMC4wIiwidmVyc2lvbiI6IjEuMC4wIiwicHVibGlzaGVyIjoiYWRtaW4iLCJzdWJzY3JpcHRpb25UaWVyIjoiVW5saW1pdGVkIiwic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciJ9XSwiY29uc3VtZXJLZXkiOiJLRElRZUJqZWJEekVWYUR1dGxqMW9ENXU5T2dhIiwiZXhwIjozNjkwMDg5NTc0LCJpYXQiOjE1NDI2MDU5Mjc4NDgsImp0aSI6IjYxYzcyYzNlLWE4ZWYtNGU5YS05ZWQ4LWNlOTkwOTA0YTZjNiJ9.OzkwD1tTaBJwX49zjt4kXN1X9ycWbRGNO0uk4bfRggkGE9EFmWdCAiy6cKSd4neczwLDm4XXIexW_G8T_ajydJr2b9hwGY_TLuxxrapNWVRqFUl3L5T-80uqXlRxQy46KORK-qn3yXBoG2X4XycSBxe-_x94CwQfmyx0SAb273flvytWyKxztvlsvBtV_OL4yJxiSM0r2a6WdfuXi823AdFzrnx3TaG0rEKPz2vpQhwZ8Z0TcTur5QysD3SBY2bZGGNduWV2EaTDrvJxuml0AAgSGU1SOgZ_X_6gCwx91yD-1vAcP449vjo71qDN1QHVyT2ZB1S6HVH7naLDE6w3KA==
```
If we change the last letter of the token which is A to B, still you get the correct and same output as when you use the valid token.

This issue continues to happen when you use any capital english letter present after A (last letter just before == characters), instead of A.

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
WSO2 API Manager Microgateway 2.6.0-RC3 

**OS, DB, other environment details and versions:**    
Ballerina 0.981.1

**Steps to reproduce:**

**Related Issues:**

**Comment by ayomawdb** [comment] 2018-12-19 11:36
Verified JWT validation with Ballerina 0.990.0 and confirmed that the validation is working as expected without the issue mentioned here. Further validated cache implementation and confirmed that the issue cannot occur with the latest version in Auth stdlib. This issue will be resolved after cross-checking with Microgateway team.

**Comment by ayomawdb** [comment] 2019-01-31 03:42
It was observed that this was due to base64-url-decoding that is performed while reading the JWT token. This behaviors is common across JWT decoders, hence not a Ballerina specific problem. Closing the issue due to this reason.

**Closed by ayomawdb** 2019-01-31 03:42 UTC
Labels: Component/stdlib, Priority/High, Type/Bug
