### ISSUE TITLE
Improve the formatting rules related to the body of expression-bodied functions

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#29550] opened 2021-03-23 23:55 UTC
Here is the sample code:

<img width="842" alt="Screen Shot 2021-03-23 at 4 54 10 PM" src="https://user-images.githubusercontent.com/2637328/112233849-6eae5080-8bf8-11eb-90d3-af6f23555c18.png">

Here is what I get after using the formatter:
<img width="1094" alt="Screen Shot 2021-03-23 at 4 54 18 PM" src="https://user-images.githubusercontent.com/2637328/112233858-70781400-8bf8-11eb-9d12-80673b314db1.png">

**Comment by IrushiL** [comment] 2021-07-29 11:45
Following improvements are done on the formatting rules:

* Preserves user-defined new lines.
* Aligns the indentation of a user-defined new line to the nearest tab. 
* Refrains from doing an opinionated line-wrapping.
* The `LetExpressionNode` breaks a new line before the `in` keyword and it is aligned to the left-hand side with a single tab space.

The formatted code would be as follows.
```bal
function (string, [string, anydata]) returns string logfmt = 
        (combined, kvPair) => let var kvStr = kvPair[0] + "=" + kvPair[1].toBalString()
    in combined is "" ? kvStr : (combined + " " + kvStr);
```

If the user decides to leave a single tab in the second line instead of two tabs, the formatted code would be as follows.
```bal
function (string, [string, anydata]) returns string logfmt = 
    (combined, kvPair) => let var kvStr = kvPair[0] + "=" + kvPair[1].toBalString()
    in combined is "" ? kvStr : (combined + " " + kvStr);
```

However, the formatting of let expressions could be improved as explained in https://github.com/ballerina-platform/ballerina-lang/issues/31950. If this is supported, the first scenario where the indentation is done for two tabs could also be achieved. 

Closing this issue since the improvement in the let expressions is tracked separately and since the rest of the issue is already fixed.

**Closed by IrushiL** 2021-07-29 11:45 UTC
Labels: Area/Formatting, Priority/Blocker, Team/CompilerFETools, Type/Bug, Version/SLAlpha3
