### ISSUE TITLE
Auto-import doesn't happen for inline function calls

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6302] opened 2018-04-03 10:42 UTC
<a href="https://github.com/yasassri"><img src="https://avatars1.githubusercontent.com/u/7681361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yasassri](https://github.com/yasassri)**
_Monday Oct 09, 2017 at 13:38 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3401_

----

When I added a JSON variable and assigned it a value by converting the message to a JSON. The composer doesn't auto-import messages package.

![screenshot from 2017-10-09 19-05-06](https://user-images.githubusercontent.com/7681361/31340784-e529b8a0-ad24-11e7-9331-612a114d7211.png)

**Comment by hevayo** [comment] 2018-06-10 09:40
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/6307 this feature will be supported via language server.

**Closed by hevayo** 2018-06-10 09:40 UTC
Labels: Imported, Type/Bug, component/Composer
