### ISSUE TITLE
Type narrowing does not work when `==` is used

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#34495] opened 2022-01-04 07:59 UTC
Consider the following code.

```ballerina
public function main() {
    int? val = 9;

    if val == () {
        return;
    }

    int x = val; //Compile error : incompatible types: expected 'int', found 'int?'
}
```

**Comment by lasinicl** [comment] 2022-01-06 03:37
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/34160. Hence closing this issue.

**Closed by lasinicl** 2022-01-06 03:37 UTC
Labels: Type/Bug, Priority/Blocker, Team/CompilerFE, Area/TypeChecker, Lang/TypeNarrowing, NBalNeeds
