### ISSUE TITLE
No suggestions for grpc:INTERNAL for caller->sendError 

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13744] opened 2019-02-21 08:50 UTC
**Description:**
Auto suggestion for grpc:INTERNAL for caller->sendError is not appearing

![image](https://user-images.githubusercontent.com/10986966/53155542-4ac84d00-35e3-11e9-898a-2d7834f7e3ba.png)

**Comment by nadeeshaan** [comment] 2019-03-13 07:01
Duplicate of #13787

**Closed by nadeeshaan** 2019-03-13 07:01 UTC
Labels: Component/LanguageServer, Type/Bug
