### ISSUE TITLE
No way to link external jar files to single bal files

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-lang#20309] opened 2019-12-10 04:48 UTC
**Description:**
$subject.

So we cannot use ballerinax/java.jdbc module in a single bal files. Earlier copying to bre/lib works and not working now. 

**Steps to reproduce:**

**Affected Versions:**

1.0.5, 1.1.0-alpha

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hevayo** [comment] 2020-01-30 05:24
Duplicate of #20281

**Closed by hevayo** 2020-01-30 05:24 UTC
Labels: Area/BuildTools, Priority/Blocker, Type/PackerinaSpecIssue
