### ISSUE TITLE
Goto def not working for std lib functions

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29445] opened 2021-03-23 08:43 UTC
**Description:**
![goto_def_error](https://user-images.githubusercontent.com/15815199/112122046-e1fa9700-8be5-11eb-9ef4-0ca3838167ff.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nadeeshaan** [comment] 2021-03-24 12:02
Duplicate of #29526. Hence closing the issue

**Closed by nadeeshaan** 2021-03-24 12:02 UTC
Labels: Status/Duplicate, Team/LanguageServer, Type/Bug, Version/SLAlpha3
