### ISSUE TITLE
Tuple de-structuring with ignored types fails

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#5407] opened 2018-03-20 15:17 UTC
Following tuple de-structuring with ignored types fails with the compilation error below.

````
function test1() returns (string, float){
    string a;
    float b;
    (a, _, b) = testMultiReturn1();
    return (a,b);
}

function testMultiReturn1() returns (string, int, float){
    return ("a", 1, 2.0);
}
````

**error**
```
a.bal:4:17:: incompatible types: expected '(string,other,float)', found '(string,int,float)'
```

**Comment by MaryamZi** [comment] 2018-06-11 10:58
Closing the issue since this seems to be fixed on the current master. Could not reproduce with 0.974.0 either.

**Tested with:**
Ballerina Source:
```bal
import ballerina/io;

function main(string... args) {
    io:println(test1());
}

function test1() returns (string, float) {
    string a;
    float b;
    (a, _, b) = testMultiReturn1();
    return (a,b);
}

function testMultiReturn1() returns (string, int, float) {
    return ("a", 1, 2.0);
}
```

Produced output:
```cmd
(a, 2.0)
```

**Closed by MaryamZi** 2018-06-11 10:58 UTC
Labels: Type/Bug, component/Compiler
