### ISSUE TITLE
When the close brace and semicolon are missing in a function, suggestions and compilation error point out  the next line

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#29552] opened 2021-03-24 03:10 UTC
**Description:**
$Subject

Refer to the following.
- Suggestion
<img width="357" alt="Screenshot 2021-03-24 at 12 45 06 AM" src="https://user-images.githubusercontent.com/12771261/112248589-2b95c100-8c7c-11eb-9732-13a123100048.png">

- Compilation Error
<img width="394" alt="Screenshot 2021-03-24 at 12 45 27 AM" src="https://user-images.githubusercontent.com/12771261/112248607-318ba200-8c7c-11eb-98b1-d53596352e33.png">

**Steps to reproduce:**

```ballerina
import ballerina/log;

public function main() {
    log:printError("asdfg")
}

public function test() {
    if(true)

    }
}
```
**Affected Versions:**
SLAlpha3

**Comment by rdulmina** [comment] 2021-04-06 07:02
Duplicate of #29418. Hence closing.

**Closed by rdulmina** 2021-04-06 07:02 UTC
Labels: Area/Compiler, Area/Parser, Team/CompilerFE, Type/Improvement
