### ISSUE TITLE
Json and UTF-8 encoding

### ISSUE THREAD

**Issue by ponsilva** [ballerina-platform/ballerina-lang#11448] opened 2018-11-16 13:47 UTC
**Description:**
{ "nome": "Mario", "età": 28, "città": "Bogotà" }
is printed as
{"nome":"Mario", "et?":28, "citt?":"Bogot?"}
after reading it from a file with UTF-8 encoding set

**Steps to reproduce:**
```
import ballerina/io;
public function main() {    
    string srcFileName = "./files/jsonsample.txt";        
    io:ReadableCharacterChannel characterChannel = new(io:openReadableFile(srcFileName), "UTF-8");   
    io:println(characterChannel.readJson());
    _ = characterChannel.close();
}
```
jsonsample.txt
```
{ "nome": "Mario", "età": 28, "città": "Bogotà" }
```

**Affected Versions:**
0.983.0

**OS, DB, other environment details and versions:**
Windows

**Comment by aashikam** [comment] 2019-08-16 04:57
Closing this issue as I couldn't reproduce this on Windows with the latest release of Ballerina version. @ponsilva Please report an issue if you encounter this problem again.

**Version** - Ballerina 1.0.0 Beta - SNAPSHOT
**OS** - Windows 10 Home

**Sample code:**
```ballerina
import ballerina/io;
public function main() {
    string srcFileName = "./issue.txt";
    var result = io:openReadableFile(srcFileName);
    if (result is io:ReadableByteChannel) {
        io:ReadableCharacterChannel characterChannel = new(result, "UTF-8");
        io:println(characterChannel.readJson());
    var result2 = characterChannel.close();
    }
}
```

**Output:**
`{"nome":"Mario", "età":28, "città":"Bogotà"}`

**Closed by aashikam** 2019-08-16 04:57 UTC
Labels: Area/StandardLibs, Type/Bug
