### ISSUE TITLE
Bad sad error with unusual/invalid match clause

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#28850] opened 2021-02-23 12:12 UTC
**Description:**
Consider the following code:
```
const KEY2 = 2;

function testMatch() {
    boolean found = false;
    int[5] nums = [0, 1, 2, 3, 4];
    foreach var counter in nums {
        match counter {
            0 => {

            }
            if true => {

            }
            KEY2 => {

            }
        }
    }
}
```
**This has one of the following 2 issues:**
1. Not sure if the match clause `if true` is valid. But the spec mentions about a `match-guard`. However, the above code doesn't give a compilation error in VSCode.
2. When we run the above code (single file), it prints a bad sad error: 
```
[2021-02-23 17:33:25,786] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.createConditionFromMatchPatterns(Desugar.java:3337)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.convertMatchClauseToIfStmt(Desugar.java:3317)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.convertMatchClausesToIfElseStmt(Desugar.java:3310)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3297)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatchStatement.accept(BLangMatchStatement.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7670)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1374)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:4926)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangWhile.accept(BLangWhile.java:78)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7670)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1374)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:4633)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangForeach.accept(BLangForeach.java:105)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7660)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7670)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1169)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1214)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7677)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:808)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7619)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:448)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:249)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:158)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:155)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```
The cause for this is in `org.wso2.ballerinalang.compiler.desugar.Desugar#createConditionFromMatchPatterns()`, it access the 1st match pattern without checking if the match patterns are empty.
 
**Steps to reproduce:**
See the description

**Affected Versions:**
SLA2

**Comment by IMS94** [comment] 2021-02-24 07:49
As per the `Mapping Match` BBE, we should be able to write:
```ballerina
    match matchExpr {
        // This pattern will only match if `var2` is of the type `string`.
        {a: var var1, b: var var2} if var2 is string => {
            io:println("Matched with string typeguard");
        }
        // This pattern will only match if `var1` is of the type `int` and `var2` is of the type `int`.
        {a: var var1, b: var var2} if (var1 is int && var2 is int) => {
            io:println("Matched with int and int typeguard : ", var1);
        }
  ...
```

**Comment by lasinicl** [comment] 2021-06-23 06:31
In the given example, the bad sad is caused by
```ballerina
if true => {

}
``` 
According to the spec,
```ballerina
match-stmt := match action-or-expr { match-clause+ }
match-clause :=
  match-pattern-list [match-guard] => statement-block
match-guard := if expression
```
```ballerina
match-pattern-list := 
  match-pattern (| match-pattern)*
```
At least a single `match-pattern` should be there prior to a `match-guard`. Hence it should be fixed from the **parser**.

**Closed** 2021-06-30 05:13 UTC
Labels: Area/Parser, Crash, Lang/BindingPatterns, Priority/Blocker, Team/CompilerFE, Type/Bug
