### ISSUE TITLE
Toml Parser Issue with # Characters

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#15685] opened 2019-06-11 22:42 UTC
A Toml configuration file with the following content:

```toml
pass = "#" 
```
The above configuration field value read fails with the following error:

error: invalid toml syntax at ballerina.conf:2

The issue seems to be happening to any value that contains a "#" character.

**Comment by hevayo** [comment] 2019-06-17 05:14
Duplicate of #9778

**Closed by hevayo** 2019-06-17 05:14 UTC
Labels: Component/Compiler, Priority/Blocker
