### ISSUE TITLE
[Tooling] Code suggestion does not work in middle of code blocks

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#26849] opened 2020-11-11 04:32 UTC
**Description:**
Please refer the below code block. In that, code suggestion does not work in the middle of the code blocks, but it works at the start and the end.

```ballerina
type Student record {
    readonly id;
    string firstName;
    string lastName;
    int intakeYear;
    float gpa;
};

type Report record {
    readonly id;
    string name;
    string degree;
    int graduationYear;
};
type ReportTable table<Report> key(id); 

type FullName record {|
    string firstName;
    string lastName;
|};

public function main() {
    
}

```

**Comment by nadeeshaan** [comment] 2021-01-04 10:13
Could not reproduce the issue in latest master. Hence closing the issue. If this issue still reproducible, please re-open

**Closed by nadeeshaan** 2021-01-04 10:13 UTC
Labels: Area/LanguageServer, Priority/Blocker, Team/Tooling
