### ISSUE TITLE
Wrong error position

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#25733] opened 2020-09-11 06:42 UTC
**Description:**
consider the bellow code 
```
// This is to verify the correct error message
public int a;
```
error message as follows
`error: .::test.bal:2:8: invalid qualifier 'public'`

error position column number has to be 1.

**Comment by SupunS** [comment] 2020-11-26 09:34
Duplicate of #24765

**Closed by SupunS** 2020-11-26 09:34 UTC
Labels: Area/Diagnostics, Area/Parser, Priority/Blocker, Team/CompilerFE, Type/Bug
