### ISSUE TITLE
Formatting does not work for attributes in records passed for parameters.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13794] opened 2019-02-22 05:04 UTC
**Description:**
Formatting does not work for attributes in records passed for parameters.
```
mysql:Client studentDb = new({
host:"localhost",
port: 5690,
name: "testdb",
username: "root",
password: "",
dbOptions: { useSSL: false }
});
```
above will not format properly.

**Comment by NipunaMarcus** [comment] 2019-05-29 05:09
Duplicate issue: https://github.com/ballerina-platform/ballerina-lang/issues/15373

**Comment by NipunaMarcus** [comment] 2019-07-02 07:31
The issue is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/16003 
hence closing the issue.

**Closed by NipunaMarcus** 2019-07-02 07:31 UTC
Labels: Area/Tooling, Component/Formatting, Component/LanguageServer, Type/Bug
