### ISSUE TITLE
code auto completion is not working.....(in vs code)

### ISSUE THREAD

**Issue by VJFernandez123** [ballerina-platform/ballerina-lang#10024] opened 2018-08-12 06:50 UTC
The user name of my machine has  a space. I think this is the issue for auto completion is not working. Also i can not use any libraries in my code.

**Comment by nadeeshaan** [comment] 2018-08-13 15:55
@VJFernandez123 this will be fixed in the next immediate release

**Comment by rasika** [comment] 2018-09-17 09:27
Hi @VJFernandez123,
Thanks for reporting this issue. We tried to reproduce the issue in Windows 10; using username "James Clark". Then saved a new ballerina file `test.bal` under the path `C:\Users\James Clark\Documents` path. Still, **we could retrieve all code completions**. 

Please note that **untitled** files in VSCode will not provide any code completions due to fact that Ballerina VSCode plugin is only activated for the files with `.bal` extension. Thus, in order to receive code completions,  you need to save it somewhere first.

If the above is not the case, can you please try it on a latest Ballerina version such as [0.981.1](https://ballerina.io/downloads/) and let us know the results.

**Used Ballerina Version:** 0.981.1
**Used VSCode Ballerina Plugin Version:** 0.981.1

**Note:** I am closing the ticket as it is working with the latest. Please  re-open if you encounter the same issue with the latest release.

**Closed by rasika** 2018-09-17 09:27 UTC
Labels: Component/LanguageServer, Resolution/InProgress, Severity/Blocker, Type/Bug
