### ISSUE TITLE
Renaming doesn't work as expected with cyclic unions

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#29742] opened 2021-03-31 10:30 UTC
**Description:**
$title.

**Steps to reproduce:**
Consider the following sample.

```ballerina
type CyclicUnion int|CyclicUnion[];

public function main() {
    CyclicUnion x = 1;
}
```

Renaming `CyclicUnion` to `Union` in the variable declaration renames as follows.
```ballerina
type CyclicUnion int|Union[];

public function main() {
    Union x = 1;
}
```

Changing the name in the type definition doesn't change anything else.
```ballerina
type Union int|CyclicUnion[];

public function main() {
    CyclicUnion x = 1;
}
```

Renaming the member of the union doesn't do anything.

**Affected Versions:**
slalpha4-SNAPSHOT

**Comment by pubudu91** [comment] 2021-04-05 12:23
This looks like a bug in the compiler. For cyclic types, it seems to create two type symbols for the same identifier, `CyclicUnion`. One, the regular type symbol created for the identifier in the type def, the second, for the reference to the type def in the union type. IMO, in the union, it should have the same type symbol as the type def.

I think in the symbol enter we've intended to do this. See https://github.com/ballerina-platform/ballerina-lang/blob/52aec0fe8322fee34e02a766a76ace53a65fdb28/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java#L1336. Here, if it contains a cyclic reference, it creates a type symbol, define it, and would later be looked up when resolving the union.

But the issue is, this `hasCyclicReference` flag is getting set after the above check is executed: https://github.com/ballerina-platform/ballerina-lang/blob/52aec0fe8322fee34e02a766a76ace53a65fdb28/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java#L1239

**Closed** 2021-04-16 11:38 UTC
Labels: Area/Compiler, Area/SemanticAPI, Priority/Blocker, Team/CompilerFE, Team/LanguageServer, Type/Bug
