### ISSUE TITLE
Compiler Crashes When a Submodule Test has a Compilation Error

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#27471] opened 2020-12-12 17:46 UTC
**Description:**
I have a package, including a submodule. When there's a compilation error in the submodule test file, the Package build is crashing with an NPE.

Following is the log generated:

```
[2020-12-12 23:09:44,091] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.Desugar.desugarObjectTypeInit(Desugar.java:5145)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5130)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:62)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:6654)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1228)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:6629)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1353)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:6629)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:6670)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:6680)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1136)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:6629)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1181)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:6629)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:949)
	at org.wso2.ballerinalang.compiler.tree.BLangClassDefinition.accept(BLangClassDefinition.java:106)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.desugarClassDefinitions(Desugar.java:870)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:773)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:6629)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:425)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:237)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:156)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:359)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:299)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:126)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:116)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:97)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:122)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:96)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.TestCommand.execute(TestCommand.java:200)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**
I observed this when there's an unused import in a test file of a submodule.

**Affected Versions:**
SLP8-SNAPSHOT

**OS, DB, other environment details and versions:**
OS: macOS

**Comment by azinneera** [comment] 2021-02-15 18:13
I tried to reproduce this with the following project:
```
proj1/
├── Ballerina.toml
├── Dependencies.toml
├── main.bal
└── modules
    └── mod1
        ├── mod1.bal
        └── tests
            └── mod1_tests.bal
```

The `proj1/modules/mod1/tests/mod1_tests.bal` has the unused `ballerina/io` import as shown below.
```
import ballerina/test;
import ballerina/io;

@test:Config{}
public function testFunc() {
  test:assertTrue(true, "Failed!");
}
```

With this project, I was not able to reproduce an NP. Instead the compilation gave the following error as intended.
```
Compiling source
	user/proj1:0.1.0
ERROR [modules/mod1/tests/mod1_tests.bal:(2:1,2:21)] unused import module 'ballerina/io'
error: compilation contains errors
```

**Comment by azinneera** [comment] 2021-02-15 18:18
It is possible to get this kind of a Null Pointer exception when an incompatible dependency distribution is used. @ThisaruGuruge can you let us know the exact scenario you tried?

**Comment by azinneera** [comment] 2021-02-15 18:37
This is reproducible with SL Alpha1 and has been fixed by https://github.com/ballerina-platform/ballerina-lang/pull/28464/. Therefore closing the issue.

**Comment by ThisaruGuruge** [comment] 2021-02-16 09:08
This can be reproducible using the following steps:

- Check out the GraphQL module
- Add `import ballerina/io;` to the following file:
https://github.com/ballerina-platform/module-ballerina-graphql/blob/442026d97073b8233b8694f861a7964c52a2e14b/graphql-ballerina/modules/parser/tests/char_reader_tests.bal#L17
  
Then this will be reproduced.

**Comment by azinneera** [comment] 2021-02-16 09:36
I was able to reproduce with the above steps. Thanks @ThisaruGuruge.

**Comment by sameerajayasoma** [comment] 2021-02-18 04:01
Is this related to package implementation?

**Comment by ayeshLK** [comment] 2021-02-19 06:07
I am writing a small application using `kafka`. In that also I am facing this similar issue. 

#### Lang Version ####

* SL Alpha 2

**Comment by ThisaruGuruge** [comment] 2021-03-30 09:13
Any update on this?

**Comment by azinneera** [comment] 2021-04-09 19:30
This looks like an issue with the compiler. Project API only resolves the imports and adds them into the package cache. This flow is working as expected. 

@pubudu91 thoughts please.

**Comment by pubudu91** [comment] 2021-04-15 04:56
> This looks like an issue with the compiler. Project API only resolves the imports and adds them into the package cache. This flow is working as expected.
> 
> @pubudu91 thoughts please.

Yeah, judging by the stack trace, looks like a bug in the compiler.

**Comment by rdhananjaya** [comment] 2021-04-28 08:47
@sameerajayasoma @azinneera What are the consequences of stopping the backend codegen when there are compilation errors in the dependencies?  Please reivew https://github.com/ballerina-platform/ballerina-lang/pull/30234

**Closed** 2021-05-03 06:23 UTC
Labels: Area/Compiler, Crash, Priority/Blocker, SwanLakeDump, Team/CompilerFE, Type/Bug
