### ISSUE TITLE
Module cache is not updated, when removing modules from IDE

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#29995] opened 2021-04-15 14:18 UTC
Steps: 

- Create a project with a sub-module. 
- Then call one of the functions in that submodule from the main module. 
- Then delete that submodule.
- You can still see LS  suggestions for that module. See the following screenshot. This is taken after removing the `calc` submodule. 

![image](https://user-images.githubusercontent.com/1356214/114883773-d6843f80-9e22-11eb-939d-50c89e4e130f.png)

**Comment by nadeeshaan** [comment] 2021-04-18 04:53
Tested locally and observed this is working. Can you confirm that there is a similar log in the output channel as following

`[Info  - 10:21:38 AM] Operation 'workspace/didChangeWatchedFiles' {module: 'testmod', uri: 'file:///.../testmod'} removed`

**Comment by IMS94** [comment] 2021-04-22 08:51
@hasithaa could you check this in the latest release and see if it's reproduced.

**Comment by malinthar** [comment] 2021-06-01 09:13
Could not reproduce this in the latest

**Comment by sanjana** [comment] 2021-06-18 09:52
Closing since this issue has been fixed in the SL Beta 1.

**Closed by sanjana** 2021-06-18 09:52 UTC
Labels: Priority/Blocker, Team/LanguageServer, Type/Bug
