### ISSUE TITLE
Finalize BIR model spec

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#19025] opened 2019-09-12 08:38 UTC
**Description:**
Finalize the BIR model tree.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment] 2020-08-10 06:40
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/24771

**Closed by Kishanthan** 2020-08-10 06:40 UTC
Labels: Area/jBallerina, Type/Task
