### ISSUE TITLE
[Debugger] backward slash should be escaped in file paths in windows

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#4482] opened 2018-01-23 06:25 UTC
**Description:**
Here is an example debug hit message.

`"{"code":"DEBUG_HIT","message":"Debug point hit.","threadId":"main:1","location":{"packagePath":".","fileName":",C:\Users\Aruna\projects\ballerina\samples\ballerina-by-example\examples\lengthof\lengthof.bal","lineNumber":9},"frames":[{"packageName":".","frameName":"main","fileName":",C:\Users\Aruna\projects\ballerina\samples\ballerina-by-example\examples\lengthof\lengthof.bal","lineID":9,"variables":[{"scope":"Local","name":"args","type":"string[]","value":"Array[0] []"},{"scope":"Local","name":"intArray","type":"int[]","value":"Array[3] [1, 2, 3]"},{"scope":"Local","name":"arrayLength","type":"int","value":"3"},{"scope":"Local","name":"jsonArray","type":"null","value":"null"}]}]}"`

This message cannot be `JSON.parse`ed. `\` characters need to be escaped. `"fileName":"C:\\examples\\lengthof\\lengthof.bal"`

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Comment by NipunaRanasinghe** [comment] 2020-07-01 07:13
Closing as the issue is no longer valid with the new jBallerina debugger implementation.

**Closed** 2020-07-01 07:14 UTC
Labels: Area/Tooling, Component/Debugger, Component/JVMCodeGen, Type/Bug
