### ISSUE TITLE
Top level completions are suggested inside a record

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13796] opened 2019-02-22 05:07 UTC
**Description:**
Top level completions are suggested inside a record and the record attributes are not getting suggested.

**Comment by nadeeshaan** [comment] 2019-03-20 07:44
Can you please share a sample for this?

**Comment by nadeeshaan** [comment] 2019-03-29 05:18
Could not reproduce in the latest master. Hence resolving the issue and if the issue observed further please reopen

**Closed by nadeeshaan** 2019-03-29 05:18 UTC
Labels: Component/LanguageServer, Type/Bug
