### ISSUE TITLE
[JBallerina] Ambiguous type error for union types

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#16304] opened 2019-07-07 17:30 UTC
**Description:**
The following program fails when compiling. The output of `jballerina build` command is also given below.

```ballerina
public function main() {
    MyRecord rec = {
        scopes: [["scope1"]]
    };
}

type MyRecord record {
    string[]|string[][] scopes;
};
```

_Output:_
```shell
Compiling source
    hello.bal
error: .::hello.bal:6:18: incompatible types: expected 'other', found 'other'
error: .::hello.bal:6:17: ambiguous type '(string[]|string[][])'
```

**Comment by grainier** [comment] 2019-07-09 01:25
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/16300, and will be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/16301

**Closed** 2019-07-11 03:46 UTC
Labels: Area/Language, Component/jBallerina, Priority/Blocker, Resolution/Duplicate
