### ISSUE TITLE
VSCode language server goes to 100% CPU after some time

### ISSUE THREAD

**Issue by wx-yz** [ballerina-platform/ballerina-lang#32020] opened 2021-08-04 23:15 UTC
**Description:**
VSCode language server process goes to 100% CPU after using the editor for some time. Roughly 30 - 45 minutes

**Steps to reproduce:**
1. Install Ballerina VSCode plugin version 2.1.0
2. Set ballerina.home to Swan Lake beta 2 release
3. Restart IDE and start using
4. After some time language server process goes to 100% CPU

**Affected Versions:**

VSCode Version
![vscode-version](https://user-images.githubusercontent.com/57770159/128266961-e9b4b6db-50d6-4afc-b1b2-41b438f57b1f.png)

Process CPU usage
![ps-view](https://user-images.githubusercontent.com/57770159/128266924-6409e5a6-ec00-4386-a5d4-40cb12a473e1.png)

Executed command (output from ps)
```
 5157 ?        Sl    17:24 /home/wxyz/.jdks/jdk-11.0.12+7/bin/java -Xbootclasspath/a: -Xms256m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/wxyz/projects/bal/heap-dump.hprof -classpath :/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/annotations-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/antlr4-runtime-4.5.1.wso2v1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/array-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/asm-7.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/asm-analysis-7.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/asm-commons-7.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/asm-tree-7.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/asm-util-7.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/atomikos-util-5.0.8.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/awslambda-extension-2.0.0-beta.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/axiom-api-1.2.22.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/axiom-impl-1.2.22.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/azurefunctions-extension-2.0.0-beta.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-bindgen-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-cli-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-core-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-lang-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-logging-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-metrics-extension-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-observability-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-observability-internal-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-parser-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-rt-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/ballerina-tools-api-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/bcpkix-jdk15on-1.61.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/bcprov-jdk15on-1.61.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/bool-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/broker-auth-0.970.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/broker-common-0.970.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/broker-coordination-0.970.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/broker-core-0.970.5.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/broker-rest-runner-0.970.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/central-client-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/commons-beanutils-1.9.4.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/commons-codec-1.9.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/commons-collections-3.2.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/commons-compress-1.19.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/commons-pool-1.5.6.wso2v1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/commons-text-1.9.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/compiler-0.8.9.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/datamapper-extension-2.0.0-beta.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/decimal-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/diagram-util-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/docerina-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/error-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/floatingpoint-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/formatter-cli-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/formatter-core-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/future-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/geronimo-activation_1.1_spec-1.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/geronimo-json_1.0_spec-1.0-alpha-1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/geronimo-stax-api_1.0_spec-1.0.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/grpc-native-0.8.0-beta.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/gson-2.7.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/handlebars-4.0.6.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/HikariCP-3.3.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/integer-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/internal-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jackson-annotations-2.11.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jackson-core-2.11.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jackson-databind-2.11.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jackson-dataformat-yaml-2.11.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jackson-datatype-jsr310-2.11.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jacocoagent.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jaeger-core-0.31.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jaeger-thrift-0.31.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/javacpp-1.4.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/java-diff-utils-4.5.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/javax.mail-1.6.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/javax.transaction-api-1.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jaxen-1.1.6.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jballerina.java-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jboss-logging-3.3.1.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jline-3.11.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/jzlib-1.1.3.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/kotlin-stdlib-1.3.31.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/kotlin-stdlib-common-1.3.31.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/kraal-0.0.16.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/language-server-commons-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/map-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/maven-resolver-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/metrics-core-3.1.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-buffer-4.1.39.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-codec-4.1.39.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-codec-http2-4.1.59.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-codec-http-4.1.59.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-common-4.1.39.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-handler-4.1.46.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-handler-proxy-4.1.39.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-resolver-4.1.39.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-tcnative-boringssl-static-2.0.25.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-transport-4.1.39.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-transport-native-epoll-4.1.39.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/netty-transport-native-kqueue-4.1.39.Final.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/object-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/observability-symbol-collector-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/okhttp-3.9.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/okio-1.13.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/openapi-cli-0.9.0-beta.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/openapi-validator-0.9.0-beta.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/org.jacoco.core-0.8.5.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/org.jacoco.report-0.8.5.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/org.wso2.carbon.core-5.1.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/org.wso2.carbon.messaging-2.3.7.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/org.wso2.carbon.metrics.core-2.3.7.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/org.wso2.securevault-1.0.0-wso2v2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/org.wso2.transport.http.netty-6.3.11.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/org.wso2.transport.local-file-system-6.0.55.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/picocli-4.0.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/progressbar-0.7.4.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/protobuf-java-3.9.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/proto-google-common-protos-1.17.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/quartz-2.3.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/quartz-jobs-2.3.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/query-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/runtime-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/shell-cli-0.0.1-SNAPSHOT.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/shell-core-0.0.1-SNAPSHOT.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/snakeyaml-1.24.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/stax2-api-3.1.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/staxon-core-1.2.0.wso2v2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/stream-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/string-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/syntax-api-calls-gen-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/table-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/testerina-core-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/testerina-runtime-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/toml-parser-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/transaction-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/transactions-5.0.8.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/transactions-api-5.0.8.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/transactions-jta-5.0.8.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/typedesc-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/value-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/woodstox-core-asl-4.2.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/bre/lib/xml-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/ballerinalang-data-mapper-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/c2c-tooling-2.0.0-beta.2.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/commons-io-2.7.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/guava-30.0-jre.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/json-to-record-converter-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/language-server-cli-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/language-server-core-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/language-server-stdio-launcher-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/org.eclipse.lsp4j-0.10.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/lang-server/lib/org.eclipse.lsp4j.jsonrpc-0.10.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/debug-adapter/lib/commons-io-2.7.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/debug-adapter/lib/debug-adapter-cli-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/debug-adapter/lib/debug-adapter-core-2.0.0-beta.2.1.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/debug-adapter/lib/java-semver-0.9.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/debug-adapter/lib/org.eclipse.lsp4j.debug-0.12.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/debug-adapter/lib/org.eclipse.lsp4j.jsonrpc-0.12.0.jar:/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2/lib/tools/debug-adapter/lib/org.eclipse.lsp4j.jsonrpc.debug-0.12.0.jar: -Dballerina.home=/home/wxyz/.local/bin/ballerina-swan-lake-beta2/distributions/ballerina-slbeta2 -Dballerina.version=2.0.0-beta.2.1 -Djava.util.logging.config.class=org.ballerinalang.logging.util.LogConfigReader -Djava.util.logging.manager=org.ballerinalang.logging.BLogManager -Denable.nonblocking=false -Djava.security.egd=file:/dev/./urandom -Dfile.encoding=UTF8 -Dballerina.target=jvm -Djava.command=/home/wxyz/.jdks/jdk-11.0.12+7/bin/java io.ballerina.cli.launcher.Main start-language-server
```

Thread dump [threaddump-1628117303948.zip](https://github.com/ballerina-platform/ballerina-lang/files/6934856/threaddump-1628117303948.zip)

Heap dump [heapdump-1628117362206.zip](https://github.com/ballerina-platform/ballerina-lang/files/6934857/heapdump-1628117362206.zip)

**OS, DB, other environment details and versions:**
Linux

```
$ java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
```

**Comment by malinthar** [comment] 2021-08-05 07:59
@wx-yz will you share the source code that you worked on, when you encountered the issue?

**Comment by wx-yz** [comment] 2021-08-05 14:33
Hi @malinthar I was trying out ballerina by example guide. Modifying, making mistakes, getting errors, and then correcting those, building and running. That's typical flow of any developer. So along that process if there's some mistake it's obviously not going to compile. So even after correcting and saving the program, these threads shouldn't start spinning and taking 100% CPU.

**Comment by malinthar** [comment] 2021-08-05 14:57
> Hi @malinthar I was trying out ballerina by example guide. Modifying, making mistakes, getting errors, and then correcting those, building and running. That's typical flow of any developer. So along that process if there's some mistake it's obviously not going to compile. So even after correcting and saving the program, these threads shouldn't start spinning and taking 100% CPU.

@wx-yz acknowledged with thanks

**Comment by IMS94** [comment] 2021-08-23 07:01
I could reproduce this randomly around a week ago and the corresponding java flight recording is attached here. As per that, seems like the compilation is going on a cycle within the parser's logic. Following is the corresponding thread dump (extracted).
```
"pool-1-thread-1" #13 prio=5 os_prio=0 cpu=7111812.35ms elapsed=7410.03s tid=0x00007f5a78db9800 nid=0xa87c7 runnable  [0x00007f5a39fa7000]
   java.lang.Thread.State: RUNNABLE
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.getNextRule(BallerinaParserErrorHandler.java:3003)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:527)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:468)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1198)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:276)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:528)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:468)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1198)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:276)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:521)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:468)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1198)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:276)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:521)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.fixAndContinue(AbstractParserErrorHandler.java:468)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1198)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:276)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:369)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:2343)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1187)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:276)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatch(AbstractParserErrorHandler.java:247)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.getResolution(AbstractParserErrorHandler.java:121)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.recover(AbstractParserErrorHandler.java:106)
	at io.ballerina.compiler.internal.parser.AbstractParser.recover(AbstractParser.java:107)
	at io.ballerina.compiler.internal.parser.BallerinaParser.recover(BallerinaParser.java:18302)
```

[ls_jfr_1.zip](https://github.com/ballerina-platform/ballerina-lang/files/7029759/ls_jfr_1.zip)

**Comment by malinthar** [comment] 2021-08-23 07:12
> Today @malinthar had reproduced this on nballerina and we have a known set of steps to reproduce it there.

Yes. When I played around with union types in the following file https://github.com/ballerina-platform/nballerina/blob/main/compiler/modules/types/core.bal could reproduce the issue.

Try creating  the following function in the above file and do multiple text edits inside the function.
```ballerina
public function singleValue(SemType t) returns [string|int|boolean|()]? {  
    if t === NIL {
        return [()];
    } 
    else if t is UniformTypeBitSet {
        return ();
    } else if isSubtypeSimple(t,INT) {
        SubtypeData sd = t.getSubTypeData(UT_INT);
    } else if  isSubtypeSimple(t,STRING) {
        SubtypeData sd = t.getSubTypeData(UT_STRING);
    }
}
```

Following are the JFR and thread, heap dumps.
JFR: https://drive.google.com/file/d/1o_qfbyDcKBolIcZN1hVt4xyBCoLhLczq/view?usp=sharing
Thread dump:
[threaddump-1628687454319(1).zip](https://github.com/ballerina-platform/ballerina-lang/files/7029820/threaddump-1628687454319.1.zip)

**Comment by IMS94** [comment] 2021-08-23 12:52
Thanks @malinthar for reproducing. When debugged this for the root cause, it was noticed that an OOM issue occurs at the same time. Created #32289 and #32290 to track them. 

After analyzing the heap dumps and thread dumps of close intervals, our guess is that the OOM issue cause GC threads to work frequently. Thus the high CPU usage. Thread dumps showed different stack traces in different dumps suggesting the above fact. Also we noticed that the GC threads have consumed a lot of CPU time as well.

We will be investigating further on this once the mentioned OOM issues are fixed.

**Comment by IMS94** [comment] 2021-09-09 07:36
With #32658, we introduce a simulator to simulate long running and extensive coding sessions against language server. It should be helpful in identifying this type of performance issues.

**Comment by mohanvive** [comment] 2021-09-14 04:03
Closed with https://github.com/ballerina-platform/ballerina-lang/issues/32658 .

**Closed by mohanvive** 2021-09-14 04:03 UTC
Labels: Type/Bug, Team/LanguageServer, Priority/Blocker, Points/7, Area/Performance
