### ISSUE TITLE
Improve diagnostics view when non project dependencies have errors.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#29994] opened 2021-04-15 14:06 UTC
This issue is observed when importing a module from the central. The module in the central is not compiling with the latest lang master. So when importing the module, LS shows diagnostics related to that module. When clicking on those diagnostics VSCode can't locate the file and asking to create a file.

![image](https://user-images.githubusercontent.com/1356214/114882570-b3a55b80-9e21-11eb-9794-ca631df5e9ad.png)

**Comment by hasithaa** [comment] 2021-04-15 14:09
I was using the VSCode dev mode.

**Comment by nadeeshaan** [comment] 2021-04-27 10:53
Caused by #30207

**Comment by dulajdilshan** [comment] 2021-04-29 08:50
Fixed in slalpha4 and slalpha5

**Closed by dulajdilshan** 2021-04-29 08:50 UTC
Labels: Priority/High, Team/LanguageServer, Type/Improvement
