### ISSUE TITLE
Values initialized in the field will not be considered within the constructor.

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-platform/ballerina-lang#6849] opened 2018-04-07 09:39 UTC
**Steps to reproduce:**
```java
type employee object {
    public {
        int age;
        string name = "A";
    }

    new (int age = 30, name) {
        self.name = self.name + name;
        self.age = age;
    }
};

function testStructInitializerOrder() returns (int, string){
    employee p = new (age = 40, "B");
    return (p.age, p.name);
}
```
this should provide employee name as AB but currently gives as BB.

**Comment by afkham** [comment] 2018-04-07 13:42
I think this is by design. Value should be initialized in the constructor only. That way it is clear that values will be initialized in only one place.

**Comment by lankavitharana** [comment] 2018-06-11 11:20
Yes this is by design, 
in the constructor, you have used "name" field, so at the beginning of the constructor, the value of the "name" field will become "B" hence the output "BB"

if you change the constructor as below
```ballerina
new (int age = 30, name) {
        self.name = self.name + name;
        self.age = age;
    }
```
that should give you the intended output "AB"

**Closed by lankavitharana** 2018-06-11 11:20 UTC
Labels: Type/Bug, component/BVM
