### ISSUE TITLE
Ballerina command fails when cache directories not present in .ballerina home

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#23106] opened 2020-05-05 12:44 UTC
**Description:**
I deleted the contents of my `.ballerina` directory and installed a fresh copy of ballerina. But when I try to run the `ballerina run` or `ballerina build` command, it failed with the following error:

```
error: unable to create target directory:
```
This error message does not provide much help with the error. Then I tried to debug it.

When debugging found that the issue is that the `balo_cache`, `bir_cache-1.2.3` and the `jar_cache-1.2.3` directories are missing and it throws an exception.

**Steps to reproduce:**
- Install ballerina 1.2.2 using the installer
- Run a sample program using it
- Remove ballerina 1.2.2 (I did this by removing `/Library/Ballerina` directory)
- Delete the above mentioned directories (`balo_cache`, `bir_cache-*`, `jar_cache-*`) from the `.ballerina` home directory.
- Install ballerina 1.2.3 using the installer
- Try to run the same program

**Affected Versions:**
1.2.2, 1.2.3

**OS, DB, other environment details and versions:**
OS: MacOS Catalina

**Comment by suganyasuven** [comment] 2020-05-11 09:48
Could not able to reproduce the issue with the mentioned steps. Hence closing the issue.

**Closed** 2020-05-11 09:52 UTC
Labels: Area/BuildTools, Type/Bug
