### ISSUE TITLE
Cannot export the diagram as a PNG

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6256] opened 2018-04-03 10:40 UTC
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Thursday Aug 03, 2017 at 10:37 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/2659_

----

Release - 0.91
Firefox

Cannot export the diagram as a PNG

**Comment by uthaiyashankar** [comment] 2018-04-03 10:40
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Thursday Aug 10, 2017 at 10:19 GMT_

----

This looks like firefox browser related disability. 
https://bugzilla.mozilla.org/show_bug.cgi?id=788226
I'm currently researching on ways to fix this issue.

**Comment by uthaiyashankar** [comment] 2018-04-03 10:40
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dilinisg](https://github.com/dilinisg)**
_Saturday Nov 04, 2017 at 16:24 GMT_

----

Can still observe in 0.95 release

**Comment by hevayo** [comment] 2018-05-14 09:17
Duplicate of #8310

**Closed by hevayo** 2018-05-14 09:17 UTC
Labels: Imported, On Hold, Priority/High, Severity/Blocker, Type/Bug, component/Composer
