### ISSUE TITLE
Testarina (and java.jdbc module) doesn't pick up mysql driver during test execution

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19069] opened 2019-09-17 07:08 UTC
**Description:**
Testarina (and java.jdbc module) doesn't pick up Mysql driver during test execution

**Steps to reproduce:**

1) Create an ballerina project
2) Create to modules namely [db, api]
3) In 'db' module initialize a jdbc client (ballerinax/java.jdbc;)
4) Use above jdbc client in api to put/get some data from a database.
5) Place my sql driver a following folder <PROJECT_HOME>/lib/
6) Add following configuration in ballerina.toml
 `
[platform]
target = "java8"

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.17"
    path = "lib/mysql-connector-java-8.0.17.jar"
    groupId = "mysql"
    modules = ["api"]
`

7) Write couple of unit testcases for the project ( preferably in 'api' module)

8) build all modules (i.e. ballerina build -a) 

9) Observe an error similar to below in the command line:
`
	[fail] Error while initializing test suite: {ballerinax/java.jdbc}ApplicationError message=error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost/choreo:No suitable driver
	at ballerinax.java_jdbc:createClient(jdbc_client.bal:88)
	   ballerinax.java_jdbc.Client:__init(client_endpoint.bal:27)
	0 passing
	0 failing
	3 skipped
`

Work around is to copy the mysql connector to following location:
`/Library/Ballerina/ballerina-1.0.0/distributions/jballerina-1.0.0/bre/lib/`

**Affected Versions:**
1.0
**OS, DB, other environment details and versions:**
MacOS+bash, MySQL, JDK 1.8
**Related Issues (optional):**

**Suggested Labels (optional):**
Bug

**Suggested Assignees (optional):**
@anupama-pathirage @Manuri

**Comment by Kishanthan** [comment] 2019-11-21 08:02
This issue is already fixed in 1.0.x branch and cannot be reproduced anymore. Further, the workaround to copy the driver to bre/lib is also not needed anymore as the build command now correctly picks the driver from the classpath.

Also since the database configurations are given via a conf file, it also has to be passed in along with the build command as follow.

`ballerina build -a -- --b7a.config.file=ballerina-test.conf `

**Closed** 2020-03-02 07:35 UTC
Labels: Area/BuildTools, Component/Testerina, Points/0.5, Priority/Blocker, Type/Bug
