### ISSUE TITLE
Invalid dignostic BCE3843 'invalid access of mutable storage in an isolated function'

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#32650] opened 2021-09-09 02:56 UTC
Reported in https://github.com/wso2/ballerina-plugin-vscode/issues/116

**Description:**
The VS Code Plugin sometimes reports diagnostics of type [BCE3943](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/ballerinalang/util/diagnostic/DiagnosticErrorCode.java) `invalid access of mutable storage in an 'isolated' function` which do not lead to compilation errors when the code is compiled with `bal build` on the command line.

The diagnostics reported by the VS Code Plugin are either false positives or there is an inconsistency between the VS Code Plugin and the command line compiler.

**Steps to reproduce:**

```bash
# clone a demo repository
$ git clone https://bitbucket.org/gubaer/ballerina-issue-dynamic-grpc.git
$ cd ballerina-issue-dynamic-grpc

# start VS code
$ code .
```
![Screenshot from 2021-09-04 13-18-20](https://user-images.githubusercontent.com/249051/132092614-4e9d25f7-a7b8-41b8-8c15-418b606654cc.png)

**Affected Versions:**
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5

VS Code Plugin v2.1.0 (6/25/2021)

**OS, DB, other environment details and versions:**
Linux integrationbox 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by MaryamZi** [comment] 2021-09-09 05:36
Probably a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/31676.

**Comment by IMS94** [comment] 2021-09-15 04:50
@MaryamZi I had a look at this. As mentioned y @nadeeshaan in #31676, this seems to be caused by subsequent compilations. Following are my findings.

When this diagnostic is reported, at https://github.com/ballerina-platform/ballerina-lang/blob/445436c5a8169bcd5e162ecf5e830c35f837d1fb/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java#L1265, `symbol.owner` and `enclInvokable.symbol` **aren't the same**. Since we check equality of identity of those objects, they don't match.

When this diagnostic isn't reported, `symbol.owner` and `enclInvokable.symbol` are the same.

**Closed** 2021-09-21 04:09 UTC
Labels: Type/Bug, Team/LanguageServer, Priority/Blocker, Area/Diagnostics, Points/3, SwanLakeDump
