### ISSUE TITLE
[Ballerina Native] Build with error: unsupported constant type: S 

### ISSUE THREAD

**Issue by muharihar** [ballerina-platform/ballerina-lang#10683] opened 2018-10-04 04:04 UTC
**Description:**
Try to compile ballerina hello-world example using ballerina native compiler.

**Steps to reproduce:**

- copy "hello-world" example from ballerina example distribution folder (ballerina)

```
cp -r /Library/Ballerina/ballerina-0.982.0/docs/examples/hello-world <destination>
```

- build using command: 
```bash
ballerina build --native -o hello_world_native  hello_world.bal 
```
- error:
```
Compiling source
    hello_world.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

**Affected Versions:**

- ballerina-0.982.0

**OS, DB, other environment details and versions:**

- MacOS High Sierra (Version 10.13.4)

**Related Issues (optional):**
- Ballerina output log:
```
[2018-10-04 10:58:52,230] ERROR {org.ballerinalang.launcher.Main} - unsupported constant type: S 
java.lang.IllegalStateException: unsupported constant type: S
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:146)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNonTerminator$ConstantLoad.accept(BIRNonTerminator.java:152)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$visit$1(BIRInstructionWriter.java:60)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:60)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:162)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$writeBBs$0(BIRInstructionWriter.java:51)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.writeBBs(BIRInstructionWriter.java:51)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeBasicBlocks(BIRBinaryWriter.java:110)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunction(BIRBinaryWriter.java:105)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.lambda$writeFunctions$0(BIRBinaryWriter.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunctions(BIRBinaryWriter.java:80)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.write(BIRBinaryWriter.java:59)
	at org.ballerinalang.compiler.backend.llvm.NativeGen.getBinaryForm(NativeGen.java:207)
	at org.ballerinalang.compiler.backend.llvm.NativeGen.getFunctionArgs(NativeGen.java:199)
	at org.ballerinalang.compiler.backend.llvm.NativeGen.genObjectFile(NativeGen.java:144)
	at org.ballerinalang.compiler.backend.llvm.NativeGen.genBinaryExecutable(NativeGen.java:95)
	at org.ballerinalang.packerina.cmd.BuildCommand.genNativeBinary(BuildCommand.java:217)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:92)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:65)
```

**Comment by vinok88** [comment] 2018-10-08 06:12
Thanks for reporting the issue. 

Ballerina native compiler is still in a POC level. It's nowhere in a usable status. This issue will be fixed in the future.

You are getting above error because of the strings within println is not yet supported. Try putting an int there, it will work.
```ballerina
import ballerina/io;
public function main() {
    io:println(10);
}
```

Stay tuned for a fully working native compiler relaese.
Thanks.

**Comment by muharihar** [comment] 2018-10-12 03:19
Thanks Vinod, It's work for me!

```
import ballerina/io;

public function main() {
    int endValue = 100;
    int sum = 0;
    int i = 0;

    while (i < endValue) {
        sum = sum + i;
        io:println(i);
        io:println(sum);

        i = i + 1;
    }
}
```

Waiting for the next fully awesome features

**Comment by sameerajayasoma** [comment] 2018-11-19 17:39
Closing the issue since this is not a bug in the native compiler.

**Closed by sameerajayasoma** 2018-11-19 17:39 UTC
Labels: Component/NativeCompiler, Type/Improvement
