### ISSUE TITLE
Bad sad error when desugaring singleton type (numeric-literal)

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#26129] opened 2020-09-28 07:13 UTC
**Description:**

Bad-Sad error for singleton type descriptor.

#### Code
```Ballerina
function convertData() {
    2 x = 2;
}
```

#### Swan Lake
```LogTalk
[2020-09-28 16:49:45,137] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:777)
        at org.wso2.ballerinalang.compiler.tree.types.BLangFiniteTypeNode.accept(BLangFiniteTypeNode.java:59)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1092)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1221)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5627)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:5637)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1019)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1057)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5644)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:731)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:158)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:396)
        at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:361)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:303)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:250)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:142)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:220)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:58)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:297)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Steps to reproduce:**
Run above code in Swan Lake channel.

**Affected Versions:**
All the Swan Lake versions are affected

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

**Suggested Labels (optional):**
Area/Parser

**Suggested Assignees (optional):**

**Comment by rdhananjaya** [comment] 2020-09-28 09:16
`2` is treated as a singleton type descriptor here. I think this is not a bug.
https://ballerina.io/ballerina-spec/spec.html#singleton-type-descriptor

**Comment by rdhananjaya** [comment] 2020-09-28 09:17
However we get a BAD-SAD for following

import ballerina/io;
```ballerina
public function main() {
    2 x = 2;
    io:println(x);
}```

```
[2020-09-28 14:29:28,605] SEVERE {b7a.log.crash} - null 
java.lang.AssertionError
	at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:777)
	at org.wso2.ballerinalang.compiler.tree.types.BLangFiniteTypeNode.accept(BLangFiniteTypeNode.java:59)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1092)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1221)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5627)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:5637)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1019)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1057)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5644)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:731)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:158)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:5586)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:396)
	at org.wso2.ballerinalang.compiler.CompilerDriver.desugar(CompilerDriver.java:361)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:303)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:250)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:142)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:220)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:58)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:297)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Comment by KRVPerera** [comment] 2020-09-28 11:17
Agree.

**Comment by lochana-chathura** [comment] 2021-03-12 08:08
The second sample also compiles with no errors in the current master. Hence closing the issue.

**Closed by lochana-chathura** 2021-03-12 08:08 UTC
Labels: Area/Desugar, CompilerSLDump, Team/CompilerFE, Type/Bug
