### ISSUE TITLE
Remote debug behavior on windows 7 firefox 59.0.2 browser is different to the linux

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8308] opened 2018-05-01 09:43 UTC
**Description:**
Remote debug behavior on windows 7 fire-fox 59.0.2 browser is different to the Linux

**Preconditions**
/etc/hosts file should be updated

**Steps to reproduce:**
1.start the composer using --port flag `ex:composer --port 9999`
2.start the sample in debug mode as ex: `ballerina run c:\ballerina\ballerina-examples\examples\hello-world\hello-world.bal --debug 5006`
3.start the composer and open the hello world sample
4.click on remote debug and set 127.0.1.1:5006 
The composer will print `"Could not connect to debugger" Retry/Cancel`

However, the debug output is as below

```
C:\ballerina\ballerina-tools-0.970.1-SNAPSHOT\bin>ballerina run c:\ballerina\ballerina-examples\examples\hello-world\hello
_world.bal --debug 5006
Ballerina remote debugger is activated on port : 5006
Hello, World!
```
**Affected Versions:**
1.ballerina-tools-0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
1.Ubuntu 16.04
2.Java 1.8.0__161
3.Windows 7

**Related Issues (optional):**

Note: on ubuntu even if we enter localhost/127.0.1.1 or hostname ex:ubuntuhost the composer side we dont see this error
![windows7_firefox](https://user-images.githubusercontent.com/6552100/39468709-2327ba44-4d52-11e8-9cb6-538a4f2774c5.png)

**Comment by pahans** [comment] 2018-06-01 08:47
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/8267

**Closed by pahans** 2018-06-01 08:47 UTC
Labels: Priority/Normal, component/Composer
