### ISSUE TITLE
FormParam is not supported for Content-Type: multipart/form-data

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#3075] opened 2017-07-26 12:26 UTC
This should be added after implementing multipart support in ballerina.

**Comment by erandidesilva** [comment] 2017-07-27 06:09
Duplicate of https://github.com/ballerinalang/ballerina/issues/2476

**Comment by shafreenAnfar** [comment] 2018-04-10 06:25
Mutipart form data is now supported.

**Closed by shafreenAnfar** 2018-04-10 06:25 UTC
Labels: HTTP, L1/L2 for May, Type/Improvement, component/stdlib
