### ISSUE TITLE
[Bug]: Listener port not starting interminently.

### ISSUE THREAD

**Issue by tharindu1st** [ballerina-platform/ballerina-lang#38948] opened 2022-11-29 16:08 UTC
### Description

We Have two services wired into a single HTTP listener instance in a single ballerina package.
When running with two services we can see the listener start intermittently.

When not starting happens As per debugging [1] not get invoked at the error state. Please refer to the ballerina module[2] used to debug.

[1] https://github.com/ballerina-platform/module-ballerina-http/blob/master/native/src/main/java/io/ballerina/stdlib/http/api/service/endpoint/Start.java#L50
[2] - https://github.com/wso2/apk/tree/main-abandoned/runtime/runtime-domain-service/ballerina

### Related area

-> Runtime

### Suggested label(s) (optional)

BUG

### Suggested assignee(s) (optional)

@TharmiganK @shafreenAnfar

**Comment by tharindu1st** [comment] 2022-12-16 08:32
@HindujaB,
This is happening due to running a worker thread with a busy while loop.
```
        worker WatchAPIThread {
            while true {
 }
}
```
Once comment out this loop listener got started properly.

**Comment by HindujaB** [comment] 2022-12-19 07:26
The issue happens due to a worker is not terminated inside the `init` method. 
The `apk` module contains the following elements. 
- A user-defined `init` function which contains a worker with a busy loop. 
- A global-level listener which is shared by multiple services.

In Ballerina runtime, we schedule the module-level functions in a specific order. And we wait for each phase to be complete before scheduling the next one. 
- `init` phase - we initialize global-level variables, execute the user-defined `init` function
- `start` phase - we start the listeners on the specified ports
- `main` phase - execute the main function or the defined services

The issue happens as the `init` phase is waiting for the worker to terminate before executing the `start` function (Where we start the listeners). As per the current behavior, each ballerina function is waiting for its workers to terminate before terminating itself. 

This is a spec deviation that is still under discussion, whether to wait for the workers or not before terminating. 
https://github.com/ballerina-platform/ballerina-lang/issues/28536

**Comment by warunalakshitha** [comment] 2023-01-03 06:11
As per the @HindujaB comment this behaviour is according to the current spec. The start phase will be start once all the workers start in the init terminated. If there are any busy loops , start phase will not be proceed. I am closing this issue since it is not a bug. 

Please feel free to reopen if you have further queries on this.

**Comment by warunalakshitha** [comment] 2023-01-13 16:54
I have reopened the issue as per latest spec discussion init should not wait until workers terminated. We need to fix the runtime.

**Closed** 2023-03-16 08:06 UTC
Labels: Type/Bug, Priority/High, Team/jBallerina, Reason/Other
