### ISSUE TITLE
Parser drops the service keyword for incomplete source snippet

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31482] opened 2021-06-29 05:39 UTC
**Description:**
$title

Consider the following source snippet which is incomplete.
`service O1 <cursor>`

**Affected Versions:**
swanlake beta2 at least

**Comment by lochana-chathura** [comment] 2021-07-01 06:53
Related to #31504

**Comment by lochana-chathura** [comment] 2021-07-15 06:00
Duplicate of #31489.

**Closed by lochana-chathura** 2021-07-15 06:00 UTC
Labels: Area/Parser, Priority/Blocker, Team/CompilerFE, Team/LanguageServer, Type/Bug
