### ISSUE TITLE
Public streams in another module cannot be directly accessed

### ISSUE THREAD

**Issue by RameshaKaru** [ballerina-platform/ballerina-lang#14385] opened 2019-03-14 05:12 UTC
**Description:**
The code did not work when trying to access public streams in another module, but it did not produce an error.
When a reference copy was made of the public stream, the code worked.

**Steps to reproduce:**

function initSubscriptionSilverPolicy() {
    stream<gateway:IntermediateStream> intermediateStream = new;
    stream<gateway:GlobalThrottleStreamDTO> resultStream = new;
    stream<gateway:EligibilityStreamDTO> eligibilityStream = new;
    forever {
        from gateway:requestStream
        select gateway:requestStream.messageID, (gateway:requestStream.subscriptionTier == "Silver") as isEligible, gateway:requestStream.subscriptionKey as throttleKey
        => (gateway:EligibilityStreamDTO[] counts) {
        foreach var c in counts{
            eligibilityStream.publish(c);
        }
        }
}
}

The above code did not work.

stream<gateway:IntermediateStream> intermediateStream = new;
stream<gateway:GlobalThrottleStreamDTO> resultStream = new;
stream<EligibilityStreamDTO> eligibilityStream = new;
stream<gateway:RequestStreamDTO> reqCopy= gateway:requestStream;
stream<gateway:GlobalThrottleStreamDTO> globalThrotCopy = gateway:globalThrottleStream;

function initSubscriptionSub_5Policy() {
    
    forever {

            from reqCopy
            select printKey(reqCopy.messageID) as messageID, true as isEligible, printKey(reqCopy.subscriptionKey) as throttleKey, 0 as expiryTimestamp
            => (EligibilityStreamDTO[] counts) {
            foreach var c in counts{
                eligibilityStream.publish(c);
            }
            }
}
}

After creating a copy, the code worked.

Given below are the records defined in another module(gateway)

public type RequestStreamDTO record {
    string messageID="";
    string apiKey="";
    string appKey="";
    string subscriptionKey="";
    string appTier="";
    string apiTier="";
    string subscriptionTier="";
    string resourceKey="";
    string resourceTier="";
    string userId="";
    string apiContext="";
    string apiVersion="";
    string appTenant="";
    string apiTenant="";
    string appId="";
    string apiName="";
    string properties="";
};

public type GlobalThrottleStreamDTO record {
    string throttleKey ="";
    boolean isThrottled=false;
    boolean stopOnQuota=false;
    int expiryTimeStamp=0;
};

public type EligibilityStreamDTO record {
    string messageID="";
    boolean isEligible=false;
    string throttleKey="";
};

public type ThrottleAnalyticsEventDTO record {
    string metaClientType="";
    string userName="";
    string userTenantDomain="";
    string apiName="";
    string apiVersion="";
    string apiContext="";
    string apiCreator="";
    string apiCreatorTenantDomain="";
    string applicationId="";
    string applicationName="";
    string subscriber="";
    string throttledOutReason="";
    string gatewayType="";
    int throttledTime=0;
    string hostname="";
};

public type IntermediateStream record{
    string throttleKey ="";
    int eventCount=0;
    boolean stopOnQuota=false;
    int expiryTimeStamp=0;
};

**Affected Versions:**
0.990.3

**Comment by gimantha** [comment] 2019-03-26 10:53
Hi @RameshaKaru 
This is actually not a bug. You cannot directly import a variable reference in a different module. You have to expose it via a getter function. Please try with a getter function. I am closing this issue. If you further have any doubts, please reopen this issue.

**Closed by gimantha** 2019-03-26 10:53 UTC
Labels: Component/Streams, Type/Bug
