### ISSUE TITLE
[Question] While debugging, is it possible to dynamically highlight sequence diagram?

### ISSUE THREAD

**Issue by scheung38** [ballerina-platform/ballerina-lang#23090] opened 2020-05-04 17:55 UTC
So user can see where it is currently in sequence diagram?

**Comment by NipunaRanasinghe** [comment] 2021-06-14 05:14
Closing as the issue is moved to the vscode plugin repository. (https://github.com/wso2/ballerina-plugin-vscode/issues/92)

**Closed by NipunaRanasinghe** 2021-06-14 05:14 UTC
Labels: Area/Debugger, Team/DevTools, Type/Question
