### ISSUE TITLE
Ballerina Performance Test Results show errors when message size is 1KiB

### ISSUE THREAD

**Issue by chrishantha** [ballerina-platform/ballerina-lang#10440] opened 2018-09-18 06:47 UTC
**Description:**
We have automated Ballerina Performance tests and we see 100% errors when the message size is 1KiB. Please refer below table for more details.

|Scenario Name|Heap Size|Concurrent Users|Message Size (Bytes)|Sleep Time (ms)|# Samples|Error Count|Error %|Average (ms)|Standard Deviation (ms)|Min (ms)|Max (ms)|75th Percentile (ms)|90th Percentile (ms)|95th Percentile (ms)|98th Percentile (ms)|99th Percentile (ms)|99.9th Percentile (ms)|Throughput (Requests/sec)|Received (KB/sec)|Sent (KB/sec)|Ballerina GC Throughput (%)|Ballerina Footprint (M)|Ballerina Average of Footprint After Full GC (M)|Ballerina Standard Deviation of Footprint After Full GC (M)|Ballerina Load Average - Last 1 minute|Ballerina Load Average - Last 5 minutes|Ballerina Load Average - Last 15 minutes|
|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
|passthrough_http|1g|100|50|0|2666360|0|0|4.46|6.6|0|230|4|6|10|24|39|76|22213.37|4013.16|5032.72|99.19|1022.5|||3.50|1.37|0|
|passthrough_http|1g|100|50|30|387572|0|0|30.91|1.11|30|77|31|31|32|32|33|42|3228.45|583.26|731.45|99.86|1022.5|||2.17|1.33|0|
|passthrough_http|1g|100|1024|0|1576|1576|100|7593.55|4261.95|0|10014|10047|10047|10047|10047|10047|10047|12.13|21.49|0|9.56|981.5|792.956|27.379|2.91|1.80|0|
|passthrough_http|1g|100|1024|30|1199|1199|100|10016|0|10000|10011|10047|10047|10047|10047|10047|10047|9.24|14.98|0|∞|-2199023255552|||3.51|2.31|0|
|passthrough_http|1g|200|50|0|4152128|4152128|100|4.93|9.45|0|3050|6|7|9|16|31|100|34602.22|69542.35|0|∞|-2199023255552|||2.66|2.30|0|
|passthrough_http|1g|200|50|30|775730|0|0|30.88|1.63|30|263|31|31|31|32|34|62|6464.04|1167.82|1464.51|99.67|1021.5|||1.96|2.05|0|
|passthrough_http|1g|200|1024|0|2690|2690|100|8890.28|3157.57|0|10015|10047|10047|10047|10047|10047|10047|20.69|34.96|0|7.13|981.5|791.852|31.801|2.79|2.34|0|
|passthrough_http|1g|200|1024|30|5126722|5126722|100|4.11|4.47|0|1030|5|5|6|11|21|57|42685.69|85788.23|0|∞|-2199023255552|||1.31|2.03|0|
|passthrough_https|1g|100|50|0|2380260|0|0|5|6.97|0|344|5|10|15|25|36|78|19823.77|3620.16|4491.32|99.21|1022.5|16.404|0|4.65|3.16|1|
|passthrough_https|1g|100|50|30|388687|0|0|30.83|1.06|30|73|31|31|31|32|32|42|3235.63|590.88|733.07|99.83|1022.5|16.774|0|2.81|2.72|0|
|passthrough_https|1g|100|1024|0|668|668|100|17114.66|10903.89|2|37327|30079|30079|31103|37119|37375|37375|4.38|10.18|0|11.45|981.5|928.015|55.644|3.24|2.91|0|
|passthrough_https|1g|100|1024|30|1417656|1417656|100|7.55|203.41|0|30020|3|4|5|9|31|130|11818.33|26775.84|0|∞|-2199023255552|||3.02|2.94|0|
|passthrough_https|1g|200|50|0|2527744|0|0|9.44|9.52|0|253|11|18|24|38|51|99|21050.67|3844.22|4769.29|98.81|1022|16.976|0|6.32|4.20|0|
|passthrough_https|1g|200|50|30|770588|0|0|31.1|2.52|30|237|31|31|32|33|35|62|6415.42|1171.57|1453.49|99.59|1021|17.328|0|3.90|3.66|0|
|passthrough_https|1g|200|1024|0|1717|1717|100|13121.47|7336.44|1053|37234|10047|30079|30079|30079|30079|33279|13.21|30.12|0|11.69|981.5|925.422|57.122|3.73|3.62|0|
|passthrough_https|1g|200|1024|30|3423826|3423826|100|5.52|12.24|0|1030|6|7|11|38|73|140|28514.3|64602.71|0|∞|-2199023255552|||1.46|2.68|0|
|transformation_http|1g|100|50|0|1676680|0|0|7.12|9.17|0|222|7|12|18|34|53|102|13967.91|2905.43|3137.32|98.57|1022.5|15.125|0|3.94|3.36|0|
|transformation_http|1g|100|50|30|388223|0|0|30.86|1.03|30|70|31|31|31|32|33|42|3233.63|672.62|726.3|99.66|1022|15.388|0|2.45|2.85|0|
|transformation_http|1g|100|1024|0|779922|779922|100|15.15|144.72|0|7249|2|3|9|22|1007|1039|6420.64|14352.4|0|91.65|999.5|169.569|20.983|3.11|3.01|0|
|transformation_http|1g|100|1024|30|779376|779376|100|15.13|139.27|0|10019|2|4|10|23|1011|1039|6487.29|14501.3|0|90.74|997.5|164.374|48.464|3.74|3.27|0|
|transformation_http|1g|200|50|0|1752440|0|0|13.65|12.1|1|270|15|23|31|48|68|130|14599.04|3036.72|3279.08|97.62|1021.5|15.465|0|5.35|3.98|0|
|transformation_http|1g|200|50|30|765001|0|0|31.33|3.07|30|265|31|32|32|35|47|62|6370.5|1325.11|1430.87|99.08|1020|15.842|0|3.57|3.57|0|
|transformation_http|1g|200|1024|0|769432|769432|100|30.69|201.12|0|3144|4|12|31|1007|1031|3039|6370.05|14239.3|0|89.63|997|172.983|32.671|3.97|3.70|0|
|transformation_http|1g|200|1024|30|778026|778026|100|30.03|215.55|0|7304|3|11|27|1003|1031|3055|6450.12|14418.28|0|89.21|1000|189.477|47.077|4.09|3.78|0|
|transformation_https|1g|100|50|0|1476741|0|0|8.08|8.23|0|220|9|14|19|33|49|88|12299.72|2582.46|2762.63|98.65|1022.5|25.222|0|4.68|4.06|0|
|transformation_https|1g|100|50|30|387507|0|0|30.92|1.08|30|73|31|31|31|32|33|44|3228.04|677.76|725.05|99.62|1022|25.015|0|3.06|3.52|0|
|transformation_https|1g|100|1024|0|382942|382942|100|31.18|16.97|1|166|40|54|63|75|83|108|3189.88|7130.51|0|98.96|1020|16.965|0|4.94|4.09|0|
|transformation_https|1g|100|1024|30|381575|381575|100|31.3|17.3|1|218|41|54|64|76|84|111|3178.18|7104.34|0|98.96|1019.5|16.918|0|6.33|4.80|1|
|transformation_https|1g|200|50|0|1589618|0|0|15.05|11.82|0|228|17|26|35|50|65|124|13240.42|2779.97|2973.92|97.74|1021.5|24.955|0|6.87|5.30|0|
|transformation_https|1g|200|50|30|760370|0|0|31.52|2.76|30|266|31|32|33|36|40|63|6332.88|1329.66|1422.42|99|1020|25.02|0|4.39|4.62|0|
|transformation_https|1g|200|1024|0|378270|378270|100|63.27|29.71|1|1120|81|102|117|135|148|191|3150.67|7042.87|0|98.26|1016.5|16.914|0|6.02|5.15|0|
|transformation_https|1g|200|1024|30|380117|380117|100|62.97|29.61|1|1084|80|103|118|137|150|187|3165.37|7075.72|0|98.27|1016|17.274|0|6.85|5.65|0|

Jenkins Log: https://wso2.org/jenkins/view/All%20Builds/job/ballerina-platform/job/ballerina-performance/42/consoleFull

A memory leak could be causing the errors. I see `java.lang.OutOfMemoryError: GC overhead limit exceeded` in logs.

**Steps to reproduce:**
Run Jenkins Job: https://wso2.org/jenkins/view/All%20Builds/job/ballerina-platform/job/ballerina-performance

**Affected Versions:**
0.981.1 

**OS, DB, other environment details and versions:**
Ubuntu 18.04

**Comment by Bhashinee** [comment] 2018-09-18 11:05
We ran this locally with 0.981.1 release in Jmeter for 500 concurrencies, 1k message for 20 minutes. These were the results.
![selection_017](https://user-images.githubusercontent.com/11239305/45683203-7771c780-bb60-11e8-8660-7f9b93a03331.jpg)

We didn't see any issues. Can you please verify that you were running these tests on the latest released pack? We had a similar issue earlier and we did a patch release for that and it is available on the Ballerina site.

**Comment by chrishantha** [comment] 2018-09-18 11:10
Could someone please verify the scripts and Ballerina programs in https://github.com/ballerina-platform/ballerina-performance? I just automated the performance tests.

@keizer619 Please confirm the Ballerina version.

**Comment by chrishantha** [comment] 2018-09-28 06:20
There was an error in the scripts. The second message size (from parameters) was not passed to JMeter servers when creating the payloads and 1KiB file was missing. When that happened, Ballerina also gave an OOM. I fixed the scripts to create the payload files properly and Ballerina tests now run without any errors. However, we need to investigate the OOM error later.

**Comment by Bhashinee** [comment] 2018-12-17 05:49
We tested the scenario on Ballerina o.990.1 and we were unable to reproduce the issue. Hence closing.

**Closed by Bhashinee** 2018-12-17 05:49 UTC
Labels: Component/HTTP, Component/stdlib, Priority/High, Type/Bug
