### ISSUE TITLE
Null pointer exception for undefined member access of object values

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#26022] opened 2020-09-23 07:22 UTC
**Description:**

#### Code
```Ballerina
type Foo object {};

function name() {
    Foo foo = new();
    foo.print();
}
```

#### Swan Lake
```LogTalk
[2020-09-23 12:31:55,974] SEVERE {b7a.log.crash} - null
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.isMemberAccessAllowed(SymbolResolver.java:1538)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupLangLibMethodInModule(SymbolResolver.java:773)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupLangLibMethod(SymbolResolver.java:646)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.getLangLibMethod(TypeChecker.java:5124)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkLangLibMethodInvocationExpr(TypeChecker.java:5118)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkObjectFunctionInvocationExpr(TypeChecker.java:5053)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.visit(TypeChecker.java:2674)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:115)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:357)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.TypeChecker.checkExpr(TypeChecker.java:336)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:2180)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:47)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2610)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2578)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2574)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:361)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2610)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:333)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2610)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2578)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2570)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:256)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:230)
	at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:322)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:256)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

#### 1.2.8
```LogTalk
error: .::c1.bal:5:9: undefined function 'print' in object 'Foo'
```

**Steps to reproduce:**
Run above code in Swan Lake channel.

**Affected Versions:**
All the Swan Lake versions are affected

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**
For the message change #25773
> error: .::c1.bal:4:15: cannot initialize abstract object 'Foo'

**Suggested Labels (optional):**
Team/CompilerFE

**Suggested Assignees (optional):**

**Comment by rasika** [comment] 2021-02-12 05:01
Possible duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/25158

**Comment by mohanvive** [comment] 2021-02-22 04:05
Above issue is already fixed in master. Hence, closing the issue.

**Closed by mohanvive** 2021-02-22 04:05 UTC
Labels: CompilerSLDump, Priority/Blocker, SwanLakeDump, Team/CompilerFE
