### ISSUE TITLE
CORS does not work

### ISSUE THREAD

**Issue by Sithumini** [ballerina-platform/ballerina-lang#19275] opened 2019-10-02 06:29 UTC
**Description:**
Cors does not work. My front-end react application (http://localhost:9092) which sends a cross-origin post request to ballerina backend (http://localhost:8081). Option call is successful(  getting 200 OK) but the CORS preflight request does not have the access-control-allow-method. So the original post request does not happen.

**Getting the below browser console errors**
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9092/TokenService/tokenservice. (Reason: missing token ‘access-control-allow-headers’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9092/TokenService/tokenservice. (Reason: CORS request did not succeed).
```

**OPTION call Response headers** 
```
access-control-allow-origin : http://localhost:8080
content-length : 0
date : Wed, 2 Oct 2019 11:18:24 +0530
server : ballerina
```

**Curl command to send a CORS preflight request.**

```
» curl -v "http://localhost:9092/TokenService/tokenservice" -X OPTIONS -H "Origin:http://localhost:8080/" -H "Access-Control-Request-Method:POST"                       

*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9092 (#0)
> OPTIONS /TokenService/tokenservice HTTP/1.1
> Host: localhost:9092
> User-Agent: curl/7.54.0
> Accept: */*
> Origin:http://localhost:8080/
> Access-Control-Request-Method:POST
>
< HTTP/1.1 200 OK
< content-length: 0
< server: ballerina
< date: Wed, 2 Oct 2019 11:30:17 +0530
<
* Connection #0 to host localhost left intact
```

**Steps to reproduce:**
cors sample

**Affected Versions:**
Ballerina 1.0.0

**OS, DB, other environment details and versions:**
MacOS 10.14

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment] 2019-10-02 14:15
@Sithumini Few things to get clarified:

1. OPTIONS call response has `access-control-allow-origin : http://localhost:8080` header, but your origin is  "http://localhost:9092" and the calling backend is http://localhost:8081. What is up and running on port 8080?
2. I guess the last curl cmd is to test the backend server whether the CORS are working properly. Why does the request is being not sent to the backend (http://localhost:8081) instead of 9092?

However can you share the Ballerina service code with us to reproduce the issue?

**Comment by chamil321** [comment] 2019-10-11 06:23
@Sithumini Can we have any update on this? Can you share the resources in order to reproduce it?

**Comment by chamil321** [comment] 2019-10-14 05:11
Closing the issue as we cannot reproduce it from our end due to the lack of resources and there are few uncleared areas in the issue regarding ports. Please reopen if same experienced again.

**Comment by Sithumini** [comment] 2019-10-14 09:41
@chamil321 The issue did not show up with Ballerina 1.0.1. But it was mandatory to add the cors allow method in resource configuration even it is already in the service configuration. 

Is that the correct behavior?

Eg: 
```
@http:ServiceConfig {
    basePath: "/basePath",
    cors: {
        allowOrigins: "http://localhost:8080",
        allowCredentials: true,
        allowMethods: ["GET", "POST", "OPTIONS"]
    }
}
service SampleService on sampleEndpointListener {

    @http:ResourceConfig {
        methods: ["POST"],
        body: "sampleGetRequest",
        path: "/",
       cors: {
            allowMethods: ["POST"]
        }
    }
```

**Comment by chamil321** [comment] 2019-10-15 04:41
@Sithumini That is not the expected  behavior. If you have not specified cors config in resourceConfig, ideally particular resource should take it's service cors config.[ BBE sample](https://v1-0.ballerina.io/learn/by-example/http-cors.html) has similar scenario where the service level config has inherited to the resource level. 

When inheriting, resource config cannot have any cors config. If it does, resource level configs will only be considered. 

As an additional condition, cors `allowMethod` is checked against the `methods` config in the resource config as well. i.e The GET method will not be allowed even though it is inherited from the Service level cors config as the `method` (HTTP verb) specified as POST in the resource config
```ballerina
@http:ServiceConfig {
    basePath: "/basePath",
    cors: {
        allowOrigins: "http://localhost:8080",
        allowCredentials: true,
        allowMethods: ["GET", "POST", "OPTIONS"]
    }
}
service SampleService on sampleEndpointListener {

    @http:ResourceConfig {
        methods: ["POST"],
        body: "sampleGetRequest",
        path: "/",
    }
```

**Comment by chamil321** [comment] 2019-10-21 08:17
Based on above comment, closing the issue

**Closed by chamil321** 2019-10-21 08:17 UTC
Labels: Area/StandardLibs, Type/Question
