### ISSUE TITLE
Unnecessary line break in API documentation

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-lang#22958] opened 2020-04-29 08:55 UTC
**Description:**
In the API docs, we are adding a new line, when a line exceeds 120 character limit, to maintain our code style guidelines. But, this new line should not effect the API documentation. But in this case, the extra new line is added in the API documentation. See the below example:

<img width="909" alt="Screenshot 2020-04-29 at 14 22 42" src="https://user-images.githubusercontent.com/40016057/80577705-f3aedb00-8a24-11ea-82f3-f9ecb135c96f.png">

This is caused due to following API doc
```ballerina
    # Serializes the provided data. Implement this to serialize any data type and return the `byte[]` value to use in
    # the Kafka producer.
```
Ideally, `value to use in the Kafka producer` should be in the same line.

The relevant page is [Kafka serializer documentation page](https://ballerina.io/learn/api-docs/ballerina/kafka/objects/Serializer.html).

**Affected Versions:**
1.2.2

**Comment by shehan360** [comment] 2020-06-01 08:00
The issue is already fixed on master branch(v2). The above PR fixes it for 1.2.x branch.

**Closed** 2020-06-04 12:52 UTC
Labels: Component/Docerina, Points/0.5, Type/Bug
