### ISSUE TITLE
[grpc] Returns "Unavailable" for grpc unary blocking scenario. 

### ISSUE THREAD

**Issue by VirajSalaka** [ballerina-platform/ballerina-lang#17966] opened 2019-08-19 08:31 UTC
**Description:**
With a slight modification, in the example for [ballerina unary blocking scenario](https://ballerina.io/learn/by-example/grpc-unary-blocking.html) returns grpc unavailable status in the client side.

The modifications are rather than using string type, I have created a separate message. And on the server side,
>	error? result = caller->send(message, headers = resHeader);
	error? result = caller->complete();
        if (result is error) {
            log:printError("Error from Connector: " + err.reason() + " - "
                                             + <string>err.detail().message);
        }

The trace log for outbound traffic from the grpc server is this.
>[2019-08-19 11:39:09,235] TRACE {http.tracelog.downstream} - [id: 0xcd3d7acc, L:/127.0.0.1:50051 - R:/127.0.0.1:63522] OUTBOUND HEADERS: streamId=3 headers=DefaultHttp2Headers[:status: 200, scheme: https, authority: https://localhost:50051, user-agent: ballerina/0.991.0, content-type: application/grpc, te: trailers, grpc-encoding: identity, grpc-accept-encoding: gzip, server: ballerina/0.991.0, date: Mon, 19 Aug 2019 11:39:09 +0530] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
[2019-08-19 11:39:09,237] TRACE {http.tracelog.downstream} - [id: 0xcd3d7acc, L:/127.0.0.1:50051 - R:/127.0.0.1:63522] OUTBOUND HEADERS: streamId=3 headers=DefaultHttp2Headers[grpc-status: 14, grpc-message: UNAVAILABLE] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true

the trace log of inbound traffic for the grpc client is this,
>[2019-08-19 11:39:09,239] TRACE {http.tracelog.upstream} - [id: 0x6e2f0534, L:/127.0.0.1:63522 - R:localhost/127.0.0.1:50051] INBOUND HEADERS: streamId=3 headers=DefaultHttp2Headers[:status: 200, scheme: https, authority: https://localhost:50051, user-agent: ballerina/0.991.0, content-type: application/grpc, te: trailers, grpc-encoding: identity, grpc-accept-encoding: gzip, server: ballerina/0.991.0, date: Mon, 19 Aug 2019 11:39:09 +0530] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
[2019-08-19 11:39:09,247] TRACE {http.tracelog.upstream} - [id: 0x6e2f0534, L:/127.0.0.1:63522 - R:localhost/127.0.0.1:50051] INBOUND HEADERS: streamId=3 headers=DefaultHttp2Headers[grpc-status: 14, grpc-message: UNAVAILABLE] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
Error from Connector: {ballerina/grpc}UNAVAILABLE - UNAVAILABLE

When I have commented the `caller->complete()`, it works well. The client receives the response as expected. 

**Steps to reproduce:**
The proto file, generated ballerina code, and user-edited ballerina code can be found [here](https://drive.google.com/open?id=1RcAksFdxVVpUFmmC5cufTh5jCjHlUgzN).
Invoke the client, you will notice the error. 

**Affected Versions:**
0.991.0

**OS, DB, other environment details and versions:**
MacOS Mojave

**Related Issues (optional):**

**Suggested Labels (optional):**
bug

**Suggested Assignees (optional):**

**Comment by daneshk** [comment] 2019-08-20 08:58
I couldn't reproduce the issue. I followed the same steps and create a secured connection between the client and the server and implement the service with the same code snippet, but didn't encounter any failures.
I am closing this issue. If you encounter this issue again, please reopen.

**Closed by daneshk** 2019-08-20 08:58 UTC
Labels: Area/StandardLibs, Component/gRPC, Type/Bug
