### ISSUE TITLE
InherentTypeViolation in the service level annotation

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-lang#31955] opened 2021-07-29 14:46 UTC
**Description:**
When I am trying to start a gRPC service with auth annotation manually using `attach` and `start` APIs, it gives the following error.

```sh
error: Test module initialization for test suite failed due to {ballerina/lang.map}InherentTypeViolation {"message":"invalid value for record field 'auth': expected value of type 'ballerina/grpc:0.8.0-beta.3:ListenerAuthConfig[]', found '()'"}
        at ballerina.grpc.0_8_0-beta_3.tests.ser:$annot_func$_210(tests/ser.bal:111)
```

**Steps to reproduce:**
You can use either one of the options to reproduce this issue.

##### Option 01
Build [this branch](https://github.com/BuddhiWathsala/module-ballerina-grpc/tree/inherent_issue) using:
```sh
./gradlew clean test
```

OR

##### Option 02
Run the following Ballerina code in the beta2 version.
```ballerina
import ballerina/http;

listener http:Listener ep = new (9256);

public type Rec record {|
    string name = "";
|};

public type Lis Rec;

public type ServiceConf record {|
    Lis[] auth?;
|};

public annotation ServiceConf Annon on service;

Rec rec = {name: ""};

service object {} ser = @Annon{auth:[rec]}
service object {
};

public function main() returns error? {
    check ep.attach(ser, "");
    check ep.'start();
}
```

Error log:
```sh
error: {ballerina/lang.array}InherentTypeViolation {"message":"incompatible types: expected 'http_grpc_issue:Rec', found '()'"}
        at buddhi.http_grpc_issue.0_1_0:$annot_func$_0(main.bal:35)
```

**Affected Versions:**
- Ballerina beta 2 onwards
- Does not appear in the Ballerina beta 1

**OS, DB, other environment details and versions:**
- macOS
- Java11

**Comment by MaryamZi** [comment] 2021-07-29 16:38
Seems to be another reordering issue.

Reproducible with 

```ballerina
class Listener {

    public function attach(service object {} s, string[]|string? name = ()) returns error? {
    }

    public function detach(service object {} s) returns error? {
    }

    public function 'start() returns error? {
    }

    public function gracefulStop() returns error? {
    }

    public function immediateStop() returns error? {
    }
}

listener Listener ep = new;

public type Rec record {|
    string name = "";
|};

public type Lis Rec;

public type ServiceConf record {|
    Lis[] auth?;
|};

public annotation ServiceConf Annon on service;

Rec rec = {name: ""};

service object {} ser = @Annon{auth:[rec]}
service object {
};

public function main() returns error? {
    check ep.attach(ser, "");
    check ep.'start();
}
```

However the compiler crashes for this sample on the current master (https://github.com/ballerina-platform/ballerina-lang/issues/31957). A contains key check can be added at https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/IsolationAnalyzer.java#L1234 to avoid the NPE and start fixing this issue.

**Comment by MaryamZi** [comment] 2021-07-29 16:46
@BuddhiWathsala, if you require a workaround, on beta2 you can defer the `ser` variable initialization to the module `init` function. The module `init` function is only called after the variables are initalized, so `rec` will be initialized before `ser`.

```ballerina
service object {} ser;

function init() {
    ser = @Annon{auth: [rec]}
    service object {
    };
}
```

On the current lang master, the crash happens when referring to a listener declaration. Since you are explicitly calling `start` if this doesn't have to be a listener declaration, you can define `ep` as a normal variable. In case this is possible, the crash won't happen if `ep` is not a listener declaration.

```ballerina
Listener ep = new;
```

**Comment by BuddhiWathsala** [comment] 2021-07-30 03:53
@MaryamZi, I actually need `ep` as a gRPC listener declaration because this scenario is used for a gRPC authentication test.

**Comment by MaryamZi** [comment] 2021-07-30 04:04
This is still a listener, the only difference is that the compiler won't call the life-cycle methods (attach and start) for you. I was wondering if that was OK, because in the example you are explicitly calling start. 

If you have 
```ballerina
listener Listener ep = new;

service object {} ser;

function init() {
    ser = @Annon{auth:[rec]}
    service object {
    };
}

public function main() returns error? {
    check ep.attach(ser, "");
    check ep.'start();
}
```

`ep.start()` is called twice. Once in the `main` function and once by the compiler when calling life-cycle methods (for some listeners like HTTP calling start twice used to result in an error previously, I'm not sure if that is the case anymore).

But if you say
```ballerina
Listener ep = new;
```

`ep` is a normal variable but is still of a listener type. So you can attach services and explicitly call start on the listener. Please note, in this case you would  also have to call `lang.runtime:registerListener(ep);` to stop the program from exiting.

You need a listener declaration (`listener Listener ep = new;`) only if there are service declarations that bind to this listener.

e.g.,
```ballerina
service on ep {
    ...
}
```

**Comment by BuddhiWathsala** [comment] 2021-07-30 05:09
@MaryamZi, yes it did work. Thanks for the workaround.

**Closed** 2023-03-01 04:11 UTC
Labels: Type/Bug, Team/CompilerFE, Area/CodeAnalysis, Reason/EngineeringMistake, Deferred
