### ISSUE TITLE
[Formatter] Handle negative test scenarios and enable possible skipped parser tests

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-lang#26583] opened 2020-10-26 04:43 UTC
**Description:**
The formatter should be able to handle negative test scenarios as well. Also, there are some parser test cases that are skipped, out of these the ones that could be enabled should be enabled.

**Steps to reproduce:**

**Affected Versions:**
Swan Lake Preview 5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment] 2020-10-28 08:52
A possible duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/26450?

**Closed** 2020-11-05 11:19 UTC
Labels: Component/Formatting, Points/2, Team/Tooling, Type/Improvement
