### ISSUE TITLE
CreateTypeCodeAction gives a CCE

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#37104] opened 2022-07-22 09:00 UTC
**Description:**
Consider:
```ballerina
import ballerina/io;

class Iterator {
    *object:I<cursor>
}

```
At `<cursor>` we get the following exception:
```java
[Error - 2:27:59 PM] CodeAction 'CreateTypeCodeAction' failed! {, error: 'class java.lang.String cannot be cast to class org.wso2.ballerinalang.compiler.util.Name (java.lang.String is in module java.base of loader 'bootstrap'; org.wso2.ballerinalang.compiler.util.Name is in unnamed module of loader 'app')'}
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.wso2.ballerinalang.compiler.util.Name (java.lang.String is in module java.base of loader 'bootstrap'; org.wso2.ballerinalang.compiler.util.Name is in unnamed module of loader 'app')
	at org.ballerinalang.langserver.codeaction.providers.CreateTypeCodeAction.getDiagBasedCodeActions(CreateTypeCodeAction.java:83)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$4(CodeActionRouter.java:124)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.lambda$getAvailableCodeActions$5(CodeActionRouter.java:115)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:112)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:167)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:332)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
See description

**Affected Versions:**
2201.1.1

**Comment by LakshanWeerasinghe** [comment] 2022-08-26 08:29
This issue cannot reproduce in `2201.2.x` branch while it is reproducible in `2201.2.0-stage`. Hence we can close this due to the fix is in `2201.2.x` branch.

**Closed as completed** 2022-09-15 08:17 UTC
Labels: Type/Bug, Priority/High, Team/LanguageServer, Points/3, Area/CodeAction, Reason/Other
