### ISSUE TITLE
Double printing panic from main

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#18520] opened 2019-09-04 06:16 UTC
**Description:**
```ballerina
import ballerina/io;
import ballerina/lang.'int as ints;

// The `parse()` function takes a `string` argument and attempts to convert it to an `int`.
function parse(string num) returns int|error {
    return ints:fromString(num);
}

public function main() {
    // The `checkpanic` unary operator can be used to lift errors.
    // In this instance, `checkpanic` is used to lift the (potential) error
    // returned by the `parse()` function. If the actual value returned
    // by the function is an `error`, the function immediately panics
    // with the error.
    // Passing a valid integer as a `string` will return an `int`.
    int y = checkpanic parse("120");
    io:println(y);

    // Passing a random `string` will result in a `panic`.
    int z = checkpanic parse("Invalid");
    io:println(z);
}
```

Output in console
```
error: {ballerina/lang.int}NumberParsingError message='string' value 'Invalid' cannot be converted to 'int'
        at ballerina.lang_int:fromString(int.bal:53)
           checkpanic:parse(checkpanic.bal:6)
           checkpanic:main(checkpanic.bal:22) 
error: {ballerina/lang.int}NumberParsingError message='string' value 'Invalid' cannot be converted to 'int'
        at ballerina.lang_int:fromString(int.bal:53)
           checkpanic:parse(checkpanic.bal:6)
           checkpanic:main(checkpanic.bal:22)
```
**Steps to reproduce:**

**Affected Versions:**
1.0-beta
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment] 2019-09-04 06:24
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/18458.

**Closed by warunalakshitha** 2019-09-04 06:24 UTC
Labels: Area/JBallerina, Type/Bug
