### ISSUE TITLE
Reformat code is removing the comments and free spaces added

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8051] opened 2018-04-25 13:56 UTC
**Description:**
Reformat code is removing the comments and free spaces added

**Affected Versions:**
Tools - beta 15

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by hevayo** [comment] 2018-06-20 19:15
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/4854

**Closed by hevayo** 2018-06-20 19:15 UTC
Labels: Priority/High, Type/Bug, component/Composer
