### ISSUE TITLE
Couldn't find the invocation symbol exception while defining a record

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/ballerina-lang#29559] opened 2021-03-24 04:25 UTC
**Description:**

**Steps to reproduce:**
1. Use this code snippet
```ballerina
type Person record {|
    string name;
    int age;
    string school;
|};

Person p = { name: "name"}
```
2. Try adding a "," (comma) after `name:  "name" ` like in the below code snippet
```ballerina
type Person record {|
    string name;
    int age;
    string school;
|};

Person p = { name: "name",}
```
3. See the ballerina output
```
java.lang.Exception: Couldn't find the invocation symbol!
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$signatureHelp$2(BallerinaTextDocumentService.java:210)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment] 2021-03-24 04:32
Duplicate of #29549 . Hence closing

**Closed by nadeeshaan** 2021-03-24 04:32 UTC
Labels: Area/Completion, Team/LanguageServer, Type/Bug, Version/SLAlpha3
