### ISSUE TITLE
JSON/record formatting do not work in all places

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#15373] opened 2019-05-22 03:55 UTC
**Description:**
The following do not format properly in VSCode:
    `artemis:Producer prod = new({host:"localhost", port:61616}, "example");`

Expected is as follows:
    `artemis:Producer prod = new({host: "localhost", port: 61616}, "example");`

The JSON formatting seems to work only if it is an assignment as follows:
    `json val = {host: "localhost", port: 61616};`

**Steps to reproduce:**
Try formatting a JSON/record expression when it is not in an assignment statement.

**Affected Versions:**
0.991.0

**OS, DB, other environment details and versions:**
Ubuntu 19.04

**Related Issues (optional):**
N/A

**Comment by NipunaMarcus** [comment] 2019-05-29 05:10
This issue is a known issue https://github.com/ballerina-platform/ballerina-lang/issues/13794 and we are working on fixing this.

**Comment by NipunaMarcus** [comment] 2019-07-02 07:31
The issue is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/16003
Hence closing this issue.

**Closed by NipunaMarcus** 2019-07-02 07:31 UTC
Labels: Area/Tooling, Component/Formatting, Type/Bug
