### ISSUE TITLE
Invalid diagnostics appear when a `.bal` is renamed in VSCode extension

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#34895] opened 2022-01-29 07:25 UTC
Open a Ballerina package with VSCode. Implement a simple HTTP example. Now rename the `.bal`. You will see invalid diagnostics in the file.

**Comment by nadeeshaan** [comment] 2022-02-03 02:56
This will be addressed with #34933

**Comment by nadeeshaan** [comment] 2022-03-25 06:50
@sameerajayasoma do you have an example scenario when this happened? I tried with the latest VSCode and VSCode plugin while I could not reproduce this issue.

**Comment by TharushiJay** [comment] 2022-04-08 07:12
Closing the issue since it cannot be reproduced.

**Closed by TharushiJay** 2022-04-08 07:12 UTC
Labels: Type/Bug, Priority/High, Team/LanguageServer

**Comment by sameerajayasoma** [comment] 2022-04-22 00:19
I can't reproduce now too. Looks like it is fixed
