### ISSUE TITLE
Need to Change the API Docs Design to Distinguish Between Ballerina & BallerinaX Modules

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#24967] opened 2020-07-17 11:13 UTC
**Description:**
Need to change the API Docs design to distinguish between Ballerina & BallerinaX modules. May be we can have 2 sections in the left navigation pane.

We have had the below in the past designs.

<img width="1680" alt="Screenshot 2020-07-28 at 16 44 06" src="https://user-images.githubusercontent.com/11707273/88658829-b0cad500-d0f1-11ea-9c4b-eaa9161eaedb.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shehan360** [comment] 2021-06-21 05:53
Closing because a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/24908

**Closed by shehan360** 2021-06-21 05:53 UTC
Labels: Area/Docerina, SwanLakeDump, Team/DevTools, Type/Improvement
