### ISSUE TITLE
Using ballerinax/postgresql module generate NoClassDefFoundError

### ISSUE THREAD

**Issue by ecoupal** [ballerina-platform/ballerina-lang#33754] opened 2021-11-10 16:01 UTC
**Description:**
Whenever I'm using the ballerinax/postgresql module I get this error:

`2021-11-10 16:52:09,720] SEVERE {b7a.log.crash} - ballerinax/postgresql/1/$configurationMapper 
java.lang.NoClassDefFoundError: ballerinax/postgresql/1/$configurationMapper
        at contiguity.expense_server.0.$configurationMapper.$configureInit(Unknown Source)
        at contiguity.expense_server.0.$_init.main(expense_server)
Caused by: java.lang.ClassNotFoundException: ballerinax.postgresql.1.$configurationMapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more`

**Steps to reproduce:**
```
import ballerinax/postgresql;

public function main() returns error? {
  postgresql:UuidValue e = new();
}
```
Ballerina.toml:

```
[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"
```

**Affected Versions:**
Ballerina Swan Lake Beta 3
Language specification 2021R1
Update Tool 1.3.5

**OS, DB, other environment details and versions:**
Darwin Kernel Version 18.7.0
PostgreSQL 14.0

**Comment by azinneera** [comment] 2021-11-11 09:28
@ecoupal thanks for reporting the issue. Can you let us know if you attempted to use a SNAPSHOT version of `Ballerina Swan Lake Beta 3` or if this happens with the release?

**Comment by ecoupal** [comment] 2021-11-12 14:02
@azinneera I use the latest slbeta3.

**Comment by ecoupal** [comment] 2021-11-14 18:05
I must be doing something wrong cause I got the same error with mongodb:

```
[2021-11-14 19:02:22,036] SEVERE {b7a.log.crash} - ballerinax/mongodb/3/$configurationMapper 
java.lang.NoClassDefFoundError: ballerinax/mongodb/3/$configurationMapper
	at contiguity.expense_server.0.$configurationMapper.$configureInit(Unknown Source)
	at contiguity.expense_server.0.$_init.main(expense_server)
Caused by: java.lang.ClassNotFoundException: ballerinax.mongodb.3.$configurationMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
```

**Comment by azinneera** [comment] 2021-11-14 18:29
Looks like there is an issue with the generated caches. Will you be able to zip and upload the following locations to check if there is an issue with the caches?
1. <USER_HOME>/.ballerina/repositories/central.ballerina.io/cache-slbeta3/ballerinax/postgresql/1.0.0
2. <USER_HOME>/.ballerina/repositories/central.ballerina.io/cache-slbeta3/ballerinax/mongodb/3.0.0

**Comment by ecoupal** [comment] 2021-11-14 19:37
@azinneera Sure, there you go!

[cache.zip](https://github.com/ballerina-platform/ballerina-lang/files/7534503/cache.zip)

**Comment by azinneera** [comment] 2021-11-16 18:58
@ecoupal thank you for providing the caches. There is an issue with the generated caches as suspected. The class files are missing in the jar. This seems to be an intermittent behaviour. Removing the [aforementioned](https://github.com/ballerina-platform/ballerina-lang/issues/33754#issuecomment-968341382) cache directories and building your project should resolve your issue. We will look into this and fix this in our next release.

**Comment by azinneera** [comment] 2021-11-29 18:15
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/32969

**Comment by azinneera** [comment] 2021-11-29 18:16
@ecoupal we have already created an issue to capture this bug. Please refer the linked issue for the progress.

**Closed by azinneera** 2021-11-29 18:16 UTC
Labels: Type/Bug
