### ISSUE TITLE
Goto Def is not working for new when the object is defined in different bal file/module

### ISSUE THREAD

**Issue by sinthuja** [ballerina-platform/ballerina-lang#21905] opened 2020-03-18 06:56 UTC
**Description:**
The goto the object constructor when referring to `new` seems to be not working when the object is defined in different bal file/module.

**Steps to reproduce:**
Try Goto def with `new` and it doesn't work as expected. 

main.bal
```
import ballerina/io;

public function main() {
    // Initializes a `Person` object.
    Person p1 = new (5, "John", "Doe");

    io:println(p1.getFullName());
}
```
person.bal 

```
type Person object {
    public int age;
    public string firstName;
    public string lastName;

    // The object initializer.
    function __init(int age, string firstName, string lastName) {
        self.age = age;
        self.firstName = firstName;
        self.lastName = lastName;
    }

    // A method returning the full name value of the `Person` object.
    function getFullName() returns string {
        return self.firstName + " " + self.lastName;
    }
};
```
**Affected Versions:**
1.2.0-RC2
**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment] 2020-03-18 17:37
Duplicate of #21790. Hence closing the issue

**Closed by nadeeshaan** 2020-03-18 17:37 UTC
Labels: Area/Tooling, Component/LanguageServer, Type/Improvement
