### ISSUE TITLE
Summarize Testarina results

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#35115] opened 2022-02-18 09:03 UTC
Please output a summarized view of test results after running `bal test` instead listing all the tests. This is especially important when there are a large number of tests. But it's bad UX to wait for an output without seeing anything. So we should show the currently running test name and progress before printing the summary, that will get updated with each test.

Eg:
```
[1/332] testTokenizer#'a.b.c.d = e;'
```

After completion, we should show a summary containing the number of total/passing tests. If there were failures, print the messages of each including stack traces.

We should only do this if we detect we are running in a terminal interface, otherwise fallback to current (with #33558 improvement).

**Comment by azinneera** [comment] 2023-03-13 12:32
Closing since the issue is addressed.

**Closed by azinneera** 2023-03-13 12:32 UTC
Labels: Type/Improvement, Team/DevTools, Area/TestFramework
