### ISSUE TITLE
java -jar not working with Ballerina 1.0.0-beta-SNAPSHOT

### ISSUE THREAD

**Issue by indikasampath2000** [ballerina-platform/ballerina-lang#18086] opened 2019-08-21 06:35 UTC
**Description:**
I have created a module like below.
```
indika@indika-ThinkPad-X1-Carbon-5th:~/Downloads/bal$ tree
.
├── Ballerina.toml
├── src
│   └── consumer
│       └── active_mq_consumer.bal
```

The `active_mq_consumer.bal` looks like below.
```
import ballerina/io;
import indikas/jms;

public function main() {
    io:println("Hello, World!");
}
```

`Ballerina.toml` as below.
```
[project]
org-name= "abc"
version= "3.4.5"
```

Module build is successful.
```
indika@indika-ThinkPad-X1-Carbon-5th:~/Downloads/bal$ ballerina build
Compiling source
	abc/consumer:3.4.5

Creating balos
	target/balo/consumer-2019r3-any-3.4.5.balo

Running tests
    abc/consumer:3.4.5
	No tests found

Generating executables
	target/bin/consumer-executable.jar
```

When I try to run the `target/bin/consumer-executable.jar`, it is giving the following message.
```
indika@indika-ThinkPad-X1-Carbon-5th:~/Downloads/bal$ java -jar target/bin/consumer-executable.jar
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

The `ballerina-internal.log` has the following stack trace.
```
[2019-08-21 11:45:45,213] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died
java.lang.NoSuchMethodError: indikas.jms.___init.indikas_jms_0_6_0__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)Ljava/lang/Object;
        at abc.consumer.___init.$moduleInit(consumer:65535)
        at abc.consumer.___init.$lambda$$moduleInit$(consumer)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:452)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:228)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:198)
        at java.lang.Thread.run(Thread.java:748)

[2019-08-21 11:45:45,221] ERROR {org.ballerinalang.jvm.util.RuntimeUtils} - indikas.jms.___init.indikas_jms_0_6_0__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)Ljava/lang/Object;
java.lang.NoSuchMethodError: indikas.jms.___init.indikas_jms_0_6_0__init_(Lorg/ballerinalang/jvm/scheduling/Strand;)Ljava/lang/Object;
        at abc.consumer.___init.$moduleInit(consumer:65535)
        at abc.consumer.___init.$lambda$$moduleInit$(consumer)
        at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:452)
        at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:228)
        at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:198)
        at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by indikasampath2000** [comment] 2019-08-26 04:53
The problem was when I use `import indikas/jms;` it's giving the reported error. But then I build the **module-jms** and copied it to the `home/indika/.ballerina/balo_cache/wso2/jms/0.6.0/jms.balo` after changing the `import wso2/jms;` it's working fine with `java -jar` not sure how the organization changes affecting the `java -jar`

**Comment by warunalakshitha** [comment] 2020-03-26 13:21
Couldn't reproduced with 1.2.0 hence closing the issue. Please reopen if you have further clarification on this.

**Closed by warunalakshitha** 2020-03-26 13:21 UTC
Labels: Area/BuildTools, Priority/High, Type/Bug
