### ISSUE TITLE
[composer] Add Resource from design is not working

### ISSUE THREAD

**Issue by kavithasub** [ballerina-platform/ballerina-lang#8122] opened 2018-04-26 06:19 UTC
**Description:**
Observed $subject, but this works from source
![addres](https://user-images.githubusercontent.com/15671620/39288914-96b9379e-4947-11e8-8674-f3c299226912.jpeg)

![srcaddres](https://user-images.githubusercontent.com/15671620/39288976-d2c3feb8-4947-11e8-871d-675bd5acc0f9.jpeg)

**Affected Versions:**
beta17

**OS, DB, other environment details and versions:**
Firefox-59.0.2
Ubuntu 15.10

**Comment by nadeeshaan** [comment] 2018-04-26 13:26
Cannot reproduce in the latest master ee2415a296c8ec08e8491a8a57ce86d47e1483ec
Hence closing the issue

**Closed by nadeeshaan** 2018-04-26 13:26 UTC
Labels: component/Composer
