### ISSUE TITLE
[Debugger] Remote debug session doesn't close properly when we disconnect from VSCode

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#30455] opened 2021-05-10 04:09 UTC
**Description:**
The remote debug session doesn't close properly when we disconnect from VSCode.

**Steps to reproduce:**
- Start a remote debug session(eg:- HelloWorld program).
- After the debug point gets hit, disconnect the debug session from VSCode(click the Disconnect(F5) icon).
- Following observation were noted:
       - `Listening for transport dt_socket at address: 5005` is printed one more time.
       - Terminal does not indicate any signs regarding debug session close. Then we need to manually close the debug session by pressing ctrl+c (in Mac).

**Comment by NipunaRanasinghe** [comment] 2022-01-27 05:15
Closing since the root cause seems to be https://github.com/ballerina-platform/ballerina-lang/issues/34828

**Closed by NipunaRanasinghe** 2022-01-27 05:15 UTC
Labels: Type/Bug, Area/Debugger, Team/DevTools, SwanLakeDump
