### ISSUE TITLE
Make available the standard libraries even without adding the import explicitly

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#31813] opened 2021-07-20 10:36 UTC
**Description:**
$title,
So the users will be able to execute commands such as `io:println()` without explicitly importing the `ballerina/io` module

**Comment by mohanvive** [comment] 2021-09-23 05:52
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/30915.

**Closed by mohanvive** 2021-09-23 05:52 UTC
Labels: Type/Improvement, Team/CompilerFETools, Area/Shell
