### ISSUE TITLE
[Formatter] Improvements when formatting on fail clause

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-lang#30953] opened 2021-06-02 06:52 UTC
**Description:**
titile

When following are formatted, no changes are being made:

![Screenshot from 2021-06-02 11-38-20](https://user-images.githubusercontent.com/46120162/120435996-00c29a00-c39c-11eb-8e78-1efdb4d7570c.png)

![Screenshot from 2021-06-02 11-38-00](https://user-images.githubusercontent.com/46120162/120436014-03bd8a80-c39c-11eb-9110-db1c89de7f15.png)

Following is the expected formatting:

![Screenshot from 2021-06-02 11-37-35](https://user-images.githubusercontent.com/46120162/120436304-644cc780-c39c-11eb-892b-4be7e1344eb1.png)

**Steps to reproduce:**

```
import ballerina/io;

function foo() returns string {
    return "foo not an error";
}

function bar() returns string {
    return "bar is an error";
}

function isOK() returns boolean {
    if (1 + 1 > 0) {
        return true;
    } 
    else {
        return false;
    }
}

// 133 in james's slides

function demo() returns error? {
    do {
        //check foo();
        //check bar();
        if isOK() {
            fail error("not OK");
        }
    } 
    on fail var e {
        io:println(e.toString());
        return e;
    }
}
```

**Comment by IrushiL** [comment] 2021-07-29 08:28
This is the expected behavior since the formatter preserves user-defined new lines while aligning them to the closest tab. The correct formatting in the above scenario is as follows. 
```
function demo() returns error? {
    do {
        //check foo();
        //check bar();
        if isOK() {
            fail error("not OK");
        }
    } on fail var e {
        io:println(e.toString());
        return e;
    }
}
```
Note that the on clause is on the same line as the previous closing brace. Taking this to the next line would mean that the user has explicitly defined a new line and therefore it is being preserved as expected.

**Closed by IrushiL** 2021-07-29 08:28 UTC
Labels: Area/Formatting, Team/CompilerFETools, Type/Bug
