### ISSUE TITLE
VS Code take too long to respond when something long is being typed

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#34919] opened 2022-02-01 08:35 UTC
**Description:**
This issue is reproducible by editing some file in nBallerina repo.

Screen recording:
https://user-images.githubusercontent.com/1496990/151935501-828af55f-a870-49aa-923b-b20fde6558dd.mp4

When the addition is small the time is bearable, but when it's a long edit, it takes an unbearably long time to compile the final version of the program. My gut feeling is lang-server doesn't debounce the compilation requests in the middle when edits are being made. Feels like all the compilation requests are being queued and each request is processed.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by malinthar** [comment] 2022-02-09 04:48
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/32020

**Comment by lochana-chathura** [comment] 2022-02-09 06:00
We tried following with the same `string.bal`. Here are @rdulmina and my observations.

1. when typing at the following cursor position `int i = "dwew<cursor>" `,

- Inside the nballerina project: Observed a slowness for `text/didChange` requests sent from the VSCode. I guess it is because each individual request consumes a certain amount of time. Therefore, there is a long queue.

- Copied the same `string.bal` content to a single ball file: Observed no slowness for `text/didChange` requests sent from the VSCode. i.e. no visible queue. 

2. when typing at the following cursor position `int i = "dwew<cursor>" ;`,
Notice the semicolon after the end quote. In this case although we keep typing at each cursor position each instance is a syntactically valid code instance. Therefore **for this scenario error handler/recovery is not involved**. 

- Inside the nballerina project: Observed the same slowness for `text/didChange` requests sent from the VSCode.

- Copied the same `string.bal` content to a single ball file: Observed no slowness for `text/didChange` requests sent from the VSCode.

From 2, we think it is okay to conclude that error recovery overhead is not the issue here.  
So the problem seems to be with a large project. 

@nadeeshaan Do we parse the entire project(each bal file) for a single  `text/didChange` request or 
we only parse the text edited bal file and get the other ones from the cache?

**Comment by nadeeshaan** [comment] 2022-02-09 06:05
@lochana-chathura we update the content of the changing file only. Also, we have added debouncing to avoid multiple compilations at the server-side as well. Based on your observation, now I'll try to figure out/ identify whether there are any other completions are being processed.

I'll update this thread with the findings.

**Comment by nadeeshaan** [comment] 2022-02-10 04:00
@rdhananjaya The debouncing is done for the Diagnostics publishing only. After running a few testing cycles, I could isolate one another place where we will have to introduce debouncing as we have done for diagnostics. 

Currently, we allow code actions to be provided as compiler plugin extensions. In order to get these code actions we have to get the compilation and then register the available code actions. Since we need to get the compilation after each of the change (since we cannot say that the particular change is associated with and import statement or not) we can identify that as one of the root causes. 

IMHO we have to fix it in the first place. We will be looking in to that and keep this issue open once the fix is merged. We'll update the issue accordingly.

**Comment by mohanvive** [comment] 2022-02-24 06:22
Related to #35057

**Closed** 2022-06-08 16:14 UTC
Labels: Type/Bug, Priority/High, Team/LanguageServer, Points/2, Reason/MultipleComponentInteraction
