### ISSUE TITLE
Function suggestions not working in the context of global variables

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17771] opened 2019-08-15 10:57 UTC
Refer to the image below
![Screenshot from 2019-08-15 16-25-05](https://user-images.githubusercontent.com/6260009/63090625-81bb6200-bf79-11e9-8d84-3688e1b74838.png)

**Comment by nadeeshaan** [comment] 2019-08-20 09:11
Checked in the latest master and could not reproduce the issue. Please make sure you have other syntax errors in the source as well. Hence closing the issue.
![Screen Shot 2019-08-20 at 2 39 16 PM](https://user-images.githubusercontent.com/1329674/63334207-89ec1680-c358-11e9-9353-a5ec019d0dda.png)

**Closed by nadeeshaan** 2019-08-20 09:11 UTC
Labels: Area/Tooling, BetaTesting, Component/VScodePlugin, Type/Bug
