### ISSUE TITLE
Attribute suggestions for a record is not working when the semi-colon is missing

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13797] opened 2019-02-22 05:10 UTC
**Description:**
Attribute suggestions for a record is not working when the semi-colon is missing

**Comment by nadeeshaan** [comment] 2019-03-21 08:13
This issue cannot reproduce in the latest master, hence closing
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/1329674/54739776-4a6da280-4bdf-11e9-8f54-4eb2846193c6.gif)

**Closed by nadeeshaan** 2019-03-21 08:13 UTC
Labels: Component/LanguageServer, Type/Bug
