### ISSUE TITLE
Intermittent failure - SQLConnectionPoolTest.testGlobalConnectionPoolSingleDestinationConcurrent

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#13972] opened 2019-02-27 09:54 UTC
**Description:**
```
[ERROR] Tests run: 101, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 42.624 s <<< FAILURE! - in TestSuite
[ERROR] testGlobalConnectionPoolSingleDestinationConcurrent(org.ballerinalang.stdlib.database.sql.SQLConnectionPoolTest)  Time elapsed: 1.366 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.ballerinalang.stdlib.database.sql.SQLConnectionPoolTest.testGlobalConnectionPoolSingleDestinationConcurrent(SQLConnectionPoolTest.java:110)
```

**Comment by Manuri** [comment] 2019-02-28 07:27
Will check this.

**Comment by pubudu91** [comment] 2019-03-22 16:31
This failed for a PR of mine today: PR #14315

**Comment by Manuri** [comment] 2019-03-23 07:07
Thanks @pubudu91, I have downloaded the log.

**Comment by Manuri** [comment] 2019-03-23 07:09
Oh, I guess you have re-triggered it. Latest failure is due to an ballerina-examples failure.

**Comment by Manuri** [comment] 2019-03-25 04:21
I couldn't locally reproduce the issue. I've improved assertion failure message to identify the issue. I'm keeping an eye on the Jenkins and Travis builds to see if this fails again.

**Comment by Manuri** [comment] 2019-07-22 07:08
Closing since this wasn't observed again. [1] has an improvement that might have an impact on this. 
Please re-open if observed again.

[1] https://github.com/ballerina-platform/ballerina-lang/pull/16910

**Closed by Manuri** 2019-07-22 07:08 UTC
Labels: Area/StandardLibs, Priority/High, Type/TestFailure
