### ISSUE TITLE
Kafka Service - Not able to run in Debug Mode

### ISSUE THREAD

**Issue by Anshulrathi** [ballerina-platform/ballerina-lang#10302] opened 2018-09-05 16:05 UTC
**Description:**
Trying to debug kafka service in IntelliJ & Composer but getting error.
    **Error:**
Ballerina remote debugger is activated on port : 55091
    could not find package wso2/kafka:*
ballerina: initiating service(s) in 'dropShipPeopleSoftPOService.bal'
Exception in thread "Thread-4" java.net.BindException: Address already in use: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Unknown Source)

Don't confuse with this error  **could not find package wso2/kafka:***. Kafka is perfectly working fine in normal Run Mode but not able to run in Debug mode.

**Steps to reproduce:**
executing the .bal kafka service file into intellij in Debug mode. 

**Affected Versions:**

**OS, DB, other environment details and versions:**
intellij / Windows 7

**Related Issues (optional):**

**Suggested Labels (optional):**
intelliJ / Composer Debugger

**Suggested Assignees (optional):**

attaching few screenshots for reference.
![image](https://user-images.githubusercontent.com/19852006/45106923-ffd67e00-b105-11e8-9adc-cbd3591cdce4.png)
![image](https://user-images.githubusercontent.com/19852006/45107043-517f0880-b106-11e8-9770-671cdaed4f9b.png)
![image](https://user-images.githubusercontent.com/19852006/45107082-73788b00-b106-11e8-9db0-9a01ed30dd31.png)
![image](https://user-images.githubusercontent.com/19852006/45107154-a6bb1a00-b106-11e8-9b11-860ee3e60d98.png)

**Comment by roonyh** [comment] 2018-09-07 05:51
Can reproduce in the vscode debugger as well. This is not related just to composer. Seems to be a bug in the debug server.

**Comment by nadeeshaan** [comment] 2018-09-17 12:03
@Anshulrathi current kafka version is compatible with ballerina v0.980.0 hence we are upgrading the kafka version to be compatible with the latest ballerina version and we'll fix the issue as soon as the new version is released

**Comment by ThisaruGuruge** [comment] 2019-08-28 11:19
Ballerina debugger is re-written and this issue is now resolved. Closing the issue.

**Closed by ThisaruGuruge** 2019-08-28 11:19 UTC
Labels: Area/StandardLibs, Component/Debugger, Type/Bug
