### ISSUE TITLE
[Bug]: Compiler incorrectly marks a required record field as an optional field 

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#39176] opened 2023-01-04 23:11 UTC
### Description

The above behavior has an impact on table-type declarations. 

### Steps to Reproduce

The following code produces a compilation error. 
```
type Department record {|
    readonly string deptNo = uuid:createType4AsString();
    string deptName;
|};

table<Department> key(deptNo) departments = table []; 
```
```
`field 'deptNo' used in key specifier must be a required field`
```

### Affected Version(s)

Ballerina 2201.3.0 (Swan Lake Update 3)

### Related area

-> Compilation

**Comment by MaryamZi** [comment] 2023-01-05 05:18
Kind of a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/33298. 

https://github.com/ballerina-platform/ballerina-lang/pull/37491#issuecomment-1290383442 may also be relevant (for the behaviour proposed until we have access to default value information at semantic analysis).

However, since defaults can be used only when they are constant

https://ballerina.io/spec/lang/master/#table-constructor-expr

> For every field-name in the key sequence of the inherent type every mapping-constructor-expr in the row-list must include a specific-field that has a value-expr that is a const-expr. It is a compile-time error if two or more rows of the table have the same key value.

even though 

```ballerina
table<Department> key(deptNo) departments = table []; 
```

will work, we won't be able to use the default even in the future, right?

```ballerina
type Department record {|
    readonly string deptNo = uuid:createType4AsString();
    string deptName;
|};

table<Department> key(deptNo) departments = table [
    {deptName: "finance"} // will result in an error
]; 
```

**Comment by MaryamZi** [comment] 2023-01-05 05:21
The original issue was due to an issue in the check for "required" in the key validation logic btw.

**Comment by MaryamZi** [comment] 2023-01-24 05:16
With https://github.com/ballerina-platform/ballerina-lang/pull/37491 the table variable declaration is allowed. 

```ballerina
table<Department> key(deptNo) departments = table []; 
```

However, even if the default is a const expression, it is not used at the moment. Being tracked by https://github.com/ballerina-platform/ballerina-lang/issues/38382 which also requires the record default value change (generating closures and having that info when type checking).

I don't think there's anything else we need to/can do atm for this issue.

**Comment by SasinduDilshara** [comment] 2023-03-03 05:18
This will be closed with https://github.com/ballerina-platform/ballerina-lang/pull/37491

**Closed by SasinduDilshara** 2023-03-03 05:18 UTC
Labels: Type/Bug, Area/Compiler, Team/CompilerFE, Points/6, userCategory/Compilation
