### ISSUE TITLE
[Improvement]: Allow users to define `org` , `version` while creating packages

### ISSUE THREAD

**Issue by tharindulak** [ballerina-platform/ballerina-lang#38792] opened 2022-11-23 09:12 UTC
### Description

Currently, users have the option to create ballerina packages using `bal new <package-name>`. In this approach users cannot further give the ballerina org name and the versions that they need.

### Describe your solution(s)

We need to provide users have the option of giving the org name and version while creating a ballerina project.
Something like `bal new <package-name> <org-name> <version>`

### Related area

-> Other Area

**Comment by azinneera** [comment] 2022-11-23 15:16
Duplicate of #37201

**Closed by azinneera** 2022-11-23 15:16 UTC
Labels: Type/Improvement, needTriage
