### ISSUE TITLE
Undefined function in anonymous block

### ISSUE THREAD

**Issue by janihur** [ballerina-platform/ballerina-lang#35753] opened 2022-04-08 09:00 UTC
**Description:**
The following construct that looks a perfectly valid Ballerina code gives unexpectedly a compilation error:
```
    {
        // undefined function println
        io:println("hello");
    }
```
When similar construct compiles just fine:
```
    {
        string hello = "hello";
        io:println(hello);
    }
```

**Steps to reproduce:**
```
$ bal --version
Ballerina 2201.0.2 (Swan Lake)
Language specification 2022R1
Update Tool 1.3.9

$ cat bug.bal 
import ballerina/io;
public function main() {
    io:println("hello");
    {
        string hello = "hello";
        io:println(hello);
    }
    {
        // undefined function println
        io:println("hello");
    }
}

$ bal build bug.bal 
Compiling source
	bug.bal
ERROR [bug.bal:(9:1,9:17)] undefined function 'println'
error: compilation contains errors
```

**Comment by lochana-chathura** [comment] 2022-06-16 12:10
Duplicate of #34568

**Closed by lochana-chathura** 2022-06-16 12:10 UTC
Labels: Type/Bug, Priority/High, Team/CompilerFE, Area/Parser, Reason/Other
