### ISSUE TITLE
Bad, sad with multiple packages using local repo

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30798] opened 2021-05-26 09:36 UTC
This is with slalpha 5. Building using build.bat. Building in front directory gets a bad, sad (ballerina-internal.log included).

[semtype.zip](https://github.com/ballerina-platform/ballerina-lang/files/6545533/semtype.zip)

**Comment by jclark** [comment] 2021-05-26 11:46
The problem is intermittent. Sometimes it gets the bad, sad; sometimes it doesn't. This is on Windows.

**Comment by manuranga** [comment] 2021-05-26 11:59
Just for the record:
Shanker was able to fix it in his machine by adding a Package.md, but issue intermittently happens for James even with that. It could be that we are depending on the directory listing order.

**Comment by uthaiyashankar** [comment] 2021-05-26 12:05
There is a different kind of intermittent error in mac : 

```
Compiling source
	jclark/nballerina.front:0.1.0
Exception in thread "main" java.lang.NullPointerException
	at io.ballerina.cli.launcher.Main.main(Main.java:63)
```

**Comment by MaryamZi** [comment] 2021-05-26 12:13
The NPE in the ImmutableTypeCloner which caused the bad, sad error as in the attached file occurs when an import cannot be resolved (https://github.com/ballerina-platform/ballerina-lang/issues/30561). With beta1 it will result in a "cannot resolve module" error. 



> There is a different kind of intermittent error in mac :
> 
> ```
> Compiling source
> 	jclark/nballerina.front:0.1.0
> Exception in thread "main" java.lang.NullPointerException
> 	at io.ballerina.cli.launcher.Main.main(Main.java:63)
> ```

Could be related to https://github.com/ballerina-platform/ballerina-lang/issues/30210. I also observed the same on Ubuntu on Swan Lake Alpha 5.

**Comment by jclark** [comment] 2021-05-26 12:41
I also get the error in https://github.com/ballerina-platform/ballerina-lang/issues/30798#issuecomment-848712884 on Windows.

**Comment by jclark** [comment] 2021-05-26 13:03
I had the project open in VSCode also. After I closed VSCode, the problem seems less frequent, but still happens.

**Comment by jclark** [comment] 2021-05-26 13:27
I checked my stuff in to a branch

https://github.com/jclark/semtype/tree/multipackage

**Comment by hevayo** [comment] 2021-05-26 16:28
I was able to reproduce the same behavior on Ubuntu with slalpha5.

This issue is most likely due to the same issue mention in https://github.com/ballerina-platform/ballerina-lang/issues/30521. And it is fixed in the latest RC with https://github.com/ballerina-platform/ballerina-lang/pull/30549. 

Since the issue is related dependent modules with hierarchical package names I try to rebuild the attached sample with "nballerinatypes" as the package name. After renaming the packages the issue seems to went away.  

We will do a proper debug and close this.

**Comment by jclark** [comment] 2021-05-27 07:27
RC5 fixes these errors, but I get another multipackage problem #30807

**Comment by azinneera** [comment] 2021-06-09 09:30
Closing since this is fixed in beta1.

**Closed by azinneera** 2021-06-09 09:30 UTC
Labels: Area/ProjectAPI, NBalNeeds, Priority/Blocker, Team/DevTools, Type/Bug
