### ISSUE TITLE
[IntelliJ] Inconsistent colours for numeric literals

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#21414] opened 2020-03-02 16:47 UTC
Refer to the image below. `int` literals are highlighted in blue while `float` literals are black (and `decimal` too). Shouldn't these be highlighted in blue as well?
![Peek 2020-03-02 22-15](https://user-images.githubusercontent.com/6260009/75697788-940dab00-5cd3-11ea-9c0a-20e5416557d8.gif)

**Comment by NipunaRanasinghe** [comment] 2020-03-11 05:38
@pubudu91 Yes you are correct. It seems to be an issue with the semantic highlighting with the recent grammar changes introduced. Thanks for reporting!

**Comment by NipunaRanasinghe** [comment] 2020-03-23 09:09
Update: I tried with the latest plugin (1.2.0) and this was not reproduced for me when I was trying the same sample, as below.

![Screenshot from 2020-03-23 14-34-00](https://user-images.githubusercontent.com/29032600/77300136-8fa54280-6d13-11ea-9ef7-37852975ac9f.png)

@pubudu91 Could you also please confirm whether this is resolved with the latest plugin, so that we can close this?

**Comment by NipunaRanasinghe** [comment] 2020-11-02 06:56
closing since not reproducible.

**Closed by NipunaRanasinghe** 2020-11-02 06:56 UTC
Labels: Component/IntellijPlugin, Later, Team/Tooling, Type/Improvement
