### ISSUE TITLE
Invalid type-checking error when calling a dependently-typed method of an object type-descriptor

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#32836] opened 2021-09-21 14:23 UTC
**Description:**
Consider the following code:

```ballerina
import ballerina/sql;

type Product record {|
    int id?;
    string productName;
    float price;
    string currency;
|};

function sample(sql:Client sqlClient) returns error? {
    stream<Product, sql:Error?> prodStream = sqlClient->query("select id, product_name as productName, price, currency from products", Product);
}
```
When compiled, it prints the following error:
```
ERROR [test.bal:(12:46,12:144)] incompatible types: expected 'stream<Product,ballerina/sql:1.0.0:Error?>', found 'stream<rowType,ballerina/sql:1.0.0:Error?>'
```
Since I pass the `rowType` as a parameter, this should return a stream of type `stream<Product, sql:Error?> prodStream`.

**Steps to reproduce:**
See description

**Affected Versions:**
SL Beta 3 RC3

**Comment by MaryamZi** [comment] 2021-09-22 03:17
There seems to be an issue in the type resolving of dependently-typed methods of object type-descriptors, probably due to the check at https://github.com/ballerina-platform/ballerina-lang/blob/v2.0.0-beta.2.1/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeChecker.java#L6116. 

Works for classes and normal functions.

Can be reproduced with

```ballerina
type Product record {|
    int id?;
    string name;
|};

function sample(ClientObject cl) returns error? {
    // Neither works.
    stream<Product> x = cl->query();
    stream<Product> y = cl->query(Product);
}

public type ClientObject client object {
    remote isolated function query(typedesc<record {}> rowType = <>) returns stream <rowType>;
};
```

**Closed** 2021-12-03 02:16 UTC
Labels: Type/Bug, Area/Compiler, Priority/Blocker, Team/CompilerFE, Points/2
