### ISSUE TITLE
Invalid syntax in the sql code used in testing crashes build with bad sad

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#20127] opened 2019-12-02 05:31 UTC
**Description:**
When there is a test case that uses h2 sql, if there's a syntax error in the sql file the build crashes with a bad sad with the following entry in the `ballerina-internal.log`:

```
[2019-12-02 10:52:58,200] SEVERE {b7a.log.crash} - org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException 
org.ballerinalang.util.exceptions.BallerinaException: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.BTestRunner.formatErrorMessage(BTestRunner.java:811)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$null$22(BTestRunner.java:668)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$28(BTestRunner.java:661)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:630)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:160)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:80)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
Caused by: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:146)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.invoke(TesterinaFunction.java:66)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$null$22(BTestRunner.java:664)
	... 11 more
Caused by: java.lang.NullPointerException
	at choreo.api.tests.test_suite_commons.configureIntrospectionApiTestData(tests/test_suite_commons.bal:145)
	at choreo.api.tests.test_suite_commons.setupIdpTestSuite(tests/test_suite_commons.bal:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:130)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:411)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:202)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:175)
	at java.lang.Thread.run(Thread.java:748)
 
```

**Steps to reproduce:**
Create a sql file with a syntax error similar to the following:
```
CREATE TABLE STATE (
  ID varchar(36) NOT NULL,
  ENTITY varchar(60) NOT NULL,
  STATE varchar(60)
  PRIMARY KEY(ID, ENTITY)
);
```
Use that in the test case possibly in a config file:

`url="jdbc:h2:mem:abc;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:components/backend/resources/databases/h2/h2-test.sql'"`

**Affected Versions:**
1.0.4

**OS, DB, other environment details and versions:**

**Comment by anupama-pathirage** [comment] 2019-12-02 10:50
@riyafa Can you please provide sample test case which can reproduce the above issue?

**Comment by mohanvive** [comment] 2021-01-27 05:10
Could not reproduce the issue in the Swan Lake release. Hence, closing the issue.

**Closed by mohanvive** 2021-01-27 05:10 UTC
Labels: Team/DevTools, Type/Bug
