### ISSUE TITLE
Compiler extension creates performance analysis files for dependencies of the application package

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#29177] opened 2021-03-12 17:29 UTC
**Description:**
A Bad Sad Error is thrown when a new connector module is pulled from Ballerina Central for the first time when compiling a Ballerina application. This happens for any new connector based application for the very first compilation. Other than the bad sad error it creates number of JSON files which are not required to be generated at the application level. Those should have been generated at the connector project and should have published to Ballerina Central inside the `.bala` file.

**Steps to reproduce:**
- Create new Ballerina project
- Open the main.bal and paste the following code.

```
import ballerinax/googleapis_calendar;
import ballerina/http;

service on new http:Listener(8090) {
    resource function get sample(http:Caller caller, http:Request request) returns error? {

        googleapis_calendar:Client googleapis_calendarEndpoint = new ({oauth2Config: {
                clientId: "ddd",
                clientSecret: "dd",
                refreshToken: "https://oauth2.googleapis.com/token",
                refreshUrl: "dddddI"
            }});
        var getEventResponse = check googleapis_calendarEndpoint->getEvent("tempA31@gmail.com", "1");
    }
}
```
- build the application
- This should result in an output as follows.

![img](https://user-images.githubusercontent.com/1388997/110975246-81698f80-8385-11eb-9be4-2cd35a08ce74.png)

**Affected Versions:**
Ballerina SL Alpha 2

**OS, DB, other environment details and versions:**
Ubuntu 18.04, JDK 11

**Related Issues (optional):**
N/A

**Comment by azinneera** [comment] 2021-03-16 06:47
This issue explains two bugs:
1. The BadSad error
2. Unnecessary generation of artifacts for bala projects

The first part is a duplicate of #29142 and hence will be tracked by the mentioned issue. This issue can be used to track point 2.

**Comment by miyurud** [comment] 2021-03-23 14:19
Will wait for [Issue 29504](https://github.com/ballerina-platform/ballerina-lang/issues/29504) to be closed to test the status of the fix.

**Comment by azinneera** [comment] 2021-03-23 19:12
@miyurud We introduced a new interface for compiler extensions in slalph3. Could you please check if this reproducible with the new compiler extension design?

**Comment by azinneera** [comment] 2022-11-05 07:14
Closing since this was not complained after Swan Lake GA. Please reopen if this is still valid.

**Closed by azinneera** 2022-11-05 07:14 UTC
Labels: Type/Bug, Priority/High, Team/CompilerFE, Area/CompilerExtensions
