### ISSUE TITLE
Member access should be considered as a variable usage

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#33734] opened 2021-11-10 06:06 UTC
Following give the warning `unused variable 'i'` when it shouldn't.

```ballerina
function f(int[] j) {
    int[] i = j;
    i[0] = 0;
}
```

**Comment by hasithaa** [comment] 2021-11-10 06:37
Your example is valid, IMO following should generate a warning. This requires more complex data flow analysis. 
```
function f() {
    int[] i = [];
    i[0] = 0;
}
```

**Comment by manuranga** [comment] 2021-11-10 06:44
I think we can consider improvements as a separate issue. False positives are higher priority and is a bug, since users have no way to get rid of them.

**Comment by jclark** [comment] 2021-11-10 07:27
@hasithaa Looks like a very hard example to me. I wouldn't worry about it at this stage. I would deal with dead stores into local variables first: e.g.

```
function foo() {
  int x = 1;
  x = 2;
}
```

**Comment by hasithaa** [comment] 2021-11-10 07:33
Ok, will  consider both member access and field access as variable usages for now.

**Comment by jclark** [comment] 2021-11-10 07:42
An usage of a variable as an lvalue *is* a variable usage. It's perfectly reasonable for the only usage of a variable to be as an lvalue.

```
int [] x = foo.bar.x;
x[1] = 2;
```

The issue with your example is not related to variable usage.  The issue is that you have heap allocated a structure, and then stored into to it, but not ever read from it. So this is like a dead-store to a local variable, but much more complicated because you are dealing with the heap. It would require really advanced analysis to deal with this in a general way.

**Comment by MaryamZi** [comment] 2021-11-10 11:45
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/33744.

**Closed by MaryamZi** 2021-11-10 11:45 UTC
Labels: Type/Bug, Team/CompilerFE
