### ISSUE TITLE
Retry statement not suggested

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#29332] opened 2021-03-18 13:02 UTC
**Description:**
<img width="800" alt="Screenshot 2021-03-18 at 18 29 29" src="https://user-images.githubusercontent.com/15815199/111630141-0cc8a200-8818-11eb-9b6a-df947cce457c.png">

**Steps to reproduce:**

**Affected Versions:**
SL Alpha 3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment] 2021-03-30 10:55
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/26590 .

**Closed by mohanvive** 2021-03-30 10:55 UTC
Labels: Team/LanguageServer, Type/Bug
