### ISSUE TITLE
Multiple Worker Receive action is not supported

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#29186] opened 2021-03-14 17:24 UTC
Consider the following code

```ballerina
import ballerina/http;
import ballerina/io;
public function main() {
    worker w1 {
        int w1val = checkpanic calculate("2*3");

        w1val -> w2;

        int w2val = <- w2;
        io:println("[w1] Message from w2: ", w2val);

        w1val ->> w3;
        w2val -> w3;

        checkpanic flush w3;
    }

    worker w2 {
        int w2val = checkpanic calculate("17*5");

        int w1val = <- w1;
        io:println("[w2] Message from w1: ", w1val);

        w1val + w2val -> w1;
    }
    worker w3 {
        [int|error, int|error]  [w1val, w2val] = <- {w1, w2};
         w2val = <- w1;
        io:println("[w3] Messages from w1: ", w1val, ", ", w2val);
    }

    wait w1;
}

function calculate(string expr) returns @tainted int|error {
    http:Client httpClient = checkpanic new ("https://api.mathjs.org");
    string response = <string> check
        httpClient->get(string `/v4/?expr=${expr}`, targetType = string);
    return check int:fromString(response);
}
```
Compiling the above code gives the below error

```
:(27:53,27:61)] multiple receive action not yet supported
error: compilation contains errors
```

**Comment by MaryamZi** [comment] 2021-03-15 05:20
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/18163.

**Closed** 2021-08-18 14:40 UTC
Labels: Type/Bug, Priority/High, Status/Duplicate, Team/CompilerFE, Lang/Workers, Spec/Different
