### ISSUE TITLE
Issue in jsonutils:fromTable

### ISSUE THREAD

**Issue by DeveloperLK** [ballerina-platform/ballerina-lang#20397] opened 2019-12-15 06:22 UTC
There is an issue in fromTable method in the jsonutils. (ballerina v1.0.3)

**e.g. (error) -**

```
import ballerina/log;
import ballerina/io;
import ballerinax/java.jdbc;
import ballerina/http;

import ballerina/jsonutils;

jdbc:Client sampleDB = new({
    url: "jdbc:mysql://localhost:3306/sample",
    username: "root",
    password: "",
    poolOptions: { maximumPoolSize: 5 },
    dbOptions: { useSSL: false }
});

type departments record {
    int dept_no;
    string dept_name;
};

@http:ServiceConfig {
    basePath: "/hello"
}
service sampleService on new http:Listener(9090) {

    @http:ResourceConfig {
        methods: ["GET"],
        path: "/hello/{departmentId}"
    }
    resource function sampleResource(http:Caller caller, http:Request req,  int departmentId) {

        int i = 0;
        while(i<10){
        
           
            var selectRet1 = sampleDB->select("SELECT * FROM departments where dept_no=?", departments,departmentId);
            if (selectRet1 is table<departments>) {
                json[] jsonConversionRet1 = <json[]>jsonutils:fromTable(selectRet1);
                string s = <string> jsonConversionRet1[0].dept_name;
                io:println("Counter: "+i.toString());
                io:println("DepartmentName: "+s);
            }
            else {
                error err = selectRet1;
                io:println("Select data from department table failed: ",<string> err.detail()["message"]);
            }

            i=i+1;
        }    

        var result = caller->respond(<@untainted> "Hello, Service Works!");
        
        if (result is error) {
            log:printError("Error sending response", result);
        }
    }
}



```

**Output (Error) :** 

_Counter: 0
DepartmentName: Support
Counter: 1
DepartmentName: Support
Counter: 2
DepartmentName: Support
Counter: 3
DepartmentName: Support
Counter: 4
DepartmentName: Support
Select data from department table failed: failed to execute select query: error while getting the connection for ClientConnector. HikariPool-1 - Connection is not available, request timed out after 30000ms.._

The error seems to be coming from jsonutils:fromTable which exhausts the MySQL database by not releasing the connections. As a solution(See below code snippet) the jsonutils:fromTable is replaced with .hasNext() and .getNext() methods. Here the dept_name is accessed through a record type.
But the problem here is that the table cannot be directly converted to json. We have to get the values from the record and construct the json. 
**e.g. (fix) -**  

```
import ballerina/log;
import ballerina/io;
import ballerinax/java.jdbc;
import ballerina/http;

jdbc:Client sampleDB = new({
    url: "jdbc:mysql://localhost:3306/sample",
    username: "root",
    password: "",
    poolOptions: { maximumPoolSize: 5 },
    dbOptions: { useSSL: false }
});

type departments record {
    int dept_no;
    string dept_name;
};

@http:ServiceConfig {
    basePath: "/hello"
}
service sampleService on new http:Listener(9090) {

    @http:ResourceConfig {
        methods: ["GET"],
        path: "/hello/{departmentId}"
    }
    resource function sampleResource(http:Caller caller, http:Request req,  int departmentId) {

        int i = 0;
        while(i<10){
        
           
            var selectRet1 = sampleDB->select("SELECT * FROM departments where dept_no=?", departments,departmentId);
            if (selectRet1 is table<departments>) {
                                
                anydata x;
                string s="";

                while(selectRet1.hasNext()){
                    x = selectRet1.getNext();
                }
                if(x is record{}){
                    s = <string>x["dept_name"];
                }

                io:println("Counter: "+i.toString());
                io:println("DepartmentName: "+s);
            }
            else {
                error err = selectRet1;
                io:println("Select data from department table failed: ",<string> err.detail()["message"]);
            }

            i=i+1;
        }    

        var result = caller->respond(<@untainted> "Hello, Service Works!");
        
        if (result is error) {
            log:printError("Error sending response", result);
        }
    }
}
```

**Output  :**

_Counter: 0
DepartmentName: Support
Counter: 1
DepartmentName: Support
Counter: 2
DepartmentName: Support
Counter: 3
DepartmentName: Support
Counter: 4
DepartmentName: Support
Counter: 5
DepartmentName: Support
Counter: 6
DepartmentName: Support
Counter: 7
DepartmentName: Support
Counter: 8
DepartmentName: Support
Counter: 9
DepartmentName: Support_

MySQL Table Structure:  Please find the attachment below (mysql.png)
![mysql](https://user-images.githubusercontent.com/36729837/70858945-46ce3880-1f31-11ea-84e8-427e45cdb33d.png)

**Comment by anupama-pathirage** [comment] 2019-12-16 10:05
This is the expected behavior of the table to JSON conversion.  With the below two lines, you are creating JSON and accessing only the first element of the JSON array (i.e. json data is not fully consumed)

```
json[] jsonConversionRet1 = <json[]>jsonutils:fromTable(selectRet1);
string s = <string> jsonConversionRet1[0].dept_name;
```

In ballerina, table to json or xml conversion happens on demand.   That means the full result does not build in the server but happens only when it is accessed. This allows unlimited payload sizes in the results, especially when we stream out the data to a service client. In the above two lines, json data is not fully consumed. In ballerina, the underlying database connection associated with table is automatically released, only if the table data is fully consumed(i.e. fully iterated via a foreach or while loop, json or xml converted data fully consumed). Otherwise, the connection will remain open assuming the payload will access later.

So you have two options here.

1. Close the table manually within the if clause.
```          
if (selectRet1 is table<departments>) {
                json[] jsonConversionRet1 = <json[]>jsonutils:fromTable(selectRet1);
                string s = <string> jsonConversionRet1[0].dept_name;
                io:println("Counter: "+i.toString());
                io:println("DepartmentName: "+s);
                selectRet1.close();
            }
```
2.  I don't see a real requirement of converting the table to json here as you are only accessing the returned data rows and json conversion is somewhat performance heavy operation as well. So instead of converting to json you can iterate the table directly and get the data as follows.

```
if (selectRet1 is table<departments>) {
                foreach departments row in selectRet1 {
                    io:println("Counter: "+i.toString());
                    io:println("DepartmentName: "+row.dept_name);
                }
            }
```
Since this is not issue, we are closing the issue. If you need further clarifications, feel free to reopen the issue.

**Closed by anupama-pathirage** 2019-12-16 10:05 UTC
