### ISSUE TITLE
DecimalNumber and HexIntLiteral give different errors for invalid type cast expressions

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#32716] opened 2021-09-14 04:46 UTC
**Description:**
Consider the following program,
``` ballerina
public function main() {
    any x = <boolean> 0;

    x = <boolean> 0x0; 
}
```
compiler output,
```
ERROR [test.bal:(2:13,2:25)] incompatible types: 'int' cannot be cast to 'boolean'
ERROR [test.bal:(4:9,4:22)] incompatible types: 'byte' cannot be cast to 'boolean'
```
As I think, the second error also should refer to `int` instead of `byte`.

**Comment by lochana-chathura** [comment] 2021-09-30 05:39
Related issue #31750

**Comment by MaryamZi** [comment] 2022-03-02 02:30
Both of these now result in the same error.

```
incompatible types: 'int' cannot be cast to 'boolean'
```

Keeping the issue open to add a test.

**Comment by KavinduZoysa** [comment] 2023-03-08 04:26
Closing since the issue is fixed.

**Closed by KavinduZoysa** 2023-03-08 04:26 UTC
Labels: Type/Improvement, Team/CompilerFE, Lang/Expressions/TypeCast, Error/TypeG
