### ISSUE TITLE
Cant goto definition of recored type

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#24308] opened 2020-06-18 10:37 UTC
<img width="681" alt="Screenshot 2020-06-18 at 4 01 07 PM" src="https://user-images.githubusercontent.com/1686124/85010347-7d556c00-b17d-11ea-9c37-38c01a9193e4.png">

source: https://dev.ballerina.io/learn/by-example/basic-documentation.html

see following error in log
```
[Info  - 4:01:29 PM] Operation 'text/hover' {projectRoot: '/Users/manu/sc/2020-06-18'}, served through cache within 0ms
[Error - 4:01:38 PM] Operation 'text/definition' failed! {uri: '/Users/manu/sc/2020-06-18/my.bal', line: 39, col: 12, error: 'Couldn't find a valid identifier token at cursor!'}
java.lang.IllegalStateException: Couldn't find a valid identifier token at cursor!
	at org.ballerinalang.langserver.util.references.ReferencesUtil.findCursorTokenAndCompileModules(ReferencesUtil.java:175)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getDefinition(DefinitionUtil.java:70)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$definition$6(BallerinaTextDocumentService.java:309)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by manuranga** [comment] 2020-06-18 10:41
It starts working when I restart, but when I do some edits somewhere else it breaks again. may be it's related to #24305 ?

**Comment by rasika** [comment] 2020-06-18 12:00
Please re-check in a docker ext jars removed pack. Seems like not reproducible now.

**Comment by nadeeshaan** [comment] 2020-06-22 05:07
This has been fixed since the Docker Compiler plugin issue is fixed. Hence closing the issue

**Closed by nadeeshaan** 2020-06-22 05:07 UTC
Labels: Area/Tooling, Component/VScodePlugin, Type/Bug
