### ISSUE TITLE
[Bug]: Dependency update warning shows for new packages in VSCode

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#40597] opened 2023-06-05 08:30 UTC
### Description

For new projects, there is no need to show the warning about the dependency update. This behavior is correct in the CLI build but the warning is shown in LS.

### Steps to Reproduce

1. Create a new package and open it is VSCode
2. Execute bal build in the VSCode terminal
    **Observation**: The dependency update warning is shown in the `Problems` tab
3. Open the Dependencies.toml 
    **Observation**: The warning goes away

**Expected behavior**:
The warning should not be shown at all for a new package

### Affected Version(s)

2201.5.0 and above

### Related area

-> Compilation

**Comment by gayaldassanayake** [comment] 2023-06-06 06:26
I was able to reproduce the issue. Will provide a fix with https://github.com/ballerina-platform/ballerina-lang/pull/40522.

**Comment by gayaldassanayake** [comment] 2023-09-13 06:33
The fix was intended to go with https://github.com/ballerina-platform/ballerina-lang/pull/41197, however was not merged due to the concerns over the design.

**Closed** 2023-12-15 06:32 UTC
Labels: Type/Bug, Priority/High, Area/ProjectAPI
