### ISSUE TITLE
[Bug]: Invalid diagnostic when initializing readonly record with object as a field

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#42749] opened 2024-05-14 08:34 UTC
### Description

$Subject.  Consider the below code. Code works fine when we remoe readonly from the type def.

Consider the following code - 

Getting following diagnostics from the compiler - 
cannot initialize abstract object 'null'
too many arguments in call to 'new()'

``` ballerina
type TokenHandler readonly & record {
    http:Client meow;
};

function foo() {
    TokenHandler handler = {
        meow: check new ("http://localhost:8080")
    };
}
```

### Related area

-> Compilation

**Comment by MaryamZi** [comment] 2024-05-17 09:11
This is not a bug.

Since the field is in a `readonly` type, the type of the field is effectively `http:Client & readonly`, and when you use a readonly intersection with a non-readonly class you get an object type, not a class. So you can't use `new` to provide a value for such a field, because `new` isn't allowed with object types, only classes.

Moreover, `new http:Client("http://localhost:8080")` wouldn't work since it creates a mutable object, not an immutable one. You need to provide an immutable value that is also a subtype of `http:Client`.

Simplified sample:

```ballerina
class MutableObject {
    string url;

    function init(string url) returns error? {
        self.url = url;
    }
}

readonly class ImmutableObject {
    string url;

    function init(string url) returns error? {
        self.url = url;
    }
}

type TokenHandler readonly & record {
    MutableObject meow;
};

function foo() {
    TokenHandler _ = {
        meow: check new ("http://localhost:8080") // error
    };

    TokenHandler _ = {
        meow: check new ImmutableObject("http://localhost:8080") // OK
    };

    TokenHandler _ = {
        meow: object { // OK, constructed as immutable object
            string url = "http://localhost:8080";
        }
    };
}
```

**Comment by anupama-pathirage** [comment] 2024-06-08 14:40
Closing the issue based on the above comment. @xlight05 feel free to reopen if you have further concerns.

**Closed by anupama-pathirage** 2024-06-08 14:40 UTC
Labels: Type/Question, Team/CompilerFE, Area/CodeAnalysis
