### ISSUE TITLE
NoClassDefFoundError when running the composer.bat file

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-lang#8444] opened 2018-05-09 08:59 UTC
**Description:**
NoClassDefFoundError when running the composer.bat file

**Steps to reproduce:**
1.Set the ballerina home to ballerina-0.970.1-SNAPSHOT/
2.Run the command composer.bat from the bin directory

**Affected Versions:**
 Ballerina 0.970.1-SNAPSHOT

**OS, DB, other environment details and versions:**
Windows 10
Java 1.8.0_171
```
C:\Users\wso2\Desktop\09052018\ballerina-tools-0.970.1-SNAPSHOT\bin>composer.bat
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/constructor/BaseConstructor
        at org.wso2.carbon.config.ConfigProviderFactory.getConfigProvider(ConfigProviderFactory.java:83)
        at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.<init>(MSF4JHttpConnectorListener.java:78)
        at org.wso2.msf4j.MicroservicesRunner.start(MicroservicesRunner.java:265)
        at org.ballerinalang.composer.server.core.Server.start(Server.java:69)
        at org.ballerinalang.composer.server.launcher.ServerLauncher.main(ServerLauncher.java:141)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.constructor.BaseConstructor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

```

**Comment by shavantha** [comment] 2018-05-14 09:40
The composer seems to start when I checked with Ballerina 0.970.2-SNAPSHOT

**Comment by rasika** [comment] 2018-05-15 05:03
Closing since cannot reproduce in the latest.

**Closed by rasika** 2018-05-15 05:03 UTC
Labels: Severity/Blocker, component/Composer
