### ISSUE TITLE
Project Compilation diagnostic does not include relative path

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#27231] opened 2020-11-27 10:53 UTC
**Description:**
When invoke the `PackageCompilation.diagnosticResult` API, it provides all the diagnostics within the given package. Although the diagnostic location only include the file name, making it hard to distinguish which file exactly when there are multiple files with same name in different modules.

**Steps to reproduce:**
Following project structure
<img width="350" alt="Screenshot 2020-11-27 at 16 19 51" src="https://user-images.githubusercontent.com/1329674/100441421-7176ba00-30cc-11eb-85c8-ba3424a05826.png">

**Affected Versions:**
SLP6-SNAPSHOT

**Comment by hevayo** [comment] 2020-12-01 04:27
Duplicate of  https://github.com/ballerina-platform/ballerina-lang/issues/27178

**Closed** 2021-01-15 18:53 UTC
Labels: Component/Compiler, Component/ProjectAPI, Priority/Blocker, SwanLakeDump, Type/Improvement
