### ISSUE TITLE
It compiles and runs well but the UI doesn't figure it out the syntax error is fixed.

### ISSUE THREAD

**Issue by mohamedrks** [ballerina-platform/ballerina-lang#4518] opened 2018-01-30 20:18 UTC
When you write a solution purposely make a syntax error. 

you would get a red lines under the exact syntax error.

then fix it but the red lines still exists without disappear. may be a UI issue the tool doesn't figure it out that the syntax error is fixed.

have a look into the following images. after refreshing browser only it disappear.

Thanks,
Best Regards,
Rikaz.

![image 1](https://user-images.githubusercontent.com/8801659/35589110-c6a662a4-0628-11e8-89db-eaa80cfe76dc.png)
![image 2](https://user-images.githubusercontent.com/8801659/35589127-ce046c8a-0628-11e8-9df4-43192d895084.png)

**Comment by nadeeshaan** [comment] 2018-05-20 05:37
Hi Rikaz (@mohamedrks)
This cannot reproduce in the latest master, hence closing the issue. If the issue exists still, please feel free to reopen.

**Closed by nadeeshaan** 2018-05-20 05:37 UTC
Labels: component/Composer
