### ISSUE TITLE
Provide a rename popup with create variable code action

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36218] opened 2022-05-19 09:33 UTC
**Description:**
$subject

**Describe your problem(s)**
Right now when we create a variable the var name is auto generated and is not contextual or descriptive.

**Describe your solution(s)**
Have look at the RedHat java plugin for how they provide this. RedHat java plugin uses the Eclipse language server (https://github.com/eclipse/eclipse.jdt.ls) to provide this functionality. We might want to look at both of those implementations.

**Comment by gayalkuruppu** [comment] 2022-05-23 08:09
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/36139

**Closed by gayalkuruppu** 2022-05-23 08:09 UTC
Labels: Type/Improvement, Team/LanguageServer, Points/6, Area/CodeAction
