### ISSUE TITLE
Ballerina VS Code plugin stops working after sometime

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#29497] opened 2021-03-23 11:25 UTC
**Description:**
* I am using VS Code version 1.54.1 with Ballerina VS Code Plugin SwanLake Alpha3.
* When using VS Code for about two to three hours suddenly VS Code ballerina plugin stops working.
* Found following error logs in VS Code ballerina extension logs.
```
[Info  - 4:15:04 PM] Operation 'text/didChange' {fileUri: 'file:///home/ayeshalm/projects/ayeshLK/kafka-weather-reporter/kafka_client.bal'} updated
[Info  - 4:15:05 PM] Operation 'text/didChange' {fileUri: 'file:///home/ayeshalm/projects/ayeshLK/kafka-weather-reporter/kafka_client.bal'} updated
[Info  - 4:15:06 PM] Operation 'text/didChange' {fileUri: 'file:///home/ayeshalm/projects/ayeshLK/kafka-weather-reporter/kafka_client.bal'} updated

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ForkJoinPool.commonPool-worker-5"
Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: Java heap space
```

**Suggested Labels:**
https://github.com/ballerina-platform/plugin-vscode/labels/Version%2FSLAlpha3

**OS, DB, other environment details and versions:**    
* Ubuntu 20.04

**Steps to reproduce:**
* Work in a Ballerina Project in VS Code with ballerina plugin enabled for 2-3 hours.

**Comment by IMS94** [comment] 2021-04-02 07:39
@ayeshLK Do you have the source code that you tried with you?

**Comment by IMS94** [comment] 2021-04-06 08:15
Tried reproducing the same with general ballerina code and investigated the memory usages/leaks using JConsole and heap dumps. Even after sometime, when a manual GC is performed (using JConsole), the memory was cleared and went back to the initial level. @nadeeshaan and I both participated above investigations.

Need to reproduce the above scenario with the help of @ayeshLK later, which we are unable to do right now due to an issue with his laptop.

**Comment by nadeeshaan** [comment] 2021-07-20 09:48
With the past releases (beta1, beta2) this issue could not be reproduced. Hence closing this issue. If the issue can be observed further, please reopen.

**Closed by nadeeshaan** 2021-07-20 09:48 UTC
Labels: Priority/Blocker, SwanLakeDump, Team/LanguageServer, Type/Bug, Version/SLAlpha3
