### ISSUE TITLE
Add float literal to the new parser

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-lang#22456] opened 2020-04-03 11:20 UTC
**Description:**
Refer: https://ballerina.io/spec/lang/2020R1/#floating-point-literal

**Comment by SupunS** [comment] 2020-04-21 07:35
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/22358

**Closed by SupunS** 2020-04-21 07:35 UTC
