### ISSUE TITLE
CCE when hover on a type

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#30780] opened 2021-05-25 09:34 UTC
When I hover on a type (eg: int, string) it causes CCE in `HoverUtil`

```
[Error - 3:02:14 PM] Operation 'text/hover' failed! {uri: '/home/dulmina/Documents/test.bal', [12:26], error: 'class io.ballerina.compiler.api.impl.symbols.BallerinaIntTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaIntTypeSymbol and io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol are in unnamed module of loader 'app')'}
java.lang.ClassCastException: class io.ballerina.compiler.api.impl.symbols.BallerinaIntTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaIntTypeSymbol and io.ballerina.compiler.api.symbols.TypeReferenceTypeSymbol are in unnamed module of loader 'app')
	at org.ballerinalang.langserver.hover.HoverUtil.getHoverForSymbol(HoverUtil.java:96)
	at org.ballerinalang.langserver.hover.HoverUtil.getHover(HoverUtil.java:74)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$hover$1(BallerinaTextDocumentService.java:161)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by IMS94** [comment] 2021-06-03 06:02
Relates to https://github.com/ballerina-platform/ballerina-lang/issues/30697

This seems to be fixed by https://github.com/ballerina-platform/ballerina-lang/pull/30722 and cannot be reproduced on master now.

**Closed by IMS94** 2021-06-03 06:02 UTC
Labels: Team/LanguageServer, Type/Bug
