### ISSUE TITLE
Ballerina automatically decoding XML content

### ISSUE THREAD

**Issue by vidurananayakkara** [ballerina-platform/ballerina-lang#39507] opened 2023-01-26 12:22 UTC
**Description:**

**Steps to reproduce:**
-- Send the below XML payload to a Ballerina service
```xml
<sequence
	xmlns="http://ws.apache.org/ns/synapse" name="documents_update" trace="disable">
	<!-- WSO2 GENERAL PROPERTIES -->
	<!-- When using the Loopback mediator, it is mandatory to set the following property -->
	<property name="api.ut.backendRequestTime" expression="get-property('SYSTEM_TIME')"/>
	<!-- Needed to use a proxy server -->
	<property name="POST_TO_URI" scope="axis2" type="STRING" value="true"/>
	<!-- SPECIFIC PROPERTIES -->
	<property name="documentId" expression="get-property('uri.var.documentId')"/>
	<!-- Load input fields into properties -->
	<script language="js">var log = mc.getServiceLog();
var payload = mc.getPayloadJSON();
log.info(JSON.stringify(payload));
for (i = 0; i &lt; payload.otherFields.length; ++i) {
mc.setProperty(payload.otherFields[i].id,payload.otherFields[i].value);
log.info(String(payload.otherFields[i].id));
}

</script>
	<!-- LOGON -->
	<sequence key="gov:apimgt/miles/general/v1.1.x/sequences/MWS_Logon.xml"/>
	<sequence key="gov:apimgt/miles/general/v1.1.x/sequences/MWSCheckErrors.xml"/>
	<filter source="$ctx:responseStatus" regex="error">
		<then>
			<loopback/>
		</then>
	</filter>
	<filter source="$ctx:country" regex="pt">
		<then>
			<sequence key="gov:apimgt/miles/documentManagement/v1.2.x/sequences/documents/document_update_document_pt.xml"/>
		</then>
	</filter>
	<!--
<log description="Log"><property expression="$body/*" name="Document update:" /></log>
-->
	<sequence key="gov:apimgt/miles/documentManagement/v1.2.x/sequences/documents/documents_read_byParameters.xml"/>
	<!--
<sequence key="gov:apimgt/miles/documentManagement/v1.2.x/sequences/documents/document_read_documentContent.xml"/><sequence key="gov:apimgt/miles/documentManagement/v1.2.x/sequences/documents/document_read_document.xml"/> -->
	<loopback/>
</sequence>
```

Upon receiving the payload from Ballerina, it is changed as below:

```xml
<sequence
	xmlns="http://ws.apache.org/ns/synapse" name="documents_update" trace="disable">
	<!-- WSO2 GENERAL PROPERTIES -->
	<!-- When using the Loopback mediator, it is mandatory to set the following property -->
	<property name="api.ut.backendRequestTime" expression="get-property('SYSTEM_TIME')"/>
	<!-- Needed to use a proxy server -->
	<property name="POST_TO_URI" scope="axis2" type="STRING" value="true"/>
	<!-- SPECIFIC PROPERTIES -->
	<property name="documentId" expression="get-property('uri.var.documentId')"/>
	<!-- Load input fields into properties -->
	<script language="js">var log = mc.getServiceLog();
var payload = mc.getPayloadJSON();
log.info(JSON.stringify(payload));
for (i = 0; i < payload.otherFields.length; ++i) {
mc.setProperty(payload.otherFields[i].id,payload.otherFields[i].value);
log.info(String(payload.otherFields[i].id));
}
	</script>
	<!-- LOGON -->
	<sequence key="gov:apimgt/miles/general/v1.1.x/sequences/MWS_Logon.xml"/>
	<sequence key="gov:apimgt/miles/general/v1.1.x/sequences/MWSCheckErrors.xml"/>
	<filter source="$ctx:responseStatus" regex="error">
		<then>
			<loopback/>
		</then>
	</filter>
	<filter source="$ctx:country" regex="pt">
		<then>
			<sequence key="gov:apimgt/miles/documentManagement/v1.2.x/sequences/documents/document_update_document_pt.xml"/>
		</then>
	</filter>
	<!--
<log description="Log"><property expression="$body/*" name="Document update:" /></log>
-->
	<sequence key="gov:apimgt/miles/documentManagement/v1.2.x/sequences/documents/documents_read_byParameters.xml"/>
	<!--
<sequence key="gov:apimgt/miles/documentManagement/v1.2.x/sequences/documents/document_read_documentContent.xml"/><sequence key="gov:apimgt/miles/documentManagement/v1.2.x/sequences/documents/document_read_document.xml"/> -->
	<loopback/>
</sequence>
```
As you notice '\&lt;' was changed with '<' character.

How do we avoid '&lt' being changed to '<'

**Comment by vidurananayakkara** [comment] 2023-02-07 07:47
Please note the source code by the customer.

```
import ballerina/io;

public function main() returns error? {

    string xmlFilePathIn = "soapin.xml";
    string xmlFilePathOut = "soapout.xml";
    
    xml messageXml = check io:fileReadXml(xmlFilePathIn);
    check io:fileWriteXml(xmlFilePathOut, messageXml);
}

```

**Comment by warunalakshitha** [comment] 2023-02-07 10:01
I have tested the above example. I couldn't reproduce the issue since I got the &lt character without any change. 
BTW is this tested in 1.2.13 since 1.2.x does not have io:fileReadXml method?

**Comment by hasithaa** [comment] 2023-02-08 14:59
After analyzing the actual use case, we found the actual issue is with `&gt;` being replaced with `>`. 

The jBallerina implementation uses woodstox as the XML parser and this issue was discussed in this [issue](https://github.com/FasterXML/woodstox/issues/41). Based on that is given behavior is spec compliant. I verified this in [XML spec](https://www.w3.org/TR/xml/#syntax) as well. It says,

> "The right angle bracket (>) may be represented using the string " &gt; ", and must, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section."

So generated XML is compliant with the XML spec. See the following program. 

```ballerina
import ballerina/io;

public function main() returns error? {
    xml a = xml `<b><a title="&lt; &gt;">&lt; &gt;</a><c><![CDATA[ &lt; &gt; ]]></c></b>`;
    xml b = xml `<b><a title="&lt; >">&lt; ></a><c> &lt; > </c></b>`;
    io:println(a == b); // true
}
```

Hence closing this issue.

**Comment by warunalakshitha** [comment] 2023-02-15 02:48
There is issue with double unescaping when we read xml file with io:fileReadXml. This can be reproducible if you read xml file as below.

```xml
<data>&lt;xsl:apply-templates someattrib=" &amp;gt;" /></data>
```

Out put

```xml
<data>&lt;xsl:apply-templates someattrib=" >" /></data>
```

But should be

```xml
<data>&lt;xsl:apply-templates someattrib=" &amp;gt;" /></data>
```

**Closed** 2023-02-22 11:01 UTC
Labels: Type/Bug, Team/jBallerina, Reason/Invalid
