### ISSUE TITLE
[Bug]: `java.lang.ClassFormatError` runtime error while invoking client resource methods in Slack connector

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#43094] opened 2024-07-13 16:57 UTC
### Description

Getting the below runtime exception when invoking some of the client resource  methods  in  the `ballerinax/slack` connector

```
[2024-07-11 04:07:55,020] SEVERE {b7a.log.crash} - Illegal field name "$Client_$get$users\.getPresence_headers" in class ballerinax/slack$test/4/tests/test_cases 
java.lang.ClassFormatError: Illegal field name "$Client_$get$users\.getPresence_headers" in class ballerinax/slack$test/4/tests/test_cases
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at ballerinax.slack$test.4.slack$1.$gen$ballerinax&0047slack&00584&00460&00460&0046&0060init&00622(slack$1:22)
        at ballerinax.slack$test.4.slack$1.$gen$ballerinax&0047slack&00584&00460&00460&0046&0060init&00621(slack$1:2)
        at ballerinax.slack$test.4.slack$1.$gen$ballerinax&0047slack&00584&00460&00460&0046&0060init&00620(slack$1:2)
        at ballerinax.slack$test.4.$_init.$gen$&0046&0060init&0062(slack:22)
        at ballerinax.slack$test.4.$_init.$moduleInit(slack)
        at ballerinax.slack$test.4.$_init.$moduleExecute(slack)
        at ballerinax.slack$test.4.$_init.$lambda$$moduleExecute$(slack)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
        at java.base/java.lang.Thread.run(Thread.java:840)
  ```

### Steps to Reproduce

Clone https://github.com/ballerina-platform/module-ballerinax-slack repository and run the gradle build on top of SL 2201.9.2 version.

### Affected Version(s)

2201.9.2

### OS, DB, other environment details and versions

MacOS

### Related area

-> Runtime

### Suggested label(s) (optional)

Could be related to the fix for https://github.com/ballerina-platform/ballerina-lang/issues/42988

**Comment by NipunaRanasinghe** [comment] 2024-07-13 16:58
Please note that this is a blocker for the revamped Slack connector (v4.0.0) release

**Comment by HindujaB** [comment] 2024-07-15 12:25
This only happens with the `test` command where a test case calls a client resource function without providing a defaultable parameter.  It seems the method name is not encoded properly.

I will verify the changes that caused this behavior and send a fix.

**Comment by HindujaB** [comment] 2024-07-15 12:33
A simplified sample to reproduce this. 
in `main.bal`
```ballerina
public isolated client class Client {
    final string greeting;

    public isolated function init(string greeting = "Hello World!") returns error? {
        self.greeting = greeting;
        return;
    }

    resource isolated function get users\.getPresence(map<string|string[]> headers = {}) returns string|error {
        return string `/users.getPresence ${self.greeting} ${headers.toString()}`;
    }
}
```

In `test.bal` inside `tests` directory
```ballerina
import ballerina/test;

Client slack = check new ("test");

@test:Config {
}
function testGetPresence() returns error? {
       json response = check slack->/users\.getPresence();
       test:assertTrue(check response.ok, "The ok attribute was not equal to true");
}
```
using `bal test` command will cause the error

**Comment by HindujaB** [comment] 2024-07-16 05:26
It seems like the issue is there in the 2201.6.x, 2201.7.x, 2201.8.x 2201.9.x as well.

**Comment by HindujaB** [comment] 2024-07-18 04:34
This issue is fixed in the master branch https://github.com/ballerina-platform/ballerina-lang/pull/42709.

**Closed** 2024-07-19 04:07 UTC
Labels: Type/Bug, Priority/Blocker
