### ISSUE TITLE
Unicode characters are not supported in identifiers

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#28376] opened 2021-02-02 10:00 UTC
Please consider the following code

```ballerina
import ballerina/io;

public function main() {
	io:println("Hello!");
}

// This is a comment
// You can have Unicode identifiers
function พิมพ์ชื่อ(string d) {
   io:println(d);
}

```
When compiling the above code, the following errors are printed.

```
Compiling source
        gimantha/myProj:0.1.0
ERROR [test.bal:(9:10,9:10)] missing function name
ERROR [test.bal:(9:19,9:20)] invalid token 'พิมพ์ชื่อ'
error: compilation contains errors
```

**Comment by lochana-chathura** [comment] 2021-02-25 11:09
Duplicate of #28269

**Closed by lochana-chathura** 2021-02-25 11:09 UTC
Labels: CompilerSLDump, Priority/Blocker, SwanLakeDump, Team/CompilerFE, Type/Bug, Type/SpecDeviation
