### ISSUE TITLE
"Call Failed" when the data table converted to JSON is set as the payload

### ISSUE THREAD

**Issue by JayathmaChathurangani** [ballerina-platform/ballerina-lang#10531] opened 2018-09-25 03:42 UTC
I am writing a simple ballerina program using the version 0.981.1 to retrieve some values from a mysql database. 

**Code:**
```
import ballerina/http;
import ballerina/mysql;
import ballerina/log;
import ballerina/io;

// Mysql as the database
endpoint mysql:Client testDB {
    host: "localhost",
    port: 3306,
    name: "type1SportsNewsDb",
    username: "root",
    password: "user",
    poolOptions: { maximumPoolSize: 50 },
    dbOptions: { useSSL: false }
};

service<http:Service> serviceSports bind { port: 8082 } {

    getAll(endpoint caller, http:Request req) {
        http:Response res = new;

        try {
            var selectRet = testDB->select("SELECT * FROM type1SportsNewsDb.news;", ());

            //json returnValue;
            match selectRet {
                table tableReturned => {
                    //convert to json
                    var jsonConversionRet = <json>tableReturned;
                    match jsonConversionRet {
                        json jsonRes => {
                            res.setPayload(untaint jsonRes);
                            tableReturned.close();
                        }
                        error e => {
                            tableReturned.close();
                            res.statusCode = 500;
                            res.setPayload({"Error": "Internal Error"});
                        }
                    }
                }
                error e => {
                    //log:printError(e.message);
                    res.statusCode = 500;
                    res.setPayload({"Error": "Internal Error"});
                }
            }
        } catch (error err) {
            res.statusCode = 500;
            res.setPayload({"Error": "Internal Error"});
        }

        _ = caller -> respond(res);
    }

    @http:ResourceConfig {
        methods: ["GET"],
        path:"test"
    }
    testService(endpoint caller, http:Request req) {
        http:Response res = new;
        res.setPayload("hello, this service provide sports news");
        _ = caller -> respond(res);
    }
}

```
**curl command:**

curl -i -X GET http://localhost:8082/serviceSports/getAll

**Response received:** 

HTTP/1.1 500 Internal Server Error
content-type: text/plain
content-length: 11
server: ballerina/0.981.1
date: Tue, 25 Sep 2018 09:00:19 +0530

call failed

**Error in console:**

ballerina: initiating service(s) in 'serviceB'
ballerina: started HTTP/WS endpoint 0.0.0.0:8082
error: ballerina/runtime:CallFailedException, message: call failed
	at serviceB:0.0.0:serviceSports.getAll(service-b.bal:57)
caused by error, message: trying to perform hasNext operation over a closed table
	at ballerina/http:respond(http_connection.bal:49)

worker errors: {default={message:"Trying to perform hasNext operation over a closed table", cause:null}}
{message:null, cause:null}

I am using the following remedies to fix it. Actually it is required to convert the JSON to string. 
log:printDebug(jsonRes.toString()); or
io:println(jsonRes.toString()); or
string ans = jsonRes.toString();

Then everything run smoothly. 
Actually this was there in version 0.95 as well.

**Comment by SupunS** [comment] 2018-09-25 05:29
When a datatable is converted to JSON it will do the conversion on-demand. Therefore the datable needs to be alive until the JSON is consumed. Above issue is because you are closing the datatable before sending it back as the response (before consumed). This is the expected behavior for datatables. Remove `tableReturned.close();` line and let the table to be auto-close. That will solve the issue.

Making `jsonRes.toString()` converts the entire table JSON in memory, and no longer depends on the backing datatable. Thats why you don't get the error. However this is not recommended.

**Closed by SupunS** 2018-09-25 05:29 UTC
