### ISSUE TITLE
[Parser] Missing identifier in XML namespace crashes the parser

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#24928] opened 2020-07-24 08:20 UTC
The following crashes the parser:
```ballerina
xmlns  as ns2;
```
Crash log:
```
[2020-07-24 13:48:10,138] SEVERE {b7a.log.crash} - io.ballerinalang.compiler.syntax.tree.IdentifierToken cannot be cast to io.ballerinalang.compiler.syntax.tree.ExpressionNode 
java.lang.ClassCastException: io.ballerinalang.compiler.syntax.tree.IdentifierToken cannot be cast to io.ballerinalang.compiler.syntax.tree.ExpressionNode
	at io.ballerinalang.compiler.syntax.tree.ModuleXMLNamespaceDeclarationNode.namespaceuri(ModuleXMLNamespaceDeclarationNode.java:40)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2962)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:410)
	at io.ballerinalang.compiler.syntax.tree.ModuleXMLNamespaceDeclarationNode.apply(ModuleXMLNamespaceDeclarationNode.java:62)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:477)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:410)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:435)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:143)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:116)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

Checked in slp2 and current master

**Comment by SupunS** [comment] 2020-07-24 08:25
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/24476

Fix is available at https://github.com/ballerina-platform/ballerina-lang/pull/24912

**Closed** 2020-07-24 08:36 UTC
Labels: Area/Language, Component/Parser, Type/Bug
