### ISSUE TITLE
Debugging doesn't work when there are records present

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#20322] opened 2019-12-10 09:34 UTC
**Description:**
When you use records in the source, debugging doesn't work, even for other variables. 

**Steps to reproduce:**
- Create a module
- Add two files: one file with the record definition and one file where that record type is used
- Debug and see

```ballerina
import ballerina/io;

public function main() {
    int b = 10;
    Person p = {
        name: "",
        age: 0
    };
    int a = 1;
    io:println(p);
    int c = 20;
    io:println();
}
```

**Comment by NipunaRanasinghe** [comment] 2021-04-05 05:00
Debugger instructions has been improved to work with the external files and therefore cannot reproduce with the latest Swan Lake Release (SLAlpha4). Hence closing the issues

**Closed by NipunaRanasinghe** 2021-04-05 05:00 UTC
Labels: Area/Debugger, Priority/Blocker, SwanLakeDump, Team/DevTools, Type/Bug
