### ISSUE TITLE
ints must overflow

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#30796] opened 2021-05-26 06:43 UTC
**Description:**
```ballerina
int i = 9223372036854775807;
i = i + 1;
```
Above should overflow and crate a runtime error, we can use `java.lang.Math.addExact()` to achieve this

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by warunalakshitha** [comment] 2021-05-28 06:53
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/20799

**Closed by warunalakshitha** 2021-05-28 06:53 UTC
Labels: Team/jBallerina, Type/Bug
