### ISSUE TITLE
Idea IDE error message is different than CLI

### ISSUE THREAD

**Issue by ChinthakaSenanayaka** [ballerina-platform/ballerina-lang#12455] opened 2018-12-04 19:19 UTC
**Description:**
When right click and run the .bal file on Idea it gives different error message stdoout than CLI. on Idea IDE it shows full module path prepended error message

CLI error stdout from .bal file run
![screenshot from 2018-12-05 00-34-05](https://user-images.githubusercontent.com/2564122/49467038-86931800-f827-11e8-821e-6ef93dae1a5c.png)

Idea IDE error stdout from .bal file run
![screenshot from 2018-12-05 00-34-18](https://user-images.githubusercontent.com/2564122/49467051-8c88f900-f827-11e8-88f9-14a37b7e65dd.png)

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Shan1024** [comment] 2018-12-05 06:31
This is not a bug. The bal file is directly executed in the terminal where in IDEA, the module is executed.

If you run it as a module in the terminal, you get the same error as the IDEA.

<img width="1199" alt="examples zsh 2018-12-05 11-59-19" src="https://user-images.githubusercontent.com/4003115/49494375-7d389880-f885-11e8-8985-884311b638fd.png">

**Comment by hasithaa** [comment] 2018-12-05 09:12
This seems to be an issue in Packaerina. I will reopen this issue, to track this requirement

**Comment by hevayo** [comment] 2021-03-03 03:50
The implementation has deviated thus closing the issue

**Closed by hevayo** 2021-03-03 03:50 UTC
Labels: Area/Packerina, Later, Team/DevTools, Type/Improvement
