### ISSUE TITLE
Add support to check type instance struct equivalency in semantic model

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#26788] opened 2020-11-06 05:38 UTC
**Description:**
Add support to check type instance struct equivalency in semantic model. This would be similar to what we have in `TypeChecker.checkStructEquivalency(bType1, bType2)`

**Affected Versions:**
2.0.0-SLP6-SNAPSHOT

**Comment by pubudu91** [comment] 2020-11-18 12:37
Duplicate of #26780

**Closed** 2020-11-23 08:28 UTC
Labels: Area/SemanticAPI, Priority/High, Team/CompilerFE, Type/Improvement
