### ISSUE TITLE
Caching flow does not work as expected

### ISSUE THREAD

**Issue by selakap** [ballerina-platform/ballerina-lang#20584] opened 2020-01-13 14:19 UTC
**Description:**
Ballerina caching flow does not work as expected and it will cause to an infinite cache expiry time.

**Steps to reproduce:**
- Set Cache expiry time for 10s (using expiryTimeMillis)
- The first request reaches the backend and returns the response (let's say at 10:00).
- Cached it and set the cache expiry time at 10:10 then return the response to the client.
- Second request (let's say after 5s, inside the 10s time period at 10:05) serve from the cache, then reset the cache expiry time again for 10s (it means the new expiry time will be 10:15).
- The third request at 10:09, again the request will serve from the cache and expiry time will reset (the new expiry time will be 10:19)
- This process will continue for each and every request inside the expiry time period.
- If we invoke after the expiry time (no request inside the expiry time interval), then the request routed to the backend since the cache has expired.

**Affected Versions:**
0.990.5

**Comment by pubudu91** [comment] 2020-01-15 19:31
The caching behaviour you have observed is correct. If you haven't set any cache control directive like `no-store`, the response will be served from the cache after validation with the origin server. Each time the response is validated, it's "freshened". This is in accordance with the behaviour described in [RFC7234#section-4.3.4](https://tools.ietf.org/html/rfc7234#section-4.3.4). 

The confusion here seems to be with the `expiryTimeMillis` config. That configuration is for the caching backend (`ballerina/cache` in this case) and it has **nothing** to do with HTTP caching. The cache provided by the `ballerina/cache` module needs to be given a cache expiry time, which it uses in its cache eviction algorithm. The eviction algorithm follows an LRU policy. This is why you keep seeing the response getting served from the cache as long as a request is made after the previous request within the time specified in `expiryTimeMillis`; the caching backend doesn't evict that response since it's being used frequently. Once the response is not used for the time period specified in `expiryTimeMillis`, it will evict the response from the cache. Now when you make a request, the client has to ask for the actual resource since it doesn't have the response in the cache anymore. Hope this clears things up.

Created #20614 for improving the documentation related to caching configs. 

If you don't want to use HTTP caching, you can disable it as follows:
```ballerina
http:Client ep = new("http://localhost:8080", config = { cache: { enabled: false } });
```

**Comment by Rajith90** [comment] 2020-01-16 09:52
Hi Pubudu,
Can you explain a bit how can I use the caching feature of the client .I want to know how etag and last-modified headers are used by the client in order to refrain serving it from cache when the resource is updated

**Comment by pubudu91** [comment] 2020-01-17 06:41
Hi Rajith,

The high level behaviour is as follows:
1) When the client receives the response for the first request for a resource, it will cache it (if it's cache-able) and return the response to the user. 

2) For the second request for the resource, it will first check the HTTP cache to see if there is a response.

3) If there was a response, it will then check if it is still "fresh". The calculation to check whether a response is fresh depends on a number of variables such as the header values of Age, Date headers, current time, request received time, response received time etc. Refer to [1] for more information on how the freshness lifetime is calculated (The behaviour of the HTTP caching client in Ballerina is in accordance to RFC7234).

4) If the response is "fresh", then it will serve that response. There is **no** communication with the origin server in this case. 

5) Suppose the response was stale (i.e., not fresh according to the freshness calculation), then, the client will send what is called a "validation request" to the origin server, with the ETag. The server will then check if the resource has changed (by comparing the ETag sent by the client and the current ETag it calculates for the resource). If it has not changed, it will send a "304 Not Modified" response back. 

6) The client will then "freshen" the cached response using the meta data of the 304 response (e.g., Date header, received time etc.) and serve it to the user. This cached response is now good to be used for some time, till it gets stale again. 

7) In step 5, suppose the response had changed. Then the origin server will send the new response. The client will invalidate the stale response and cache the new response. This new cached response is then again subjected to the process from step (2) for subsequent requests.

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching is an excellent intro to HTTP caching, if you want more info.

**Comment by pubudu91** [comment] 2020-01-22 06:28
Hope the above explanation clears any confusion regarding the HTTP caching implementation. Since this is not a bug, I'm closing this issue.

**Closed by pubudu91** 2020-01-22 06:28 UTC
Labels: Area/StandardLibs, Component/HTTP, Resolution/Not a bug
