### ISSUE TITLE
Incorrect offset identified by the parser

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#33224] opened 2021-10-14 03:43 UTC
**Description:**
Consider the following source snippet,

```
function testIterableOperation() {
    error onConflictError = error("Key Conflict", message = "cannot insert.");
    Customer c1 = {id: 1, name: "Melina", noOfItems: 12};
    Customer c2 = {id: 2, name: "James", noOfItems: 5};
    Customer c3 = {id: 3, name: "Anne", noOfItems: 20};

    Person p1 = {firstName: "Amy", lastName: "Melina", age: 23};
    Person p2 = {firstName: "Frank", lastName: "James", age: 30};

    Customer[] customerList = [c1, c2, c3];
    Person[] personList = [p1, p2];

    string outputNameString =
                from var person in personList
                let var test = person.firstName + <cursor>
}
```

with respect to the cursor position, I can extract the BinaryExpression and the text range for the binary expression is (605, 623)

Now, If I get the rhsExpr and access the text range, I get (625, 625)

So, shouldn't the text range of the binary expression be (605, 625)?

**Affected Versions:**
Swanlake-beta4-SNAPSHOT at least

**Comment by lochana-chathura** [comment] 2021-11-08 08:25
I think this is a bug.
 
[1] `var a = b + c;`
```
text range of b + c: (8,13)
text range of b:     (8, 9)
text range of c:     (12,13) // within the parent node text range 
```
[2] `var a = b + MISSING[];`
```
text range of b + MISSING[]: (8,11)
text range of b:             (8, 9)
text range of MISSING[]:     (12,12) // not within the parent node text range 
```

The problem is with the node width calculation algorithm. 
When calculating the node width, we get the first child and last child, and from that, node width is derived.

https://github.com/ballerina-platform/ballerina-lang/blob/a5ff9b927875c0030e7c1c40c6a03d33b65eace5/misc/toml-parser/src/main/java/io/ballerina/toml/internal/parser/tree/STNode.java#L319-L327

Here at L322, last child needs to satisfy `child.widthWithMinutiae != 0`.
I think the reason for that condition is to not include "empty NodeLists" in node width.

But for nodes enclosing missing tokens also have `child.widthWithMinutiae = 0`, thus not being considered as the last child.
For example in [2], the last child is considered as `+` token instead of `rhs-expr` which consists of missing identifier token.

Test sample affecting the first child.
[1] 
``` 
var a =
 1 ..< 3;
```
```
text range of 1 ..< 3: (8,15)
text range of 1:       (8, 9)  // within the parent node text range 
text range of 3:       (14,15)
```
[2]
```
var a = // make sure to include newline here as we need leading whitespace for ..< token.
 MISSING[] ..< 3;
```
```
text range of 1 ..< 3: (9,14)
text range of 1:       (8, 8)  // not within the parent node text range 
text range of 3:       (13,14)
```

Please find the test samples here: https://gist.github.com/lochana-chathura/7f6840dc8867adb7e1ef7b34016cd2b4

**Comment by sameerajayasoma** [comment] 2021-11-11 21:53
Ack. This is a bug in my code, a nasty one. :) Can you provide a fix?

**Comment by nadeeshaan** [comment] 2021-11-12 02:43
> Ack. This is a bug in my width calculation logic, a nasty one. :) Can you provide a fix? We survived roughly 1.5 years with this.
> 
> Btw, why is this a blocker? @nadeeshaan

@sameerajayasoma this was leading to few scenario failures in the LS's spec conformance related to let expression and the let variable declaration. Recently we found an alternative way to overcome this with a completed expression check bypassing the range check. Sorry I missed to change the label. I think we can remove the blocker label now.

**Comment by lochana-chathura** [comment] 2021-11-29 06:52
@nadeeshaan fix for this issue is https://github.com/lochana-chathura/ballerina-lang/commit/f9826bae04bb4c7d13905ce1bce0486f334a6e56. 43 out of 1579 LS tests failed. Subsequent LS diff is this: https://github.com/lochana-chathura/ballerina-lang/commit/c1a19d25a6001fa45418328c3530b016d9858a73. Is it acceptable?

I'm thinking whether we need to change for the GA?

**Comment by nadeeshaan** [comment] 2021-12-06 04:51
@lochana-chathura Please find my observation as follows,
For example, consider this source snippet,

```
1 public function testFunction() {
2     record {|
3         int age;
4         string name;
5     |} person = { age:10, name:"Mary"};
6     person.
7 }
```
Apart from the completion, we replace the `person.` part with an empty string. in the sense line 6 char 5 to line 6 char 11 (5, 4 to 5, 11).
With the new change the end of the replacing range has been changed to **line 7 char 1 (6, 0)** where we are going to replace the newline as well. So this change is changing a quite a lot.
In that regard given the gravity/ impact of the change, I think better if we can hold this for GA if we can't figure out the reason for the change.

**Comment by lochana-chathura** [comment] 2021-12-06 05:17
The above sample is recovered as,

```
1 public function testFunction() {
2     record {|
3         int age;
4         string name;
5     |} person = { age:10, name:"Mary"};
6     person.
7 MISSING[] MISSING[;]}
```
The thing is earlier if we take the line range of the `field-access` expression at line 6, it was **line 6 char 5** to **line 6 char 12**.
But the line range of `field name` was **line7 char 1** to **line7 char 1** which is outside the parent node's line range.

Now that we include `field-name` also into the parent node's line range, the new line range for the `field-access` is **line 6 char 5** to **line7 char 1**.

This is the same thing as the original issue you have mentioned in https://github.com/ballerina-platform/ballerina-lang/issues/33224#issue-1025911845. The only diff is now we are talking in terms of line range instead of text range.

+1 to not include this for the GA.

**Closed** 2023-02-28 05:17 UTC
Labels: Type/Bug, Priority/High, Team/CompilerFE, Area/Parser, Later, Deferred
