### ISSUE TITLE
Ballerina build command fails for multiple modules having services with same port

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#18940] opened 2019-09-08 15:15 UTC
**Description:**
This issue occurred when the project contains multiple modules which contain services with the same port.

Get the following error while building the project.
```shell
I'm the before suite function!
I'm the before function!
I'm in test function!
I'm the after function!
I'm the after suite function!
	1 passing
	0 failing
	0 skipped
    daneshk/grpc_server_streaming_service:0.1.0
	[fail] Error while initializing test suite: {ballerina/grpc}InternalError message=Failed to start server connector '0.0.0.0:9090'. Address already in use
	at ballerina.grpc.Listener:start(service_endpoint.bal:76)
	   ballerina.grpc.Listener:__start(service_endpoint.bal:33)
I'm the before suite function!
I'm the after function!
I'm the after suite function!
	0 passing
	0 failing
	1 skipped
    daneshk/grpc_unary_blocking_client:0.1.0
```

**Comment by Ibaqu** [comment] 2020-01-28 11:02
This issue has been fixed as of Ballerina version 1.1.0 

Tested against v.1.0.0 and the issue is reproducible but seems to be fixed for v.1.1.0

**Closed** 2020-01-29 08:56 UTC
Labels: Area/TestFramework, Component/Testerina, Type/Bug
