### ISSUE TITLE
Improve syntax errors

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#3673] opened 2017-10-18 06:43 UTC
Current error strategy doesn't give meaningful syntax errors most of the time, it's better if we can improve that to print a meaningful error in such cases.

**Comment by yasassri** [comment] 2017-10-18 08:34
I had the following service,

```
service <http> ConnectionTerminateService {
     resource connectionTerminateResource (http:Request req, http:Response res, string path) {
        http:ClientConnector httpCheck = create http:ClientConnector("http://localhost:9090",{});
        string method = req.getMethod();
        res = httpCheck.execute(method, path, req);
        res.send;
    }
```
Note that () are missing in this res.send line. When compliled it gave me the following error.

`error: ../../../../Ballerina_prod/Lonrunning/artifatcs/longRunning/ConnectionTerminateService.bal:20:9: undefined field 'send' in struct 'ballerina.net.http:Response'`

**Comment by yasassri** [comment] 2017-10-18 08:50
Issue 2, I compiled the following code,

```
package longRunning;

import ballerina.net.http;
import ballerina.lang.system;

@http:configuration {
    basePath:"/slowfirst"
}
service <http> SlowBackEndFirstService {
    string connection = system:getEnv("CONNECTION");

     @http:resourceConfig {
        methods:["POST", "GET", "HEAD", "PUT", "DELETE"],
        path:"/call/{path}"
    }
    resource slowBackEndOneResource (http:Request req, http:Response res, @http:PathParam {value:"path"}string path) {

        http:ClientConnector httpCheck = create http:ClientConnector(connection, {});
        string method = req.getMethod();
        res = httpCheck.execute(method, path, req);

        res.send();
    }
}
```
Please note that I have the old syntax for reading path params, Guss the error I got :)

```
./ballerina run ../../../../Ballerina_prod/Lonrunning/artifatcs/longRunning/SlowBackEndFirstService.bal 
error: fail to compile file: null
```

**Comment by yasassri** [comment] 2017-10-18 09:13
Accidentally ran ballerina with the following command.

`./../../../0.94Release/shafreen/ballerina-0.93.1-SNAPSHOT/bin/ballerina run ../`

This gave me the following error.

`ballerina: index: 0, Size: 0`

**Comment by moizalicious** [comment] 2017-10-18 12:19
I came across a case when I made a function recurse infinitely. When the following code is run in the main thread:
```
function foo1() {
    foo1();
}
```
I get the error `ballerina: 2000`

**Comment by erandidesilva** [comment] 2017-10-20 05:52
When the enclosing brackets are not closed properly "extraneous input" error is given.

**Comment by sanjiva** [comment] 2018-01-20 09:23
I get "extraneous input '>'" in this case:
```
function<TempSvc> resourceR1 () {
}
```
The issue is missing a variable name after "TempSvc":
```
function<TempSvc s> resourceR1 () {
}
```

That's not a useful error.

**Comment by hasithaa** [comment] 2020-08-24 07:45
Closing this issue, since this has been addressed with the new parser implementation.

**Closed by hasithaa** 2020-08-24 07:45 UTC
Labels: Area/Language, Compiler/Diagnostics, Resolution/Fixed, Type/NewFeature
