### ISSUE TITLE
Debugger becomes broken after pressing stop button

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#8890] opened 2018-06-06 07:01 UTC
Can be reproduced with hello world main sample.
If we press stop btn next to resume btn, while flow is paused on a debug hit, we cannot start subsequent debug sessions until we restart composer.

**Comment by pahans** [comment] 2018-06-07 10:57
Could not reproduce this issue.

**Comment by pahans** [comment] 2018-06-07 11:41
Was able to reproduce this with electron.

**Comment by pahans** [comment] 2018-07-10 14:32
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/9576 @kaviththiranga can you verify the fix?

**Closed by pahans** 2018-07-10 14:32 UTC
Labels: Component/Composer, Priority/High, Type/Bug
