### ISSUE TITLE
[Bug]: Getting No such type error when building graphql test package

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#39453] opened 2023-01-31 11:49 UTC
### Description

Error encountered while executing the command `gradle test`:
```
error: No such type: Package: ballerina/graphql/1/$_init,
          TypeName: $type$$anonType$_17, Shape: record {| ballerina/graphql:1.6.0:ErrorDetail[]? errors; |}
```
The graphql repo has two modules:
1. Main module (`ballerina`)
2. Test module (`ballerina-test`)

the main module includes a submodule called `parser` which defines the following type: [type](https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/ballerina/modules/parser/records.bal#L38)
```ballerina
public type ErrorDetail record {|
    string message;
    Location[] locations?;
    (int|string)[] path?;
    map<anydata> extensions?;
|};
```
The main module also defines the following [type](https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/ballerina/records.bal#L135) and [errors](https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/ballerina/errors.bal#L47)

```ballerina
public type ErrorDetail record {|
    *parser:ErrorDetail;
|}; 

public type InvalidDocumentError distinct (RequestError & error<record {| ErrorDetail[]? errors; |}>);
public type PayloadBindingError distinct (ClientError & error<record {| ErrorDetail[]? errors; |}>);
```

Note that when the command `gradle clean build` is executed, both main and test modules' tests run without any issue. But when the command `gradle test` is executed, tests from the main module run as expected but tests from the test module fail with the above mentioned error.

Note: this [test](https://github.com/ballerina-platform/module-ballerina-graphql/blob/master/ballerina-tests/tests/35_client_test.bal#L175) in the test module uses one of the aforementioned error types.

### Related area

-> Compilation

**Comment by warunalakshitha** [comment] 2023-01-31 13:02
We had a debug session and found record {| ballerina/graphql:1.6.0:ErrorDetail[]? in InvalidDocumentError is not in the bir type definitions list. This cause no such type error at the runtime

**Comment by pcnfernando** [comment] 2023-01-31 13:30
@MohamedSabthar what's the ballerina-lang version you tried?

**Comment by MohamedSabthar** [comment] 2023-01-31 13:37
> @MohamedSabthar what's the ballerina-lang version you tried?

 2201.4.0-20230103-130200-7894a0e5 timestamp version used in the module

**Comment by pcnfernando** [comment] 2023-02-01 17:10
This is due to a regression from https://github.com/ballerina-platform/ballerina-lang/pull/38765/
With above said PR, the error type loading which was done through ErroTypeConstants in imported modules has changed causing the regression. We'll be reverting the PR for 2201.4.0 release

**Comment by Nadeeshan96** [comment] 2023-02-07 09:27
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39472.

**Closed by Nadeeshan96** 2023-02-07 09:27 UTC
Labels: Type/Bug, Area/Compiler, Priority/Blocker, Reason/Regression, userCategory/Compilation
