### ISSUE TITLE
Following code doesn't compile (variable/function scope issue in service definition)

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-lang#19648] opened 2019-10-30 06:56 UTC
**Description:**
Consider following code:
```ballerina
import ballerina/http;
type Builder object {

    function aFunction() returns error? {
        // Some stuff I want to do.
    }

    public function build() returns service {
        return @http:ServiceConfig {
            basePath: "/"
        }
        service {
            @http:ResourceConfig {
                path: "/*"
            }
            resource function serve(http:Caller outboundEp, http:Request req) returns error? {
                return aFunction(outboundEp, req); // <- This line doesn't compile, because its not visible ( self.aFunction(..) doesn't work also)
            }
        };
    }
};
```
Work around would be to define a global variable of `Builder`  then access `aFunction`. Thats ugly.

**Steps to reproduce:**
N/A
**Affected Versions:**
1.0.1
**OS, DB, other environment details and versions:**
Mac / JDK 1.8
**Related Issues (optional):**
https://github.com/ballerina-platform/ballerina-lang/issues/19608
**Suggested Labels (optional):**

Blocker, High Priority (since the workaround is pretty ugly), Enhancement

**Suggested Assignees (optional):**
@hasithaa

**Comment by pubudu91** [comment] 2019-10-30 10:04
Can't `aFunction()` be outside `Builder` object? Using `aFunction()` like this seems wrong to me. The service you create and return will have a longer lifespan than the `Builder` object which creates it right? So what happens once the `Builder` object is no longer there and the resource gets invoked?

**Comment by hasithaa** [comment] 2019-10-30 11:23
This is wrong. Spec says 
>Within a method-body, the fields and methods of the object are not implicitly in-scope; instead the keyword ``self`` is bound to the object and can be used to access fields and methods of the object.

In this particular code, `aFunction()` won't be visible to the method, hence it won't visible to the closure. If you use `self.aFunction()`, it will be visible, But since you are trying to access it inside a service value saying `self` will not work. Because it will now look for method inside the service. So the compiler behavior is correct.

**Comment by hasithaa** [comment] 2019-10-30 11:33
This approach uses a service value as a closure, which gives a state to the service. But Ballerina services are stateless.

**Comment by jclark** [comment] 2019-10-30 11:47
I would write it like this (haven't checked if it works...):

```
import ballerina/http;
type Builder object {

    function aFunction() returns error? {
        // Some stuff I want to do.
    }

    public function build() returns service {
        Builder builder = self;
        return @http:ServiceConfig {
            basePath: "/"
        }
        service {
            @http:ResourceConfig {
                path: "/*"
            }
            resource function serve(http:Caller outboundEp, http:Request req) returns error? {
                return builder.aFunction(outboundEp, req);
            }
        };
    }
};
```

**Comment by hasithaa** [comment] 2019-10-30 12:09
@jclark Yes, This should work. Unfortunately, we don't support object closures right now. https://github.com/ballerina-platform/ballerina-lang/issues/9144 was created to capture this.

**Comment by hasithaa** [comment] 2019-10-31 04:38
Closing this issue as this is not a bug and other improvement captured in https://github.com/ballerina-platform/ballerina-lang/issues/9144

**Closed by hasithaa** 2019-10-31 04:38 UTC
Labels: Area/Language, Resolution/Not a bug, Type/Bug
