### ISSUE TITLE
Error is shown in an incorrect line

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#29473] opened 2021-03-23 11:04 UTC
**Description:**
$title
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/19838787/112136881-95b75300-8bf5-11eb-8e91-54f94c6bba93.gif)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment] 2021-06-30 18:13
Related to #29418.

**Comment by lochana-chathura** [comment] 2021-07-01 03:51
Duplicate of #29418

**Closed by lochana-chathura** 2021-07-01 03:51 UTC
Labels: Area/Diagnostics, Priority/High, Team/CompilerFE, Type/Bug, Version/SLAlpha3
