### ISSUE TITLE
JVM verification error at runtime

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#20104] opened 2019-11-29 06:48 UTC
[jvm-verification-err.txt](https://github.com/ballerina-platform/ballerina-lang/files/3904027/jvm-verification-err.txt)

[cause-diff.txt](https://github.com/ballerina-platform/ballerina-lang/files/3904031/cause-diff.txt)

Code Base: https://github.com/ballerina-platform/playground (4d3230da2754da60b4f53fc8a44773331a43dfa1)

A JVM verification error occurs for above change of mine to the code base.

**Comment by warunalakshitha** [comment] 2021-06-25 10:04
I have tried the above scenario with fllowing code.

```
import ballerina/log;

const ErrorResponse = "Error";
const DataResponse = "Data";
const ControlResponse = "Control";

type ResponseType ErrorResponse|DataResponse|ControlResponse;

type PlaygroundResponse record {
    ResponseType 'type;
    string? data;
};

type ResponseHandler function (PlaygroundResponse|string resp, boolean cache);

public function main() {
    error executorResult = error("some Error");
    ResponseHandler respHandler = function(PlaygroundResponse|string resp, boolean cache) {
    };
    string msg = "Error invoking executor. ";
    respHandler(createErrorResponse(msg), false);
    log:printError(msg + executorResult.message());
}

function createErrorResponse(string data) returns PlaygroundResponse {
    return <PlaygroundResponse>{"type": ErrorResponse, "data": data};
}
```

**Comment by warunalakshitha** [comment] 2021-06-25 10:07
I couldn't reproduce the issue and the code runs fine. We have fixed some codegen issues related to record types in swan lake . It seems the above has been already fixed in swan lake.

**Comment by warunalakshitha** [comment] 2021-06-29 06:54
I am closing this as per the above comment. Please reopen if you encounter the issue again.

**Closed by warunalakshitha** 2021-06-29 06:54 UTC
Labels: Area/JVMCodeGen, SwanLakeDump, Team/jBallerina, Type/Bug
