### ISSUE TITLE
VS Code plugin shows errors for same service/endpoint names in different files

### ISSUE THREAD

**Issue by himasha** [ballerina-platform/ballerina-lang#8295] opened 2018-05-01 05:28 UTC
**Steps to reproduce:**
1. Add demo.bal to folder f1.
2. Add a new folder inside f1 like f1->f2.
3. Add a demo2.bal (same content as demo.bal with few changes) to folder f2.
4. VS Code editor shows errors for service/endpoint names as redeclared symbols.

<img width="555" alt="screen shot 2018-05-01 at 10 49 38 am" src="https://user-images.githubusercontent.com/9687840/39462356-7d61fbf6-4d2e-11e8-8299-ea317f04a2a0.png">

These files can be executed without an error and the services are hosted successfully.

**Affected Versions:**
0.970.0 
**OS, DB, other environment details and versions:**
Mac 10.13.2

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment] 2018-06-24 14:15
If all the files are in the same package isn't this the expected behavior? When I tried in two packages issue could not reproduce. Hence closing the issue and please reopen if the issue exist further

**Closed by nadeeshaan** 2018-06-24 14:15 UTC
Labels: Type/Bug, component/LanguageServer
