### ISSUE TITLE
Formatting doesn't work properly with object constructor expression

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#34961] opened 2022-02-07 12:00 UTC
**Description:**
$title

**Steps to reproduce:**
Consider the following screen capture
![format2](https://user-images.githubusercontent.com/19838787/152784144-04b8db87-4d4b-418d-badf-bbde66ea715f.gif)

```ballerina
const number = 10;

int intVal = 60;

type AnnotRecord record {|
    int x;
|};

annotation AnnotRecord Config2 on class;

function closuresWithObjectConstrExprWithAnnotsAsFunctionDefaultParam(int b,
                                       object {
                                           int y;
                                           function foo(int c) returns int;
                                       } obj = @Config2 {
                                           x: intVal
                                       } object {
                                           int y = number;
                                           function foo(int c) returns int {
                                               return c + number;
                                           }
                                       }) returns int {
    return number + b + obj.y + obj.foo(20);
}
```
**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by AzeemMuzammil** [comment] 2022-08-24 06:41
Duplicate of #37098

**Closed by AzeemMuzammil** 2022-08-24 06:41 UTC
Labels: Type/Bug, Area/Formatting, Team/CompilerFETools, Points/1
