### ISSUE TITLE
Annot-access-expr gives null inside `init` function

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#33243] opened 2021-10-14 13:19 UTC
**Description:**
Consider the below sample
```bal 
annotation map<string> myAnnot on function, type ;

@myAnnot {
    fieldA: "ballerina"
}
type MyInt record {||};

function init() {
    io:println(MyInt.@myAnnot);
}
```
It prints null. It's correctly gives to output `{"fieldA":"ballerina"}` inside the main function

**Affected Versions:**
Current master

**Comment by gimantha** [comment] 2023-02-28 05:29
Cannot reproduce in 2201.3.0 hence closing.

**Closed by gimantha** 2023-02-28 05:29 UTC
Labels: Type/Bug, Team/CompilerFE
