### ISSUE TITLE
[Testerina] Mocked HTTP services not initialize when `http:OAuth2ClientCredentialsGrantConfig` is used for HTTP clients

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-lang#29901] opened 2021-04-07 13:28 UTC
**Description:**
When I use `http:OAuth2ClientCredentialsGrantConfig` in HTTP client and testing the project, the mocking services are not getting initialized and gives connection refused error.

```
import ballerina/http;
import ballerina/io;

http:Client logAnalyticsEp = check new("http://localhost:9096/v1/workspaces", {
    auth: {
        tokenUrl: "http://localhost:9095/azureoauth2/token",
        clientId: "clid124",
        clientSecret: "clsc972"
    }
});

service /svc on new http:Listener(9090) {
    resource function get path(http:Caller caller, http:Request request) {

        var logAnalyticsStatus = logAnalyticsEp->post("/query", {query: "print 1"});

        error? result = caller->respond("Hello Ballerina!");
        if (result is error) {
            io:println("Error in responding: ", result);
        }
    }
}
```
error:
```
time = 2021-04-07 18:53:35,783 level = ERROR module = ballerina/oauth2 message = "Failed to call the token endpoint." error = "Failed to send the request to the endpoint. Connection refused" 
error: error Error ("Failed to call the token endpoint.",error("Failed to send the request to the endpoint. Connection refused"))
error: there are test failures
```
**Steps to reproduce:**
1. Write an HTTP client which uses `http:OAuth2ClientCredentialsGrantConfig` (or you can clone https://github.com/madushajg/ballerina-http-client-oauth2)
2.run `bal test`

**Affected Versions:**
Swan Lake Alpha 3

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/29900

**Comment by Dilhasha** [comment] 2021-04-08 02:51
@madushajg This is not an issue with the test framework. Even if you move the logic to main function and do a 'bal run', this is reproducible. See the below error, we'll have to check the oath2 module to see what goes wrong there.

`Caused by: error Error ("Failed to call the token endpoint.",error("Failed to send the request to the endpoint. Connection refused"))
	at ballerina.oauth2.1_1_0-alpha5.oauth2_errors.prepareError(oauth2_errors.bal:27)
	at ballerina.oauth2.1_1_0-alpha5.client_oauth2_provider.sendRequest(client_oauth2_provider.bal:382)
	at ballerina.oauth2.1_1_0-alpha5.client_oauth2_provider.getAccessTokenFromAuthorizationRequest(client_oauth2_provider.bal:316)
	at ballerina.oauth2.1_1_0-alpha5.client_oauth2_provider.getOAuth2TokenForClientCredentialsGrant(client_oauth2_provider.bal:228)
	at ballerina.oauth2.1_1_0-alpha5.client_oauth2_provider.generateOAuth2Token(client_oauth2_provider.bal:197)
	at ballerina.oauth2.1_1_0-alpha5.$value$ClientOAuth2Provider.init(client_oauth2_provider.bal:171)
	at ballerina.oauth2.1_1_0-alpha5.$value$ClientOAuth2Provider.call(client_oauth2_provider.bal)
	at ballerina.oauth2.1_1_0-alpha5.$value$ClientOAuth2Provider.$init$(client_oauth2_provider.bal:159)
	at ballerina.oauth2.1_1_0-alpha5.$value$ClientOAuth2Provider.call(client_oauth2_provider.bal)
	at ballerina.http.1_1_0-alpha5.$value$ClientOAuth2Handler.init(auth_client_oauth2_handler.bal:46)
	at ballerina.http.1_1_0-alpha5.$value$ClientOAuth2Handler.call(auth_client_oauth2_handler.bal)
	at ballerina.http.1_1_0-alpha5.$value$ClientOAuth2Handler.$init$(auth_client_oauth2_handler.bal:38)
	at ballerina.http.1_1_0-alpha5.$value$ClientOAuth2Handler.call(auth_client_oauth2_handler.bal)
	at ballerina.http.1_1_0-alpha5.http_secure_client.initClientAuthHandler(http_secure_client.bal:245)
	at ballerina.http.1_1_0-alpha5.$value$HttpSecureClient.init(http_secure_client.bal:39)
	at ballerina.http.1_1_0-alpha5.$value$HttpSecureClient.call(http_secure_client.bal)
	at ballerina.http.1_1_0-alpha5.$value$HttpSecureClient.$init$(http_secure_client.bal:23)
	at ballerina.http.1_1_0-alpha5.$value$HttpSecureClient.call(http_secure_client.bal)
	at ballerina.http.1_1_0-alpha5.http_secure_client.createHttpSecureClient(http_secure_client.bal:209)
	at ballerina.http.1_1_0-alpha5.$value$HttpCachingClient.init(caching_http_caching_client.bal:46)
	at ballerina.http.1_1_0-alpha5.$value$HttpCachingClient.call(caching_http_caching_client.bal)
	at ballerina.http.1_1_0-alpha5.$value$HttpCachingClient.$init$(caching_http_caching_client.bal:28)
	at ballerina.http.1_1_0-alpha5.$value$HttpCachingClient.call(caching_http_caching_client.bal)
	at ballerina.http.1_1_0-alpha5.caching_http_caching_client.createHttpCachingClient(caching_http_caching_client.bal:266)
	at ballerina.http.1_1_0-alpha5.http_client_endpoint.createDefaultClient(http_client_endpoint.bal:672)
	at ballerina.http.1_1_0-alpha5.http_client_endpoint.createCookieClient(http_client_endpoint.bal:667)
	at ballerina.http.1_1_0-alpha5.http_client_endpoint.checkForRetry(http_client_endpoint.bal:572)
	at ballerina.http.1_1_0-alpha5.http_client_endpoint.initialize(http_client_endpoint.bal:542)
	at ballerina.http.1_1_0-alpha5.$value$Client.init(http_client_endpoint.bal:59)
	at ballerina.http.1_1_0-alpha5.$value$Client.call(http_client_endpoint.bal)
	at ballerina.http.1_1_0-alpha5.$value$Client.$init$(http_client_endpoint.bal:35)
	at ballerina.http.1_1_0-alpha5.$value$Client.call(http_client_endpoint.bal)
	at madushagunasekara.svc.0_1_0.$_init.$gen$$0046$0060init$0062(svc:4)
	at madushagunasekara.svc.0_1_0.$_init.$moduleInit(svc)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: error("Failed to send the request to the endpoint. Connection refused")
	at io.ballerina.runtime.api.creators.ErrorCreator.createDistinctError(ErrorCreator.java:189)
	at io.ballerina.runtime.api.creators.ErrorCreator.createDistinctError(ErrorCreator.java:171)
	at org.ballerinalang.stdlib.oauth2.OAuth2Client.createError(OAuth2Client.java:295)
	at org.ballerinalang.stdlib.oauth2.OAuth2Client.callEndpoint(OAuth2Client.java:282)
	at org.ballerinalang.stdlib.oauth2.OAuth2Client.doHttpRequest(OAuth2Client.java:97)
	at ballerina.oauth2.1_1_0-alpha5.oauth2_commons.doHttpRequest(oauth2_commons.bal:72)
	at ballerina.oauth2.1_1_0-alpha5.client_oauth2_provider.sendRequest(client_oauth2_provider.bal:380)
	... 41 more
 `

**Comment by Dilhasha** [comment] 2021-04-08 02:56
@ldclakmal FYA

**Comment by ldclakmal** [comment] 2021-04-08 04:30
@madushajg @Dilhasha AFAIR when you start the mock service with the path `http://localhost:9095/azureoauth2/token` separately and execute this program, it worked successfully. So, we identified the problem as the mock service is not started before the program get executed. The error message itself says that the request sent to the endpoint failed because of connection refused. IMO, that problem has nothing to do with `oauth2` implementation. Please correct me if I am wrong here.

**Comment by Dilhasha** [comment] 2021-04-08 04:51
@ldclakmal I think I was quick to comment. Will check on this.

**Comment by Dilhasha** [comment] 2021-04-08 13:56
@madushajg 

These are the findings from the investigation.

- The http:Client endpoint initialization does a call to token endpoint when there is an auth configuration as in [[1]](https://github.com/madushajg/choreo-logging/blob/sl-alpha4/migration/logs_retriever.bal#L21). This call is done as an optimization to cache some required information to make sure that there is no delay even in the first call.

- When you have the client endpoint initialization defined at the global level, this happens in the module init.

- But, the mock services are defined at test level and these are intialized during the test init which happens after the module init.

- Thus, the endpoint initialization fails because the module init happens before the test init and the mock token service is not started yet.

- Given the way the test framework is implemented, the behaviour you observed is expected.

- To overcome the issue, we need to make sure that the mock token service is up and running before the client endpoint is initialized.

With the current implementation of the test framework, we do not have a straightforward way to start the mock services before the module init. But, we have a workaround in mind that might work to test this scenario. I will check on this and get back to you with more details ASAP.

**Comment by Dilhasha** [comment] 2021-04-09 19:07
@madushajg 

This is the proposed solution.

As explained in the previous comment given the way Ballerina is designed this is the expected behavior when you have auth configuration in the http client initialization at module level.

In order to overcome the above issue, you can have 3 separate ballerina projects i.e. 

- Actual service (logging_service)
- Mock services for testing (logging_mocks)
- Test cases (logging_tests)

You can use configurable variables to define the configurations inside the client initialization. This will allow you to have the default configuration to point to the Azure endpoint and the test configurations to point to the mock services using a Config.toml file. (Please note that function mocking is not capable to serve this purpose, because it comes into effect only at test init phase.)

As the next step, you need to start the mock services before the actual client initialization. For this we can define an init method for the mock service package as follows. Note that your mock services need to be defined as service objects and need to be attached to a listener inside the specified ‘init’ function. Make sure to start the listener as this will start the mock services before the client initialization.

```
import ballerina/http;
import ballerina/lang.runtime;

http:Service s = service object {
    resource function get getResource(http:Caller caller, http:Request req) {
        
    }
};

function init() returns error? {
    http:Listener ln = check new (9090);
    check ln.attach(s);
    check ln.'start();
}
```

Inside the tests project source, import both mock service and the actual service in the default module. This will make sure that all services(both mock and actual) are up and running before the tests get executed.

Please refer to the proposed changes I shared with you offline and raise any questions/clarifications.

**Comment by Dilhasha** [comment] 2021-04-22 15:02
We were able to achieve the requirement by using functions to initialize the HTTP client and auth configs as follows. 

```
http:Client ep = check new(getEpUrl(), getAuthConfig());

function getAuthConfig() returns http:ClientConfiguration {
    return {
    auth: {
        tokenUrl: getTokenUrl(),
        clientId: getClientId(),
        clientSecret: getClientSecret(),
        optionalParams: {}
    }
};}
```

Then, these initialization functions will be mocked by disabling auth, JWT cache at the test level.

```
@test:Mock {
    functionName: "getAuthConfig"
}
function getMockAuthConfig() returns http:ClientConfiguration{
       return {};
}
```

Closing this issue as a feasible solution is provided.

**Closed by Dilhasha** 2021-04-22 15:02 UTC
Labels: Area/Testerina, Priority/Blocker, Team/TestFramework, Type/Bug
