### ISSUE TITLE
Incorrect terms in HTTP API docs

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#22041] opened 2020-03-21 07:36 UTC
**Description:**
The docs for `.getHeader()` and `.getHeaders()` on `http:Response` say "**An exception is thrown** if no header is found.".

https://ballerina.io/v1-2/learn/api-docs/ballerina/http/objects/Response.html#getHeader

Same for `http:Request`.

We should be saying "Panics" instead of "An exception is thrown". 

May have to check all docs.

**Affected Versions:**
1.2.0

**Comment by chamil321** [comment] 2020-04-02 03:25
The issue is by https://github.com/ballerina-platform/ballerina-lang/pull/22396, hence closing

**Closed by chamil321** 2020-04-02 03:25 UTC
Labels: Area/StandardLibs, Component/HTTP, Points/1, Type/Docs
