### ISSUE TITLE
GraalVM native-image build is failing with `Non-reducible loop requires too much duplication`

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-lang#38072] opened 2022-10-05 05:36 UTC
**Description:**
When building the native-image for in-memory websubhub [1] sample got following error at compile time. 
```sh
Error: Non-reducible loop requires too much duplication. Setting MaxDuplicationFactor to a value higher than 40.0 may resolve this.
Detailed message:
Call path from entry point to ballerina.in_memory_hub$0046dispatcher/1.dispatcher.syncDispatcherState(Strand): 
	at ballerina.in_memory_hub$0046dispatcher.1.dispatcher.syncDispatcherState(dispatcher.bal)
	at ballerina.in_memory_hub.1.start_hub.$syncDispatcherState$lambda$_0$(start_hub.bal:24)
	at ballerina.in_memory_hub.1.start_hub$$Lambda$944/0x00000007c2041040.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.concurrent.LinkedBlockingQueue$LBQSpliterator.tryAdvance(LinkedBlockingQueue.java:930)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:203)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback.handle(ReferenceCountedOpenSslClientContext.java:256)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback_handle_e21486683ddb969ec67d269d0970fda063b7e350(generated:0)
```
Since the error describes that we need to increase `-H:MaxDuplicationFactor` configuration, ran the build again after setting `-H:MaxDuplicationFactor` configuration to 800+ value. Then got the following error:
```sh
Error: Number of elements in a node list too high: 65537
Detailed message:
Call path from entry point to ballerina.in_memory_hub$0046dispatcher/1.dispatcher.syncDispatcherState(Strand): 
	at ballerina.in_memory_hub$0046dispatcher.1.dispatcher.syncDispatcherState(dispatcher.bal)
	at ballerina.in_memory_hub.1.start_hub.$syncDispatcherState$lambda$_0$(start_hub.bal:24)
	at ballerina.in_memory_hub.1.start_hub$$Lambda$948/0x00000007c200c440.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1492)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:203)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback.handle(ReferenceCountedOpenSslClientContext.java:256)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY_Nonvirtual_ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback_handle_e21486683ddb969ec67d269d0970fda063b7e350(generated:0)
``` 

Related JAR file can be found here [2].

[1] - https://github.com/ballerina-platform/module-ballerina-websubhub/tree/main/examples/in-memory-hub/hub
[2] - https://drive.google.com/file/d/174W-4RozmijPYT05vO5fCmfeYnb4mWqz/view?usp=sharing

**Comment by ayeshLK** [comment] 2022-10-05 07:12
@warunalakshitha / @HindujaB any idea on how to fix this ?

**Comment by warunalakshitha** [comment] 2022-10-05 07:20
We need to investigate on this to find why we need higher duplication factor. Can u break the syncDispatcherState and see still it can be reproducible?

**Comment by TharmiganK** [comment] 2022-10-17 07:17
> We need to investigate on this to find why we need higher duplication factor. Can u break the syncDispatcherState and see still it can be reproducible?

@warunalakshitha Breaking the content in the for loop to a separate function then the sample work fine with `MaxDuplicationFactor=25`

**Comment by gabilang** [comment] 2022-10-31 05:13
A similar error log is obtained when creating a GraalVm native image for the following ballerina program.
```ballerina
isolated map<int[]> m = {};

public function main() {
    int i = 0;
    while (i < 2) {
        lock {
            foreach string k in m.keys() {
                lock {
                    _ = m.get(k);
                }
            }
        }
        i = i + 1;
    }
}
```
The is is not happening with master and there with `2201.3.0` RC, `2201.2.2` and earlier versions. It seems the above issue has been solved by the PR https://github.com/ballerina-platform/ballerina-lang/pull/37659 where as part of optimization we made record check point call calls as non-terminator instructions.

As a loop optimization strategy `GraalVM` performs reductions on control flow graph. When the graph is irreducible (the CFG cannot be transformed to a single node), it may need more space to run the program (higher runtime memory footprint) with a performance degradation. That may be the reason for the `GraalVM` needs a higher `MaxDuplicationFactor`.

**Comment by HindujaB** [comment] 2022-11-02 15:57
As per https://github.com/ballerina-platform/ballerina-lang/issues/38072#issuecomment-1296551546, the fix is already merged into the master. It'll be available for update 4.

**Comment by HindujaB** [comment] 2022-11-11 04:17
Closing the issue as the fix will be available for update 4. Please re-open if there are any clarifications.

**Comment by Thevakumar-Luheerathan** [comment] 2023-01-26 05:20
I'm getting maxduplication issue for hackathon problem 7.1 and 7.2 with the following error message.
```
Error: Non-reducible loop requires too much duplication. Setting MaxDuplicationFactor to a value higher than 40.0 may resolve this.
```

**Comment by gabilang** [comment] 2023-01-26 07:48
It seems it's only happening with `bal test --native`

**Closed** 2023-05-18 15:16 UTC
Labels: Type/Bug, Team/jBallerina, Area/GraalVM, Reason/Complex
