### ISSUE TITLE
[IDEA Debugger] Debugger does not step into when objects are created

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-lang#20298] opened 2019-12-09 12:12 UTC
**Description:**
When the breakpoint is on new object instantiation, the debugger does not step into the __init function.

**Steps to reproduce:**

**Affected Versions:**
ballerina -v
jBallerina 1.1.0-alpha
Language specification 2019R3
Command 1.1.0-alpha

**OS, DB, other environment details and versions:**
MacOSX (10.15.1)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
@NipunaRanasinghe

**Comment by NipunaRanasinghe** [comment] 2021-02-24 06:39
Closing since a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/27550.

**Closed by NipunaRanasinghe** 2021-02-24 06:39 UTC
Labels: Area/Debugger, SwanLakeDump, Team/Tooling, Type/Bug
