### ISSUE TITLE
Keep getting an exception saying `couldn't find the invocation symbol`

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29510] opened 2021-03-23 16:29 UTC
As I'm typing, keep seeing the following exception very frequently.
```
[Error - 9:54:54 PM] Operation 'text/signature' failed! {uri: '/c%3A/Users/Pubudu/Projects/openapi/bookstore/bookstore-service.bal', [13:20], error: 'Couldn't find the invocation symbol!'}
java.lang.Exception: Couldn't find the invocation symbol!
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$signatureHelp$2(BallerinaTextDocumentService.java:210)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by nadeeshaan** [comment] 2021-03-24 05:44
Duplicate of #29549

**Closed by nadeeshaan** 2021-03-24 05:44 UTC
Labels: Team/LanguageServer, Type/Bug, Version/SLAlpha3
