### ISSUE TITLE
Debug workers did not work for all the break points in multiple workers

### ISSUE THREAD

**Issue by ChinthakaSenanayaka** [ballerina-platform/ballerina-lang#10745] opened 2018-10-09 08:38 UTC
**Description:**
Debug workers did not work for all the break points in multiple workers

**Steps to reproduce:**
Debug ON
![idea plugin debug worker error](https://user-images.githubusercontent.com/2564122/46656717-53882b80-cbcc-11e8-9702-92ecea588873.png)
1 out of 2 breakpoints get the hit not all

RUN (debug OFF)
![idea plugin run worker no error](https://user-images.githubusercontent.com/2564122/46656730-584cdf80-cbcc-11e8-8a25-718465748bf3.png)

**Affected Versions:**
Ballerina 0.982

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by vinok88** [comment] 2018-10-10 05:42
Isn't this is the expected behavior when you have breakpoints in concurrent parts? 
I have the similar experience in other languages (java) as well.

**Comment by vinok88** [comment] 2018-10-10 06:30
I rechecked this in VsCode. And it works fine as Chinthaka expected. Then this has to be a bug in the IntelliJ plugin. Let's try to fix!

**Comment by NipunaRanasinghe** [comment] 2020-09-15 13:34
Closing since this is already fixed with JDI-based new debugger implementation.

**Closed by NipunaRanasinghe** 2020-09-15 13:34 UTC
Labels: Component/Debugger, Component/IntellijPlugin, SwanLakeDump, Team/Tooling, Type/Bug, Type/Improvement
