### ISSUE TITLE
Issue in Type Inference with `error`

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#25291] opened 2020-08-15 11:08 UTC
The following code results in the error: "error: .::worker_interaction.bal:10:9: invalid worker send statement position, can not be used after a non-error return"

```ballerina
import ballerina/http;

public function main() {
    worker w1 returns error? {
        http:Client httpClient = new ("https://api.mathjs.org");
        int v1 = 0;
        var response = httpClient->get("/v4/?expr=2*3");
        if response is error { return response; }
        else { v1 = 1; }
        v1 -> w2;
    }
    worker w2 returns error? {
        int v1 = check <- w1;
    }
}
```

But the error goes away if we provide the actual types for "response" rather than using "var". 

```ballerina
import ballerina/http;

public function main() {
    worker w1 returns error? {
        http:Client httpClient = new ("https://api.mathjs.org");
        int v1 = 0;
        error|http:Response response = httpClient->get("/v4/?expr=2*3");
        if response is error { return response; }
        else { v1 = 1; }
        v1 -> w2;
    }
    worker w2 returns error? {
        int v1 = check <- w1;
    }
}
```

**Comment by rdhananjaya** [comment] 2021-04-01 13:46
Cannot reproduce in Swanlake alpha-4.

Code used:
```ballerina
import ballerina/http;

public function main() {
    worker w1 returns error? {
        http:Client httpClient = checkpanic new ("https://api.mathjs.org");
        int v1 = 0;
        var response = httpClient->get("/v4/?expr=2*3");
        if response is error { return response; }
        else { v1 = 1; }
        v1 -> w2;
    }
    worker w2 returns error? {
        int v1 = check <- w1;
    }
}
```

**Comment by rdhananjaya** [comment] 2021-04-06 05:15
Closing as we can't reproduce this.

**Closed by rdhananjaya** 2021-04-06 05:15 UTC
Labels: Area/Compiler, Lang/Workers, Priority/Blocker, SwanLakeDump, Team/CompilerFE, Type/Bug
