### ISSUE TITLE
[Bug]: Compilation fails with "error: invalid organization name" although orgname is valid

### ISSUE THREAD

**Issue by SumayyaZiyad** [ballerina-platform/ballerina-lang#39721] opened 2023-02-24 05:31 UTC
### Description

I am trying to build [this project](https://github.com/SumayyaZiyad/SampleChoreoProject) workspace in the order of fares->inventory->booking->reservation (based on dependencies)
Each of the dependent packages have been packed and pushed to local central using `bal push --repository=local`

While the compilation and pushing of the first three modules are successful, the compilation of the reservation module fails with the following error (attaching the full log):

`Compiling source
        SumayyaTestOrg/ReservationAPI:1.0.0
Error while pulling package [SumayyaTestOrg/FaresAPI:1.0.0]: error: invalid organization name. Organization name can only contain alphanumeric values with lower case letters and cannot start with numeric valuesorg_name = SumayyaTestOrg
ballerina/observe:1.0.7 [central.ballerina.io -> home repo]  100% [===========================================================] 206/206 KB (0:00:00 / 0:00:00) 
        ballerina/observe:1.0.7 pulled from central successfully
ERROR [SumayyaTestOrg/InventoryAPI/1.0.0::service.bal:(3:1,3:45)] cannot resolve module 'SumayyaTestOrg/FaresAPI as fares_api'
ERROR [SumayyaTestOrg/InventoryAPI/1.0.0::service.bal:(20:5,20:19)] undefined module 'fares_api'
ERROR [SumayyaTestOrg/InventoryAPI/1.0.0::service.bal:(20:5,20:19)] unknown type 'Fare'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(1:1,1:45)] cannot resolve module 'SumayyaTestOrg/FaresAPI as fares_api'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(19:6,19:20)] undefined module 'fares_api'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(19:6,19:20)] unknown type 'Fare'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(38:5,38:19)] undefined module 'fares_api'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(38:5,38:19)] unknown type 'Fare'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(78:9,78:23)] undefined module 'fares_api'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(78:9,78:23)] unknown type 'Fare'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(78:37,78:109)] incompatible type for parameter 'targetType' with inferred typedesc value: expected 'typedesc<(ballerina/http:2.6.0:Response|anydata)>', found 'typedesc<other>'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(138:31,138:49)] invalid field access: 'fare' is not a required field in record 'SumayyaTestOrg/BookingAPI:1.0.0:BookingRecord', use member access to access a field that may have been specified as a rest field
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(139:37,139:61)] invalid field access: 'flightDate' is not a required field in record 'SumayyaTestOrg/BookingAPI:1.0.0:BookingRecord', use member access to access a field that may have been specified as a rest field
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(143:35,143:57)] invalid field access: 'flightNo' is not a required field in record 'SumayyaTestOrg/BookingAPI:1.0.0:BookingRecord', use member access to access a field that may have been specified as a rest field
WARNING [ballerinax/twitter/3.1.0::types.bal:(23:5,23:17)] undocumented field 'auth'
ERROR [SumayyaTestOrg/InventoryAPI/1.0.0::service.bal:(3:1,3:45)] cannot resolve module 'SumayyaTestOrg/FaresAPI as fares_api'
ERROR [SumayyaTestOrg/InventoryAPI/1.0.0::service.bal:(20:5,20:19)] undefined module 'fares_api'
ERROR [SumayyaTestOrg/InventoryAPI/1.0.0::service.bal:(20:5,20:19)] unknown type 'Fare'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(1:1,1:45)] cannot resolve module 'SumayyaTestOrg/FaresAPI as fares_api'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(19:6,19:20)] undefined module 'fares_api'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(19:6,19:20)] unknown type 'Fare'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(38:5,38:19)] undefined module 'fares_api'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(38:5,38:19)] unknown type 'Fare'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(78:9,78:23)] undefined module 'fares_api'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(78:9,78:23)] unknown type 'Fare'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(78:37,78:109)] incompatible type for parameter 'targetType' with inferred typedesc value: expected 'typedesc<(ballerina/http:2.6.0:Response|anydata)>', found 'typedesc<other>'
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(138:31,138:49)] invalid field access: 'fare' is not a required field in record 'SumayyaTestOrg/BookingAPI:1.0.0:BookingRecord', use member access to access a field that may have been specified as a rest field
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(139:37,139:61)] invalid field access: 'flightDate' is not a required field in record 'SumayyaTestOrg/BookingAPI:1.0.0:BookingRecord', use member access to access a field that may have been specified as a rest field
ERROR [SumayyaTestOrg/BookingAPI/1.0.0::service.bal:(143:35,143:57)] invalid field access: 'flightNo' is not a required field in record 'SumayyaTestOrg/BookingAPI:1.0.0:BookingRecord', use member access to access a field that may have been specified as a rest field
WARNING [ballerinax/twitter/3.1.0::types.bal:(23:5,23:17)] undocumented field 'auth'
HINT [service.bal:(39:5,39:5)] concurrent calls will not be made to this method since the service is not an 'isolated' service
error: compilation contains errors`

However, the organization name is as follows.
<img width="306" alt="Screenshot 2023-02-24 at 10 57 47 AM" src="https://user-images.githubusercontent.com/36619740/221099432-6f25b9f1-ad5b-4f6c-949f-6c9198de4e20.png">

### Steps to Reproduce

1. Clone https://github.com/SumayyaZiyad/SampleChoreoProject
2. Build the packages in the order of fares->inventory->booking->reservation. Between each build, push the required dependent packages to local central

### Affected Version(s)

Reproducible on both 2201.3.2 and 2201.4.0 RC2

### OS, DB, other environment details and versions

MacOS Ventura

### Related area

-> Compilation

**Comment by gayaldassanayake** [comment] 2023-02-24 06:07
I was able to reproduce the issue locally. The bug is two folds.
1. When building ReservationAPI, FaresAPI which is already packed and in the local repo fails to be fetched from the local repository. Reasons for this needs to be investigated.
2. Due to the above failure, when `FaresAPI` is tried to fetch from the central repository, it fails due to an inconsistency in organization name validation between the CLI & toml validation VS central. The central requires the org name to be entirely lowercase while the CLI commands allow to have uppercase chars.

**Comment by Dilhasha** [comment] 2023-02-24 06:10
@SumayyaZiyad Have you added the local dependency to `Ballerina.toml`?

**Comment by SumayyaZiyad** [comment] 2023-02-24 06:11
> @SumayyaZiyad Have you added the local dependency to `Ballerina.toml`?

Yes.

**Comment by Dilhasha** [comment] 2023-02-24 06:15
Shall we add the transitive dependency too?

**Comment by SumayyaZiyad** [comment] 2023-02-24 06:17
Adding that worked. :)

**Comment by Dilhasha** [comment] 2023-02-24 06:21
Based on how local dependencies work, we need all dependencies specifically mentioned to be pulled from the local repository otherwise resolution engine tries to pull from central. :)

**Comment by SumayyaZiyad** [comment] 2023-02-24 06:26
Ack, thank you!

**Comment by gayaldassanayake** [comment] 2023-02-24 06:43
Closing this issue since point 2 in https://github.com/ballerina-platform/ballerina-lang/issues/39721#issuecomment-1442854347 is addressed.
The issue of inconsistent org field validation in CLI and central is tracked by https://github.com/ballerina-platform/ballerina-lang/issues/39723.

**Closed by gayaldassanayake** 2023-02-24 06:43 UTC
Labels: Type/Bug, Area/CLI, Team/DevTools
