### ISSUE TITLE
Auto Completions breaks after adding a worker

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#9266] opened 2018-06-26 12:23 UTC
Please refer following code.
```ballerina 
function main(string... args) {
    // auto completions works as expected
    worker worker1 {
    }
// auto completions are broken after adding a worker.
}
```

**Comment by nadeeshaan** [comment] 2018-07-02 12:18
Tested in the latest master and cannot reproduce the issue. Hence closing the issue and please reopen if the issue exists further

**Closed by nadeeshaan** 2018-07-02 12:18 UTC
Labels: Component/LanguageServer, Type/Bug
