### ISSUE TITLE
Auto suggestions and not available for Websocket upgrade inside resource config

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13749] opened 2019-02-21 09:16 UTC
**Description:**
Auto suggestions and not available for Websocket upgrade inside resource config
eg: webSocketUpgrade: {upgradePath: "/{username}",upgradeService: serviceName}

**Comment by nadeeshaan** [comment] 2019-03-13 06:57
Duplicate of #12504

**Closed by nadeeshaan** 2019-03-13 06:57 UTC
Labels: Component/LanguageServer, Type/Bug
