### ISSUE TITLE
Error is shown when ballerina home is set in vscode settings.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13788] opened 2019-02-22 04:13 UTC
**Description:**
When pulling docker module from central, success message is shown and a consecutive error is shown when ballerina home is set in vscode settings.

**Comment by kaviththiranga** [comment] 2019-03-12 11:49
is this happening because we are not using configured Ballerina distro to pull the module?

**Comment by rasika** [comment] 2019-03-13 03:32
We are using shell command execution `ballerina pull <module_name>` to execute the command. Usually installers should replace `ballerina` command with the latest.

@srsharon Can you check whether output of the `ballerina -v` is same as VSCode configured `ballerina.home`(it should be different in this case).

I suppose, we need to get VSCode configured `ballerina.home` through the LSP config changes inorder to execute `ballerina pull` command. WDYT?

**Comment by rasika** [comment] 2019-05-02 05:07
Closing since not reproducible in the latest. Please re-open if needed.

**Closed by rasika** 2019-05-02 05:07 UTC
Labels: Area/Tooling, Component/LanguageServer, Component/VScodePlugin, Type/Bug
