### ISSUE TITLE
Refactor pure type references

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#28995] opened 2021-03-04 05:59 UTC
**Description:**
Given that the concept of pure type is not there anymore, we need to refactor its references.

**Affected Versions:**
slalpha2

**Comment by MaryamZi** [comment] 2022-03-01 02:53
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/29851.

**Closed by MaryamZi** 2022-03-01 02:53 UTC
Labels: Type/Improvement, Area/Compiler, Team/CompilerFE, Reason/Other
