### ISSUE TITLE
Cant run ballerina files using absolute path

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#6846] opened 2018-04-07 08:48 UTC
**Description:**
```
dir1
 |- dir2 
     |- test.bal
```
When we are in `dir2` and when we try tun the file using absolute file path, error occurs saying that the file cannot be found.

If we try to run the file when we are in the `dir1` directory, we don't get any error.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment] 2018-06-13 04:05
If the test.bal belongs to a package, then the package should be run, from the root of the package directory, giving the package name as the argument to the CLI command. eg: `ballerina run <pkgName>`.

If the test.bal does not belong to a package (i.e: default package), then you can run it from anywhere, by giving the absolute path to the file. Tested with v0.974.0 and this behavior is working correctly.

**Comment by SupunS** [comment] 2018-06-13 06:42
@Shan1024 Im closing this issue, since this is no longer reproducible. Please reopen this, if you encounter the issue again.

**Closed by SupunS** 2018-06-13 06:42 UTC
Labels: Type/Bug, component/BVM
