### ISSUE TITLE
Cannot access a regular field as a method call 

### ISSUE THREAD

**Issue by parkavi11** [ballerina-platform/ballerina-lang#20141] opened 2019-12-02 08:34 UTC
**Description:**
When attempting to do a function call on a regular field by assuming it's a function pointer, Bad Sad Error is obtained.
**Affected Versions:**
1.0.3
**OS, DB, other environment details and versions:**

**Comment by MaryamZi** [comment] 2019-12-02 08:42
Can you please share sample code to reproduce, or share the following info?

Is it a record/object field or a module/local variable? If it is the latter is it declared as a function type or with `var`?

**Comment by parkavi11** [comment] 2019-12-02 08:46
It is a record field in my case.

**Comment by rdhananjaya** [comment] 2019-12-02 11:23
This is probably due to skipping some type checking step. Was able to reproduce the bad-sad in the following code. @parkavi11 can you confirm whether your case is similar?

```ballerina
type RO record {
  function (int i) returns int f;
};

public function main() {
  RO ro = { f: function(int i) returns int { return i; } };
  int i = ro.f(1); // this works
  int j = ro.f(); // this does not typecheck correclty hence fail
}
```

**Comment by rdhananjaya** [comment] 2019-12-04 08:04
This should be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19976

**Comment by irshadnilam** [comment] 2019-12-06 04:28
This is fixed with https://github.com/ballerina-platform/ballerina-lang/pull/19976
I have manually checked the above code snippet by @rdhananjaya

**Closed** 2019-12-06 04:30 UTC
Labels: Area/Language, Priority/Blocker, Type/Bug

**Comment by MaryamZi** [comment] 2019-12-06 04:38
@irshadnilam shall we add a test for the same, if we don't have one already?

**Comment by irshadnilam** [comment] 2019-12-06 04:41
@MaryamZi There are test cases that goes through that path. (Checking arguments). 
That PR is merged. I'll add some more test cases in a separate PR.
