### ISSUE TITLE
[UX] Print unit test failures at the bottom

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#33558] opened 2021-11-01 13:30 UTC
It is more ergonomic to see the errors at the bottom of a build, otherwise one has to scroll to the correct location. (even in GitHub Action/Azure, it will auto scroll to bottom on failed builds)

**Comment by azinneera** [comment] 2023-03-13 12:32
Closing since the issue is addressed.

**Closed** 2023-03-13 12:32 UTC
Labels: Type/Improvement, good first issue, Team/DevTools, Area/TestFramework
