### ISSUE TITLE
[Bug]: High CPU when using vscode editor

### ISSUE THREAD

**Issue by tharindu1st** [ballerina-platform/ballerina-lang#38696] opened 2022-11-16 11:33 UTC
### Description

Observe High CPU with code suggestion.
[threaddumps.zip](https://github.com/ballerina-platform/ballerina-lang/files/10021150/threaddumps.zip)

### Affected Version(s)

2201.2.3

### OS, DB, other environment details and versions

Ubuntu 20.04
Kernel 5.14.0-1051-oem

### Related area

-> Formatter

**Comment by IMS94** [comment] 2022-11-29 11:10
Had a look at the thread dump. Seems like a thread is consuming lot of CPU time around parser's recovery logic:
```java
"pool-1-thread-1" #13 prio=5 os_prio=0 cpu=117212.66ms elapsed=2038.02s tid=0x00007f9754cca800 nid=0x416a8 runnable  [0x00007f97265e1000]
   java.lang.Thread.State: RUNNABLE
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:883)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:279)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:373)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:2406)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1219)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:279)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:373)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:2406)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1219)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekMatchInSubTree(AbstractParserErrorHandler.java:279)
	at io.ballerina.compiler.internal.parser.AbstractParserErrorHandler.seekInAlternativesPaths(AbstractParserErrorHandler.java:373)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatchInAlternativePaths(BallerinaParserErrorHandler.java:2406)
	at io.ballerina.compiler.internal.parser.BallerinaParserErrorHandler.seekMatch(BallerinaParserErrorHandler.java:1219)
```
We have seen a similar behavior sometime back in code-server/choreo as well. This happens rarely and some combinations of incomplete code segments cause the parser to perform some intensive calculations to determine the best possible path to recover.

I assume @tharindu1st didn't experience a high memory usage (out of memory issue), only the CPU usage spike. @lochana-chathura @rdulmina what do you think?

**Comment by rdulmina** [comment] 2022-11-30 04:06
ErrorHandler usually runs recursively to determine the best solution. If there is a reproducible sample we can have a look

**Comment by IMS94** [comment] 2022-11-30 10:19
I tried to reproduce this locally using the APK project. And I could reproduce https://github.com/ballerina-platform/ballerina-lang/issues/38775 which was caused by the `ConstantValueResolver`. A PR to fix this in 2201.2.x branch have been sent with https://github.com/ballerina-platform/ballerina-lang/pull/38790.

![Screenshot from 2022-11-30 15-46-48](https://user-images.githubusercontent.com/11285165/204769925-3a97ca09-9199-40cb-8ce9-c1876cc352b3.png)

When an OOM occurs, CPU usages goes high due to thrashing (GC trying to cleanup memory, JVM not doing any effective work). It can be the cause for this issue. I will continue to test on 2201.3.0-rc3 (because testing in 2201.2.3 again will reproduce the OOM issue only).

**Comment by IMS94** [comment] 2022-12-05 04:56
The fix for the mentioned OOM issue is merged with https://github.com/ballerina-platform/ballerina-lang/pull/38790 and will be available in 2201.2.4.

**Comment by tharindu1st** [comment] 2022-12-08 11:50
@IMS94 we now testing with 2021.3.0 and will let you know if this fix works for us.

Thanks
Tharindu

**Comment by IMS94** [comment] 2022-12-15 05:44
@tharindu1st thanks! How did it go? Did you experience the same?

**Comment by IMS94** [comment] 2023-01-17 05:40
Closing this since the original issue is not no longer being reported. Please reopen or create a new issue if you encounter this again.

**Closed by IMS94** 2023-01-17 05:40 UTC
Labels: Type/Bug, Team/LanguageServer, Area/Performance, Reason/EngineeringMistake
