### ISSUE TITLE
Cast of module-type-defn not needed for in match-clause

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#33341] opened 2021-10-22 08:47 UTC
**Description:**
$subject

**Steps to reproduce:**
```
type Break "break";
type If "if";
type Token Break|If;

function fooBreakContinue(Break bc) {
}

function fooIf(If x) {
}

function foo(Token t) {
    match t {
        "break" => {
            fooBreakContinue(t); // error: incompatible types: expected 'break', found 'Token'
        }
        "if" => {
            fooIf(<If>t); // no error
        }
    }
}
public function main() {
    foo("break");
}
```

**Affected Versions:**
swan-lake beta3

**Comment by KRVPerera** [comment] 2022-01-30 21:18
duplicate of #30191

**Closed by KRVPerera** 2022-01-30 21:18 UTC
Labels: Type/Bug, Team/CompilerFE, Lang/TypeNarrowing, Lang/Statements/Match
