### ISSUE TITLE
Misleading error message for new expression for stream

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#32738] opened 2021-09-14 13:15 UTC
Consider the following:
```ballerina
type Foo record {
    readonly int x;
    int y;
    int z?;
};

public function main() {
    StreamImplementor si = object {
        public isolated function next() returns record {|Foo value;|}? {
            return ();
        }
    };
    var st = new stream<Foo>(si); // error
}

type StreamImplementor object {
    public isolated function next() returns record {|anydata value;|}?;
};
```
The error message given for the above is:
```
incompatible types: expected 'record {| Foo value; |}?', found 'record {| anydata value; |}?'
```
Isn't this a bit misleading? What the arg list expects in this case is a single arg compatible with the `StreamImplementor` object type. The error message reads like it expects a record type.

**Comment by MaryamZi** [comment] 2022-03-02 02:16
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/32151.

**Closed by MaryamZi** 2022-03-02 02:16 UTC
Labels: Type/Bug, Type/Improvement, Team/CompilerFE, Area/Diagnostics, Reason/Other
