### ISSUE TITLE
Compiler showing all errors instead of the toplevel

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#18421] opened 2019-09-02 06:34 UTC
**Description:**
The compiler gives a list of all the errors in the union instead of only the top level error. Note it in the following example:

**Steps to reproduce:**
```ballerina
public type Detail record {
    string message;
    error cause?;
};

public const CONNECTION_ERROR = "WsConnectionError";
public type WsConnectionError error<CONNECTION_ERROR, Detail>;

public const INVALID_CONTINUATION_FRAME_ERROR = "WsInvalidContinuationFrameError";
public type WsInvalidContinuationFrameError error<INVALID_CONTINUATION_FRAME_ERROR, Detail>;

public const GENERIC_ERROR = "WsGenericError";
public type WsGenericError error<GENERIC_ERROR, Detail>;

public type WebSocketError WsConnectionError|WsInvalidContinuationFrameError|WsGenericError;


public function acceptWebSocketUpgrade(map<string> headers) returns string|WebSocketError {
    return "hello";
}

public function main(string... args) {
    string text = acceptWebSocketUpgrade({});
}
```
Compilation failure:
`error: .::error.bal:23:19: incompatible types: expected 'string', found '(string|WsConnectionError|WsInvalidContinuationFrameError|WsGenericError)'`

Expected:
`error: .::error.bal:23:19: incompatible types: expected 'string', found '(string|WebSocketError)'`

**Affected Versions:**
Ballerina 1.0.0-alpha3

**Comment by hasithaa** [comment] 2019-10-24 08:34
This is happening because of the compiler flatten union types to a single set for the optimization. With this, we lose "original type" information. Which cause this problem. So this is not a bug, but it is not convenient for the user. One option is to keep the original type for the purpose of the diagnostics.

**Comment by MaryamZi** [comment] 2021-03-27 08:15
Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/29362.

```ballerina
public type Detail record {
    string message;
    error cause?;
};

public type WsConnectionError error<Detail>;

public type WsInvalidContinuationFrameError error<Detail>;

public type WsGenericError error<Detail>;

public type WebSocketError WsConnectionError|WsInvalidContinuationFrameError|WsGenericError;


public function acceptWebSocketUpgrade(map<string> headers) returns string|WebSocketError {
    return "hello";
}

public function main() {
    string text = acceptWebSocketUpgrade({});
}
```

This now results in
```cmd
ERROR [foo.bal:(20:19,20:45)] incompatible types: expected 'string', found '(string|WebSocketError)'
```

**Closed by MaryamZi** 2021-03-27 08:15 UTC
Labels: Area/Compiler, Area/Diagnostics, SwanLakeDump, Team/CompilerFE, Type/Improvement
