### ISSUE TITLE
[Bug]: Named arguments after positional argument gives Bad Sad Error

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#39846] opened 2023-03-10 04:21 UTC
### Description

When we used named arguments after positional argument for a function which has an included record parameter, the program fails at compilation with Bad Sad Error. IMO I expect a compiler error if we don't support such argument pattern, otherwise it should work.

### Steps to Reproduce

Run the following ballerina program:
```bal
import ballerina/io;

type Response record {|
    string message;
    int code;
    string details;
|};

public function main() {
    Response resp = {message: "error", code: 5, details: "{a: 1, b: \"2\"}"};
    print("loging details", resp, integration_tool = "BALLERINA", integration_type = "API");
}

type Values record {|
    never msg?;
    anydata...;
|};

function print(string msg, *Values values) {
    io:print("msg : " + msg + " ");
    foreach [string, anydata] ['key, value] in values.entries() {
        io:print('key + " : " + value.toString());
        io:print(" ");
    }
}
```

```console
$ bal run
Compiling source
        sample.bal
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-03-10 09:41:11,203] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.createAndAddRecordFieldForIncRecordLiteral(Desugar.java:9390)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.setFieldsForIncRecordLiterals(Desugar.java:9379)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.reorderNamedArgs(Desugar.java:9357)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.reorderArguments(Desugar.java:9084)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6734)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6373)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:128)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8926)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3526)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:51)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8901)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8939)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8945)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1380)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8901)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1426)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8901)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:830)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8901)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:473)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:451)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

### Affected Version(s)

Ballerina SwanLake 2201.4.0

### OS, DB, other environment details and versions

MacOS Ventura with aarch64

### Related area

-> Compilation

**Comment by MaryamZi** [comment] 2023-03-10 04:26
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/39067. cc @chiranSachintha

**Comment by TharmiganK** [comment] 2023-03-10 05:18
Closing this issues since it is duplicate of the above issue

**Comment by chiranSachintha** [comment] 2023-03-13 04:13
This issue is similar to https://github.com/ballerina-platform/ballerina-lang/issues/39067, but the difference is that here we use the position argument for the included record parameter. This has been fixed with this [PR](https://github.com/ballerina-platform/ballerina-lang/pull/39683). We can use this issue to add a test for it.

**Comment by chiranSachintha** [comment] 2023-03-19 15:26
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/39683

**Closed by chiranSachintha** 2023-03-19 15:26 UTC
Labels: Type/Bug, Team/CompilerFE, Reason/Other, userCategory/Compilation
