### ISSUE TITLE
VSCode plugin does not detect methods defined under same module

### ISSUE THREAD

**Issue by kasvith** [ballerina-platform/ballerina-lang#13969] opened 2019-02-27 09:15 UTC
**Description:**
Ballerina VSCode plugin is unable to detect functions defined under the same module. It will display them as **undefined function** on hover with red underlining. 

**Steps to reproduce:**

- Try out **Create new Module** in [Community Program](https://ballerina.io/community-program/).
- Build it and run it.
- Open up VSCode inside the project folder
- Go to calculator folder and click lib.bal
- Scroll to bottom
![screenshot from 2019-02-27 14-35-42](https://user-images.githubusercontent.com/13379595/53478510-00d8de80-3a9d-11e9-93a0-dce502334765.png)
- Can see **undefined function add** on hover.

**Affected Versions:**
- Ballerina 0.990.3

**OS, DB, other environment details and versions:**
- Ubuntu 18.04 x64
- VSCode 1.31.1

**Related Issues (optional):**

**Suggested Labels (optional):**
VSCode plugin

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment] 2019-03-20 07:16
Hi @kasvith ,
I tried the steps as you mentioned and I could not reproduce the issue in both v0.990.3 as well as in the latest master. One of the possible issues could be the project structure. So, check whether there both lib.bal and main.bal reside in the same folder (calculator module).
Since this isn't reproducible I'm closing the issue and if the issue can be experienced further, please reopen.

**Closed by nadeeshaan** 2019-03-20 07:16 UTC
Labels: Component/LanguageServer, Component/VScode plugin, Type/Bug

**Comment by kasvith** [comment] 2019-03-20 16:06
sure if I encountered it again will reopen
