### ISSUE TITLE
Assumption regarding field order causes raw templates to be incorrectly desugared

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29342] opened 2021-03-18 17:11 UTC
Consider the following:
```ballerina
public function main() {
    string name = "Pubudu";
    Printable p = `Hello ${name}!`;
}

public type Printable anydata|PrintableRawTemplate|error;

public type PrintableRawTemplate object {
    *object:RawTemplate;
    public Printable[] insertions;
};
```
Running the above results in the following panic:
```
error: {ballerina/lang.object}InherentTypeViolation {"message":"invalid value for object field 'strings': expected value of type '(string[] & readonly)', found '(anydata|PrintableRawTemplate|error)[]'"}
        at $value$$rawTemplate$PrintableRawTemplate$_0:init(test.bal:9)
           $value$$rawTemplate$PrintableRawTemplate$_0:$init$(test.bal:5)
           test:main(test.bal:5)
```
The issue here is the assumption at https://github.com/ballerina-platform/ballerina-lang/blob/cb159add4f161490593ad771db6c5c81121fabf2/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java#L6880

This expects that the fields would always be ordered as `strings` and `insertions`. But in cases like above, when the `insertions` has been overridden, the order of this changes. Need to fix this desguaring logic to not depend on an assumed order.

**Comment by grainier** [comment] 2021-06-17 01:38
Couldn't reproduce in slbeta2 (master). Hence, closing.

**Closed by grainier** 2021-06-17 01:38 UTC
Labels: Priority/High, SwanLakeDump, Team/CompilerFE, Type/Bug
