### ISSUE TITLE
Array size greater than 2,147,483,647 causes error

### ISSUE THREAD

**Issue by ghost** [ballerina-platform/ballerina-lang#13158] opened 2019-01-11 18:52 UTC
**Description:**
Defining an array with fixed length greater than 2,147,483,647 produces an error message and a file called `ballerina-internal.log`.

Error message:
```
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

`ballerina-internal.log`:
```
[2019-01-11 16:45:17,208] ERROR {org.ballerinalang.launcher.Main} - For input string: "2147483648" 
java.lang.NumberFormatException: For input string: "2147483648"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:587)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitArrayTypeNameLabel(BLangParserListener.java:644)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$ArrayTypeNameLabelContext.exitRule(BallerinaParser.java:3038)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:491)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:126)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:99)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:434)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:304)
	at org.wso2.ballerinalang.compiler.Compiler.lambda$compilePackages$3(Compiler.java:153)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:155)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:179)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:88)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:76)
	at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:355)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:112)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:302)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:67)
 ```

**Steps to reproduce:**
```ballerina
public function main() {
    int[2147483648] a;
}
```

**Affected Versions:**
- Ballerina version: 0.990.2

**OS, DB, other environment details and versions:**
- Operating System: elementaryOS 5.0 Juno (Ubuntu-based)

**Comment by hasithaa** [comment] 2020-04-24 12:53
This needs to be handled when building the AST.

**Comment by mohanvive** [comment] 2021-01-25 07:56
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/13156. Hence, closing this issue and further track in previous issue.

**Comment by MaryamZi** [comment] 2021-07-14 08:21
Reopening this since the crashing needs to be fixed.

**Closed** 2021-08-10 06:28 UTC
Labels: Type/Bug, Area/Compiler, Priority/Blocker, Team/CompilerFE, Area/Diagnostics, Crash
