### ISSUE TITLE
[Bug]: Unable to distinguish enum symbol from union-type symbol in Semantic API

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-lang#38179] opened 2022-10-12 08:18 UTC
### Description

Consider following code

```ballerina
public enum Baz {
    # This is open
    OPEN,
    # This is close
    CLOSE
}

public type State Baz;
```

`TypeReferenceTypeSymbol typeReferenceTypeSymbol = <State>;` // I have set the State as typereferenceTypeSymbol
calling `typeReferenceTypeSymbol.typeDescriptor()` returns `UnionTypeSymbol` but it should return `EnumSymbol`

### Related area

-> Compilation

**Comment by dulajdilshan** [comment] 2023-07-25 08:33
We can get the enum-type by `typeReferenceTypeSymbol.definition()`

**Comment by dulajdilshan** [comment] 2023-08-08 05:53
This is a kind of expected behavior (according to the design decisions). Therefore, we are fixing @lnash94's original issue (which is "unable to distinguish enum and union-type) by introducing new APIs within `UnionTypeSymbol`

> ```ballerina
> enum Result {
>     NOTAVAILABLE,
>     AVAILABLE
> }
> 
> type RAction Result;
> ```
> 
> When we are going to take typeDescriptor() from `RAction` it returns `BallerinaUnionTypeSymbol` instead of TypeReference. Is this the expected type?
> 
> Reference issue: [ballerina-platform/openapi-tools#1472](https://github.com/ballerina-platform/openapi-tools/issues/1472)

**Comment by dulajdilshan** [comment] 2023-08-08 05:55
Changing the issue title to "[Bug]: Unable to distinguish enum symbol from union-type symbol in Semantic API" due to this

> This is a kind of expected behavior (according to the design decisions). Therefore, we are fixing @lnash94's original issue (which is "unable to distinguish enum and union-type) by introducing new APIs within `UnionTypeSymbol`

**Comment by dulajdilshan** [comment] 2023-09-05 05:59
We had a discussion sometime back with @MaryamZi and @lnash94, and decided not to send any updates for this since we shouldn't expose any attributes through UnionTypeSymbol to check whether it is an enum or not (complying with the spec), The correct behaviour would be - the Semantic API user should get the visible-symbols and retrieve the enum symbol

**Comment by dulajdilshan** [comment] 2024-01-17 08:41
Closing this due to the last comment

**Closed by dulajdilshan** 2024-01-17 08:41 UTC
Labels: Type/Bug, Team/CompilerFETools, Points/2, Area/SemanticAPI, userCategory/Compilation, SwanLake2023
