### ISSUE TITLE
Compiler crashes when using `transactional-expr` with no `transaction-stmt` in the code 

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35214] opened 2022-02-24 04:12 UTC
**Description:**
$title

**Steps to reproduce:**
```ballerina
public function main() returns error? {
    if transactional {

    }
    // works if this transaction stmt is there.
    // transaction {
    //     check commit;
    // }
}
```
Error log:
```
SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.getInternalTransactionModuleInvokableSymbol(TransactionDesugar.java:668)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7651)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangTransactionalExpr.accept(BLangTransactionalExpr.java:40)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3444)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1317)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1359)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8393)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:795)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```
**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by lochana-chathura** [comment] 2022-02-24 08:08
Duplicate of #33087

**Closed by lochana-chathura** 2022-02-24 08:08 UTC
Labels: Type/Bug, Team/CompilerFE, Lang/Transactions
