### ISSUE TITLE
Runtime nballerina crash

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#31008] opened 2021-06-05 08:04 UTC
If you checkout and build the nballerina repo, and then run on the following file:

```
function foo(int x, int y) returns int {
  int sum = x + y;
  return sum;
}
```

I get a runtime crash:

```
[2021-06-05 15:01:05,915] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.internal.values.ArrayValue (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.internal.values.ArrayValue are in unnamed module of loader 'app')
        at wso2.nballerina$0046nback.0_1_0.$value$Scaffold.init(build.bal:26)
        at wso2.nballerina$0046nback.0_1_0.$value$Scaffold.call(build.bal)
        at wso2.nballerina$0046nback.0_1_0.$value$Scaffold.$init$(build.bal:16)
        at wso2.nballerina$0046nback.0_1_0.$value$Scaffold.call(build.bal)
        at wso2.nballerina$0046nback.0_1_0.build.buildFunction(build.bal:47)
        at wso2.nballerina$0046nback.0_1_0.nback.compileModule(nback.bal:15)
        at wso2.nballerina.0_1_0.main.main(main.bal:24)
        at wso2.nballerina.0_1_0.$_init.$lambda$main$(nballerina)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:597)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:327)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jclark** [comment] 2021-06-05 08:06
I tagged it https://github.com/ballerina-platform/nballerina/releases/tag/jballerina-bug-31008

**Comment by jclark** [comment] 2021-06-05 08:12
You may hit #31009 trying to build it.

**Comment by HindujaB** [comment] 2021-06-10 06:06
can be reproduced with this code
```ballerina
public function main() returns error? {
    check testArray([1]);
}

function testArray(int[] input) returns error? {
    int[] arr = from var val in input
        select check add(val);
}

function add(int a) returns int|error {
    return error("Invalid value");
}
```

**Comment by grainier** [comment] 2021-06-11 03:53
> can be reproduced with this code
> 
> ```ballerina
> public function main() returns error? {
>     int[] arr2 = from var val in [1]
>         select check add(val);
> }
> 
> function add(int a) returns int|error {
>     return error("Invalid value");
> }
> ```

If this is the case, this is a duplicate of #31041.

**Closed** 2021-06-16 04:26 UTC
Labels: Crash, NBalNeeds, Priority/Blocker, Team/CompilerFE, Team/jBallerina, Type/Bug
