### ISSUE TITLE
Symbols are dropped within the match statement block

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28980] opened 2021-03-03 10:09 UTC
**Description:**
Consider the following example,

```
function bar (string | int | boolean i)  returns (string | int | boolean) {
    string | int | boolean var1 =  "Test";
    [string, int, boolean] var2 = ["Foo", 12, true];
    int var4 = 12;
    string var5 = "test";
    Person p = { name : "Tom", age : 10};

    match var4 {
        var t => {
            <cursor>
        }
    }

    return 1;
}

type Person record {
    string name;
    int age;
};

```

At the cursor position, symbol `t` is missing

**Comment by pubudu91** [comment] 2021-03-15 14:38
Duplicate of #28780?

**Closed** 2021-04-07 12:02 UTC
Labels: Area/SemanticAPI, Priority/Blocker, SwanLakeDump, Team/CompilerFE, Type/Bug
