### ISSUE TITLE
Suggesting Replace with code action but doesn't make any changes

### ISSUE THREAD

**Issue by mindula** [ballerina-platform/ballerina-lang#36632] opened 2022-06-21 05:47 UTC
**Description:**
In the following scenario, `replace with` code action is suggested but it doesn't make any changes when applied. 

https://user-images.githubusercontent.com/61020198/174724932-c6140395-c5f4-4b24-9b7b-de3e5993ca75.mov

**Steps to reproduce:**
```
import ballerina/http;

function test() {
    http:<cursor>
}
```

**Comment by TharushiJay** [comment] 2022-06-21 07:04
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/34714

**Comment by IMS94** [comment] 2022-06-22 05:23
@TharushiJay As you think what is the common fix? Checking for line breaks in minutiae?

**Closed** 2022-08-15 09:04 UTC
Labels: Type/Bug, Team/LanguageServer, Points/2, Area/CodeAction, Reason/EngineeringMistake
