### ISSUE TITLE
Diagnostic doesn't work

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#16779] opened 2019-07-16 08:54 UTC
**Description:**
See below 

![image](https://user-images.githubusercontent.com/6178058/61280340-50fad800-a7d5-11e9-8b68-3fd7faa270bc.png)

**Comment by nadeeshaan** [comment] 2019-07-16 12:02
Tried the sample and I could get the diagnostics. @shafreenAnfar could you confirm if you can get diagnostics for the syntax errors?

**Comment by nadeeshaan** [comment] 2019-07-24 04:21
Checked with the latest master and could not reproduce the issue. Hence closing the issue. Please feel free to reopen if the issue can still be reproduced

**Closed by nadeeshaan** 2019-07-24 04:21 UTC
Labels: Area/Tooling, Component/LanguageServer, Priority/Blocker
