### ISSUE TITLE
[Bug]: Ballerina Notebook not working with 2201.10.0

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#43345] opened 2024-09-02 06:23 UTC
### Description

The following error occurred while attempting to run a Ballerina Notebook in 2201.10.0.

```
Incompatible ballerina version 
```

### Affected Version(s)

2201.10.0

### OS, DB, other environment details and versions

Windows

### Related area

-> Editor

**Comment by tharindulak** [comment] 2024-09-04 03:34
This issue is fixed in VSCode 4.7.6. Please reopen if the issue is still there.

**Closed by tharindulak** 2024-09-04 03:34 UTC
Labels: Type/Bug, needTriage, userCategory/Editor
