### ISSUE TITLE
Repeated error messages about not being able to connect to remote repo when building a module

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#18188] opened 2019-08-26 08:55 UTC
For example,
```
> Task :ballerina-jvm-old:createOldBirJar
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
could not connect to remote repository or unexpected response received.
        ballerina/jvm
```
The above is not really helpful. And it seems it keeps retrying over and over. 

Ideally, the two error messages should be separate. If it was a question of connecting to the remote repo, it should ideally tell the user why it's trying to connect to the remote repo.
e.g., `module 'xyz' not found. Attempting to pull it from the remote repository 'http://central.ballerina.io'`

Also, shouldn't this either be prefixed with `error:` or `ballerina:`?

**Comment by hemikak** [comment] 2019-08-27 06:44
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/18177

**Closed** 2019-08-29 05:15 UTC
Labels: Area/BuildTools, Priority/High, Type/Bug, Type/Improvement
