### ISSUE TITLE
[Spec Deviation] Type narrowing does not happen with equality checks

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18167] opened 2019-08-25 09:49 UTC
**Description:**
According to the "Implicit variable type narrowing" section of the spec

"Given an expression E with static type boolean, and a variable x with static type Tx, we define how to determine

- a narrowed type for x implied by truth of E and
- a narrowed type for x implied by falsity of E

....

- If E has the form x == E1 or E1 == x where the static type of E1 is an expression whose static type is a singleton simple type T1, then
   - the narrowed type for x implied by truth of E is the intersection of Tx and T1
   - the narrowed type for x implied by falsity of E is Tx with T1 removed
- If E has the form x != E1 or E1 != x where the static type of E1 is an expression whose static type is a singleton simple type T1, then
   - the narrowed type for x implied by truth of E is Tx with T1 removed
   - the narrowed type for x implied by falsity of E is the intersection of Tx and T1

..."

But the following fails.

**Steps to reproduce:**
```ballerina
const ONE = 1;

public function main(string... args) {
    int i = 1;
    ONE ob = ONE;

    if (i == ob) { // or even i == ONE
        ONE b = i; // incompatible types: expected '1', found 'int'
    }
}
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-alpha3
Language specification 2019R2
Ballerina tool 1.0.0
```

**Comment by MaryamZi** [comment] 2019-08-25 15:13
Doesn't work for `type ONE 1;` either.

**Comment by rdulmina** [comment] 2021-05-03 11:18
Closing due to duplicate of #30165

**Closed by rdulmina** 2021-05-03 11:18 UTC
Labels: Area/Compiler, Spec/2019R3, Team/CompilerFE, Type/SpecDeviation
