### ISSUE TITLE
While loop with condition in a global variable

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#16493] opened 2019-07-11 20:02 UTC
**Description:**
In the following code, concurrent changes to the global variable do not get reflected for the loop and it runs forever. But if we put something like an io:println() within the loop, it works.

```ballerina
import ballerina/io;
import ballerina/runtime;

boolean waiting = true;

public function testWaitForAllWorkers() {
    test();
    io:println("Finishing Default Worker");
    while(waiting) {
    }
}

function test() {
    worker w1 {
        return;
    }

    worker w2 {
        runtime:sleep(2000);
        io:println("Finishing Worker w2");
        waiting = false;
    }
}
```

**Comment by gabilang** [comment] 2021-06-30 10:32
Even the problem is there when we have an external module call or an async call or even some sort of delay inside the worker as given in the following code. 
```
import ballerina/io;
boolean waiting = true;

public function main() {
   waitForWorkers();
}

function waitForWorkers() {
   
   test();

   // io:println("default worker");   //having something like an external module call here makes the problem go away

   while (waiting) {}
}

function test() {

   @strand {thread: "any"}
   worker w2 {
      io:println("w2");
      waiting = false;
   }
}
```

**Comment by Nadeeshan96** [comment] 2021-08-11 13:10
This problem comes randomly because the global variable is not available only in the main memory, but gets cached. So it is not visible for other threads. The same problem is seen in Java also.
References: [1](https://stackoverflow.com/questions/25425130/loop-doesnt-see-value-changed-by-other-thread-without-a-print-statement) [2](https://stackoverflow.com/questions/39558261/why-my-boolean-variable-should-be-volatile-while-stopping-thread-loop) [3](https://stackoverflow.com/questions/53780267/an-equivalent-to-java-volatile-in-python)  [4](https://stackoverflow.com/questions/20786483/code-not-executed-without-a-print-statement) [5](https://www.geeksforgeeks.org/volatile-keyword-in-java/)

**Comment by Nadeeshan96** [comment] 2021-08-11 13:10
The problem went off when we code gen all the global variables volatile (tested with few code snippets which had the problem). To see how it affects the performance when an variable is made volatile, the following two code snippets were run and the time to run was measured.

```ballerina
int num = 0;
 
public function main() {
  while(num<5000000000){
      num+=1;
  }
}
```
when `num` is `volatile` : 146.575 s
when `num` is not `volatile` : 126.994 s

```ballerina
int num = 0;
 
public function main() {
   @strand{thread: "any"}
   worker w1 {
       while(num<5000000000){
           num+=1;
       }
   }
}
```
when `num` is `volatile` : 39.440 s
when `num` is not `volatile` : 4.623 s

**Comment by Nadeeshan96** [comment] 2021-08-11 13:11
**Some suggestions to overcome the issue :**

1. Using locks properly when accessing shared state among workers, when programming.
For example the following code runs fine.
```ballerina
import ballerina/io;
boolean waiting = true;

public function main() {
   waitForWorkers();
}

function waitForWorkers() {
   
   test();
   while (get()) {}
}

function test() {

   @strand {thread: "any"}
   worker w2 {
      io:println("w2");
      waiting = false;
   }
}

function get() returns boolean {
    lock{
        return waiting;
    }
}
```

2. Finding which variables are accessed by more than one thread when compiling the code and make them `volatile` by the compiler.

3. Introducing a keyword or an annotation like `@volatile` to mark some variables as `volatile` by the programmer.

**Comment by hasithaa** [comment] 2021-08-12 10:20
​Did you observe this behavior with local variables with multiple workers which run on different threads?​

**Comment by hasithaa** [comment] 2021-08-12 10:23
I guess we don't want to expose this kind of complexity to the user. So Option 2 is the best IMO. @jclark @sameerajayasoma @manuranga Thoughts?

**Comment by Nadeeshan96** [comment] 2021-08-12 12:06
> ​Did you observe this behavior with local variables with multiple workers which run on different threads?​

Yes, in the instances I checked the while loop stopped running and code executed successfully. However I am not sure whether there are times that while loop running thread does not see the updated value in this case also. I read that when the threads are in the same core they can access the updated value [[3]](https://stackoverflow.com/questions/53780267/an-equivalent-to-java-volatile-in-python) so that may have happened and if if the threads are on different cores the above problem happens.

**Comment by jclark** [comment] 2021-08-12 13:01
The right solution is to use `lock`.  The isolated feature (which is the foundation of safe concurrency in Ballerina) is built on the idea of using `lock` to access shared mutable state.  The way to make this more user friendly is to tell the user when and where they need to lock (preferably within VSCode).

**Comment by lankavitharana** [comment] 2021-08-14 04:31
I vaguely remember JDK bugs submitted for this [1] [2] and one of which was submitted by us, and the response from them was to use "volatile"

[1] - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8228899
[2] - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8179334

**Comment by Nadeeshan96** [comment] 2021-08-16 11:14
> I vaguely remember JDK bugs submitted for this [1] [2] and one of which was submitted by us, and the response from them was to use "volatile"
> 
> [1] - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8228899
> [2] - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8179334

We made all the global variables in the Ballerina program `volatile` and ran few tests. They then executed without any problem. However, it seems it has a significant impact on performance https://github.com/ballerina-platform/ballerina-lang/issues/16493#issuecomment-896814148.

**Comment by Nadeeshan96** [comment] 2021-08-16 11:18
> The right solution is to use `lock`. The isolated feature (which is the foundation of safe concurrency in Ballerina) is built on the idea of using `lock` to access shared mutable state. The way to make this more user friendly is to tell the user when and where they need to lock (preferably within VSCode).

As the right solution is to use `lock`, we will go with this. Created issue #32185 to make this more user friendly.

**Comment by warunalakshitha** [comment] 2021-08-18 10:29
Closing the issue as per the last comment. Please reopen if you have further queries on this.

**Closed by warunalakshitha** 2021-08-18 10:29 UTC
Labels: Type/Bug, Priority/High, Team/jBallerina, Points/3, Later
