### ISSUE TITLE
Debug points put in a http to websocket upgrade resource won't hit

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#13592] opened 2019-02-13 05:55 UTC
**Description:**
Debug points put in a http to websocket upgrade resource does not work

**Steps to reproduce:**
~~~ballerina
import ballerina/http;

@http:ServiceConfig {
    basePath: "/chat"
}
service chatUpgrader on new http:Listener(9090) {
    @http:ResourceConfig {
        webSocketUpgrade: {
            upgradePath: "/{username}",
            upgradeService: serviceName
        }
    }
    resource function upgrader(http:Caller caller, http:Request request, string username) {
        http:WebSocketCaller wsCaller;  // <--- Breakpoint here won't hit
        wsCaller = caller->acceptWebSocketUpgrade({});
    }
}

service serviceName on new http:WebSocketListener(9091) {
    resource function onText(http:WebSocketCaller caller, string text, boolean finalFrame) {
          // <--- Breakpoint here will hit
    }
}
~~~

**Affected Versions:**
0.990.3

**Comment by NipunaRanasinghe** [comment] 2021-04-06 04:43
Closing since resource function debugging is working as expected in the latest Ballerina Swan Lake release (SLAlpha4) and hence cannot be reproduced.

**Closed by NipunaRanasinghe** 2021-04-06 04:43 UTC
Labels: Area/Debugger, SwanLakeDump, Team/DevTools, Type/Bug
