### ISSUE TITLE
NullPointerException in PackageFileWriter.java

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#18316] opened 2019-08-29 11:52 UTC
**Description:**
When building the ballerina package mentioned in this commit [1], the following error stack trace will be logged in the `ballerina-internal.log` file.
```
[2019-08-29 17:14:34,428] ERROR {org.ballerinalang.tool.Main} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:51)
	at org.ballerinalang.packerina.writer.BirFileWriter.writeBIRToPath(BirFileWriter.java:100)
	at org.ballerinalang.packerina.task.CreateBirTask.writeImportBir(CreateBirTask.java:71)
	at org.ballerinalang.packerina.task.CreateBirTask.execute(CreateBirTask.java:47)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:388)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```

[1] https://github.com/pramodya1994/ballerina-integrator/commit/b30b787a22e92ac6e89f4d9cc43a1f7e4f40db2e

**Steps to reproduce:**
1. Clone ballerina integrator repo and checkout to the above commit.
2. `cd templates/gsheets_salesforce_integration`
3. `ballerina build gsheets_salesforce_integration`
4. Check `ballerina-internal.log` file.

**Affected Versions:**
Ballerina 1.0.0-alpha3
Language specification 2019R2
Ballerina tool 1.0.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment] 2019-08-29 12:04
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/18258

**Comment by anupama-pathirage** [comment] 2019-08-30 08:03
Closing since this is a duplicate of #18258

**Closed by anupama-pathirage** 2019-08-30 08:03 UTC
