### ISSUE TITLE
[Bug]: Error during interop validation for the bindgen generated code for `java.io.InputStream`

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#42818] opened 2024-05-29 02:44 UTC
### Description

Following the steps in https://ballerina.io/learn/call-java-code-from-ballerina/#use-the-snakeyaml-java-library-in-ballerina results in the following error output.

```
$ bal build

Resolving Maven dependencies
	Downloading dependencies into /Users/dilhashanazeer/Downloads/yaml_package/generated/9x/proj9x/target/platform-libs

Compiling source
	dilhashanazeer/proj9x:0.1.0
ERROR [modules/java.io/InputStream.bal:(433:1,436:12)] {ballerina/jballerina.java}INSTANTIATION_ERROR ''java.io.InputStream' is abstract, and cannot be instantiated'
error: compilation contains errors

```

Note: The same bindgen-generated code builds without an issue in 2201.8.x versions.

Raised in https://discord.com/channels/957996897782616114/1242859630468665476/1242859630468665476

### Affected Version(s)

2201.9.0

### Related area

-> Runtime

**Comment by Dilhasha** [comment] 2024-05-29 02:53
The diagnostic is added by the `InteropValidator`.

I tried reverting the last commit to the `InteropValidator.java` which was the only change done with U9.
https://github.com/ballerina-platform/ballerina-lang/commit/22c886001fdcf70c8750a57369b07bf33a761b4a 

I could still reproduce the issue without these changes.


The diagnostic is issued during `validateModulePackages` https://github.com/ballerina-platform/ballerina-lang/blob/2201.9.x/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/codegen/interop/InteropValidator.java#L76

@warunalakshitha

**Comment by gabilang** [comment] 2024-05-29 11:30
The issue is happening due to the fix added for https://github.com/ballerina-platform/ballerina-lang/issues/41452, where adding interop functions to call constructors of java abstract classes has been made to result in compilation errors. 

Instantiating an abstract class using the ballerina interop function which is written to call the constructor of an abstract class will result in `java.lang.InstantiationError`. So defining such functions is redundant and cannot be used. 
But `bindgen` tool is generating external functions for constructor calls of Java abstract classes too. IMO the correct way would be not to generate external functions for those cases from the bindgen tool side. 
@warunalakshitha @NipunaRanasinghe WDYT?

**Comment by warunalakshitha** [comment] 2024-05-29 13:22
Yes. We need to fix in bindgen tool to not to generate external functions for constructors of abstract java classes.

**Comment by NipunaRanasinghe** [comment] 2024-05-30 08:28
@warunalakshitha @gabilang Created a separate issue to track the bindgen changes. https://github.com/ballerina-platform/ballerina-lang/issues/42830

**Comment by gabilang** [comment] 2024-06-18 07:25
A fix for this issue has been added to bindgen-tool https://github.com/ballerina-platform/ballerina-lang/pull/42891 and the release note of `2201.9.0` has been updated with this backward incompatible change. Hence closing this issue.

**Closed by gabilang** 2024-06-18 07:25 UTC
Labels: Type/Bug, Area/JVMCodeGen, Priority/Blocker, Team/jBallerina
