### ISSUE TITLE
Debugger frames need to be in proper JSON format to provide better formatting in composer UI

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#8946] opened 2018-06-08 06:45 UTC
**Description:**
Currently ballerina core debugger outputs frames as strings like this.
```
{
"packageName":"ballerina.http",
"frameName":"get",
"fileName":"http_caching_client.bal",
"lineID":370,"variables":[
{"scope":"Local","name":"self","type":"ballerina.http:HttpCachingClient","value":"struct HttpCachingClient {serviceUri:\\\"http:\\/\\/www.simpsonquotes.xyz\\\", config:{url:\\\"http:\\/\\/www.simpsonquotes.xyz\\\", circuitBreaker:null, timeoutMillis:60000, keepAlive:AUTO, chunking:AUTO, httpVersion:\\\"1.1\\\", forwarded:\\\"disable\\\", followRedirects:null, retryConfig:null, proxy:null, connectionThrottling:null, secureSocket:null, cache:{enabled:true, isShared:false, expiryTimeMillis:86400, capacity:8388608, evictionFactor:0.2, policy:CACHE_CONTROL_AND_VALIDATORS}, compression:AUTO, auth:null}, httpClient:{serviceUri:\\\"http:\\/\\/www.simpsonquotes.xyz\\\", config:null}, cache:{}, cacheConfig:{enabled:true, isShared:false, expiryTimeMillis:86400, capacity:8388608, evictionFactor:0.2, policy:CACHE_CONTROL_AND_VALIDATORS}}"},{"scope":"Local","name":"path","type":"string","value":"\\/quote"},{"scope":"Local","name":"request","type":"null","value":"null"},{"scope":"Local","name":"req","type":"null","value":"null"}
]}
```
suggested format

```js
{
    "packageName": "ballerina.http",
    "frameName": "get",
    "fileName": "http_caching_client.bal",
    "lineID": 370,
    "variables": [
        {
            "scope": "Local",
            "name": "self",
            "type": "ballerina.http:HttpCachingClient",
            "value": {
                "serviceUri": "http://www.simpsonquotes.xyz",
                "config": {
                    "url": "http://www.simpsonquotes.xyz",
                    "circuitBreaker": null,
                    "timeoutMillis": 60000,
                    "keepAlive": "AUTO",
                    "chunking": "AUTO",
                    "httpVersion": "1.1",
                    "forwarded": "disable",
                    "followRedirects": null,
                    "retryConfig": null,
                    "proxy": null,
                    "connectionThrottling": null,
                    "secureSocket": null,
                    "cache": {
                        "enabled": true,
                        "isShared": false,
                        "expiryTimeMillis": 86400,
                        "capacity": 8388608,
                        "evictionFactor": 0.2,
                        "policy": "CACHE_CONTROL_AND_VALIDATORS",
                        "compression": "AUTO",
                        "auth": null
                    },
                    "httpClient": {
                        "serviceUri": "http://www.simpsonquotes.xyz",
                        "config": null
                    },
                    "cacheConfig": {
                        "enabled": true,
                        "isShared": false,
                        "expiryTimeMillis": 86400,
                        "capacity": 8388608,
                        "evictionFactor": 0.2,
                        "policy": "CACHE_CONTROL_AND_VALIDATORS"
                    }
                }
            }
        },
        {
            "scope": "Local",
            "name": "path",
            "type": "string",
            "value": "/quote"
        },
        {
            "scope": "Local",
            "name": "request",
            "type": "null",
            "value": "null"
        },
        {
            "scope": "Local",
            "name": "req",
            "type": "null",
            "value": "null"
        }
    ]
}
}
```

**Comment by lankavitharana** [comment] 2018-07-04 07:22
can't we format the json when it comes to the debugger client side?

**Comment by pahans** [comment] 2018-07-04 08:20
That's what we are doing right now.  Check `variables[0].value` in the example it's not json parsable.

**Comment by pahans** [comment] 2018-10-31 16:28
Changed the severity because current implementation is very fragile and error prone due to this.

**Comment by NipunaRanasinghe** [comment] 2020-07-01 07:36
Closing since the issue is no longer valid with the new jBallerina debugger implementation

**Closed by NipunaRanasinghe** 2020-07-01 07:36 UTC
Labels: Area/Tooling, Component/Debugger, Component/JVMCodeGen, Priority/High, Type/Bug
