### ISSUE TITLE
<json> json|error casting is not working

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#13980] opened 2019-02-27 20:20 UTC
**Description:**
<int> converts int|error into an int. Works fine, no issues.
```
    string s = "1";
    int|error iError = int.convert(s);
    int i = <int> iError;
```

Then I thought <json> would convert json|error into a json.
```
    Drink fanta = {id: 1, desc: "fanta"};
    json|error jError = json.convert(fanta);
    json j = <json> jError;
```

VSCode doesn't complain anything, but compilation is failing with `{"message":"assertion error: expected 'json', found 'map<json>'"}`

Issue is in the <json> jError part. If I do, _ = <json> jError; I get the same compilation error.

**Comment by nadeeshaan** [comment] 2019-02-28 03:09
@raj-rajaratnam Just tried the sample in latest master and could not see the error log. When tried it on v0.990.3 only could reproduce the error log. 
Diagnostics are basically provided by the compiler since at language server level we do not alter those. It seems this is being a runtime error and can you check this in the latest nightly build?

**Comment by MaryamZi** [comment] 2019-02-28 09:17
Yes this is due to `<json> jError` resulting in a panic.

With 0.990.3, the diamond operator served as a type assertion operator, which results in a panic if the type of the value is not an exact match with the type specified in the diamond operator.

Record to JSON conversion with `json.convert(fanta);` returns a `map<json>` when successful. Thus, the assertion `<json> jError` fails since the type of `jError` (`map<json>`) is not exactly `json`.

As per the 0.990.0 spec, with https://github.com/ballerina-platform/ballerina-lang/pull/13479 we have updated the diamond operator to perform casting. Thus the behaviour with the current master/latest nightly builds is that it will check if the value belongs to the type specified in the type descriptor (`<json>`). 

Since `json` is `() | boolean | int | float | decimal | string | json[] | map<json>`, 
the line `<json> jError` does not panic now, since `jError` of type `map<json>` belongs to `json`.

**Comment by MaryamZi** [comment] 2019-03-13 05:47
Closing this issue since answered. Please do reopen if there are further concerns.

**Closed by MaryamZi** 2019-03-13 05:47 UTC
Labels: Type/Question
