### ISSUE TITLE
Avoid creating new types each time in std lib extern implementations

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#21063] opened 2020-02-14 03:57 UTC
Came across the following in the `ExternRequest` class:
https://github.com/ballerina-platform/ballerina-lang/blob/d865ebf978dc89545a6165a54ca5f38d0680665f/stdlib/http/src/main/java/org/ballerinalang/net/http/nativeimpl/ExternRequest.java#L62

If the type doesn't change, there is no need to create types for each value created. Some of the types can be referred to from the symbol table and those that are not there can be created as final variables.

This is just one instance I came across. Need to check and fix in other std lib modules as well.

**Comment by chamil321** [comment] 2020-04-02 03:23
The issue is by https://github.com/ballerina-platform/ballerina-lang/pull/22396, hence closing

**Closed by chamil321** 2020-04-02 03:23 UTC
Labels: Area/StandardLibs, Points/2, Type/Improvement
