### ISSUE TITLE
Generated code is wrong with option `create variable and check error`

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-lang#36194] opened 2022-05-18 08:25 UTC
**Description:**
Consider the below line of code

`check io:fileReadJson(inputFile);
`
In vscode when selected the option to create variable and check error, this generated the following.

`json|io:Error fileReadJson = check io:fileReadJson(inputFile); 
`
where as the expectation was
`json fileReadJson = check io:fileReadJson(inputFile);
`
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by IMS94** [comment] 2022-05-30 18:26
I tested this locally on 2201.1.0, 2201.0.3 and 2201.1.1-SNAPSHOT branches. But couldn't reproduce this.
![create_var_and_check_error](https://user-images.githubusercontent.com/11285165/171044473-04b3ad2a-522c-476d-9057-0e8d94da25a7.gif)
@Dilhasha can you check if I missed something?

**Comment by Dilhasha** [comment] 2022-05-31 05:46
This is the output I'm getting with ballerina version `2201.0.3` and vscode 
![capture2](https://user-images.githubusercontent.com/5234641/171101263-0ff6fa7f-fe59-4ead-a75c-b05292cc249c.gif)

**Comment by Dilhasha** [comment] 2022-05-31 06:13
![capture1](https://user-images.githubusercontent.com/5234641/171104922-39c2ad6f-b57e-4561-a3a7-27d1b6c4b438.gif)

I still get the issue with ballerina dist version `2201.0.3`

**Comment by Dilhasha** [comment] 2022-05-31 06:25
I created the ballerina project with `bal new` and added the line `io:fileReadJson("");` inside the main function.
Following are the settings on Ballerina extension.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/5234641/171106433-7c9b90c0-c5f4-43ee-9a98-786e7cb715b7.png">

**Comment by IMS94** [comment] 2022-05-31 06:36
@Dilhasha Thanks! Understood the scenario now. It's reproducible.

**Comment by IMS94** [comment] 2022-06-01 07:31
The mentioned case is reproducible in 2201.0.3 and 2201.1.0. But fixed in 2201.1.1-SNAPSHOT (2201.1.x branch).
![2201 1 1_create_var_and_check_error](https://user-images.githubusercontent.com/11285165/171351343-724d6f5f-2de2-4878-b37c-0727c82b74c2.gif)

**Closed** 2022-06-02 09:00 UTC
Labels: Type/Bug, Priority/High, Team/LanguageServer, Points/1, Area/CodeAction, Reason/Invalid
