### ISSUE TITLE
Try-it is not working for some samples

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-lang#8253] opened 2018-04-27 07:45 UTC
**Steps to reproduce:**
1. Run the HTTP 2.0 Service sample.
2. Open the try-it

![37](https://user-images.githubusercontent.com/1845370/39350826-f7236692-4a1c-11e8-99c5-0ee2bcb371e0.png)

**Affected Versions:**
Version - Ballerina-0.970.0-rc1

**OS, DB, other environment details and versions:**
Firefox Browser - 59.0.2 (64-bit)

**Comment by pahans** [comment] 2018-05-09 08:45
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/8268

**Closed by pahans** 2018-05-09 08:45 UTC
Labels: Priority/High, component/Composer
