### ISSUE TITLE
[Bug]: Daily build failing when applying readonly over a union

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/ballerina-lang#41393] opened 2023-09-16 04:01 UTC
### Description

Fallowing code fails to compile in the[ current daily full build](https://github.com/ballerina-platform/ballerina-release/actions/runs/6201590609)
```
import ballerina/io;
const IDENTIFIER = 0;
const STRING_LITERAL = 4;

type VariableLengthToken readonly & ([IDENTIFIER, string] |
                                     [STRING_LITERAL, string]);
public function main() {
    VariableLengthToken? token = [STRING_LITERAL, "a"]; // <- fail with incompatible types: expected 'VariableLengthToken?', found '[int,string]'
    io:println(token);
}
```
It works fine if don't have a union in `VariableLengthToken` (ie. `type VariableLengthToken readonly & ( [STRING_LITERAL, string]);`

### Related area

-> Compilation

**Comment by rdulmina** [comment] 2023-09-17 05:15
Duplicate of #41285

**Closed by rdulmina** 2023-09-17 05:15 UTC
Labels: Type/Bug, needTriage, userCategory/Compilation
