### ISSUE TITLE
XML literals don't work when there is more than one item

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28299] opened 2021-01-30 02:24 UTC
These both get compilation errors:

```
xml x = xml`I am <i>very</i> sad`;
xml x = xml`I am <?pi?> sad`;
```

In this case, it seems to throw away all except the first item:

```
import ballerina/io;

xml x = xml`<p/>xyz`;

public function main() {
  io:println("Length should be 2: ", x.length());
  io:println("xml is: ", x);
}
```

This gives:

```
Length should be 2: 1
xml is: <p/>
```

**Comment by rdhananjaya** [comment] 2021-03-05 09:20
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/26340

**Closed by rdhananjaya** 2021-03-05 09:20 UTC
Labels: Area/Parser, CompilerSLDump, Lang/XML, Priority/Blocker, Team/CompilerFE, Type/Bug
