### ISSUE TITLE
Error: Method is too large

### ISSUE THREAD

**Issue by isuruRuhu** [ballerina-platform/ballerina-lang#26800] opened 2020-11-06 13:06 UTC
**Description:**
When compiling a ballerina file, I get the ` method is too large` error. 
<img width="409" alt="Screenshot 2020-11-06 at 17 59 41" src="https://user-images.githubusercontent.com/45358089/98366406-efa9e880-2059-11eb-9b69-93107b57609a.png">

This happened with several methods. 

**Steps to reproduce:**

Get this error, when the method has
- a large array (i.e with 1500 elements).  
or 
- a large JSON. 

**Affected Versions:**
Ballerina Swan Lake Preview 5

**OS, DB, other environment details and versions:**
N/A

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

Suggested Assignees (optional):
N/A

**Comment by MaryamZi** [comment] 2020-11-09 06:23
This is being tracked with https://github.com/ballerina-platform/ballerina-lang/issues/19033.

https://github.com/ballerina-platform/ballerina-lang/issues/19033#issuecomment-531637621 mentions possible workarounds too.

**Comment by anupama-pathirage** [comment] 2021-01-28 17:47
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/19033

**Closed by anupama-pathirage** 2021-01-28 17:47 UTC
Labels: Resolution/Duplicate, Team/jBallerina
