### ISSUE TITLE
High error rate in load tests for update 9

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#42566] opened 2024-04-17 02:34 UTC
**Description:**
$Subect.  Seems like this happened right after we bumped the versions for update9

Ref:
https://github.com/ballerina-platform/module-ballerina-http/blob/master/load-tests/h1_h1_passthrough/results/summary.csv#L465

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment] 2024-04-17 08:02
@HindujaB I was able to reduce the reproducer with this sample:
```bal
import ballerina/http;

service /api on new http:Listener(9090) {

    resource function get greeting(http:Request req) returns string {
        return "Hello, World!";
    }
}
```

If I remove the `http:Request` from the resource signature then there was no memory issue

When we have a signature parameter like `http:Request` we built it from the netty request using the following runtime method: `ValueCreator.createObjectValue`. Link: https://github.com/ballerina-platform/module-ballerina-http/blob/ea36127c62d925e4df13527466219972269e3587/native/src/main/java/io/ballerina/stdlib/http/api/HttpDispatcher.java#L426

**Comment by HindujaB** [comment] 2024-04-17 11:19
The issue is happening due to the internally created strands not garbage collected. These strands are created to invoke record default values in a non-Ballerina-dependent environment (from `netty` threads). I am currently working on a fix for this.

**Comment by TharmiganK** [comment] 2024-04-18 02:40
Tested this change in the [linked PR](https://github.com/ballerina-platform/ballerina-lang/pull/42576) with HTTP and now load tests are having 0% error rate:
https://github.com/ballerina-platform/module-ballerina-http/pull/1948/files
(The snowpeak load test is failing due to some other reason)

Also tested the changes locally by monitoring the memory. There is no high memory usuage, the memory usage is similar to update 8:
<img width="696" alt="Screenshot 2024-04-18 at 08 09 34" src="https://github.com/ballerina-platform/ballerina-lang/assets/63336800/bcc4354c-da95-4ee1-8fdf-1cd7fd5e3f07">

**Closed** 2024-04-29 04:59 UTC
Labels: Type/Bug, Priority/Blocker, Area/Scheduler
