### ISSUE TITLE
[VScode plugin] Compilation error suggestions does not get highlighted correctly

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#29434] opened 2021-03-23 08:25 UTC
**Description:**
Here I have incorrectly use 'const' keyword, but vscode plugin highlight variable intead of const key word.

![image](https://user-images.githubusercontent.com/4163165/112115407-2a628680-8bdf-11eb-9b5b-187ea14609ce.png)

**Comment by warunalakshitha** [comment] 2021-03-23 08:26
![image](https://user-images.githubusercontent.com/4163165/112115693-7c0b1100-8bdf-11eb-9307-3e6e42f23ab2.png)

Here semicolon is missing. But it shows next line.

**Comment by sameerajayasoma** [comment] 2021-03-23 21:35
Another case:

<img width="402" alt="Screen Shot 2021-03-23 at 2 34 39 PM" src="https://user-images.githubusercontent.com/2637328/112221654-ef635180-8be4-11eb-9871-2cef0071090c.png">

**Comment by lochana-chathura** [comment] 2021-04-02 10:15
This is a known issue with the parser.

The first sample is a Duplicate of #24765
The second and third samples are Duplicate of #29418

Hence, closing this issue.

**Closed by lochana-chathura** 2021-04-02 10:15 UTC
Labels: Area/Compiler, Area/Parser, Team/CompilerFE, Type/Bug, Version/SLAlpha3
