### ISSUE TITLE
[Bug]: More CancellationException with module imports 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#37599] opened 2022-09-01 05:53 UTC
### Description

Observed more CancellationException in LS debug logs, when the program has a http import. This leads to slowness in suggestions.   

### Steps to Reproduce

Remove `@display` annotation and type it again in the program 1. Then remove http module import and try to write it again.

Program 1 - withhttp
```ballerina
import ballerina/http;
import ballerina/io;

public function main() returns error? {
    http:Client cl = check new("https://example.com/");
    io:println("Hello");
}

type SomeConfig record {
    string username;
    @display {
        label: "abc",
        iconPath: "a"
    }
    string token;
};
```

Program 2 - withouthttp
```ballerina
import ballerina/io;

public function main() returns error? {
    io:println("Hello");
}

type SomeConfig record {
    string username;
    @display {
        label: "abc",
        iconPath: "a"
    }
    string token;
};
```

### Affected Version(s)

Ballerina version output: Ballerina 2201.2.0 (Swan Lake Update 2)
Language specification 2022R3
Update Tool 1.3.10
Plugin version: 3.1.0

Windows 10

### Labels

LanguageServer

**Comment by hasithaa** [comment] 2022-09-01 05:57
HTTP compiler plugin could be the root cause for this.

![image](https://user-images.githubusercontent.com/1356214/187841934-dd1ba695-35a7-483b-aa3f-701f55d8b553.png)

Attaching JPS

[withhttp.zip](https://github.com/ballerina-platform/ballerina-lang/files/9467213/withhttp.zip)
[withouthttp.zip](https://github.com/ballerina-platform/ballerina-lang/files/9467216/withouthttp.zip)

**Comment by IMS94** [comment] 2023-02-08 12:44
Closing this since we weren't able to reproduce this. Please reopen if the same issue arises.

**Closed by IMS94** 2023-02-08 12:44 UTC
Labels: Type/Bug, Priority/High, Team/LanguageServer, Points/2, Reason/Other
