### ISSUE TITLE
Syntax errors are not meaningful

### ISSUE THREAD

**Issue by maheeka** [ballerina-platform/ballerina-lang#4363] opened 2018-01-04 09:57 UTC
**Description:**
Consider the following source. 
![image](https://user-images.githubusercontent.com/1029806/34557983-240fafd0-f162-11e7-9b2f-9c4e3b777fdd.png)
The error should be that the statement is not allowed. But the shown error is,
"mismatched input '['. expecting Identifier at Line:9:15"

**Steps to reproduce:**
Open the below bal file.
```ballerina
import ballerina.net.http;

@http:configuration {
    basePath:"/product"
}
service<http> productService {

    map productMap = loadProducts();
    productMap["001"] = {name:"Pencil",price:20};

}
```

**Affected Versions:** 0.95.6

**OS, DB, other environment details and versions:** N/A

**Comment by SupunS** [comment] 2018-06-12 11:46
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/3673

**Closed by SupunS** 2018-06-12 11:46 UTC
Labels: Type/Bug, component/Compiler
