### ISSUE TITLE
Can't test if `is readonly`

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#34944] opened 2022-02-03 10:11 UTC
```ballerina
import ballerina/io;

type Person record {|
    string name;
|};

public function main() {
    readonly & Person p = { name: "manu" };
    Person p2 = p;
    io:println(p2 is readonly);
}
```
Above should compile and output true, but currently it fails at compile time.
```
ERROR [main.bal:(10:16,10:30)] incompatible types: 'manu/isreadonly:0.1.0:Person' will not be matched to 'readonly'
```

**Comment by MaryamZi** [comment] 2022-02-09 02:26
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/22785.

**Closed by MaryamZi** 2022-02-09 02:26 UTC
Labels: Type/Bug, Team/CompilerFE
