### ISSUE TITLE
Fix issue where runtime type is misused.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#4479] opened 2018-01-22 09:28 UTC
**Description:**

```ballerina
struct Protocols {
    string data;
    Protocol[] plist;
}

struct Protocol {
    string name;
    string url;
}

function main (string[] args) {
    json j = {data:"data", plist:[{name:"a", url:"h1"}, {name:"b", url:"h1"}]};
    var protocolsData, _ = <Protocols>j;
}
```
Runtime type of the variable `protocolsData` is `Protocol`. But it should be `Protocol[]`.

**Steps to reproduce:**

This PR has the fix for this issue: https://github.com/ballerinalang/ballerina/pull/4450

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment] 2018-10-10 11:13
Tried out the following program:
```ballerina
import ballerina/io;

type Protocols record {
    string data;
    Protocol[] plist;
};

type Protocol record {
    string name;
    string url;
};

public function main() {
    json j = {data:"data", plist:[{name:"a", url:"h1"}, {name:"b", url:"h2"}]};
    var protocolsData = check <Protocols>j;
    foreach p in protocolsData.plist {
        match p {
                Protocol prt => io:println(prt);
        }
    }
}
```
This resulted in the following output:
```
{name:"a", url:"h1"}
{name:"b", url:"h2"}
```
So it seems the issue is fixed. Hence closing this issue.

**Closed by pubudu91** 2018-10-10 11:13 UTC
Labels: Component/Compiler, Type/Bug
