### ISSUE TITLE
Crash during compilation of transaction code

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#28843] opened 2021-02-23 10:11 UTC
**Description:**
The following code maybe incorrect but it crashes during compilation:
```
import ballerina/lang.'transaction as transactions;

public function testTransactions() returns error? {
    
    transaction {
        transactions:Info transInfo = transactions:info();
        string res = "";

        var commitResult = commit;
        if commitResult is () {
            res = "Transaction committed";
        } else {
            res = "Transaction failed";
        }
    }
}
```
A better error message would be more appropriate. Following is seen in the ballerina-internal.log
```
[2021-02-23 15:40:02,919] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.getInternalTransactionModuleInvokableSymbol(TransactionDesugar.java:656)
	at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.invokeRollbackFunc(TransactionDesugar.java:486)
	at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.createRollbackIfFailed(TransactionDesugar.java:447)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.createTrxInternalOnFail(Desugar.java:5109)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5203)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangTransaction.accept(BLangTransaction.java:66)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7683)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7724)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7734)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1231)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7683)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1276)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7683)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7741)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:783)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7683)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:449)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:249)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:158)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:388)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:327)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:129)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:257)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Steps to reproduce:**
Run the code given above using the command
`bal run file_name.bal` to observe the log in the `ballerina-internal.log`
**Affected Versions:**
Swan lake alpha2 

**OS, DB, other environment details and versions:**
Ubuntu 20.04

**Comment by mohanvive** [comment] 2021-03-02 05:17
@riyafa I couldn't reproduce the issue in Swan Laka Alpha2, and the above code runs without any issues. 
Can you please confirm the version and issue please?

**Comment by mohanvive** [comment] 2021-03-02 07:22
Closing the issue because it is not reproducible. Please reopen if you encounter above issue again.

**Closed by mohanvive** 2021-03-02 07:22 UTC
Labels: CompilerSLDump, Lang/Transaction, Team/CompilerFE, Type/Bug
