### ISSUE TITLE
Invalid compilation error with valid `key-expression` when accessing members of a list

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35045] opened 2022-02-12 08:04 UTC
**Description:**
The spec says

> if the **static type of container-expression** is a subtype of string or of xml or of **basic type list**, then the contextually expected type for key-expression is int and the **static type of key-expression must be a subtype of int**.

The static type of `key-expression` is expected to be a subtype of `int`. But the following examples result in compilation errors.

**Steps to reproduce:**
```ballerina
const index = 0;

type IntType1 3|4;

type IntType2 int:Signed8|int:Signed16;

function init() {
    int[] arr = [10, 20, 30, 40, 50, 60, 70, 80];

    int i0 = 0;
    io:println(arr[i0]); // OK

    int:Signed8 i1 = 1;
    io:println(arr[i1]); // invalid list member access expression: value space 'int:Signed8' out of range

    byte i2 = 2;
    io:println(arr[i2]); // invalid list member access expression: value space 'int:Signed8' out of range

    int:Signed32|int:Signed16 i3 = 3;
    io:println(arr[i3]); // invalid list member access expression: value space 'int:Signed8' out of range

    IntType1 i4 = 4;
    io:println(arr[i4]); // OK

    IntType2 i5 = 5;
    io:println(arr[i5]); // invalid list member access expression: value space 'int:Signed8' out of range

    io:println(arr[index]); // OK
}
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by MaryamZi** [comment] 2022-03-04 08:19
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/33346?

**Closed** 2022-03-04 08:43 UTC
Labels: Type/Bug, Team/CompilerFE, Area/TypeChecker, Error/TypeK
