### ISSUE TITLE
Bad Sad for an "enum" declaration with syntax errors

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-lang#28212] opened 2021-01-25 22:22 UTC
Here is the sample code 

```
enum Color {
    BLUE, 
}
```

error:
```
[2021-01-25 14:19:56,013] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1778)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangConstant.accept(BLangConstant.java:107)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:262)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineTypeNodes(SymbolEnter.java:1061)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineConstructs(SymbolEnter.java:366)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:300)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:262)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:255)
        at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:367)
        at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
        at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:322)
        at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:145)
        at io.ballerina.projects.PackageCompilation.diagnosticResult(PackageCompilation.java:104)
        at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:87)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:118)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:135)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:248)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Comment by lochana-chathura** [comment] 2021-03-04 15:13
Duplicate of #28957

**Closed by lochana-chathura** 2021-03-04 15:13 UTC
Labels: CompilerSLDump, Lang/EnumDeclaration, Priority/Blocker, Team/CompilerFE, Type/Bug
