### ISSUE TITLE
[Question] Example not executing in play.ballerina.io

### ISSUE THREAD

**Issue by scheung38** [ballerina-platform/ballerina-lang#23088] opened 2020-05-04 16:34 UTC
```
import ballerina/io;

public function main() {
    @strand {thread: "any"}
    worker w1 {
        io:println("Hello, World! #m");
    }

    @strand {thread: "any"}
    worker w2 {
        io:println("Hello, World! #n");
    }
    @strand {thread: "any"}
    worker w3 {
        io:println("Hello, World! #k");
    }
}
```

<img width="488" alt="Screenshot 2020-05-04 at 17 32 29" src="https://user-images.githubusercontent.com/1273014/80989921-7d97e300-8e2d-11ea-9250-995494b956bf.png">

**Comment by kaviththiranga** [comment] 2020-08-03 04:48
@scheung38 Sorry for the delayed response. Can you retry running this? I cannot reproduce this now. Please check the screenshot below.

However, couple of weeks back, we identified an issue where executor service (which is responsible for running the compiled jars for playground) did not respond properly. We fixed it as soon as we found it. I suspect, you may have faced the same issue.

<img width="1440" alt="Screenshot 2020-08-03 at 10 15 09" src="https://user-images.githubusercontent.com/1505855/89146809-6ecae480-d572-11ea-9615-0a5635e84be8.png">

**Comment by kaviththiranga** [comment] 2020-08-03 04:51
I am closing this as per the last reply, please feel free to reopen if you still face the same issue. Thank you.

**Closed by kaviththiranga** 2020-08-03 04:51 UTC

**Comment by scheung38** [comment] 2020-08-03 07:11
Thank you for updating, in a related question how do we go from main to multiple strands and back to main thread?
