### ISSUE TITLE
Issue while running ballerina which has been built from source

### ISSUE THREAD

**Issue by m0nk3ydluffy** [ballerina-platform/ballerina-lang#16098] opened 2019-06-28 11:08 UTC
**Description:**
After building ballerina in my system, I am unable to run the ballerina executable placed in distribution/zip/ballerina-tools/build/extracted-distributions/ballerina-tools-0.992.0-m2-SNAPSHOT/bin

**Affected Versions:**
0.992.0-m2

**OS, DB, other environment details and versions:**
OS: Ubuntu 16.04

**ballerina-internal.log contents:**
`[2019-06-28 16:05:07,858] ERROR {org.ballerinalang.launcher.Main} - org.ballerinalang.launcher.BLauncherCmd: Provider org.ballerinalang.protobuf.cmd.GrpcCmd could not be instantiated 
java.util.ServiceConfigurationError: org.ballerinalang.launcher.BLauncherCmd: Provider org.ballerinalang.protobuf.cmd.GrpcCmd could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.ballerinalang.launcher.Main.getInvokedCmd(Main.java:104)
	at org.ballerinalang.launcher.Main.main(Main.java:62)
Caused by: java.lang.NoClassDefFoundError: org/ballerinalang/net/grpc/exception/BalGenerationException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.ballerinalang.net.grpc.exception.BalGenerationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
 `

**Comment by pahans** [comment] 2019-08-11 07:52
duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/16196
This is fixed in latest master.

**Closed by pahans** 2019-08-11 07:52 UTC
Labels: Area/Build, Type/Bug
