### ISSUE TITLE
How can I pass a variable to filter?

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-lang#13452] opened 2019-02-04 17:11 UTC
**Description:**

```
import ballerina/io;

public type Balance record {
    string asset;
    string free;
    string locked;
};

public type Wallet record {
    Balance[] balances;
};

public function main(string... args) {
    Balance bal1 = {asset:"BTC", free:"12", locked:"8"};
    Balance bal2 = {asset:"LTC", free:"2", locked:"1"};
    Wallet wal = {balances:[bal1, bal2]};
    io:println(wal);
    string BTC = "BTC";
    Balance[] bal = wal.balances.filter(
                    function (Balance b) returns boolean {
                        return b.asset == BTC;
                    }
                );
    io:println(bal);
}
```
When I move that string BTC variable to a global variable, it works, but this should ideally work for locla variables as well. 

**Affected Versions:**
0.990.2

**Comment by pubudu91** [comment] 2019-02-05 02:54
This is because closures are not yet supported for lambdas. Duplicate of #10149

**Comment by raj-rajaratnam** [comment] 2019-03-10 04:13
@pubudu91 @hasithaa @anupama-pathirage Is there a fix for this yet? This is a blocker for us. Any workaround?

**Comment by hasithaa** [comment] 2019-03-11 02:37
@raj-rajaratnam, @NatashaWso2 is working on the fix. We are almost there but requires additional modifications to support some other scenarios. You can track the issue progress from here. https://github.com/ballerina-platform/ballerina-lang/issues/13849. We are expecting to merge this into the master later in this week.

**Comment by hasithaa** [comment] 2019-03-11 02:38
Related to #13849

**Closed** 2019-03-28 12:11 UTC
Labels: Component/BVM, Component/Compiler

**Comment by raj-rajaratnam** [comment] 2019-04-19 18:54
@hasithaa this is not fully fixed it seems. See https://github.com/ballerina-platform/ballerina-lang/issues/15068
