### ISSUE TITLE
TOML parse breaks when given an directory path in windows

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-lang#17758] opened 2019-08-15 09:57 UTC
**Description:**
It is not possible to give a windows directory path in the toml file used by the config library. 

**Steps to reproduce:**
```toml
mount_path = "C:/Users/Administrator/Downloads"
```

When running the app:
```
C:\Users\Administrator\IdeaProjects\bal-http-server>ballerina run target\bin\server-executable.jar
error: For input string: "sers"
```

**OS, DB, other environment details and versions:**
Windows

**Comment by parkavi11** [comment] 2020-05-13 09:28
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/21638. Here the solution is to give path within single quotes instead of double quotes as the toml library allows paths within single quotes.

**Closed** 2020-05-13 09:28 UTC
Labels: Area/BuildTools, BetaTesting, Component/Packerina, Type/Bug
