### ISSUE TITLE
LinkageError: duplicate field name

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#30116] opened 2021-04-21 03:59 UTC
Doing `bal run` on the attached project results in the error:

```
Error: LinkageError occurred while loading main class jjc.semtype.0_1_0.$_init
        java.lang.ClassFormatError: Duplicate field name "$type$(jjc$0047semtype$00580$00461$00460$0058BddNode & readonly)" with signature "Lio.ballerina.runtime.api.types.Type;" 
in class file jjc/semtype/0_1_0/$_init
```
[semtype.zip](https://github.com/ballerina-platform/ballerina-lang/files/6347917/semtype.zip)

**Comment by jclark** [comment] 2021-04-21 04:54
It seems to be caused by these lines in `parseXTypes`:

```
 foreach var j in js {
        s.push(check parseXType(env, j, pathAppend(parent, i)));
        i += 1;    
    }
```

**Comment by jclark** [comment] 2021-04-21 04:56
Changing to:

```
   foreach var j in js {
        SemType t = check parseXType(env, j, pathAppend(parent, i));
        s.push(t);
        i += 1;    
    }
```

makes the LinkageError go away.

**Comment by warunalakshitha** [comment] 2021-04-29 08:24
After debugging the issue It seems the error occurs due to duplicate type definitions.
![image](https://user-images.githubusercontent.com/4163165/116522019-4e0da080-a8f2-11eb-88f0-fe9d679db293.png)

The second type definition is added in https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/util/ImmutableTypeCloner.java#L618

**Comment by warunalakshitha** [comment] 2021-04-29 08:25
We can skip the duplicate type definitions during codegen, but the correct fix would be to handle those in the compiler front end.

**Comment by warunalakshitha** [comment] 2021-04-29 08:27
Please check https://github.com/ballerina-platform/ballerina-lang/issues/30116 which seems related to same duplicate type definition issue.

**Comment by MaryamZi** [comment] 2021-04-30 05:09
Reproducible with the following example.

```ballerina
type Foo readonly & record {| |};

public readonly class Bar {
    Foo[] arr = [];
}

function parse() returns error? {
    Bar[] s = [];
    s.push(check parseBar());
}

function parseBar() returns Bar|error => error("error!");
```

Seems to be happening when [resolving type params](https://github.com/ballerina-platform/ballerina-lang/blob/vswan-lake-alpha5/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/TypeParamAnalyzer.java#L741).

**Closed** 2021-05-03 11:12 UTC
Labels: Priority/Blocker, SwanLakeDump, Team/CompilerFE, Type/Bug
