### ISSUE TITLE
Parameter refered function pointer as default param in function 

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#21519] opened 2020-03-07 03:17 UTC
**Description:**
Below code snippet throws a bad sad error.

```
function test(string nnn, function () returns string fn = () => nnn) returns string {
    return fn();
}
```

**Comment by MaryamZi** [comment] 2021-01-27 07:21
ballerina-internal.log

```log
[2021-01-27 12:51:11,303] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:404)
	at org.wso2.ballerinalang.compiler.bir.model.BIROperand.accept(BIROperand.java:36)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:448)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNonTerminator$FPLoad.accept(BIRNonTerminator.java:715)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$visit$1(BIRInstructionWriter.java:131)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.visit(BIRInstructionWriter.java:125)
	at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:419)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.lambda$writeBBs$0(BIRInstructionWriter.java:88)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRInstructionWriter.writeBBs(BIRInstructionWriter.java:88)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunction(BIRBinaryWriter.java:280)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.lambda$writeFunctions$5(BIRBinaryWriter.java:186)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.writeFunctions(BIRBinaryWriter.java:186)
	at org.wso2.ballerinalang.compiler.bir.writer.BIRBinaryWriter.serialize(BIRBinaryWriter.java:85)
	at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:265)
	at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:253)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:163)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:387)
	at io.ballerina.projects.ModuleCompilationState$1.generatePlatformSpecificCode(ModuleCompilationState.java:54)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:326)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:136)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:122)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:98)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:135)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:97)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:155)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Comment by warunalakshitha** [comment] 2021-06-03 12:03
We had quick look at this issue. The issue is closure desuger does not handle when we use the parameter referred to function pointer as default param. 
So bir function generated like below

`

function test(string nnn){
    // default param stmts
    nnn = "waruna";
    fn = $lamda( $map);

    // closure stmts
    $map = {};
    $map["nnn"] = nnn;
  
    // other function body stmts
     return fn();
}

`

Here $map is not found during default param initialization. We cannot use the function closure map here since it is initiated after default statements. Either Closer desuger needs to move that before the default statements and rewrite default params into closure map 
Or
 use a separate closure map for default function pointer variables with default params.

**Comment by MaryamZi** [comment] 2022-02-24 06:28
@chiranSachintha, can you check this with the function default value improvements?

**Comment by chiranSachintha** [comment] 2022-02-24 06:55
> @chiranSachintha, can you check this with the function default value improvements?

@MaryamZi This issue is fixed with this PR(https://github.com/ballerina-platform/ballerina-lang/pull/31589)

**Closed** 2022-03-22 06:27 UTC
Labels: Type/Bug, Priority/Blocker, Team/CompilerFE, Area/Desugar, SwanLakeDump, Lang/Function, Crash
