### ISSUE TITLE
Source view completions and hover does not work on Windows

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6441] opened 2018-04-03 10:47 UTC
<a href="https://github.com/roonyh"><img src="https://avatars0.githubusercontent.com/u/3872221?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roonyh](https://github.com/roonyh)**
_Wednesday Jan 03, 2018 at 07:53 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4918_

----

**Description:**
In the source view completions and hover does not work in windows 10, Chrome

**Affected Product Version:**
v0.95.6

**OS, DB, other environment details and versions:**    
Windows 10
Chrome v63

**Comment by hevayo** [comment] 2018-05-15 08:29
Duplicate of #6473

**Closed by hevayo** 2018-05-15 08:29 UTC
Labels: Imported, OS/Windows, component/Composer
