### ISSUE TITLE
IntelliJ does not resolve "gsheets" reference

### ISSUE THREAD

**Issue by sajinieKavindya** [ballerina-platform/ballerina-lang#13143] opened 2019-01-11 07:54 UTC
**Description:**
I have imported the wso2/gsheets4 module to my Ballerina project at the beginning, but the IDE is still suggesting me to import it.  

<img width="499" alt="screen shot 2019-01-11 at 12 24 22 pm" src="https://user-images.githubusercontent.com/17607360/51020281-1bfe9600-15a4-11e9-9007-53f08d49fedb.png">

<img width="434" alt="screen shot 2019-01-11 at 12 30 07 pm" src="https://user-images.githubusercontent.com/17607360/51020243-04bfa880-15a4-11e9-83dd-1be3e9783b06.png">

**Affected Versions:**
Ballerina v0.990.2
IntelliJ plugin v0.990.1

**Comment by NipunaRanasinghe** [comment] 2019-01-23 08:42
Could you please specify your IntelliJ IDEA version and the OS type to reproduce the issue?

**Comment by sajinieKavindya** [comment] 2019-01-23 09:19
IntelliJ IDEA version - 2018.3.2 (Ultimate Edition)
mac OS version 10.14.2

**Comment by NipunaRanasinghe** [comment] 2019-06-12 08:51
Closing since this is fixed by introducing the language server based semantic analyzing.

**Closed by NipunaRanasinghe** 2019-06-12 08:51 UTC
Labels: Area/Tooling, Component/IntellijPlugin, Type/Bug
