### ISSUE TITLE
Build fails when imports are used among packages

### ISSUE THREAD

**Issue by Kavindu-Dodan** [ballerina-platform/ballerina-lang#10851] opened 2018-10-15 09:03 UTC
**Description:**
Ballerina build fails when a package contains an entry point with imports from other local pacakges. Following is the message and  NPE is recorded when this error occurred,

Console output  - 

> Generating executables
> ballerina: Oh no, something really went wrong. Bad. Sad.
> 
> There should be a file named "ballerina-internal.log" in the current directory.
> If you are able to share with us the code that broke Ballerina then
> we would REALLY appreciate if you would report this to us:
> go to https://github.com/ballerina-platform/ballerina-lang/issues and
> create a bug report with both this log file and the sample code.
> 
> We thank you for helping make us better dancers.

ballerina-internal.log 

> [2018-10-15 14:21:36,655] ERROR {org.ballerinalang.launcher.Main} - null 
> java.lang.NullPointerException
> 	at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:39)
> 	at org.wso2.ballerinalang.compiler.BinaryFileWriter.addPackageBinaryContent(BinaryFileWriter.java:188)
> 	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:154)
> 	at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:127)
> 	at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:88)
> 	at java.util.ArrayList.forEach(ArrayList.java:1257)
> 	at org.wso2.ballerinalang.compiler.Compiler.write(Compiler.java:105)
> 	at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:97)
> 	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:95)
> 	at java.util.Optional.ifPresent(Optional.java:159)
> 	at org.ballerinalang.launcher.Main.main(Main.java:65)

**Steps to reproduce:**

Crete a project with following package structure (minimal)

> /  <- project root
> |
> - my.foo <- first package
>       |
>        - FooFunctions.bal <- Some .bal file
> |
>  - my.bar <- second package
>       |
>       - BarFunctions.bal <- Another .bal file

Try to import my.bar from my.foo 

> import org-name/my.bar;
> 
> public function main(string... args) {
> }

running `ballerina build` from project root level fails the build with above reported outputs. Anyway I can still build individual packages and run the package specifically with entry point.

**Affected Versions:**

0.982.0

**OS, DB, other environment details and versions:**

Mac OS 10.13.6

**UPDATE -** 

This won't occur if I use a .bal in project root level. For example with following folder structure,

> /  <- project root
> |
> - my.foo <- first package
>       |
>       - FooFunctions.bal <- Some .bal file
> |
> - my.bar <- second package
>       |
>      -BarFunctions.bal <- Another .bal file
> |
>   test.bal  <- root level .bal

having my main() entry point in test.bal won't cause this error. But as docs suggests, this is not recommended.

**Comment by Kavindu-Dodan** [comment] 2018-10-15 09:11
> **Description:**
> Ballerina build fails when a package contains an entry point with imports from other local pacakges. Following is the message and NPE is recorded when this error occurred,
> 
> Console output -
> 
> > Generating executables
> > ballerina: Oh no, something really went wrong. Bad. Sad.
> > There should be a file named "ballerina-internal.log" in the current directory.
> > If you are able to share with us the code that broke Ballerina then
> > we would REALLY appreciate if you would report this to us:
> > go to https://github.com/ballerina-platform/ballerina-lang/issues and
> > create a bug report with both this log file and the sample code.
> > We thank you for helping make us better dancers.
> 
> ballerina-internal.log
> 
> > [2018-10-15 14:21:36,655] ERROR {org.ballerinalang.launcher.Main} - null
> > java.lang.NullPointerException
> > at org.wso2.ballerinalang.programfile.PackageFileWriter.writePackage(PackageFileWriter.java:39)
> > at org.wso2.ballerinalang.compiler.BinaryFileWriter.addPackageBinaryContent(BinaryFileWriter.java:188)
> > at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:154)
> > at org.wso2.ballerinalang.compiler.BinaryFileWriter.writeLibraryPackage(BinaryFileWriter.java:127)
> > at org.wso2.ballerinalang.compiler.BinaryFileWriter.write(BinaryFileWriter.java:88)
> > at java.util.ArrayList.forEach(ArrayList.java:1257)
> > at org.wso2.ballerinalang.compiler.Compiler.write(Compiler.java:105)
> > at org.ballerinalang.packerina.BuilderUtils.compileWithTestsAndWrite(BuilderUtils.java:97)
> > at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:95)
> > at java.util.Optional.ifPresent(Optional.java:159)
> > at org.ballerinalang.launcher.Main.main(Main.java:65)
> 
> **Steps to reproduce:**
> 
> Crete a project with following package structure (minimal)
> 
> > /  <- project root
> > |
> > /my.foo <- first package
> > |
> > - FooFunctions.bal <- Some .bal file
> > |
> > / my.bar <- second package
> > |
> > - BarFunctions.bal <- Another .bal file
> 
> Try to import my.bar from my.foo
> 
> > import org-name/my.bar;
> > public function main(string... args) {
> > }
> 
> running `ballerina build` from project root level fails the build with above reported outputs. Anyway I can still build individual packages and run the package specifically with entry point.
> 
> **Affected Versions:**
> 
> 0.982.0
> 
> **OS, DB, other environment details and versions:**
> 
> Mac OS 10.13.6
> 
> **UPDATE -**
> 
> This won't occur if I use a .bal in project root level. For example with following folder structure,
> 
> > /  <- project root
> > |
> > /my.foo <- first package
> > |
> > - FooFunctions.bal <- Some .bal file
> > |
> > /my.bar <- second package
> > |
> > -BarFunctions.bal <- Another .bal file
> > |
> > test.bal  <- root level .bal
> 
> having my main() entry point in test.bal won't cause this error. But as docs suggests, this is not recommended.

**Comment by parkavi11** [comment] 2020-02-12 12:08
Imports can be used within modules thereby this issue is fixed with ballerina version 1.0.0.

**Comment by hevayo** [comment] 2020-02-12 12:54
The issue is no longer relevant with the current code base.

**Closed by hevayo** 2020-02-12 12:54 UTC
Labels: Area/BuildTools, Component/Packerina, Type/Bug
