### ISSUE TITLE
Proxy service for soap back ens is not working

### ISSUE THREAD

**Issue by Rajith90** [ballerina-platform/ballerina-lang#14962] opened 2019-04-05 12:14 UTC
**Description:**
I have written following pass though service for the soap back end "http://ws.cdyne.com/phoneverify/phoneverify.asmx".

`
import ballerina/log;
import ballerina/http;
import ballerina/config;
import ballerina/time;

http:Client soap_1_0_0_prod = new (
    "http://ws.cdyne.com/phoneverify/phoneverify.asmx",
    config = { 
    cache: { enabled: false },
	chunking: http:CHUNKING_ALWAYS
});

@http:ServiceConfig {
    basePath: "/soap/1.0.0"
}
service myService1 on new http:Listener(9090) {
    @http:ResourceConfig {
        methods: ["POST"],
        path: "/*"
    }
    resource function post_89de80b5_b01e_4973_a1df_3887fa77f2b1 (http:Caller outboundEp, http:Request req) {
    
    string urlPostfix = untaint req.rawPath.replace("/soap/1.0.0","");
    
        http:Response|error clientResponse;
        clientResponse = soap_1_0_0_prod->forward(urlPostfix, req);
        if(clientResponse is http:Response) {
            var outboundResult = outboundEp->respond(clientResponse);
            if (outboundResult is error) {
                log:printError("Error when sending response", err = outboundResult);
            }
        }
    }
}
 `

**Steps to reproduce:**
Then I have used following curl command.
`curl -k -X POST "http://localhost:9090/soap/1.0.0/" -H "accept: text/xml" -H "SOAPAction: http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumber" -H "Content-Type: text/xml" -H "Authorization: Bearer b8242f8f-55c2-344a-8115-7984d57f2654" -d "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:quer=\"http://ws.cdyne.com/PhoneVerify/query\"><soapenv:Header/><soapenv:Body><quer:CheckPhoneNumber><quer:PhoneNumber>18006785432</quer:PhoneNumber><quer:LicenseKey>0</quer:LicenseKey></quer:CheckPhoneNumber></soapenv:Body></soapenv:Envelope>"`

But the back end returns 500 error response. 
But when I proxies the same soap service with WSO2 API Manager gateway, it works fine

**Affected Versions:** 0.990.3

**Comment by Bhashinee** [comment] 2019-04-06 04:22
@Rajith90 Can you please try without having the finishing '/' of the curl command URL as follows,
`curl -k -X POST "http://localhost:9090/soap/1.0.0" -H "accept: text/xml" -H "SOAPAction: http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumber" -H "Content-Type: text/xml" -H "Authorization: Bearer b8242f8f-55c2-344a-8115-7984d57f2654" -d "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:quer=\"http://ws.cdyne.com/PhoneVerify/query\"><soapenv:Header/><soapenv:Body><quer:CheckPhoneNumber><quer:PhoneNumber>18006785432</quer:PhoneNumber><quer:LicenseKey>0</quer:LicenseKey></quer:CheckPhoneNumber></soapenv:Body></soapenv:Envelope>"`

**Comment by Bhashinee** [comment] 2019-05-10 05:59
Reason for this is from this line `string urlPostfix = untaint req.rawPath.replace("/soap/1.0.0","");` you replace the incoming request's raw path's "/soap/1.0.0" part into an empty string. 

Since you are sending a backslash at the end of the URL from CURL, urlPostfix becomes "/". ex: `urlPostfix = "/"`. So the final URL to which the request is forwarded is "http://ws.cdyne.com/phoneverify/phoneverify.asmx/". In Ballerina, we don't remove any characters given by the user when forwarding the request. 

When we try to access the server with the above URL, the server sends a 500 error response. You'll see this behavior when you try to access it even with a browser.

**Comment by Bhashinee** [comment] 2019-05-10 06:00
Closing the issue, as this is not a bug in Ballerina.

**Closed by Bhashinee** 2019-05-10 06:00 UTC
Labels: Area/StandardLibs
