### ISSUE TITLE
Intermittent failure - WebSubContentTypeSupportTestCase

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-lang#13922] opened 2019-02-26 08:37 UTC
**Description:**
```
[2019-02-22 07:11:45,285] INFO {WebSubContentTypeSupportTestCase} - [1mtestAuthenticatedTextContentReceiptForInternalHub: [34m[1mRUNNING[0m 
[2019-02-22 07:11:45,723] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriber: <websub><request>Notification</request><type>Internal</type></websub> 
[2019-02-22 07:11:45,723] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriber: <websub><request>Notification</request><type>Remote</type></websub> 
[2019-02-22 07:11:45,724] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriberTwo: <websub><request>Notification</request><type>Remote</type></websub> 
[2019-02-22 07:11:45,725] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriberTwo: <websub><request>Notification</request><type>Internal</type></websub> 
[2019-02-22 07:12:00,163] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2019-02-22 07:12:00,162 ERROR [ballerina/websub] - Error delivering content to callback[http://localhost:8181/websubTwo] for topic[http://one.websub.topic.com]: Connection refused: localhost/127.0.0.1:8181  
[2019-02-22 07:12:00,181] INFO {org.ballerinalang.test.context.ServerLogReader} - JSON WebSub Notification Received by websubSubscriberTwo: {"action":"publish", "mode":"internal-hub"} 
[2019-02-22 07:12:00,189] INFO {org.ballerinalang.test.context.ServerLogReader} - JSON WebSub Notification Received by websubSubscriber: {"action":"publish", "mode":"internal-hub"} 
[2019-02-22 07:12:30,289] SEVERE {org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase} - [1mtestAuthenticatedTextContentReceiptForInternalHub: [31m[1mFAILED -> Timeout expired waiting for matching log: Text WebSub Notification Received by websubSubscriber: Text update for internal Hub[0m 
```

https://api.travis-ci.org/v3/job/496833194/log.txt

**Comment by MaryamZi** [comment] 2019-02-28 07:54
Looking at the logs mentioned in #13924, #13925 and #13926, they all seem to have failed in the same build as this.

Reconstructed log - 
```
[2019-02-22 07:11:45,285] INFO {WebSubContentTypeSupportTestCase} - �[1mtestAuthenticatedTextContentReceiptForInternalHub: �[34m�[1mRUNNING�[0m 
[2019-02-22 07:11:45,723] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriber: <websub><request>Notification</request><type>Internal</type></websub> 
[2019-02-22 07:11:45,723] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriber: <websub><request>Notification</request><type>Remote</type></websub> 
[2019-02-22 07:11:45,724] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriberTwo: <websub><request>Notification</request><type>Remote</type></websub> 
[2019-02-22 07:11:45,725] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriberTwo: <websub><request>Notification</request><type>Internal</type></websub> 
[2019-02-22 07:12:00,163] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2019-02-22 07:12:00,162 ERROR [ballerina/websub] - Error delivering content to callback[http://localhost:8181/websubTwo] for topic[http://one.websub.topic.com]: Connection refused: localhost/127.0.0.1:8181  
[2019-02-22 07:12:00,181] INFO {org.ballerinalang.test.context.ServerLogReader} - JSON WebSub Notification Received by websubSubscriberTwo: {"action":"publish", "mode":"internal-hub"} 
[2019-02-22 07:12:00,189] INFO {org.ballerinalang.test.context.ServerLogReader} - JSON WebSub Notification Received by websubSubscriber: {"action":"publish", "mode":"internal-hub"} 
[2019-02-22 07:12:30,289] SEVERE {org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase} - �[1mtestAuthenticatedTextContentReceiptForInternalHub: �[31m�[1mFAILED -> Timeout expired waiting for matching log: Text WebSub Notification Received by websubSubscriber: Text update for internal Hub�[0m 
[2019-02-22 07:12:30,308] INFO {WebSubContentTypeSupportTestCase} - �[1mtestAuthenticatedTextContentReceiptForRemoteHub: �[34m�[1mRUNNING�[0m 
[2019-02-22 07:13:15,310] SEVERE {org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase} - �[1mtestAuthenticatedTextContentReceiptForRemoteHub: �[31m�[1mFAILED -> Timeout expired waiting for matching log: Text WebSub Notification Received by websubSubscriber: Text update for remote Hub�[0m 
[2019-02-22 07:13:15,316] INFO {WebSubContentTypeSupportTestCase} - �[1mtestUnauthenticatedTextContentReceiptForInternalHub: �[34m�[1mRUNNING�[0m 
[2019-02-22 07:14:00,318] SEVERE {org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase} - �[1mtestUnauthenticatedTextContentReceiptForInternalHub: �[31m�[1mFAILED -> Timeout expired waiting for matching log: Text WebSub Notification Received by websubSubscriberTwo: Text update for internal Hub�[0m 
[2019-02-22 07:14:00,319] INFO {WebSubContentTypeSupportTestCase} - �[1mtestUnauthenticatedTextContentReceiptForRemoteHub: �[34m�[1mRUNNING�[0m 
[2019-02-22 07:14:45,321] SEVERE {org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase} - �[1mtestUnauthenticatedTextContentReceiptForRemoteHub: �[31m�[1mFAILED -> Timeout expired waiting for matching log: Text WebSub Notification Received by websubSubscriberTwo: Text update for remote Hub�[0m 
```

Closing the other issues and renaming this issue to check on the entire `WebSubContentTypeSupportTestCase` test itself.

**Comment by MaryamZi** [comment] 2019-03-18 07:13
Closing this issue since we've not observed the failure recently. 

Please re-open if the failure is observed again, with the complete log if possible.

**Comment by shafreenAnfar** [comment] 2020-05-31 08:38
It seems the issue is still there and I encountered this issue a couple of times in the past few days. Following is an excerpt of the log file.

`[2020-05-31 04:50:38,582] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,580 INFO  [ballerina/websub] - Intent verification successful for mode: [subscribe], for callback URL: [http://localhost:23282/websub]  
[2020-05-31 04:50:38,589] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,587 INFO  [ballerina/websub] - Intent verification successful for mode: [subscribe], for callback URL: [http://localhost:23282/websubTwo]  
[2020-05-31 04:50:38,597] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,595 INFO  [ballerina/websub] - Update notification done for Topic [http://one.websub.topic.com]  
[2020-05-31 04:50:38,599] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,597 ERROR [ballerina/websub] - Error delivering content to callback[http://localhost:23181/subscriberWithNoPathInAnnot] for topic[http://one.websub.topic.com]: Something wrong with the connection  
[2020-05-31 04:50:38,612] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,611 ERROR [ballerina/websub] - Error delivering content to callback[http://localhost:23181/subscriberWithNoPathInAnnot] for topic[http://one.websub.topic.com]: Something wrong with the connection  
[2020-05-31 04:50:38,620] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,620 ERROR [ballerina/websub] - Error delivering content to callback[http://localhost:23181/subscriberWithNoPathInAnnot] for topic[http://one.websub.topic.com]: Something wrong with the connection  
[2020-05-31 04:50:38,704] INFO {org.ballerinalang.test.context.ServerLogReader} - JSON WebSub Notification Received by websubSubscriberTwo: {"action":"publish", "mode":"remote-hub"} 
[2020-05-31 04:50:38,786] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,785 INFO  [ballerina/websub] - Update notification done for Topic [http://one.websub.topic.com]  
[2020-05-31 04:50:38,796] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,794 ERROR [ballerina/websub] - Error delivering content to callback[http://localhost:23181/subscriberWithNoPathInAnnot] for topic[http://one.websub.topic.com]: Something wrong with the connection  
[2020-05-31 04:50:38,800] INFO {org.ballerinalang.test.context.ServerLogReader} - JSON WebSub Notification Received by websubSubscriber: {"action":"publish", "mode":"remote-hub"} 
[2020-05-31 04:50:38,801] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:38,800 ERROR [ballerina/websub] - Error delivering content to callback[http://localhost:23181/subscriberWithNoPathInAnnot] for topic[http://one.websub.topic.com]: Something wrong with the connection  
[2020-05-31 04:50:39,071] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriber: <websub><request>Notification</request><type>Remote</type></websub> 
[2020-05-31 04:50:39,071] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriber: <websub><request>Notification</request><type>Internal</type></websub> 
[2020-05-31 04:50:39,072] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriberTwo: <websub><request>Notification</request><type>Remote</type></websub> 
[2020-05-31 04:50:39,072] INFO {org.ballerinalang.test.context.ServerLogReader} - XML WebSub Notification Received by websubSubscriberTwo: <websub><request>Notification</request><type>Internal</type></websub> 
[2020-05-31 04:50:39,541] INFO {org.ballerinalang.test.context.ServerLogReader} - Text WebSub Notification Received by websubSubscriber: Text update for internal Hub 
[2020-05-31 04:50:39,543] INFO {org.ballerinalang.test.context.ServerLogReader} - Text WebSub Notification Received by websubSubscriberTwo: Text update for internal Hub 
[2020-05-31 04:50:39,556] SEVERE {org.ballerinalang.test.context.ServerLogReader} - 2020-05-31 04:50:39,554 ERROR [ballerina/websub] - Error delivering content to callback[http://localhost:23181/subscriberWithNoPathInAnnot] for topic[http://one.websub.topic.com]: Something wrong with the connection  
[2020-05-31 04:51:23,572] SEVERE {org.ballerinalang.test.service.websub.basic.WebSubContentTypeSupportTestCase} - [1mtestAuthenticatedJsonContentReceiptForInternalHub: [31m[1mFAILED -> Timeout expired waiting for matching log: JSON WebSub Notification Received by websubSubscriber: {"action":"publish", "mode":"internal-hub"}[0m `

Below is the complete log and [the link](https://scans.gradle.com/s/nl4n2jei5w2ug) has the gradle build scan summery.
[log-websub.txt](https://github.com/ballerina-platform/ballerina-lang/files/4707351/log-websub.txt)

**Comment by Bhashinee** [comment] 2020-10-25 08:59
Closing the issue as these are enabled now

**Closed by Bhashinee** 2020-10-25 08:59 UTC
Labels: Component/IntegrationTest, Component/WebSub, Priority/Blocker, Team/StandardLibs, Type/TestFailure
