### ISSUE TITLE
[Transaction] If block is executed even when the condition is false when debugging transactions 

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6281] opened 2018-04-03 10:41 UTC
<a href="https://github.com/dilinisg"><img src="https://avatars2.githubusercontent.com/u/1845370?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Sep 04, 2017 at 15:35 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/3008_

----

Pack - 04/09

The following program runs correctly. But, when debugging, the If block is executed even when the condition is false in transactions and then committed and aborted blocks are executed. The behaviour is wrong.

```
import ballerina.data.sql;
import ballerina.lang.system;

function main (string[] args) {
    sql:ConnectionProperties properties = {maximumPoolSize: 1};
    sql:ClientConnector db = create sql:ClientConnector (sql:MYSQL, "localhost", 3306, "test1", "root", "password", properties);
    transaction {
        sql:Parameter[] parameters = [];
        int i = db.update("INSERT INTO `students` values (1, 'Dilini')", parameters);
        system:println("Inserted count:" + i);
        if (i == 0) {
            abort;
        }
        } failed {
        system:println("Failed..");
        retry 3;
        } aborted {
        system:println("Transaction aborted..");
    } committed {
        system:println("Transaction committed...");
    }
}
```

**Comment by uthaiyashankar** [comment] 2018-04-03 10:41
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Wednesday Sep 06, 2017 at 06:21 GMT_

----

This need to be tested on ballerina core level hence created a issue on ballerina core.
Please refer: https://github.com/ballerinalang/ballerina/issues/3281

**Comment by hevayo** [comment] 2018-05-14 09:59
Duplicate of #3281

**Closed by hevayo** 2018-05-14 09:59 UTC
Labels: Debugger, Imported, Priority/Highest, Severity/Critical, Type/Bug, component/Composer
