### ISSUE TITLE
Compiler crashes in let-expr for transactional-expr

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#35042] opened 2022-02-11 11:46 UTC
**Description:**
$subject

**Steps to reproduce:**
```ballerina
public function main() {
    io:println(let null _ = null in transactional);
}
```
**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

<details>
  <summary>Stack trace.(Click to expand)</summary>

```
[2022-02-11 17:12:07,876] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.TransactionDesugar.getInternalTransactionModuleInvokableSymbol(TransactionDesugar.java:668)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7651)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTransactionalExpr.accept(BLangTransactionalExpr.java:40)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7301)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1416)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1549)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1543)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:63)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:8065)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1452)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangLetExpression.accept(BLangLetExpression.java:60)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7301)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7301)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeConversionExpr.accept(BLangTypeConversionExpr.java:79)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8400)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:5821)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangListConstructorExpr$BLangArrayLiteral.accept(BLangListConstructorExpr.java:104)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExprs(Desugar.java:8400)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteInvocation(Desugar.java:6406)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6346)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangInvocation.accept(BLangInvocation.java:126)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:8367)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3438)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangExpressionStmt.accept(BLangExpressionStmt.java:51)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8380)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8386)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1317)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1359)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8393)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:795)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8342)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:454)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:453)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:390)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:159)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:137)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:182)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)

```
</details>

**Comment by MaryamZi** [comment] 2022-03-03 03:37
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/33087.

**Closed by MaryamZi** 2022-03-03 03:37 UTC
Labels: Type/Bug, Team/CompilerFE, Crash, Reason/Other
