### ISSUE TITLE
[Improvement]: Support dependant type inference based on future type

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-lang#43177] opened 2024-07-26 06:25 UTC
### Description

My requirement is to invoke an HTTP resource asynchronously. 

What I've tried was, 
```
future<CentralDocResp|error> resp = start bCentralApi->get("docs/" + libName);
````

This gives the following error.
```
incompatible type for parameter 'targetType' with inferred typedesc value: expected 'typedesc<(ballerina/http:2.11.3:Response|anydata|stream<ballerina/http:2.11.3:SseEvent,error?>)>', found 'typedesc<future<(wso2/ballerina_copilot.retrieve.central:0.1.0:CentralDocResp|error)>>'
```

If we are not supported dependant types for futures, one way would be to pass the targetType explicitly. but that also doesn't work properly because of a separate issue. 
https://github.com/ballerina-platform/ballerina-lang/issues/43178

As of now, we will need the following workaround to make this happen. 
```
future<CentralDocResp|error> resp = start getDocFromCentral("ballerinax/hello");

function getDocFromCentral(string libName) returns CentralDocResp|error {
    CentralDocResp resp = check bCentralApi->get("docs/" + libName);
    return resp;
}
```

I feel like this requirement is straightforward and frequent.  Would it be possible for the compiler to figure out dependant type based on the future type? Not sure if this is the right approach tho. 

### Related area

-> Compilation

**Comment by MaryamZi** [comment] 2024-07-26 07:48
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/38482. I'm not entirely sure if this needs to be supported, but the error is incorrect anyway. 

Passing the argument explicitly is the workaround, but looks like the future value's type uses the wider type causing the other issue (transferred to the lang repo - https://github.com/ballerina-platform/ballerina-lang/issues/43178).

We can use https://github.com/ballerina-platform/ballerina-lang/issues/38482 to track the original issue anyway.

**Closed by MaryamZi** 2024-07-26 07:48 UTC
Labels: Type/Improvement, Status/Duplicate, Team/CompilerFE, Reason/Other, userCategory/Compilation
