### ISSUE TITLE
Wrong byte-code generated for type reference types

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#34341] opened 2021-12-15 09:15 UTC
Wrong byte-code generated for `handle` related code

```
[fail] testStmtFuncCallWithLiterals:

    java.lang.VerifyError: Bad invokespecial instruction: current class isn't assignable to reference class.
        Exception Details:
        Location:
        wso2/nballerina$0046jni$0046llvm/0/$value$Function.init(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/internal/values/HandleValue;ZLjava/lang/Object;ZLio/ballerina/runtime/api/values/BObject;Z)Ljava/lang/Object; @102: invokespecial
        Reason:
        Error exists in the bytecode
        Bytecode:
        0000000: 2bb4 0019 9900 07b8 001f bf01 3a08 0937
        0000010: 0901 3a0b 013a 0c01 3a0d 0336 0e2b b400
        0000020: 239d 00a3 150e ab00 0000 00ed 0000 0005
        0000030: 0000 0000 0000 0032 0000 0001 0000 0048
        0000040: 0000 0002 0000 0086 0000 0003 0000 008e
```

steps reproduce
1) Check out nballerina repo at https://github.com/ballerina-platform/nballerina/commit/896fa4f8627ff9f36d20004937cf86ded9c7800d.
2) Run
```
cd llvm_jni
./gradlew testBuild
cd ../testbuild
bal test
```

Affected version: SL beta 6

**Comment by Nadeeshan96** [comment] 2021-12-17 04:16
This error can be reproduced by the following code snippet.

```bal
public function main() {
    Function fn = new ("llvmFunction");
}

public type FunctionDecl Function;

public class Function {
    string functionName;
    function init(string functionName) {
        self.functionName = functionName;
    }  
}
```

**Comment by manuranga** [comment] 2021-12-17 04:23
Does this mean this is not related to `handle`?

**Comment by Nadeeshan96** [comment] 2021-12-17 04:44
> Does this mean this is not related to `handle`? If so can you please change the title.

Yes, when we checked this was caused due to type reference after having `public type FunctionDecl Function;` type definition code line. Currently I do not have Github permission to change the title, we will change later.

**Comment by pcnfernando** [comment] 2022-01-05 06:42
Verified the https://github.com/ballerina-platform/ballerina-lang/pull/34468 fix on [nballerina ](https://github.com/ballerina-platform/nballerina/commit/896fa4f8627ff9f36d20004937cf86ded9c7800d.)

3 tests were failing related to parsing. Clarified from @heshanpadmasiri @Nadeeshan96 as they are not related to jbal.

**Comment by hasithaa** [comment] 2022-01-05 17:38
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34468

**Closed by hasithaa** 2022-01-05 17:38 UTC
Labels: Type/Bug, Priority/Blocker, Team/CompilerFE
