### ISSUE TITLE
[Bug]: NPE in compilation when using a grpc:Caller inside a `forEach` in a dynamic listener 

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-lang#37660] opened 2022-09-07 05:11 UTC
### Description

In a case as below,
```ballerina
import ballerina/grpc;

isolated function getReflectionService() returns grpc:Service {
    grpc:Service reflectionService = @grpc:ServiceDescriptor {descriptor: ROOT_DESCRIPTOR_REFLECTION} isolated service object {
        remote function ServerReflectionInfo(ServerReflectionServerReflectionResponseCaller caller,
                    stream<ServerReflectionRequest, grpc:Error?> clientStream) returns error? {
            check clientStream.forEach(function(ServerReflectionRequest req) {
                if req.file_containing_symbol !is () {
                    FileDescriptorResponse[] response = [];
                    response.forEach(function(FileDescriptorResponse fdr) {
                        checkpanic caller->sendServerReflectionResponse({
                            valid_host: req.host,
                            original_request: req
                        });
                    });
                }
            });
        }
    };
    return reflectionService;
}
```

Following NPE occures when doing `bal build`.
```
[2022-09-07 10:23:16,239] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.getJVMIndexOfVarRef(JvmInstructionGen.java:1289)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.loadVar(JvmInstructionGen.java:1995)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateFPLoadIns(JvmInstructionGen.java:1725)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmInstructionGen.generateInstructions(JvmInstructionGen.java:2151)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmCodeGenUtil.getLastScopeFromBBInsGen(JvmCodeGenUtil.java:563)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateBasicBlocks(MethodGen.java:477)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.genJMethodForBFunc(MethodGen.java:237)
        at org.wso2.ballerinalang.compiler.bir.codegen.methodgen.MethodGen.generateMethod(MethodGen.java:163)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmValueGen.createObjectMethods(JvmValueGen.java:623)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmValueGen.createObjectValueClass(JvmValueGen.java:583)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmValueGen.lambda$generateValueClasses$0(JvmValueGen.java:222)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmValueGen.generateValueClasses(JvmValueGen.java:216)
        at org.wso2.ballerinalang.compiler.bir.codegen.JvmPackageGen.generate(JvmPackageGen.java:799)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:96)
        at org.wso2.ballerinalang.compiler.bir.codegen.CodeGenerator.generate(CodeGenerator.java:71)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:309)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:473)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:381)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:165)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:134)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:112)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:111)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:122)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:252)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

This doesnt fail when one `forEach` is removed or the `caller->sendServerReflectionResponse` statement is removed.

### Steps to Reproduce

Extract the following zip and do a `bal build`
[grpc_reflection_client.zip](https://github.com/ballerina-platform/ballerina-lang/files/9502884/grpc_reflection_client.zip)

### Affected Version(s)

2201.1.1
2201.2.0-rc

### Labels

CompilerFE

**Comment by gabilang** [comment] 2022-09-15 04:55
The issue can be reproduced with the following code.
```ballerina
public type Obj object {
};

public class Foo {
    function fooFunc() {
    }
}

function getFooObj() returns Obj {
    Obj refObj = object {
        function info(Foo foo, stream<int, error?> s) returns error? {
            check s.forEach(function(int j) {
                int[] arr = [];
                arr.forEach(function(int i) {
                    foo.fooFunc();
                });                 
            });
        }
    };
    return refObj;
}
```
It seems the the issue is arising due to a bug in calculating resolved level of closure variables for the cases similar to above.

**Comment by gabilang** [comment] 2022-09-22 03:32
Removing `jBallerina` label since need to be fixed from closure desugar.

**Comment by gabilang** [comment] 2022-11-01 07:27
It looks like the issue has been fixed in master by some other PR.

**Closed** 2023-06-09 08:41 UTC
Labels: Type/Bug, Team/CompilerFE, Points/1
