### ISSUE TITLE
Invalid diagnostic position for invalid error constructor positional args

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#28613] opened 2021-02-12 06:42 UTC
**Description:**
```ballerina
public function main() {
    error e = error("hi", error("hi"), "c", "d");
}
```

Output:
```
ERROR [main.bal:(2:27,2:38)] additional positional arg in error constructor
ERROR [main.bal:(2:27,2:38)] additional positional arg in error constructor
```

![Screenshot 2021-02-12 at 12 10 12](https://user-images.githubusercontent.com/1496990/107737894-8528d880-6d2b-11eb-878b-ec6d36b41c13.png)

**Steps to reproduce:**

**Affected Versions:**
Swanlake alpha 1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lochana-chathura** [comment] 2021-04-02 12:51
Duplicate of #24765. 
This is a known issue when giving diagnostics for the invalid nodes.

**Closed by lochana-chathura** 2021-04-02 12:51 UTC
Labels: Area/Diagnostics, Area/Parser, Team/CompilerFE, Type/Bug
