### ISSUE TITLE
Type guard type suggestions are not supported 

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13765] opened 2019-02-21 15:01 UTC
**Description:**
Type guard type suggestions are not supported 

![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/10986966/53178256-867d0a00-3617-11e9-9e46-6ec848df665b.gif)

**Comment by nadeeshaan** [comment] 2019-06-23 11:10
type guard is supported via the snippet suggestion when the variable name is typed. This is by design and hence closing the issue

**Closed by nadeeshaan** 2019-06-23 11:10 UTC
Labels: Area/Tooling, Component/LanguageServer, Type/Bug
