### ISSUE TITLE
Incorrect type information with AST

### ISSUE THREAD

**Issue by nadheesh** [ballerina-platform/ballerina-lang#21766] opened 2020-03-14 07:33 UTC
**Description:**
Some of the Client type variables are assigned the type "other", when building the AST. Moreover, the invocations using those objects have null symbols. 

**Steps to reproduce:**

```
import wso2/sfdc46;

public const string SF_URL = "https://ap15.salesforce.com";
sfdc46:Client salesforceClient = new(SF_URL);
sfdc46:SalesforceBulkClient sfBulkClient = salesforceClient->createSalesforceBulkClient();
```

**Affected Versions:**
v1.2.1-SNAPSHOT at least

**Comment by pubudu91** [comment] 2020-03-14 09:06
Is the sales force connector migrated to 1.2.0-SNAPSHOT?

**Comment by hasithaa** [comment] 2020-03-14 15:30
The above program generates the following errors. 
```
error: .::test.bal:1:1: cannot resolve module 'wso2/sfdc46'
error: .::test.bal:4:1: undefined module 'sfdc46'
error: .::test.bal:4:1: unknown type 'Client'
error: .::test.bal:5:1: undefined module 'sfdc46'
error: .::test.bal:5:1: unknown type 'SalesforceBulkClient'
error: .::test.bal:5:44: invalid remote function invocation, expected an client object
```

This is happening because 1.2.0 compiler can't resolve the module'wso2/sfdc46'. This module compiled on the 2019R3 spec version, which is not compatible with 1.2.0 compiler. So from the semantic analysis phase above generated errors are expected. So it is not a bug. However, this is a UX issue:

1) The error message is not helpful for the user. We need to improve this. 
2) LS (VSCode) code suggestion "pull module" completes successfully. But the issue still exists. Initially, this confused me. So users too. @nadeeshaan we need to handle this case in LS as well.

**Comment by nadeeshaan** [comment] 2020-03-14 15:37
> The above program generates the following errors.
> 
> ```
> error: .::test.bal:1:1: cannot resolve module 'wso2/sfdc46'
> error: .::test.bal:4:1: undefined module 'sfdc46'
> error: .::test.bal:4:1: unknown type 'Client'
> error: .::test.bal:5:1: undefined module 'sfdc46'
> error: .::test.bal:5:1: unknown type 'SalesforceBulkClient'
> error: .::test.bal:5:44: invalid remote function invocation, expected an client object
> ```
> 
> This is happening because 1.2.0 compiler can't resolve the module'wso2/sfdc46'. This module compiled on the 2019R3 spec version, which is not compatible with 1.2.0 compiler. So from the semantic analysis phase above generated errors are expected. So it is not a bug. However, this is a UX issue:
> 
> 1. The error message is not helpful for the user. We need to improve this.
> 2. LS (VSCode) code suggestion "pull module" completes successfully. But the issue still exists. Initially, this confused me. So users too. @nadeeshaan we need to handle this case in LS as well.

I think, after the pull module execution we have to clear the cached compiler contexts and re-initialize tthem. But, for the moment the workaround would be to reload the window. We'll address this issue

**Comment by pubudu91** [comment] 2020-03-15 14:36
Should we even be pulling the module from Central if the versions are incompatible? IIRC @warunalakshitha faced the same issue as well. When trying to compile, it successfully pulls a module from Central and gives the above errors on being unable to resolve the module.

**Comment by hasithaa** [comment] 2021-03-17 12:08
With SwanLake we have introduced new Compiler APIs to handle this use case and we are no longer planning to fix this in 1.x
Hence I am closing this issue

**Closed by hasithaa** 2021-03-17 12:08 UTC
Labels: Area/Compiler, Area/Diagnostics, Team/CompilerFE, Team/DevTools, Team/Tooling, Type/Bug
