### ISSUE TITLE
JSON to record conversion should fail if there's no equivalent fields in json

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#9343] opened 2018-07-03 05:45 UTC
**Description:**
JSON to Record conversion does not fail when there are no equivalent record fields in the JSON.
The following code runs without any issue but in reality it should throw an error:

```
import ballerina/io;

type event record{
    boolean ^"left";
    boolean ^"right";
    boolean up;
    boolean down;
};
function main(string... args) {
   json val = {"hello":"world"};
   event data = check <event>val;
    io:println(data);
}
```

**Comment by SupunS** [comment] 2018-07-06 03:43
This is not a bug, but rather intended behavior. Hence removing the tag.

However, we may have to revisit this behavior, with the open/closed records.

**Comment by warunalakshitha** [comment] 2019-01-02 16:20
This will produce an error with new convert method added with 0.990.0 version.

`type event record{
    boolean ^"left";
    boolean ^"right";
    boolean up;
    boolean down;
};

public function main (string... args) {
   json val = {"hello":"world"};
   event|error data =  event.convert(val);
    io:println(data);

}`

This is because we can not stamp JSON to record if there is no equivalent fields in json. following sample will work without any issue.

`
public function main (string... args) {
   json val = {"left":true,"right":false,"up":true,"down":false };
   event|error data =  event.convert(val);
    io:println(data);
}`

**Comment by warunalakshitha** [comment] 2019-01-15 11:55
Closing the issue with above comment.

**Closed by warunalakshitha** 2019-01-15 11:55 UTC
Labels: Component/Compiler, Severity/Major, Type/Task
