### ISSUE TITLE
When default module using a config declared in `Config.toml` without specifying the module name in `Config.toml` throws an error when running the package

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-lang#29427] opened 2021-03-23 08:13 UTC
**Description:**
The module name should be optional for default module when declaring configs in `Config.toml`.
But when running the ballerina package using `bal run` command, the following error will print.
```
$ bal run

Compiling source
	pramodya/simpleDbDataLoader:0.1.0

Creating bala
	target/bala/pramodya-simpleDbDataLoader-any-0.1.0.bala

Running executable

error: [Config.toml:(2:1,2:33)] invalid module structure found for module 'simpleDbDataLoader'. Please provide the module name as '[simpleDbDataLoader]'
```

Config.toml
```toml
csvPath = "./files/contacts.csv"
```

main.bal
```ballerina
import ballerina/log;
import ballerina/io;

configurable string csvPath = ?;

public function main() returns error? {
    stream<string[], io:Error>|error|() readCsvResult = readCsv(csvPath);
    if readCsvResult is stream<string[], io:Error> {
        Contact[] students = getStudents(readCsvResult);
    } else {
        if readCsvResult is error {
            log:printError("Reading csv failed", 'error = readCsvResult);   
        } else {
            log:printError("Reading csv failed");   
        }
    }
}

function readCsv(string path) returns stream<string[], io:Error>|error? {
    stream<string[], io:Error> readCsv = check io:fileReadCsvAsStream(path);
    return readCsv;
}

function getStudents(stream<string[], io:Error> readCsv) returns Contact[] {
    Contact[] contacts = [];
    error? forEach = readCsv.forEach(function(string[] row){
        Contact contact = getContact(row);
        contacts[contacts.length()] = contact;
    });
    return contacts;
}
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment] 2021-03-24 03:54
Related to issue #28999

**Comment by riyafa** [comment] 2021-04-05 08:00
This is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/28999

**Closed by riyafa** 2021-04-05 08:00 UTC
Labels: Lang/Configurable, Team/jBallerina, Type/Bug, Version/SLAlpha3
