### ISSUE TITLE
[debugger] `EXIT` message sent when a single worker exits

### ISSUE THREAD

**Issue by roonyh** [ballerina-platform/ballerina-lang#5216] opened 2018-03-13 23:52 UTC
**Description:**

In a case like this,

```ballerina
import ballerina.io;
function main (string[] args) {
    worker aWorker {
        io:println("a worker");  // breakpoint
        io:println("done");
    }    
    
    worker anotherWorker {
        io:println("another worker"); // breakpoint
        io:println("done");
    }
    
    worker someOtherWorker {
        io:println("some other worker"); // breakpoint
        io:println("done");
    }
}
```
All three workers will stop at breakpoints but when a single worker is resumed and it exits, the debug server sends an `EXIT` messege and shuts down.

**Comment by NipunaRanasinghe** [comment] 2020-07-01 07:11
Closing as the issue is no longer valid with the new jballerina debugger implementation.

**Closed by NipunaRanasinghe** 2020-07-01 07:11 UTC
Labels: Area/Tooling, Component/Debugger, Component/JVMCodeGen, Type/Bug
