### ISSUE TITLE
Variable doesn't get narrowed down within the loop

### ISSUE THREAD

**Issue by isuruRuhu** [ballerina-platform/ballerina-lang#40643] opened 2023-06-08 11:28 UTC
### Description

I get the following error `invalid attempt to assign a value to a variable narrowed outside the loop` for the following code segment

```
string? emailContent = emailTemplatesMap[mailType.toString()];
            string? emailSubject = emailTemplatesMap[mailType.toString() + EMAIL_SUBJECT_SUFFIX];
            if emailSubject is () || emailContent is () {
                log:printError("error occurred while reading the templates associated with mailType : " + mailType.toString());
                createErrorResponse(res, "error while sending the email. email type not found");
            } else {
                emailSubject = re `\$environment`.replace(<string>emailSubject, environment);
                foreach var [k, v] in modifications.entries() {
                    string:RegExp pattern = check regexp:fromString("\\" + TEMPLATE_PREFIX + <string>k);
                    emailSubject = pattern.replace(<string>emailSubject, <string>v);
                    emailContent = pattern.replace(<string>emailContent, <string>v);
                }
                // send email
                email:Error? response = check smtpClient->send(to = recipient, subject = <string>emailSubject, 'from = sender, body = "", options = {htmlBody: emailContent, cc: ccRecipient});
                if (response is email:Error) {
                    string errMsg = response.message();
                    log:printError("error while sending the email: " + errMsg);
                    createErrorResponse(res, errMsg);
                }
```

I get the error for the following two lines
<img width="492" alt="Screenshot 2023-06-08 at 16 57 36" src="https://github.com/ballerina-platform/ballerina-lang/assets/45358089/3e14c914-6419-48cd-badc-b684fc925ebf">

### Related area

-> Compilation

**Comment by MaryamZi** [comment] 2023-06-08 12:37
This is not a bug. Assigning a value to a type-narrowed variable resets the narrowing. Therefore, using a type-narrowed variable in a loop and updating it could lead to type compatibility errors if allowed.

For example, if within the foreach loop one of the variables was used as a `string`, on subsequent iterations it may not or may not be a string.

```ballerina
        foreach var [k, v] in modifications.entries() {
            string content = emailContent;

            // ...
            emailContent = pattern.replace(<string>emailContent, <string>v); // although a string value is assigned type is reset to `string?`. Can also assign nil here.
        }
```

Therefore, we disallow assigning to narrowed variables within loops. You could use a separate variable of the narrowed type.

**Comment by MaryamZi** [comment] 2023-06-13 09:54
Closing this since it is the expected behaviour. Please reopen if you have any concerns.

**Closed** 2023-06-30 05:17 UTC
Labels: Type/Question, Team/CompilerFE, userCategory/Compilation
