### ISSUE TITLE
Multiple Services Observability Scenario Using High CPU

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#22820] opened 2020-04-21 14:53 UTC
In the multiple service interaction scenario defined here: https://github.com/lafernando/samples/tree/master/ballerina/ecommerce. The CPU usage for the billing, shipping, and the ordermgt services CPU usage is kept in a very high level (~200%) even after requests have finished publishing, and even after we shutdown the Prometheus server. For some reason, those processes keeps consuming lots of CPU. 

The request simulation can be done with the following command:
ballerina run target/bin/simulator.jar 100 1000

We don't need 1000 requests to be published, but we can see the CPU usage rise after starting the publishing. We can stop the publishing, and kill Prometheus, but the CPU utilization would still be high. 

Similar behavior is observed with just metrics enabled (tracing disabled), i.e. services run similar to following:
``` bash
ballerina run target/bin/cart.jar --b7a.observability.metrics.enabled=true --b7a.observability.metrics.prometheus.port=9797
```
![x](https://user-images.githubusercontent.com/2379767/79881262-d5ead180-83a5-11ea-8640-089fb867aa1a.png)

**Comment by madushajg** [comment] 2021-07-16 15:03
This issue happened due to heavy string concatenation operations performed at the metric reporter[1]. 

We reproduced the issue in Ballerina 1.2.13 and identified the string concatenation as the culprit by referring to the JFRs with Prometheus scraping[2] and without Prometheus scraping [3].

We were also able to reproduce this in Ballerina SL Beta2 by migrating the eCommerce service to Ballerina SL Beta2 [4].

The fix is done for **Ballerina SL Beta2** and below are the flame graphs observed before the fix[5] and after the fix[6].

Before the fix:
![Screenshot 2021-07-15 at 23 08 02](https://user-images.githubusercontent.com/26219651/125833344-ee67710f-c7b8-4565-bbfc-9c7f6b6afa9a.png)

After the fix:
![Screenshot 2021-07-15 at 22 46 30 (2)](https://user-images.githubusercontent.com/26219651/125833204-e7941e5f-8468-4229-a9e8-2e31b89d0801.png)

Observed the following after the fix [7].

1. The CPU utilization of affected services reduced (However still using a considerable amount of CPU due to the larger number of metrics)
2. When we stop the Prometheus server, the CPU usage is reduced immediately
3. Even after the simulator finished sending requests, the CPU usages remain the same until the Prometheus server is scraping metics.

Closing this issue since the reported issues have been fixed.

[1] https://github.com/ballerina-platform/module-ballerinax-prometheus/blob/2b33c5eeef9e6399523edf60985ddbfd2b7396b6/prometheus-extension-ballerina/metric_reporter.bal#L62-L101
[2] https://drive.google.com/file/d/1JKzuzQ5zxhgEsmrqYIts8acG7lQYEMtm/view?usp=sharing
[3] https://drive.google.com/file/d/11lG6H-GAYTfPmdCb8rFlJR_AZKgiVMlb/view?usp=sharing
[4] https://github.com/madushajg/ecommerce-service/tree/with-prometheus-beta2
[5] https://drive.google.com/file/d/1Kv4bFd2Wkzsv4wghuvTi63VaPnJiOrdG/view?usp=sharing
[6] https://drive.google.com/file/d/1vlQqYdbw_J7c_GWpFwocCapSXZimd7Qq/view?usp=sharing
[7] https://github.com/ballerina-platform/module-ballerinax-prometheus/pull/96

**Closed by madushajg** 2021-07-16 15:03 UTC
Labels: Priority/Blocker, Team/Observability, Type/Bug
