### ISSUE TITLE
Bad sad when applying Unary negation to a byte variable

### ISSUE THREAD

**Issue by rpjayasekara** [ballerina-platform/ballerina-lang#32926] opened 2021-09-27 08:00 UTC
**Description:**
$title

**Steps to reproduce:**
```
public function main() {
    byte a = 1;
    int e = -a;
}

```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Nadeeshan96** [comment] 2021-09-27 08:57
Duplicate of #31826

**Closed** 2021-09-27 10:02 UTC
Labels: Type/Bug, Area/Compiler, Team/CompilerFE, Error/TypeI, Lang/Expressions/Unary
