### ISSUE TITLE
Import command crashes 

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#27926] opened 2021-01-18 16:02 UTC
**Description:**

```Ballerina
import ballerina/float;
//import ballerina/lang.'float as float;
```

```LogTalk
 
[2021-01-18 20:57:06,893] SEVERE {b7a.log.crash} - java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:825)
        at org.ballerinalang.central.client.CentralAPIClient.getPackageVersions(CentralAPIClient.java:196)
        at io.ballerina.projects.internal.repositories.RemotePackageRepository.getPackageVersions(RemotePackageRepository.java:115)
        at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolveFromRepository(DefaultPackageResolver.java:134)
        at io.ballerina.projects.internal.environment.DefaultPackageResolver.resolvePackages(DefaultPackageResolver.java:79)
        at io.ballerina.projects.PackageResolution.createDependencyGraphFromSources(PackageResolution.java:237)
        at io.ballerina.projects.PackageResolution.getDependencyGraphWithPackageDescriptors(PackageResolution.java:197)
        at io.ballerina.projects.PackageResolution.buildDependencyGraph(PackageResolution.java:132)
        at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:59)
        at io.ballerina.projects.PackageResolution.from(PackageResolution.java:66)
        at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:174)
        at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:80)
        at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:167)
        at io.ballerina.projects.Package.getCompilation(Package.java:117)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:153)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
        ... 20 more
```

**Steps to reproduce:**

**Affected Versions:**
SwanLake

**OS, DB, other environment details and versions:**
macOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hemikak** [comment] 2021-02-17 04:43
Hi @KRVPerera,

Which  swan lake release was this ?

**Comment by hemikak** [comment] 2021-02-17 04:46
Please check again if issue still persists.

**Comment by KRVPerera** [comment] 2021-02-17 04:51
I am seeing this in `slalpha2` pack as well.

**Comment by hemikak** [comment] 2021-02-18 17:09
Can you attach the example.bal file ?

**Comment by KRVPerera** [comment] 2021-03-04 07:49
Tested on 
Ballerina Swan Lake Alpha 2
Language specification v2020-12-17
Update Tool 0.8.20

[t7.bal.zip](https://github.com/ballerina-platform/ballerina-lang/files/6081720/t7.bal.zip)

**Comment by azinneera** [comment] 2021-06-23 06:55
Blocked on #31211

**Comment by Ibaqu** [comment] 2021-12-14 07:47
I have tested this with `build` and `run` and it doesnt seem to be reproducible in the current Beta 6 pack

Tested on : 
```
Ballerina Swan Lake Beta 6
Language specification 2021R1
Update Tool 1.3.6
```

```
PS D:\Documents\Workspace\BallerinaProject\t7bal> bal build .\t7.bal
Compiling source
        t7.bal
ERROR [t7.bal:(1:1,1:24)] cannot resolve module 'ballerina/ as float'
ERROR [t7.bal:(1:18,1:18)] missing as keyword
ERROR [t7.bal:(1:18,1:18)] missing identifier
error: compilation contains errors
```
--
```
PS D:\Documents\Workspace\BallerinaProject\t7bal> bal run .\t7.bal
Compiling source
        t7.bal
ERROR [t7.bal:(1:1,1:24)] cannot resolve module 'ballerina/ as float'
ERROR [t7.bal:(1:18,1:18)] missing as keyword
ERROR [t7.bal:(1:18,1:18)] missing identifier
error: compilation contains errors 
```

**Comment by Ibaqu** [comment] 2021-12-14 08:04
LS seems to behaving normally despite having `import ballerina/float` with no exceptions in the output tab. The suggestions also continue to work

**Comment by Ibaqu** [comment] 2021-12-14 08:09
Closing issue since this does not seem to be reproducible

**Closed by Ibaqu** 2021-12-14 08:09 UTC
Labels: Type/Bug, Priority/Blocker, Team/DevTools, SwanLakeDump, Area/ProjectAPI
