### ISSUE TITLE
incorrect snippet for typeguard 

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#17820] opened 2019-08-15 16:53 UTC
**Description:**

**Steps to reproduce:**
add  variable named `a` type of `any|error`. add a type guard.
```
    if (a is error) {
        
    } else  else {
        
    }
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaviththiranga** [comment] 2019-08-16 05:20
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/17796

**Closed by kaviththiranga** 2019-08-16 05:20 UTC
Labels: Area/Tooling, Component/LanguageServer
