### ISSUE TITLE
Incorrect ordering of braces in the completion item

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-lang#34868] opened 2022-01-27 07:08 UTC
**Description:**

Please refer to the screen recording below.

https://user-images.githubusercontent.com/27485094/151290303-219313ac-0434-46ac-8c67-75fad25d5764.mov

**Steps to reproduce:**
```
type Person record {|
    string name;
    int age;
|};
type TableRec record {|
    table<Person> personTable;
|};
TableRec  t = {person<cursor>}; // Insert completion item for personTable here
```
**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake) RC2

**Comment by IMS94** [comment] 2022-02-24 08:02
VSCode suggests to escape `$`, `\` and `}` characters in placeholders with `\` (https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar). Though it was implemented, couldn't achieve the expected behavior. Need to dig deep.

**Comment by IMS94** [comment] 2022-03-01 11:29
When investigated, it was noticed that the response from LS contains 4 back slashes instead of 1 as below:
```json
    {
        "label": "personTable",
        "kind": 5,
        "detail": "TableRec.personTable",
        "sortText": "K",
        "insertText": "personTable: ${1:table [{name: \"\", age: 0\\\\}]}",
        "insertTextFormat": 2
    },
```
Found out that the cause for these additional `\` is the post processing step in `CompletionUtil.getCompletionItems()` at:
```java
return items.stream()
                .map(LSCompletionItem::getCompletionItem)
                .peek(CompletionUtil::processCompletionItems)
                .collect(Collectors.toList());
```

**Comment by IMS94** [comment] 2022-03-01 11:29
This will automatically be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/35137. Marking as blocked for now.

**Comment by IMS94** [comment] 2022-03-02 10:37
I tried applying #35137 locally and it still did not solve the issue, since in this case the default value is still `table [{}]`. Note the closing `}` inside the brackets. Therefore, I tried an alternative approach in #35224.

**Closed** 2022-03-11 08:47 UTC
Labels: Type/Bug, Team/LanguageServer, Points/1, Area/Completion, GA-Test-Hackathon, Reason/Complex
