### ISSUE TITLE
Improve error message .ballerina creation fails

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#20026] opened 2019-11-22 09:04 UTC
**Description:**
Once .ballerina folder ownership changed for current user (Runs in sudo). If user tries to run it again it shows as unable to create target directory. This message has to be improved by checking .ballerina permission and prompt the permission issue.

`error: unable to create target directory: <source location>/target`

**Comment by snow6oy** [comment] 2019-11-22 09:11
As the user who stumbled across this, I can testify that it took a few days to resolve. This was because a side-effect of running ballerina under sudo is that $DOCKER environment mysteriously stops working. When this is the initial symptom you have to backtrack quite a few steps to get to the cause.

**Comment by pramodya1994** [comment] 2022-03-28 09:08
We had this `checkWritePermission(..)` method in `ProjectUtils`, and we removed that in this [commit](https://github.com/ballerina-platform/ballerina-lang/commit/1f34d462647).
@azinneera What was the reason to remove that? and shall we add similar functionality here?

**Comment by pramodya1994** [comment] 2022-03-29 09:43
In the new project API implementation, we are creating the ballerina user home using `BallerinaUserHome` class.
There we are checking permission by catching `AccessDeniedException`, and throwing it with an appropriate error message in [1]. Hense, closing this issue.
```
ballerina: permission denied to create the directory: /Users/pramodya/.ballerina/repositories
```

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/environment/BallerinaUserHome.java#L43

**Closed by pramodya1994** 2022-03-29 09:43 UTC
Labels: Type/Improvement, Team/DevTools, Points/0.5, SwanLakeDump, Area/ProjectAPI
