### ISSUE TITLE
vscode plugin not working remotely in WSL

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#33305] opened 2021-10-21 03:32 UTC
I tried to use the vscode plugin remotely in WSL.

Withing WSL2, I do `code .` in the nballerina/compiler directory.

I get the following errors in the output tab:

```
Active the Ballerina VS Code extension.
ballerina command _stderr: /bin/sh: 1: ballerina: not found
ballerina command err: Error: Command failed: ballerina version
/bin/sh: 1: ballerina: not found
bal command stdout: Update Tool 1.3.5
bal command _stderr: Error: Could not find or load main class VS
Caused by: java.lang.ClassNotFoundException: VS
'bal' executor is picked up by the plugin.
Ballerina version output: Update Tool 1.3.5
Error executing 'bal home'.
<---- cmd output ---->
Error: Could not find or load main class VS
Caused by: java.lang.ClassNotFoundException: VS
<---- cmd output ---->
Plugin version: 2.1.1
Ballerina version: Update Tool 1.3.5
Failed to activate Ballerina extension. Error when checking ballerina version. Ballerina version Update Tool 1.3.5 is not supported. 
                        The extension supports Ballerina Swan Lake and 1.2.x versions.
``` 

If I run `bal version` in a WSL terminal I get

```
Ballerina Swan Lake Beta 3
Language specification 2021R1
Update Tool 1.3.5
```

`bal home` shows:

```
/usr/lib/ballerina/distributions/ballerina-slbeta3
```

**Comment by anupama-pathirage** [comment] 2021-11-29 20:02
Created https://github.com/wso2/ballerina-plugin-vscode/issues/136 to track this, hence closing this issue.

**Closed by anupama-pathirage** 2021-11-29 20:02 UTC
Labels: Type/Bug

**Comment by kaviththiranga** [comment] 2022-01-04 08:33
Found the root cause: check https://github.com/ballerina-platform/ballerina-lang/issues/34496
