### ISSUE TITLE
[Bug]: Module-level variables not getting type-narrowed within the function scope

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#42028] opened 2024-01-22 06:42 UTC
### Description

Refer to the below code, which is a simplified version to reproduce the issue. 
This fails with the compilation error `operator '+' not defined for '(string|int)' and 'string'`.

```ballerina
string|int value = "foo";

function foo() {
    if value is string {
        value += "bar";
    }
}
```

### Affected Version(s)

2201.8.x

### Related area

-> Compilation

**Comment by LakshanWeerasinghe** [comment] 2024-01-22 08:43
The [spec](https://ballerina.io/spec/lang/master/#conditional_variable_type_narrowing) currently allow type narrowing for "local variable or parameter" only. Even if make this final this won't work.

**Comment by LakshanWeerasinghe** [comment] 2024-01-22 08:54
In this case a work around can be suggested,
```
string|int value = "foo";

public function main() {
    string|int v = value;
    if v is string {
        v += "bar";
    }
    io:println(v);
    io:println(value);
}
```
Here we assign the module level variable to a local variable and use it for type narrowing.

**Comment by LakshanWeerasinghe** [comment] 2024-01-22 09:18
closing since this is a duplicate of [spec issue](https://github.com/ballerina-platform/ballerina-spec/issues/1260).

**Closed by LakshanWeerasinghe** 2024-01-22 09:18 UTC
Labels: Type/Bug, Priority/Blocker, Team/CompilerFE
