### ISSUE TITLE
Sticky errors when changing the dependency versions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#36521] opened 2022-06-13 07:30 UTC
My scenario is like follows:
- There's a dependency that I use in my project. Let's say version `0.0.1`. 
- Then I add something else to that package and release `0.0.2`.
- Now I go and bump the dependency version in my project's `Ballerina.toml`.
- In the editor, I keep getting the error `unknown type` for it. But in completions, this type comes up.

Refer to the following:

https://user-images.githubusercontent.com/6260009/173302119-5a3a2475-4802-4ce7-9efa-523307026121.mov

**Comment by IMS94** [comment] 2022-06-30 04:32
Tried to reproduce this locally with multiple versions of the same package in the local repo. Couldn't reproduce this. Closing...

**Closed by IMS94** 2022-06-30 04:32 UTC
Labels: Type/Bug, Team/LanguageServer, Points/1, Reason/Invalid
