### ISSUE TITLE
Improve DataProvider 

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#31146] opened 2021-06-14 07:55 UTC
Improve DataProvider  feature in following ways

- Each test case should have a unique id. Instead of returning an array of arrays, we may leverage ballerina tables for this.
- Test output to be qualified by the unique id.
- Being able to filter by id when using the `--tests` flag. Eg: `bal test --tests testIntermediateFiles["main.ll"]`
- Rerun failed feature should only run the failed cases.

**Comment by jclark** [comment] 2021-06-14 07:59
The top priority thing is to print the unique id when running tests. Imagine you have a DataProvider that reads test cases from a directory with hundreds of test cases. Big problem at the moment is that when a test fails, you don't know which one it was.

**Comment by jclark** [comment] 2021-06-14 08:00
Another thing I noticed is that it doesn't allow the argument list to be a tuple: it only seems to support arrays. The right way to represent the argument list of a function is with a tuple.

**Comment by Dilhasha** [comment] 2021-06-16 10:39
We had a discussion and plan to implement a design as follows.

- Test provider can return a map of tuples as the data set as in the below example.

```
function stringDataProvider3() returns map<[int, int, int]> {
	map<[int, int, int]> cases = {
    		"Case1" : [1, 5, 6],
    		"Case2" : [10, 15, 25]
	};
	return cases;
}

```

- The key used in the map will act as the unique id to identify each test case. 

- The key appended to the test function name will be used in test report, test filtering using `--test` and also to identify the tests to rerun.
	E.g. testAddingValues#Case1

Appreciate your thoughts on this.
@jclark @manuranga

**Comment by manuranga** [comment] 2021-06-16 11:35
In some cases id and the data might be the same, so it'll look like:
```
function fileProvider() returns map<[string]> {
	map<[string]> cases = {
    		"input1.json" : ["input1.json"],
    		"input2.json" : ["input2.json"]
	};
	return cases;
}
```
It's ok, but bit redundant, not sure if we should special case this.

**Comment by jclark** [comment] 2021-06-16 11:53
@Dilhasha I think that's OK. The other approach is to use a table rather than a map, but that complicates things for average users. Please allow the return type to be `map<T>|error`, with error meaning that there was an error generating the data (which should be helpfully reported by testerina).

**Comment by Dilhasha** [comment] 2021-06-16 12:46
I 

> @Dilhasha I think that's OK. The other approach is to use a table rather than a map, but that complicates things for average users. Please allow the return type to be `map<T>|error`, with error meaning that there was an error generating the data (which should be helpfully reported by testerina).

@jclark +1, we'll handle the errors as requested.
@manuranga Let's see if special casing such scenarios are needed, once we have the initial implementation
 in place. WDYT?

**Comment by Dilhasha** [comment] 2021-06-16 12:57
Adding to above, 
We are also working on implementing the test engine in Ballerina. I'm currently working on a PoC based on which we will start designing the test engine in Ballerina.

It will allow users to dynamically register test cases using `test:register`. A set of data driven tests can be initialised as follows. 

```
    string[] fruits = ["apple", "banana", "cherry"];
    foreach string v in fruits {
        test:register(v + "Test", function() {
            test:assertEquals(v.length(), 6);
        });
    }
```
IMO, most of the issues with the data provider will be addressed when we have these changes in place.

**Comment by manuranga** [comment] 2021-06-18 11:53
- Map approach look ok to me
- Don't like `testAddingValues#Case1` much, I like `testAddingValues["Case1"]`. This way, if we were to support non-map case, we can json serialize the tuple and show something useful, for when a user don't give an explicit name eg: `add[1,2]`
- In the new test engine approach, how is the registration code running ? Is it in a module init function?
- Does this new approach render DataProvided redundant?

**Comment by hevayo** [comment] 2021-06-18 14:20
We found typing  `testAddingValues["Case1"]` as args for `--tests` is some what hard since you need to escape the `"`. So we will stick with the `#` sign. For data providers that return an array we will use the index as the identifire ie `testAddingValues#0, testAddingValues#1 ...` 

For the new engine we haven't thought through the full design, we will create a separate ticket on that. And yes data provider will be somewhat redundant.

**Comment by manuranga** [comment] 2021-06-18 16:01
Hmm, This is bit subjective, but I though escaping would be harder with `#`, ie if a case id has a `#` is eg `#ballerinalang vs #otherlang` it will become ambiguous. It's ok if we don't do any escaping at first, but it gives us a chance to do it later.

**Comment by Dilhasha** [comment] 2021-06-22 11:01
> Hmm, This is bit subjective, but I though escaping would be harder with `#`, ie if a case id has a `#` is eg `#ballerinalang vs #otherlang` it will become ambiguous. It's ok if we don't do any escaping at first, but it gives us a chance to do it later.

AFAIU, the same logic is valid if we are using`["`, `"]` as the separator right? The key can be something like `[Case1]` and we would end up with `["[Case1]"]`. I agree that it is subjective :)

For now, I'm closing this issue since the requested changes have been merged and will be available with Beta2. Please re-open if you think we require anymore changes.

**Comment by Dilhasha** [comment] 2021-06-23 09:44
@manuranga 

The behaviour you have mentioned is reproducible for me intermittently. While we investigate and fix the issue, you can run a specific test by giving the module name as a prefix. 

e.g. `bal test --tests nballerina.front:testParser#31`

**Comment by manuranga** [comment] 2021-06-23 10:00
The workaround works for me, thank you.

**Comment by Dilhasha** [comment] 2021-06-30 14:13
Closing this issue as all the requested improvements and issues are addressed.

**Closed by Dilhasha** 2021-06-30 14:13 UTC
Labels: Area/BuildTools, Area/Testerina, NBalNeeds, Points/2, Team/DevTools, Team/TestFramework, Type/Improvement
