### ISSUE TITLE
Prints java stacktraces when building from source

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#4484] opened 2018-01-23 11:42 UTC
**Description:**
Multiple exceptions with stacktraces similar to below, can be seen when building ballerina from source, using maven.
```
[2018-01-23 16:51:08,373] ERROR [org.ballerinalang.net.http.HttpUtil] - no matching resource found for path : /echo/bar , method : GET  
no matching resource found for path : /echo/bar , method : GET
[2018-01-23 16:51:08,374] ERROR [org.ballerinalang.net.http.HttpDispatcher] - error: no matching service found for path : /foo/message 
org.ballerinalang.connector.api.BallerinaConnectorException: no matching service found for path : /foo/message
	at org.ballerinalang.net.http.HttpDispatcher.findService(HttpDispatcher.java:74)
	at org.ballerinalang.net.http.HttpDispatcher.findResource(HttpDispatcher.java:118)
	at org.ballerinalang.test.services.testutils.Services.invokeNew(Services.java:48)
	at org.ballerinalang.test.services.ServiceTest.testServiceAvailabilityCheck(ServiceTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Affected Versions:**
0.95.8-SNAPSHOT

**OS, DB, other environment details and versions:**
jdk1.8.0_144, Maven 3.2.5

**Comment by hemikak** [comment] 2018-09-20 06:17
The above logs cannot be seen in builds as of now(20/09/2018). Refer https://travis-ci.org/ballerina-platform/ballerina-lang/builds/430662910?utm_source=github_status&utm_medium=notification. Hence closing.

**Comment by hemikak** [comment] 2018-09-20 10:32
Was not able to reproduce this issue with jdk 1.8.0_144 as well.

**Closed** 2018-09-20 10:32 UTC
Labels: Component/BVM, Resolution/Cannot Reproduce, Type/Bug
