### ISSUE TITLE
Goto definition doesn't work for xmlutils:fromJSON

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#21954] opened 2020-03-18 13:01 UTC
**Description:**

In Json to XML conversion BBE goto definition doesn't work for xmlutils:fromJSON()

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.2.0
VSCode
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment] 2020-03-18 17:11
@rdhananjaya, can you try reloading the window? This couldn't reproduce locally in the latest rc2

**Comment by rdhananjaya** [comment] 2020-03-18 17:29
This time (with a new VSCode instance) it worked.

**Comment by nadeeshaan** [comment] 2020-03-19 03:58
> This time (with a new VSCode instance) it worked.

@rdhananjaya yes, for the cache to populate successfully, it needs a new VSCode instance after installing the plugin. Hence closing the issue.

**Closed by nadeeshaan** 2020-03-19 03:58 UTC
Labels: Area/Tooling, Component/LanguageServer
