### ISSUE TITLE
Ballerina Debugger shows internal details of records in debugger window.

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-lang#29622] opened 2020-11-09 11:12 UTC
Moving issue https://github.com/wso2-enterprise/choreo/issues/1650

## Describe your problem(s)
Please see the attached screenshot.
Showing something like `instance of org.ballerinax.jdbc.table.BCursorTable(id=4788) doesn't add value when the user is debugging her program.

## Describe your solution
Shall we show the content of the record instance instead.

## Time Estimate
![image](https://user-images.githubusercontent.com/3402882/98525336-54ee1b80-229e-11eb-8bf0-0d4fc212b5b5.png)

**Comment by praveennadarajah** [comment] 2021-05-17 07:31
The above issue is not reproducible in the latest ballerina distribution:
```
Ballerina Swan Lake Alpha 5
Language specification v2020-12-17
Update Tool 1.3.3
```

Tested code sample:
```
type Employee record {
    readonly int id;
    string name;
    float salary;
};

public function main() {
    table<Employee> employeeTab = table [
      {id: 1, name: "John", salary: 300.50},
      {id: 2, name: "Bella", salary: 500.50},
      {id: 3, name: "Peter", salary: 750.0}
    ];
}
```

- Add a debug point at the end of the `main()` method and start the program in debug mode. The debug view looks as follows:
![image](https://user-images.githubusercontent.com/11292766/118448246-644b9700-b70f-11eb-8539-0f6aeec1f74d.png)

- Here the `table` type visible variable gives meaningful information to the user.

**Comment by NipunaRanasinghe** [comment] 2021-06-02 06:54
Closing since tha table variable presentation is improved with the latest debugger changes for SwanLake.

**Closed by NipunaRanasinghe** 2021-06-02 06:54 UTC
Labels: Area/Debugger, SwanLakeDump, Type/NewFeature
