### ISSUE TITLE
Confusion regarding distribution property in Ballerina.toml

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-lang#36487] opened 2022-06-09 05:44 UTC
**Description:**
All stdlibs were updated with `distribution` property in Ballerina.toml file with project API changes as mentioned in the [initial issue](https://github.com/ballerina-platform/ballerina-lang/issues/32190). However in the recent release process, we came to know that this property is overridden quietly even though it is explicitly mentioned in the toml file. 

IMO is this not the correct behaviour[[1](https://github.com/ballerina-platform/ballerina-standard-library/issues/2477#issuecomment-992122944)]. Especially in stdlibs where the distribution used to build the modules are an intermediate one. This has resulted in modules being pushed to central with distribution including `rc` flag. This was manually identified and reverted on time.

Correct behaviour should be the distribution flag should be validated and ballerina push failed if there is a mismatch, rather than simply overriding

**Comment by azinneera** [comment] 2023-02-14 05:14
The `distribution` property does not override anything. Rather it is not used anywhere. The property was designed to give a warning to the user if the distribution used for the building is lesser than the version specified by this property. The pack that is used to build is controlled by the `gradle. properties file which the standard library is already maintaining. 

Nonetheless, agree that this confuses the user and this will go away once the warning. is issued which is being tracked with https://github.com/ballerina-platform/ballerina-spec/issues/903. 

Closing this since this is not a bug.

**Closed by azinneera** 2023-02-14 05:14 UTC
Labels: Type/Bug, Priority/High, Team/DevTools, Area/ProjectAPI
