### ISSUE TITLE
No compilation error in `async send` with non-empty failure type and no subsequent `flush`/`sync send`

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-lang#36079] opened 2022-05-10 07:55 UTC
**Description:**

$title

Spec says

> If the receive-action corresponding to an async-send-action has a non-empty failure type, then it is a compile-time error unless it can be determined that a sync-send-action or a flush-action will be executed before the sending worker terminates with success.

But seems no compilation is thrown in the below code.

**Steps to reproduce:**
```bal
import ballerina/io;
import ballerina/lang.runtime;

int x = 5;
public function main() {
    worker w1  returns string {
        5 -> w2;
        io:println("w1 almost done");
        return "done"; 
    }

    worker w2 returns error? {
        runtime:sleep(2);
        x-=1;
        if(x>1) {
            return error("error at w2");
        }
        io:println("w2 receiving");
        int x = <- w1;
        io:println("w2 received " + x.toBalString());
    }

    string p = wait w1;
    io:println("wait: ", p);
}
```

**Affected Versions:**
Ballerina 2201.0.2 (Swan Lake)

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment] 2022-05-10 14:29
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/19120.

**Closed by MaryamZi** 2022-05-10 14:29 UTC
Labels: Type/Bug, Team/CompilerFE, Reason/Invalid
