### ISSUE TITLE
[LS Code Actions] "Document This" code action generates parameter documentations in a wrong order

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#29463] opened 2021-03-23 10:40 UTC
**Description:**
Please refer the below session and note that "Document this" code action generates parameter documentations in a wrong order.

![Peek 2021-03-23 15-599](https://user-images.githubusercontent.com/29032600/112133947-3b68c300-8bf2-11eb-9ce0-36c19bcabbf6.gif)

**Steps to reproduce:**
Use the sample code below and invoke "Document This" code action on top of the `partition` method.

```ballerina
import ballerina/io;

# Description  
class Partitioner {

    public function partition(string datasetFilePath, function... criterias) {
        stream<string[], io:Error>|error csvStream2 = io:fileReadCsvAsStream(datasetFilePath);
        // Loop through the stream and print the content.
        if (csvStream2 is error) {

        } else {
            error? e = csvStream2.forEach(function(string[] val) {
                                              io:println(val);
                                          });
        }
    }
}

# Description
# + return - Return Value Description  
public function main() returns error? {

}
```

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment] 2021-03-24 10:42
Duplicate of #29475. Hence Closing

**Closed by nadeeshaan** 2021-03-24 10:42 UTC
Labels: Area/CodeAction, Team/LanguageServer, Type/Bug, Version/SLAlpha3
