### ISSUE TITLE
Testarina code coverage report is skipping lines

### ISSUE THREAD

**Issue by LakshanKarunathilake** [ballerina-platform/ballerina-lang#30905] opened 2021-06-01 05:58 UTC
**Description:**
We were waiting for the test coverage in resource functions and happy to see that since alpha versions but we noticed that in the report some lines are skipping and we want to know that is affecting the code coverage. 

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/33603053/120273577-50d22b80-c2cc-11eb-816c-5aa58ec830e6.png)

![image](https://user-images.githubusercontent.com/33603053/120273624-634c6500-c2cc-11eb-82b1-7643bb357570.png)

**Affected Versions:**
Ballerina swan lake alpha 5

**Comment by Dilhasha** [comment] 2021-06-09 06:08
I was able to reproduce the above behavior in a simple Ballerina project.
https://github.com/Dilhasha/service-test-repo

**Comment by Dilhasha** [comment] 2021-06-09 11:05
We were able to reproduce the issue for above case 1 in a simple function and it seems to be an issue with the bal to java conversion because it's showing some coverage even when we generate test report using JaCoCo directly. 
Created https://github.com/ballerina-platform/ballerina-lang/issues/31061

**Comment by azinneera** [comment] 2021-06-17 07:07
Closing since this will be tracked by #31061

**Closed by azinneera** 2021-06-17 07:07 UTC
Labels: Area/Testerina, Team/TestFramework, Type/Bug
