### ISSUE TITLE
Semantic error in source files are not shown when there are errors in test sourcces

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#32967] opened 2021-09-29 10:54 UTC
**Description:**
$title

**Steps to reproduce:**
Consider a multi module project where there are two modules and tests in the modules. 
1. Add the following source snippet within a test source, where the function `xyz` is undefined.
```
function testF() {
    int x = xyz();
}
```
2. Add the following function in a source file other than a test source
```
function helloFunction() returns int {
}
```
3. Above function does not have an associated return statement, hence the compiler should complain with a semantic error.
4. In this case the compiler does not show any semantic errors.

**Affected Versions:**
SwanLake-Beta4-SNAPSHOT at least

**Comment by MaryamZi** [comment] 2022-03-02 11:44
This particular behaviour is not related to having tests. 

The behaviour is the same for a single bal file.

```ballerina
function testF() {
    int x = xyz();
}

function helloFunction() returns int {
}
```

The `undefined function 'xyz'` error is logged in the semantic analysis phase whereas the `this function must return a result` error is logged in the code analysis phase.

By design, if there are semantic errors, we don't proceed to code analysis. 

Closing this issue since it is the expected behaviour. Please reopen if this does not address the concern.

**Closed by MaryamZi** 2022-03-02 11:44 UTC
Labels: Type/Question, Priority/High, Area/Compiler, Team/CompilerFE, Reason/Invalid
