### ISSUE TITLE
Parenthesis do not get highlighted properly 

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-lang#15959] opened 2019-06-24 05:41 UTC
**Description:**
The related parenthesis do not get highlighted properly.  In VS code when we click at open `parenthesis` it highlights closing one related. 

**Steps to reproduce:**

Please see screenshot below. 

<img width="576" alt="Screen Shot 2019-06-24 at 11 06 11 AM" src="https://user-images.githubusercontent.com/4967046/59994216-b2b1a180-9670-11e9-81ee-802c141ee76f.png">

**Affected Versions:**

Plugin version: 0.991.2
Ballerina version: 0.991.0

**Comment by kaviththiranga** [comment] 2019-06-25 05:20
Seems it is not working for block level statements. It works fine on functions.

**Comment by kaviththiranga** [comment] 2019-06-25 05:50
hmm, seems for worker declarations too, it works fine. Only for if, while - it is broken.

**Comment by kaviththiranga** [comment] 2019-06-25 05:53
@roonyh, I could get it working by only providing the language configuration to vscode and skipping the textmate grammar file. (Simply commenting out grammar section from package.json contributions).

Hence I suspect this has something to do with tokenizer.

**Comment by kaviththiranga** [comment] 2019-06-25 05:53
Accidentally closed.

**Comment by kaviththiranga** [comment] 2019-06-25 07:34
Found the root cause,
https://github.com/ballerina-platform/ballerina-grammar/blob/master/syntaxes/ballerina.YAML-tmLanguage#L247
Removing above rule from grammar fixed it

**Comment by kaviththiranga** [comment] 2019-06-25 07:35
Seems this is related https://github.com/Microsoft/vscode/issues/45890

**Comment by kaviththiranga** [comment] 2019-08-30 10:43
Fixed with https://github.com/ballerina-platform/ballerina-grammar/pull/46

**Closed by kaviththiranga** 2019-08-30 10:43 UTC
Labels: Area/Tooling, Component/VScodePlugin, Type/Bug
