### ISSUE TITLE
Uninitialized variable error in match-stmt

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-lang#33517] opened 2021-10-29 12:46 UTC
**Description:**
$subject

**Steps to reproduce:**
```
function foo(int i) {
    int j;
    match i {
        3 => {
            j = 3;
        }
        _ => {
            panic error("MSG");
        }
    }
    int k = j; // error:variable 'j' may not have been initialized
}

public function main() {
}
```

**Affected Versions:**
swan-lake beta3 rc1

**Comment by MaryamZi** [comment] 2022-03-03 16:03
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/25857

**Closed as completed** 2022-03-03 16:04 UTC
Labels: Type/Bug, Priority/High, Status/Duplicate, Team/CompilerFE, Lang/Statements/Match, Reason/Invalid
