### ISSUE TITLE
XML iterator need to be update to return xml

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22135] opened 2020-03-24 07:50 UTC
**Description:**
Please refer the spec: https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/lib/xml.bal#L74

In current implementation each item is treated xml|string.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment] 2021-01-27 03:55
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/24562.

Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/26825.

**Closed by MaryamZi** 2021-01-27 03:55 UTC
Labels: Priority/High, Team/CompilerFE, Type/SpecDeviation
