### ISSUE TITLE
[Identifier Encoding] Leading/trailing spaces are not encoded when encoding quoted identifiers

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#27817] opened 2021-01-12 11:32 UTC
**Description:**
Please refer the following scenario, where we have expressions like 
1. ```foo is '\ \/\:\@\[\`\{\~\u{2324}_123_ƮέŞŢ_Student```
2. ```foo is int | string```

In the pre-processing phase of the ballerina debug expression evaluator, all the identifiers inside the user given expression will be encoded, since the debugger depends on the ballerina runtime variables. And in order to trim leading and trailing whitespaces around the expression tokens, we are doing a <string>.trim() invocation(otherwise the types we get in case 2 will be "int " and " string"). This is where the leading space of a encoded quoted identifier can get removed, which causes potential bugs in the identifier encoding depended implementations.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment] 2021-09-01 05:52
The ` ` space character is supported by jvm, we don't encode it in the identifier.  
As this is happening only at the debugger and only if the identifier starts with a space,  is it possible to handle them separately in the same place before trimming?

**Comment by praveennadarajah** [comment] 2021-12-10 11:24
The above issue is not reproducible due to the recent debugger changes. Hence closing the issue.

**Closed by praveennadarajah** 2021-12-10 11:24 UTC
Labels: Type/Bug, Area/Debugger, Team/DevTools
