### ISSUE TITLE
JVM code and module restructure with proper phases

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#19027] opened 2019-09-12 08:41 UTC
**Description:**
JVM code and module restructure with proper phases for each major activity.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment] 2019-12-09 04:59
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/19027

**Comment by manuranga** [comment] 2020-03-23 05:38
new `BackendDriver.java` (`ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/bir/BackendDriver.java`) addresses this

**Closed by manuranga** 2020-03-23 05:38 UTC
Labels: Area/jBallerina, Type/Task
