### ISSUE TITLE
Show the Ballerina & BallerinaX Differentiation in the API Docs Home Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-lang#24908] opened 2020-07-23 06:21 UTC
**Description:**
We need to think of a way to show the Ballerina & BallerinaX differentiation in the API Docs Home Page[1] with respect to changing the URL of them as discussed in [2] and the change in the title suggested in [3].

This should be applied in both 1.2.x & Swan Lake versions.

[1] https://ballerina.io/learn/api-docs/ballerina/
[2] https://github.com/ballerina-platform/ballerina-dev-website/issues/1097
[3] https://github.com/ballerina-platform/ballerina-lang/issues/24914

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shehan360** [comment] 2021-06-30 08:34
Closing as a duplicate of https://github.com/ballerina-platform/ballerina-dev-tools/issues/81

**Closed by shehan360** 2021-06-30 08:34 UTC
Labels: Area/Docerina, SwanLakeDump, Team/DevTools, Type/Improvement
