### ISSUE TITLE
Invalid compilation error when printing a query expression

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#35241] opened 2022-02-25 09:04 UTC
**Description:**
$title

**Steps to reproduce:**
```ballerina
public function main() {
    io:println(from int a in [1, 2, 3] select a); // ambiguous type '[int, int]' 
}
```

**Affected Versions:**
Ballerina 2201.0.0 (Swan Lake)

**Comment by MaryamZi** [comment] 2022-03-04 09:03
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/35031

**Closed by MaryamZi** 2022-03-04 09:03 UTC
Labels: Type/Bug, Status/Duplicate, Team/CompilerFE, Error/TypeK, Lang/Expressions/Query, Reason/Other
