### ISSUE TITLE
Ballerina build failure not resulting in non-zero exit code

### ISSUE THREAD

**Issue by grahnj** [ballerina-platform/ballerina-lang#21624] opened 2020-03-11 05:16 UTC
**Description**
When a ‘ballerina build’ command fails it is not setting a non-zero exit code.

**Steps to reproduce:**
Change the default unit test so that it fails. Check errorlevel (Windows); value is not set.

**Affected Versions:**
1.1.3 (haven’t checked 1.1.4)

**OS, DB, other environment details and versions:**
Tested on Windows

**Related Issues (optional):**
As a side-effect, when the ballerina-action in Github workflow has a failing build step, it reports as ‘passed’. 

**Suggested Labels (optional):**
Cli

**Comment by janihur** [comment] 2020-03-11 06:18
In Linux (Ubuntu 19.04) the exit code is always zero:

```
$ ballerina version
jBallerina 1.1.2
Language specification 2019R3
Ballerina tool 0.8.0
$ ballerina build -o build/test.jar test.bal 
Compiling source
        test.bal

Generating executables
        build/test.jar
$ echo $?
0
$ vi test.bal 
$ ballerina build -o build/test.jar test.bal 
Compiling source
        test.bal
error: .::test.bal:3:9: unknown type 'jsonX'
jani@baldev:~/bal-ss-1/language-examples$ echo $?
0
```

**Comment by lafernando** [comment] 2020-03-11 08:31
Duplicate of #20967

**Comment by hevayo** [comment] 2020-07-29 03:59
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/431

**Closed by hevayo** 2020-07-29 03:59 UTC
Labels: Area/BuildTools
