### ISSUE TITLE
ClassCastException: BasicLiteralNode cannot be cast to BindingPatternNode

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#25736] opened 2020-09-11 08:38 UTC
**Description:**
#### Code
```Ballerina
public function main() {
    int[1*2] intArr = [1];
}
```

#### Output
```LogTalk
[2020-09-11 14:02:54,076] SEVERE {b7a.log.crash} - io.ballerinalang.compiler.syntax.tree.BasicLiteralNode cannot be cast to io.ballerinalang.compiler.syntax.tree.BindingPatternNode 
java.lang.ClassCastException: io.ballerinalang.compiler.syntax.tree.BasicLiteralNode cannot be cast to io.ballerinalang.compiler.syntax.tree.BindingPatternNode
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.getBLangVariableNode(BLangNodeTransformer.java:3833)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createBLangVarDef(BLangNodeTransformer.java:2566)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2542)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:424)
        at io.ballerinalang.compiler.syntax.tree.VariableDeclarationNode.apply(VariableDeclarationNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3925)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1405)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:424)
        at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1318)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1289)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:424)
        at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:519)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:424)
        at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:449)
        at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:144)
        at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
        at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
        at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:57)
        at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
        at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:299)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.tool.Main.main(Main.java:57)
```

**Affected Versions:**
slp3

**Suggested Labels (optional):**
Language/BindingPatterns Area/Parser 

**Related Issues (optional):**
#25125 #24473

**Comment by lochana-chathura** [comment] 2021-03-04 17:00
Most probably duplicate of #26635.

**Closed** 2021-03-26 10:52 UTC
Labels: Area/Parser, SwanLakeDump, Team/CompilerFE, Type/Bug
