### ISSUE TITLE
Annotations are not suggested for half completed attribute names 

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#14028] opened 2019-03-01 04:45 UTC
**Description:**
Annotations are not suggested for half completed attribute names, also annotation complition support is only for the first attribute.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10986966/53616893-c725e600-3c0a-11e9-8c35-7a23d7dd078b.gif)

**Comment by nadeeshaan** [comment] 2019-03-13 08:32
Duplicate of #12504

**Closed by nadeeshaan** 2019-03-13 08:32 UTC
Labels: Component/LanguageServer, Severity/Critical, Type/Bug
