### ISSUE TITLE
Auto completions for http package alias completion on global variable definition level.

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13750] opened 2019-02-21 09:42 UTC
**Description:**
Auto completions for http package alias completion on global variable definition level.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/10986966/53159006-f628d000-35ea-11e9-8bf2-b76575a3b327.gif)

**Comment by nadeeshaan** [comment] 2019-03-13 07:06
Duplicate of #13735

**Closed by nadeeshaan** 2019-03-13 07:06 UTC
Labels: Component/LanguageServer, Type/Bug
