### ISSUE TITLE
[Tooling] Auto completion does not work within existing code block

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#26846] opened 2020-11-10 18:40 UTC
**Description:**
Please consider the below ballerina query snippet. It does not provide any completion suggestion. 

```
type Student record {
    readonly id;
    string firstName;
    string lastName;
    int intakeYear;
    float gpa;
};

type Report record {
    readonly id;
    string name;
    string degree;
    int graduationYear;
};
type ReportTable table<Report> key(id); 

type FullName record {|
    string firstName;
    string lastName;
|};

public function main() {
    
}
```

auto completion does not work within the existing code block. It works only in the top and bottom of bal file.

**Comment by nadeeshaan** [comment] 2021-01-04 10:44
Checked in latest master, and could not observe the issue. If the issue is still reproducible, please reopen

**Closed by nadeeshaan** 2021-01-04 10:44 UTC
Labels: Area/LanguageServer, Priority/Blocker, Team/Tooling
