### ISSUE TITLE
Fix disabled tests under broken group

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#12213] opened 2018-12-01 18:53 UTC
There are few test cases added to "broken" group and disabled. These are L1 for the release.

**Comment by Kishanthan** [comment] 2018-12-01 20:12
Failing tests are :

[ERROR] Failures: 
[ERROR]   FreezeAndIsFrozenTest.testAdditionToFrozenInnerJson » Test 
The exception was ...
[ERROR]   FreezeAndIsFrozenTest.testAdditionToFrozenJson » Test 
The exception was throw...
[ERROR]   FreezeAndIsFrozenTest.testFrozenInnerJsonModification » Test 
The exception wa...
[ERROR]   FreezeAndIsFrozenTest.testFrozenJsonModification » Test 
The exception was thr...
[ERROR]   MatchStructuredRecordPatternsTest.testMatchStatementBasics4:80 » BLangRuntime ...
[ERROR]   MatchStructuredRecordPatternsTest.testMatchStatementBasics5:91 » NullPointer
[ERROR]   MatchStructuredRecordPatternsTest.testRuntimeCheck:122 » NullPointer
[ERROR]   StringTest.testLengthofNull » Test 
The exception was thrown with the wrong me...
[ERROR]   TableLiteralSyntaxTest.testTableAddOnConstrainedTableWithViolation » Test 
Exp...
[ERROR]   TableLiteralTest.testTableWithAnyDataToJson » Test 
The exception was thrown w...
[ERROR]   XMLAccessTest.testXMLSequenceAccessWithOutOfIndex » Test 
Expected exception o...

**Comment by anupama-pathirage** [comment] 2018-12-03 03:47
Check all the disabled tests as well. Some commits have disable tests https://github.com/ballerina-platform/ballerina-lang/issues/12255

**Comment by Kishanthan** [comment] 2018-12-04 07:39
worker sync send test case is failing with following error

[ERROR] WorkerSyncSendTest.errorAfterSendTest:84 expected [true] but found [false]

**Comment by SupunS** [comment] 2018-12-04 12:51
https://github.com/ballerina-platform/ballerina-lang/issues/11854 should also part of this.

**Comment by hasithaa** [comment] 2021-06-10 03:28
@MaryamZi Can we close this, since you have fixed this for SL Beta1?

**Comment by MaryamZi** [comment] 2021-06-10 03:33
> @MaryamZi Can we close this, since you have fixed this for SL Beta1?

Yeah, we don't seem to have the "broken" group anymore and for whatever that is disabled individual issues have been created or comments have been added to issues tracking the root cause (to enable the tests when fixing the issue).

**Closed by MaryamZi** 2021-06-10 03:33 UTC
Labels: Area/UnitTest, Team/CompilerFE, Team/StandardLibs, Type/Task, Type/TestFailure
