### ISSUE TITLE
System error in list constructor with union type descriptor

### ISSUE THREAD

**Issue by hrennau** [ballerina-platform/ballerina-lang#19730] opened 2019-11-03 16:25 UTC
**Description:**
A system error occurs in response to a list constructor with a union type descriptor. Per specification "6.6 List constructor", it should work and lead to an inherent type int[2].

Program:
```ballerina
import ballerina/io;

public function main() {
    int[2] | int[3] | int[4] value = [1, 7];
    value.push(99);
    io:println("value: ", value);
}
```

Message:
ballerina: Oh no, something really went wrong. Bad. Sad.

**Steps to reproduce:**
Source code attached.

**Affected Versions:**
Ballerina 1.0.0
Language specification 2019R3

[issue_20191103a.zip](https://github.com/ballerina-platform/ballerina-lang/files/3801772/issue_20191103a.zip)

**Comment by SupunS** [comment] 2019-11-04 06:35
@MaryamZi: shouldn't this give a compile error, since `value` is a union type?

**Comment by MaryamZi** [comment] 2019-11-05 06:32
@SupunS as discussed offline, IMO calling a langlib method on a union is valid since the method-call-expr section of the spec says

"A method-call-expr either calls a method or calls a function in the lang library. The evaluation of the method-call-expr starts by evaluating expression resulting in some value v. There is no contextually expected type for expression.

If the static type of expression is a subtype of object, and the object type includes a method named method-name, then the method-call-expr is executed by calling that method on v.

Otherwise, the method-call-expr will be turned into a call to a function in the lang library m:method-name(expression, arg-list), where m is an automatically created module prefix for a module lang.M of the lang library, where M is selected as follows.

- If the **static type of expression is a subtype of some basic type** with identifier B, and the module lang.B contains a function method-name then M is B. The identifier for a basic type is the reserved identifier used in type descriptors for subtypes of that basic type, as listed in the Lang library section.
- Otherwise, M is value."

Since the members are all subtypes of `int[]` we should be able to call anything valid on `int[]` right?

**Comment by SupunS** [comment] 2019-11-05 06:43
Ack.

In that case, the types for the lang-lib method invocation should be correctly set from the desugar phase I guess. I assume it currently comes as union, but it should then comes as the common super type (`int[]` in this case).

**Comment by MaryamZi** [comment] 2019-11-05 06:49
@SupunS yes, seems like union types have not been handled correctly.

However, in this case since all three possible member types are closed arrays, this should result in a compilation error, since it is not possible to push a member to such an array. This is being tracked by https://github.com/ballerina-platform/ballerina-lang/issues/18662.

@hrennau if you need to use a lang library method such as `.push()` with a variable defined with a union type, I'm afraid as a workaround you would have to first assign it to a non-union type and then call the method.

```ballerina
import ballerina/io;

public function main() {
    int[2] | int[] arr = [1, 7, 3];
    int[] value = arr;
    value.push(99);
    io:println("value: ", value);
}
```

**Comment by MaryamZi** [comment] 2020-03-19 17:06
Update:

The original example does not result in a bad, sad error in jBallerina 1.1.0 and later versions. Results in an index out of range error at runtime instead (since the array created is a closed array).

With the upcoming Ballerina 1.2.0 release, the constraint on a list-constructor-expression for a closed array to have exactly the same number of elements as the size specified for the array has been relaxed, for when the element type has a filler value. For element types that have a filler value, it will possible to create a closed array using a list-constructor-expression with less members than the specified size; the remainder will be filled automatically using the filler value.

e.g.,
```ballerina
import ballerina/io;

public function main() {
    int[4] value = [1, 2];  // valid now
    io:println(value.toJsonString()); // [1, 2, 0, 0]
}
```

Thus, from 1.2.0 onward `int[2] | int[3] | int[4] value = [1, 7]` will fail at compile time with an `ambiguous type '(int[2]|int[3]|int[4])'` error since `[1, 7]` is a valid constructor for all 3 possible types.

The latter scenario also works on 1.1.0 and later versions without the assignment to another variable.

```ballerina
import ballerina/io;

public function main() {
    int[2] | int[] arr = [1, 7, 3];
    arr.push(99);
    io:println(arr.toJsonString()); // [1, 7, 3, 99]
}
```

Closing this issue since this cannot be reproduced now, and operations on the array work as expected.

**Closed by MaryamZi** 2020-03-19 17:06 UTC
Labels: Area/Language, Compatibility/Minor, Resolution/Cannot Reproduce, Type/Bug
