### ISSUE TITLE
Match statement - something went wrong

### ISSUE THREAD

**Issue by hrennau** [ballerina-platform/ballerina-lang#19720] opened 2019-11-01 23:24 UTC
**Description:**
Match statement triggered "ballerina: Oh no, something really went wrong. Bad. Sad."

**Steps to reproduce:**
Code:
``` ballerina
import ballerina/io;

public function main() {
    map<anydata> r = {x: "abc", y:1};
    demomatch(r);
}

public function demomatch(anydata v) {
    match v {
        {yin: _, yim: _} => {io:println("yin yim");}
        var z => {io:println("Default branch");}
    }
}
```
Log: see attachment
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/3799889/ballerina-internal.log)

**Comment by gimantha** [comment] 2019-11-04 04:31
I changed the line `map r = {x: "abc", y:1};` to `map<anydata> r = {x: "abc", y:1};`, hence the former case is not allowed in 1.0. Still the issue can be reproduced

**Comment by MaryamZi** [comment] 2021-01-27 11:06
This produces a "pattern will not be matched" error on sl-alpha1 for `{yin: _, yim: _}`.

**Comment by KavinduZoysa** [comment] 2021-01-29 09:02
The issue is fixed in PR https://github.com/ballerina-platform/ballerina-lang/pull/28215

**Closed** 2021-04-16 05:52 UTC
Labels: Area/Compiler, Lang/BindingPatterns, Priority/High, SwanLakeDump, Team/CompilerFE, Type/Bug
