### ISSUE TITLE
[API Docs] Fails to generate a table with proper indentation

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#22596] opened 2020-04-12 16:10 UTC
**Description:**
> $Title on the website.

The Stdlib module page, which shows module.md and other functions altogether do not seem to indent properly (learn/api-docs/ballerina/java/index.html)
![Selection_127](https://user-images.githubusercontent.com/8381003/79073634-48541580-7d05-11ea-9bab-0cf5085bf329.png)

The page which directs when you click on the function shows it properly (learn/api-docs/ballerina/java/functions.html)

![Selection_126](https://user-images.githubusercontent.com/8381003/79073653-5dc93f80-7d05-11ea-8274-f243aa173c9e.png)

Tabel in the function description
https://github.com/ballerina-platform/ballerina-lang/pull/22556/files#diff-98c8c70e07faba09acc1dd804da4b3f1R62

**Affected Versions:**
v1.2.0

**Comment by praneesha** [comment] 2020-04-20 14:31
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/22789.

**Closed by praneesha** 2020-04-20 14:31 UTC
Labels: Component/Docerina, Type/Bug, Type/Docs
