### ISSUE TITLE
Error diagnostic duplication

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#30830] opened 2021-05-28 06:58 UTC
**Description:**
![Screenshot 2021-05-28 at 12 24 38](https://user-images.githubusercontent.com/15815199/119942752-d34aaa80-bfaf-11eb-888e-4ad237cdb5b3.png)

**Steps to reproduce:**
```ballerina
public function main() {
    int[] arr = [1, 2, 3];
    int[] arr2= [];
    fail from var i in arr
    do {
        arr2.push(i);
    };
}
```

**Affected Versions:**
SL beta 1 RC 5

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by malinthar** [comment] 2021-06-17 12:12
Could not reproduce in slbeta2. It is possible that this is caused by having the compiler-toolkit vscode extension enabled along with the ballerina vscode extension.

![ss](https://user-images.githubusercontent.com/35211477/122394212-577ec500-cf93-11eb-96ae-1487c14b1855.png)

**Comment by IMS94** [comment] 2021-06-18 09:15
Closing since it is not reproducible on master

**Closed by IMS94** 2021-06-18 09:15 UTC
Labels: Area/Diagnostics, Team/LanguageServer, Type/Bug

**Comment by pcnfernando** [comment] 2021-07-08 08:02
@malinthar yes I had compiler-toolkit enabled

**Comment by IMS94** [comment] 2021-07-08 09:14
@pcnfernando That should be the case. Using both plugins at the same time cause the same diagnostics to be published twice.
