### ISSUE TITLE
[Bug]: Function must return a result diagnostic is not showing

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#38066] opened 2022-10-05 04:40 UTC
### Description

Function must return a result diagnostic is not shown when user define a function inside a module without a returning a value.

<img width="324" alt="Screenshot 2022-10-05 at 10 01 50" src="https://user-images.githubusercontent.com/46857198/193981757-ae6a07c5-9d0a-4cdb-9c6a-e69c6b209469.png">

### Steps to Reproduce

1. Create a ballerina project.
2. Add a new ballerina module.
3. Add the below code snippet to a `bal` file inside the module'.
```
function name() returns string {
    
}
```

**Comment by dulajdilshan** [comment] 2022-10-26 10:55
Simplified `Steps to reproduce`

Add the code below 

```
public function name() returns string {
    
}

function runThis() {
    var d = 3
}
```

Here, `Function must return a result` diagnostic is not showing for `name()` function.

**Comment by gimantha** [comment] 2022-10-27 08:04
> Simplified `Steps to reproduce`
> 
> Add the code below
> 
> ```
> public function name() returns string {
>     
> }
> 
> function runThis() {
>     var d = 3
> }
> ```
> 
> Here, `Function must return a result` diagnostic is not showing for `name()` function.
> 
> @gimantha @MaryamZi Any idea?

This could be due to the way we handle the errors. In runThis function, we report that there is a missing semicolon. So may be we are not fully going through the functions to check all the errors and returning it. But once that issue is fixed by the user, `Function must return a result` will be given. IMO this is not a blocker. I will check the whether this can be easily fixed or not

**Comment by dulajdilshan** [comment] 2022-10-27 08:18
Another scenario happens when a particular file contains this code block with another erroneous code block within two files inside the same module 

Ex: 

module1->file1.bal

```ballerina
public function name() returns string {
}
```

module1->file2.bal

```ballerina
function runThis() {
    var d = 3
}
```
Here we only see the error in `file2.bal`. (However, after fixing this, the error in the `file1.bal` is shown)

**Comment by dulajdilshan** [comment] 2022-10-27 08:25
This kind of scenario occurs when a user adds a module (let's say `mod1`) to her project and removes all the content inside the `mod1.bal` and writes below code snippet
```ballerina
public function name() returns string {
}
``` 

Since now the files inside the `tests` contain errors, and the user now in the current file `mod1.bal`, she doesn't see any errors in the current file


https://user-images.githubusercontent.com/25485997/198231505-6f17b331-d1e3-460f-bc1c-d72426f4f828.mov

**Comment by MaryamZi** [comment] 2022-10-27 08:34
The "this function must return a result" error is a code analysis error. 

We don't usually go to code analysis and subsequent phases if there's parser and/or semantic errors. The behaviour is the same for

```ballerina
public function name() returns string {
    
}

function runThis() {
    string _ = 3;
}
```

```cmd
$ bal build
Compiling source
        maryam/temp:0.1.0
ERROR [main.bal:(6:16,6:17)] incompatible types: expected 'string', found 'int'
```

So the errors shown on VSCode could also be related to what phases are run.

**Comment by dulajdilshan** [comment] 2022-11-02 04:36
On Hold for the project API team to discuss for a proper solution

**Comment by dulajdilshan** [comment] 2022-11-03 09:26
Here, we need an API from the Project API to enable the running code-analyzer phase.

We have to make `IsToolingCompilation` true in `CompilerPhaseRunner`

Created a new issue to track it: https://github.com/ballerina-platform/ballerina-lang/issues/38545

**Comment by dulajdilshan** [comment] 2022-11-16 07:39
Related Discussion: https://github.com/ballerina-platform/ballerina-lang/discussions/27938

**Comment by dulajdilshan** [comment] 2022-11-16 09:23
Had a live discussion with @sameerajayasoma @mohanvive @gimantha @azinneera and Myself, the conclusion as follows.

- making `isToolCompilation` will make the compiler run the `CodeAnalyzer` phase. But before that, we need to verify the flow of the code analyzer. We strongly need to verify whether it will not break the code-analyzer if we go forward running the  `CodeAnalyzer` phase with semantic or syntax errors in a given ballerina code.

**Comment by dulajdilshan** [comment] 2023-11-23 04:17
This is fixed.

<img width="571" alt="image" src="https://github.com/ballerina-platform/ballerina-lang/assets/25485997/fb1b32c8-7d51-4bfa-b2a9-187bcbec4883">

**Closed by dulajdilshan** 2023-11-23 04:17 UTC
Labels: Type/Bug, Priority/High, Status/Blocked, Area/Compiler, Team/CompilerFETools, Area/Diagnostics, Points/0.5, userCategory/Editor
