### ISSUE TITLE
`ballerina build` command gets failed when the org-name of Ballerina.toml file is mentioned as ballerina

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#11309] opened 2018-11-12 05:55 UTC
**Description:**
`ballerina build` command gets failed when the org-name of `Ballerina.toml` file is mentioned as _ballerina_. This should be failed by giving an proper error message without stopping the build silently.

**Steps to reproduce:**
1. Create a project as `package-sample` and initiate it with `ballerina init`.
2. Update the `Ballerina.toml` file as follows:
```
[project]
org-name = "ballerina"
version = "0.0.1"
```
3. Build the module with `ballerina build sample`

The current output is as follows:
```
Compiling source
    ballerina/sample
```
This should be improved with proper error message.

**Affected Versions:**
Ballerina 0.983.0

**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS

**Suggested Labels (optional):**
Component/central
Type/Bug

**Suggested Assignees (optional):**
@NatashaWso2

**Comment by ponsilva** [comment] 2018-11-20 10:32
I agree with the proposal to show an error message; sometimes it is difficult to understand what is really going on.

In fact, I created a user named ballerina in my Linux VM.
So the ballerina init command created a Ballerina.toml file as follows:
```
[project]
org-name = "ballerina"
version = "0.0.1"
```
Of course the problem arises even if I didn't explicitly updated the Ballerina.toml file!

**Comment by suganyasuven** [comment] 2020-02-10 10:00
#20321

**Comment by suganyasuven** [comment] 2020-02-11 05:15
Duplicate of #20321

**Comment by suganyasuven** [comment] 2020-02-11 05:28
This issue is due to the constraint added to prevent the module with org-name as `ballerina` pushing to central. Thus, we need to add a fix for this special case.

**Comment by pramodya1994** [comment] 2020-02-25 10:05
@suganyasuven Shall we add a test case in `jballerina-integration-test/src/test/java/org/ballerinalang/test/packaging/PackagingNegativeTestCase.java` for this use-case after fixing this

**Comment by hevayo** [comment] 2021-06-09 09:28
Fixed in SL

**Closed by hevayo** 2021-06-09 09:28 UTC
Labels: Priority/High, Team/DevTools, Type/Bug
