### ISSUE TITLE
Trap doesn't work with sync send

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#18650] opened 2019-09-05 13:25 UTC
**Description:**
$title. 

Using trap with sync send was not possible due to https://github.com/ballerina-platform/ballerina-lang/issues/18160. This will be fixed with https://github.com/ballerina-platform/ballerina-lang/pull/18649.

However trap doesn't work, and the panic is propagated all the way.

**Steps to reproduce:**
```ballerina
import ballerina/io;
import ballerina/runtime;

public function main() {
    worker w1 {
        int i = 100;
        error? v = trap i ->> w2;
    }

    worker w2 {
        runtime:sleep(5000);
        int lw;

        if (true) {
            panic error("err reason");
        }

        lw = <- w1;
        io:println("[w2 <- w1] lw: ", lw);
    
    }

    wait w1;
}
```

```cmd
$ ballerina run test.bal 
[2019-09-05 17:01:29,813] ERROR {org.ballerinalang.jvm.scheduling.Scheduler} - Strand died 
error: err reason 
        at test:$lambda$1(test.bal:15)
```

**Comment by MaryamZi** [comment] 2019-09-05 16:37
Doesn't seem to be working with start too, could be an issue with actions in general.

```ballerina
import ballerina/io;

function foo() returns int {
    if (true) {
        panic error("err");
    }

    return 1;
}

public function main(string... args) {
    future<int>|error i = trap start foo();

    if (i is error) {
        io:println("error occurred ", i.reason());
    } else {
        int j = wait i;
        io:println("value ", j);
    }
}
```

**Comment by warunalakshitha** [comment] 2019-09-16 10:19
I have tested trap with sync send and print the error value. Seems working fine for me.

**Comment by warunalakshitha** [comment] 2019-09-24 19:15
I am closing this since it is working in latest 1.0.1 branch. Please reopen if the issue is still exist.

**Closed by warunalakshitha** 2019-09-24 19:15 UTC
Labels: Area/JBallerina, Area/Language, Type/Bug
