### ISSUE TITLE
Cookie support for client connector

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#4630] opened 2018-02-09 09:45 UTC
**Description:**
ATM ballerina has HTTP session cookie support for server connector. Client connector should also get the ability to exchange cookie if needed.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
feature

**Suggested Assignees (optional):**

**Comment by arukshani** [comment] 2018-10-11 09:30
Closing since this is a duplicate of #10729

**Closed by arukshani** 2018-10-11 09:30 UTC
Labels: Component/HTTP, Component/stdlib, Type/Task
