### ISSUE TITLE
Code that broke Ballerina with java.lang.NullPointerException when reading a result-stream of a mysql query

### ISSUE THREAD

**Issue by ratnajothy** [ballerina-platform/ballerina-lang#36690] opened 2022-06-23 09:07 UTC
**Description:**
```
[2022-06-20 10:18:58,941] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:164)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:445)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$4(BIROptimizer.java:126)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:126)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:403)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:103)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:103)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:83)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:82)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:271)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:443)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:380)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:166)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:135)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:169)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:112)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:93)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:205)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 ```

**Steps to reproduce:**
In a GET service endpoint, change [1] to [2].
[1]
```
  stream<Quotation, error?> resultQuotationStream = dbClient->query(`SELECT QUOTATIONID, SUPPLIERID, BRANDNAME, AVAILABLEQUANTITY, EXPIRYDATE, UNITPRICE, REGULATORYINFO FROM QUOTATION;`);
  check from Quotation quotation in resultQuotationStream
  do {
        info.supplierQuotes.push(quotation);
  };
  foreach Quotation quotation in info.supplierQuotes {
        Supplier supplier = check dbClient->queryRow(`SELECT SUPPLIERID, NAME, SHORTNAME, EMAIL, PHONENUMBER FROM SUPPLIER WHERE SUPPLIERID=${quotation.supplierID};`);
        quotation.supplier = supplier;
  }
```

[2] 
```
  stream<Quotation, error?> resultQuotationStream = dbClient->query(`SELECT QUOTATIONID, SUPPLIERID, BRANDNAME, AVAILABLEQUANTITY, EXPIRYDATE, UNITPRICE, REGULATORYINFO FROM QUOTATION;`);
  check from Quotation quotation in resultQuotationStream
  do {
        Supplier supplier = check dbClient->queryRow(`SELECT SUPPLIERID, NAME, SHORTNAME, EMAIL, PHONENUMBER FROM SUPPLIER WHERE SUPPLIERID=${quotation.supplierID};`);
        quotation.supplier = supplier;
        info.supplierQuotes.push(quotation);
  };
```
**Affected Versions:** Ballerina SDK 2201.0.4

**OS, DB, other environment details and versions:** Choreo, MYSQL connector

**Comment by Nadeeshan96** [comment] 2022-06-30 06:54
This seems to be a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/34557.

**Comment by pcnfernando** [comment] 2022-07-01 11:29
This seems to happen when a narrowed symbol is looked through closures.
As a temporary workaround instead of narrowing; you can check the client creation to return the error to the enclosing function.

```ballerina
resource function get medicalNeedInfo() 
    returns MedicalNeedInfo[]|error {
        MedicalNeedInfo[] medicalNeedInfo = [];
         // instead of type narrowing; check the dbClient creation exp
        // mysql:Client|sql:Error dbClient = new (dbHost, dbUser, dbPass, db, dbPort);
        // if dbClient is mysql:Client {
                mysql:Client dbClient = check new (dbHost, dbUser, dbPass, db, dbPort);
                stream<MedicalNeedInfo, error?> resultStream = dbClient->query(`SELECT I.NAME, NEEDID, PERIOD, URGENCY,
                                                                                NEEDEDQUANTITY, REMAININGQUANTITY
                                                                                FROM MEDICAL_NEED N
                                                                                LEFT JOIN MEDICAL_ITEM I ON I.ITEMID=N.ITEMID;`);
                check from MedicalNeedInfo info in resultStream
                do {
                    medicalNeedInfo.push(info);
                };
                foreach MedicalNeedInfo info in medicalNeedInfo {
                    info.period.day = 1;
                    info.supplierQuotes = [];
                    info.beneficiary = check dbClient->queryRow(`SELECT B.BENEFICIARYID, B.NAME, B.SHORTNAME, B.EMAIL, B.PHONENUMBER 
                                                                        FROM BENEFICIARY B RIGHT JOIN MEDICAL_NEED M ON B.BENEFICIARYID=M.BENEFICIARYID
                                                                        WHERE M.NEEDID=${info.needID};`);
                    stream<Quotation, error?> resultQuotationStream = dbClient->query(`SELECT QUOTATIONID, SUPPLIERID, BRANDNAME,
                                                                                    AVAILABLEQUANTITY, Q.PERIOD, EXPIRYDATE,
                                                                                    UNITPRICE, REGULATORYINFO
                                                                                    FROM MEDICAL_NEED N
                                                                                    RIGHT JOIN QUOTATION Q ON Q.ITEMID=N.ITEMID
                                                                                    WHERE DATEDIFF(Q.PERIOD, ${info.period})=0;`);
                    check from Quotation quotation in resultQuotationStream
                    do {
                        quotation.supplier = check dbClient->queryRow(`SELECT SUPPLIERID, NAME, SHORTNAME, EMAIL, PHONENUMBER FROM SUPPLIER
                                                                    WHERE SUPPLIERID=${quotation.supplierID}`);
                        info.supplierQuotes.push(quotation);
                    };
                }
                check dbClient.close();
        // }
        return medicalNeedInfo;
    }
```

**Comment by SasinduDilshara** [comment] 2023-03-22 11:42
I observed following behaviour.

If we run the above code by separating the logic on another function, it works without any errror.

```
import ballerinax/mysql.driver as _;
import ballerina/sql;
import ballerinax/mysql;
import ballerina/io;

type Quotation record {
    int quotationID;
    int supplierID;
    string brandName;
    int availableQuantity;
    string expiryDate;
    int unitPrice;
    string regulatoryInfo;
    Supplier supplier?;
};

type Supplier record {
    int supplierID;
    string name;
    string shortName;
    string email;
    string phoneNumber;
};

type Info record {
    Quotation[] supplierQuotes;
};

Info info = {supplierQuotes: []};

public function main() returns error? {
    
  mysql:Client|sql:Error dbClient = new ("localhost", "root", pw, "inventory", 3306);

  if (dbClient is sql:Error) {
    io:println("Error in creating db client", dbClient.message());
  } else {
    io:println("DB client created successfully");

    check createTables(dbClient);
    check insertData(dbClient);
    check insertData(dbClient);
    check insertData(dbClient);

    check test(dbClient, info);
  }
  io:println(info.supplierQuotes.length()); // Prints 3
  io:println(info);
}

function createTables(mysql:Client dbClient) returns error? {
    _ = check dbClient->execute(`Drop table if exists QUOTATION`);
    _ = check dbClient->execute(`Drop table if exists SUPPLIER`);
    
    _ = check dbClient->execute(`create table QUOTATION(
        QUOTATIONID int, SUPPLIERID int, BRANDNAME varchar(255), AVAILABLEQUANTITY int, EXPIRYDATE varchar(255), UNITPRICE int, REGULATORYINFO varchar(255)
    )`);
    
    _ = check dbClient->execute(`create table SUPPLIER(
        SUPPLIERID int, NAME varchar(255), SHORTNAME varchar(255), EMAIL varchar(255), PHONENUMBER varchar(255)
    )`);
}

function insertData(mysql:Client dbClient) returns error? {
    _ = check dbClient->execute(`Insert into QUOTATION(
        QUOTATIONID, SUPPLIERID, BRANDNAME, AVAILABLEQUANTITY, EXPIRYDATE, UNITPRICE, REGULATORYINFO) Values (1, 1, 'A', 10, '2021-01-01', 100, 'B')`);
    
    _ = check dbClient->execute(`Insert into SUPPLIER(
        SUPPLIERID, NAME, SHORTNAME, EMAIL, PHONENUMBER) Values (1, 'A', 'B', 'C', 'D'
    )`);
}

function test(mysql:Client dbClient, Info info) returns error? {
    stream<Quotation, error?> resultQuotationStream = dbClient->query(`SELECT QUOTATIONID, SUPPLIERID, BRANDNAME, AVAILABLEQUANTITY, EXPIRYDATE, UNITPRICE, REGULATORYINFO FROM QUOTATION;`);
    check from Quotation quotation in resultQuotationStream
    do {
        Supplier supplier = check dbClient->queryRow(`SELECT SUPPLIERID, NAME, SHORTNAME, EMAIL, PHONENUMBER FROM SUPPLIER WHERE SUPPLIERID=${quotation.supplierID};`);
        quotation.supplier = supplier;
        info.supplierQuotes.push(quotation);
    };
}
```

**Comment by SasinduDilshara** [comment] 2023-03-22 11:45
If we remove the `test` function in the above sample[https://github.com/ballerina-platform/ballerina-lang/issues/36690#issuecomment-1479406761] and add the logic to the main function, it gives compiler crash error

```
import ballerinax/mysql.driver as _;
import ballerina/sql;
import ballerinax/mysql;
import ballerina/io;

type Quotation record {
    int quotationID;
    int supplierID;
    string brandName;
    int availableQuantity;
    string expiryDate;
    int unitPrice;
    string regulatoryInfo;
    Supplier supplier?;
};

type Supplier record {
    int supplierID;
    string name;
    string shortName;
    string email;
    string phoneNumber;
};

type Info record {
    Quotation[] supplierQuotes;
};

Info info = {
    supplierQuotes: []
};

public function main() returns error? {
    
  mysql:Client|sql:Error dbClient = new ("localhost", "root", pw, "inventory", 3306);

  if (dbClient is sql:Error) {
    io:println("Error in creating db client", dbClient.message());
  } else {
    io:println("DB client created successfully");

    check createTables(dbClient);
    check insertData(dbClient);
    check insertData(dbClient);
    check insertData(dbClient);
    
    stream<Quotation, error?> resultQuotationStream = dbClient->query(`SELECT QUOTATIONID, SUPPLIERID, BRANDNAME, AVAILABLEQUANTITY, EXPIRYDATE, UNITPRICE, REGULATORYINFO FROM QUOTATION;`);
    check from Quotation quotation in resultQuotationStream
    do {
        Supplier supplier = check dbClient->queryRow(`SELECT SUPPLIERID, NAME, SHORTNAME, EMAIL, PHONENUMBER FROM SUPPLIER WHERE SUPPLIERID=${quotation.supplierID};`);
        quotation.supplier = supplier;
        info.supplierQuotes.push(quotation);
    };
  }
    io:println(info);
    io:println(info.supplierQuotes);
}

function createTables(mysql:Client dbClient) returns error? {
    _ = check dbClient->execute(`Drop table if exists QUOTATION`);
    _ = check dbClient->execute(`Drop table if exists SUPPLIER`);
    
    _ = check dbClient->execute(`create table QUOTATION(
        QUOTATIONID int, SUPPLIERID int, BRANDNAME varchar(255), AVAILABLEQUANTITY int, EXPIRYDATE varchar(255), UNITPRICE int, REGULATORYINFO varchar(255)
    )`);
    
    _ = check dbClient->execute(`create table SUPPLIER(
        SUPPLIERID int, NAME varchar(255), SHORTNAME varchar(255), EMAIL varchar(255), PHONENUMBER varchar(255)
    )`);
}

function insertData(mysql:Client dbClient) returns error? {
    _ = check dbClient->execute(`Insert into QUOTATION(
        QUOTATIONID, SUPPLIERID, BRANDNAME, AVAILABLEQUANTITY, EXPIRYDATE, UNITPRICE, REGULATORYINFO) Values (1, 1, 'A', 10, '2021-01-01', 100, 'B')`);
    
    _ = check dbClient->execute(`Insert into SUPPLIER(
        SUPPLIERID, NAME, SHORTNAME, EMAIL, PHONENUMBER) Values (1, 'A', 'B', 'C', 'D'
    )`);
}

```

Error is 

```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2023-03-22 17:15:07,275] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:159)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:467)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$3(BIROptimizer.java:121)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:121)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRFunction.accept(BIRNode.java:425)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$1(BIROptimizer.java:107)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:107)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRPackage.accept(BIRNode.java:89)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer.optimizePackage(BIROptimizer.java:83)
        at org.wso2.ballerinalang.compiler.bir.BIRGen.genBIR(BIRGen.java:286)
        at io.ballerina.projects.internal.CompilerPhaseRunner.birGen(CompilerPhaseRunner.java:220)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:157)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:451)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:171)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:183)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:221)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
 
ERROR [.:(1:1,1:1)] Compilation failed due to an unhandled exception
error: compilation contains errors
```

**Comment by SasinduDilshara** [comment] 2023-03-27 04:28
```
import ballerinax/mysql.driver as _;
import ballerina/sql;
import ballerinax/mysql;

type A record {
};

public function main() returns error? {

  mysql:Client|sql:Error dbClient = new ("localhost", "root", pw, "inventory", 3306);

  if (dbClient is sql:Error) {
  } else {
    check from var _ in dbClient->query(``, A)
    do {
        check dbClient.close();
    };
  }
}
```

This is a simple version for this error

**Comment by SasinduDilshara** [comment] 2023-03-28 05:40
More simplified version of this error withour SQL>

```
class EvenNumberGenerator {
    int i = 0;
    public isolated function next() returns record {|int value;|}|error? {
        self.i += 2;
        return {value: self.i};
    }
}

public function main() returns error? {

  EvenNumberGenerator evenGen = new ();
  stream<int, error?> evenNumberStream = new (evenGen);
  int|string a = 1;

  if (a is int) {
  } else {
    check from var _ in evenNumberStream
    do {
        string _ = a;
    };
  }
}
```

**Comment by SasinduDilshara** [comment] 2023-03-28 05:43
This issue happen when the code have `check <query expression>`.
But this check expression should be an effective one, if it is a redundant check or a no-usage check, then this error will not happen.

The error occurred due to following line.
https://github.com/ballerina-platform/ballerina-lang/blob/0c90f9d40175f7d911695715ccb6867d35760c4e/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/desugar/Desugar.java#L5953

**Closed** 2023-06-15 17:58 UTC
Labels: Type/Bug, Priority/Blocker, Team/CompilerFE
