### ISSUE TITLE
Irrelevant return tags in ballerina docs cause compilation failure with NPE

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#8133] opened 2018-04-26 08:16 UTC
**Description:**
$subject with bellow stacktrace.

```bash
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:417)
        at org.wso2.ballerinalang.compiler.tree.BLangDocumentation.accept(BLangDocumentation.java:62)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1256)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1208)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:1200)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$17(SemanticAnalyzer.java:364)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:364)
        at org.wso2.ballerinalang.compiler.tree.BLangObject.accept(BLangObject.java:131)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1256)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:1208)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:1200)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$1(SemanticAnalyzer.java:237)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:237)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:190)
        at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:223)
        at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:159)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:126)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:118)
        at org.wso2.ballerinalang.compiler.CompilerDriver.lambda$compilePackageSymbol$1(CompilerDriver.java:117)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:117)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:91)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:126)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:142)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:72)
        at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:265)
        at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:206)
        at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:188)
        at org.ballerinalang.launcher.util.BCompileUtil.compile(BCompileUtil.java:105)
        at org.ballerinalang.mongodb.MongoDBConnectionInitTest.setup(MongoDBConnectionInitTest.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
        at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at org.testng.TestRunner.privateRun(TestRunner.java:782)
        at org.testng.TestRunner.run(TestRunner.java:632)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
        at org.testng.SuiteRunner.run(SuiteRunner.java:268)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
        at org.testng.TestNG.run(TestNG.java:1064)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
```

**Steps to reproduce:**
Have an object with ballerina doc with return tags.

eg:
```ballerina
documentation {
    Represents MongoDB client endpoint.

    R{{epName}} The name of the endpoint
    R{{config}} The configurations associated with the endpoint
}
public type Client object {
// Some code
}
```
**Affected Versions:**
9.7.0-beta17

**Comment by MaryamZi** [comment] 2018-09-19 14:32
Closing this issue since it is no longer reproducible with Ballerina 0.981.2-SNAPSHOT, with the changes to documentation.

Tested with the following:
**Scenario 1**
```bal
# Represents the MongoDB client endpoint.
#
# + return - `epName` The name of the endpoint
# + return - `config` The configurations associated with the endpoint
public type Client object {
   // Some code
};

public function main() {
}
```
produced the error
`error: .::doc_bug.bal:4:1: extraneous input '# + return - '`

**Scenario 2**
```bal
# Represents the MongoDB client endpoint.
#
# + return - `epName` The name of the endpoint
public type Client object {
   // Some code
};

public function main() {
}
```
produced the error
`warning: .::doc_bug.bal:3:1: no documentable return parameter`

**Closed by MaryamZi** 2018-09-19 14:32 UTC
Labels: Component/Docerina, Type/Bug
