### ISSUE TITLE
Let expression is not yet supported for record fields and object fields

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#29162] opened 2021-03-12 05:48 UTC
Record fileds and objects fields are not allowed in Let Expr in CodeAnalyzer
![image](https://user-images.githubusercontent.com/9362271/110897879-44b97c00-8324-11eb-9fc3-97d4bd47be8f.png)

In the spec, it is not mentioned that records fields and objects fields are not allowed

**Comment by MaryamZi** [comment] 2022-02-28 13:21
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/21382.

**Closed by MaryamZi** 2022-02-28 13:21 UTC
Labels: Type/Bug, Priority/High, Team/CompilerFE, Area/TypeChecker, Area/CodeAnalysis, Spec/Different, Reason/Other
