### ISSUE TITLE
Workers cannot send objects to other workers but can return

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#12491] opened 2018-12-05 06:38 UTC
Following code will not work 

```ballerina
function scheduleTimer(int w1Delay, int w1Interval, int w2Delay, int w2Interval, string errMsgW1, string errMsgW2) {
    worker default {
        errorMsgW1 = errMsgW1;
        errorMsgW2 = errMsgW2;
        timer1 <- w1;
        timer2 <- w2;
    }
    worker w1 {
        task:Timer? t;
        (function() returns error?) onTriggerFunction = onTriggerW1;
        if (errMsgW1 == "") {
            t = new task:Timer(onTriggerFunction, (), w1Interval, delay = w1Delay);
            _ = t.start();
        } else {
            function (error) onErrorFunction = onErrorW1;
            t = new task:Timer(onTriggerFunction, onErrorFunction, w1Interval, delay = w1Delay);
            _ = t.start();
        }
        t -> default;
    }
    worker w2 {
        task:Timer? t;
        (function() returns error?) onTriggerFunction = onTriggerW2;
        if (errMsgW2 == "") {
            t = new task:Timer(onTriggerFunction, (), w2Interval, delay = w2Delay);
            _ = t.start();
        } else {
            function (error) onErrorFunction = onErrorW2;
            t = new task:Timer(onTriggerFunction, onErrorFunction, w2Interval, delay = w2Delay);
            _ = t.start();
        }
        t -> default;
    }
}
```

But following works

```ballerina
function scheduleTimer(int w1Delay, int w1Interval, int w2Delay, int w2Interval, string errMsgW1, string errMsgW2) {
    worker w1 returns task:Timer? {
        task:Timer? t;
        (function() returns error?) onTriggerFunction = onTriggerW1;
        if (errMsgW1 == "") {
            t = new task:Timer(onTriggerFunction, (), w1Interval, delay = w1Delay);
            _ = t.start();
        } else {
            function (error) onErrorFunction = onErrorW1;
            t = new task:Timer(onTriggerFunction, onErrorFunction, w1Interval, delay = w1Delay);
            _ = t.start();
        }
        return t;
    }
    worker w2 returns task:Timer? {
        task:Timer? t;
        (function() returns error?) onTriggerFunction = onTriggerW2;
        if (errMsgW2 == "") {
            t = new task:Timer(onTriggerFunction, (), w2Interval, delay = w2Delay);
            _ = t.start();
        } else {
            function (error) onErrorFunction = onErrorW2;
            t = new task:Timer(onTriggerFunction, onErrorFunction, w2Interval, delay = w2Delay);
            _ = t.start();
        }
        return t;
    }

    errorMsgW1 = errMsgW1;
    errorMsgW2 = errMsgW2;
    timer1 = wait w1;
    timer2 = wait w2;
}
```

**Comment by NatashaWso2** [comment] 2018-12-14 06:53
Only anydata types can be interacted among workers i.e. worker send and receive actions. Since workers are modeled as simple functions the same semantics for functions applies to the workers. So workers can return any value regardless of whether it is of anydata type. Closing this issue since it is the expected behavior.

**Closed by NatashaWso2** 2018-12-14 06:53 UTC
Labels: Component/BVM, Component/Compiler, Type/Bug
