### ISSUE TITLE
Comments available before a closing curly brace indent incorrectly once formatted.

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#28516] opened 2021-02-09 02:56 UTC
**Description:**
Comments available before a closing curly brace indent incorrectly once formatted.

Before formatting...
```
import ballerina/http;

service on new http:Listener(8090) {
    resource function get .(http:Caller caller, http:Request req) {
        string[] fruits = ["asd"];
        foreach var item in fruits {

        }
        //Comment
    }
}
```

After formatting...
```
import ballerina/http;

service on new http:Listener(8090) {
    resource function get .(http:Caller caller, http:Request req) {
        string[] fruits = ["asd"];
        foreach var item in fruits {

        }
    //Comment
    }
}
```

**Steps to reproduce:**

**Affected Versions:**
slp8

**Comment by IrushiL** [comment] 2021-02-15 07:38
Closing this issue since it is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/26380. Please refer the linked issue for tracking purposes.

**Closed by IrushiL** 2021-02-15 07:38 UTC
Labels: Area/Formatting
