### ISSUE TITLE
Failure in test init when running nballerina compiler package

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-lang#31748] opened 2021-07-16 08:04 UTC
**Description:**
When building the nballerina/compiler package, the build fails due to an exception thrown in test init. All the tests are passing but due to the failure in test init, the end result is a failure.

**Steps to reproduce:**
build nballerina compiler package: https://github.com/ballerina-platform/nballerina/tree/main/compiler

Error printed:
```
	nballerina
error: Test module initialization for test suite failed due to java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    wso2/nballerina/0_1_0/tests/testSuite.$streamLambda$_26(Lio/ballerina/runtime/internal/scheduling/Strand;Lio/ballerina/runtime/internal/values/MapValue;ZLio/ballerina/runtime/internal/values/MapValue;Z)Z @312: istore
  Reason:
    Type 'io/ballerina/runtime/internal/values/ErrorValue' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @312
    flags: { }
    locals: { 'io/ballerina/runtime/internal/scheduling/Strand', 'io/ballerina/runtime/internal/values/MapValue', integer, 'io/ballerina/runtime/internal/values/MapValue', integer, 'io/ballerina/runtime/api/values/BString', 'java/lang/Object', 'io/ballerina/runtime/api/values/BString', integer, 'java/lang/Object', 'io/ballerina/runtime/api/values/BString', integer, integer, 'io/ballerina/runtime/internal/values/ErrorValue', integer, integer }
    stack: { 'io/ballerina/runtime/internal/values/ErrorValue' }
  Bytecode:
    0000000: 2ab4 0011 9900 07b8 0017 bf01 3a05 013a
    0000010: 0601 3a07 0336 0801 3a09 013a 0a03 360b
    0000020: 0336 0c01 3a0d 0336 0e03 360f 2ab4 001b
    0000030: 9d01 3e15 0fab 0000 0000 01a5 0000 000b
    0000040: 0000 0000 0000 0063 0000 0001 0000 0096
    0000050: 0000 0002 0000 00c0 0000 0003 0000 00db
    0000060: 0000 0004 0000 00ed 0000 0005 0000 0105
    0000070: 0000 0006 0000 010d 0000 0007 0000 0115
    0000080: 0000 0008 0000 0121 0000 0009 0000 0129
    0000090: 0000 000a 0000 0131 1100 0036 0fb2 0417
    00000a0: 3a07 2dc0 0082 1907 b900 8c02 003a 0619
    00000b0: 06c0 0097 3a05 b201 e53a 072b c000 8219
    00000c0: 07b9 008c 0200 c000 973a 0a11 0001 360f
    00000d0: 2a19 0504 190a 04b8 043e 3a09 2ab6 0035
    00000e0: 9a00 faa7 0003 1909 c101 0c9a 0007 04a7
    00000f0: 0004 0336 0b11 0002 360f 150b 9d00 06a7
    0000100: 0019 1909 c003 0eb6 0441 360c 150c 3608
    0000110: 1100 0336 0fa7 003d 1909 b201 10b8 0041
    0000120: 360b 1100 0436 0f15 0b9d 0006 a700 1e19
    0000130: 09c0 0043 3a0d 190d 360e 1100 0536 0fa7
    0000140: 0027 1100 0636 0fa7 0003 1100 0736 0fa7
    0000150: 0003 1508 360e 1100 0836 0fa7 000b 1100
    0000160: 0936 0fa7 0003 1100 0a36 0f15 0eac 2ab4
    0000170: 00a5 2a59 b400 1b04 645a b500 1b32 c004
    0000180: 4359 b404 4536 0e59 b404 464c 59b4 0447
    0000190: 3d59 b404 484e 59b4 0449 3604 59b4 044a
    00001a0: 3a05 59b4 044b 3a06 59b4 044c 3a07 59b4
    00001b0: 044d 3608 59b4 044e 3a09 59b4 0451 3a0a
    00001c0: 59b4 0453 360b 59b4 0455 360c 59b4 0458
    00001d0: 3a0d b404 5936 0fa7 fe5c bb04 4359 b704
    00001e0: 5a59 150e b504 4559 2bb5 0446 591c b504
    00001f0: 4759 2db5 0448 5915 04b5 0449 5919 05b5
    0000200: 044a 5919 06b5 044b 5919 07b5 044c 5915
    0000210: 08b5 044d 5919 09b5 044e 5919 0ab5 0451
    0000220: 5915 0bb5 0453 5915 0cb5 0455 5919 0db5
    0000230: 0458 5915 0fb5 0459 3a10 2ab4 00a5 2a59
    0000240: b400 1b5a 0460 b500 1b19 1053 150e ac  
  Stackmap Table:
    same_frame(@11)
    full_frame(@51,{Object[#13],Object[#130],Integer,Object[#130],Integer,Object[#151],Object[#4],Object[#151],Integer,Object[#4],Object[#151],Integer,Integer,Object[#67],Integer,Integer},{})
    same_frame_extended(@152)
    same_frame(@203)
    same_frame(@230)
    same_frame(@242)
    same_locals_1_stack_item_frame(@243,Integer)
    same_frame(@245)
    same_frame(@258)
    same_frame(@272)
    same_frame(@280)
    same_frame(@290)
    same_frame(@303)
    full_frame(@314,{Object[#13],Object[#130],Integer,Object[#130],Integer,Object[#151],Object[#4],Object[#151],Integer,Object[#4],Object[#151],Integer,Integer,Object[#67],Top,Integer},{})
    full_frame(@322,{Object[#13],Object[#130],Integer,Object[#130],Integer,Object[#151],Object[#4],Object[#151],Integer,Object[#4],Object[#151],Integer,Integer,Object[#67],Integer,Integer},{})
    same_frame(@330)
    same_frame(@338)
    same_frame(@342)
    same_frame(@350)
    full_frame(@358,{Object[#13],Object[#130],Integer,Object[#130],Integer,Object[#151],Object[#4],Object[#151],Integer,Object[#4],Object[#151],Integer,Integer,Object[#67],Top,Integer},{})
    full_frame(@366,{Object[#13],Object[#130],Integer,Object[#130],Integer,Null,Null,Null,Integer,Null,Null,Integer,Integer,Null,Integer,Integer},{})
    full_frame(@474,{Object[#13],Object[#130],Integer,Object[#130],Integer,Object[#151],Object[#4],Object[#151],Integer,Object[#4],Object[#151],Integer,Integer,Object[#67],Integer,Integer},{})

	at wso2.nballerina.0_1_0:.<testinit>(nballerina:-1)
	   jdk.internal.reflect.NativeMethodAccessorImpl:invoke0(NativeMethodAccessorImpl.java:-2)
	   jdk.internal.reflect.NativeMethodAccessorImpl:invoke(NativeMethodAccessorImpl.java:62)
	   jdk.internal.reflect.DelegatingMethodAccessorImpl:invoke(DelegatingMethodAccessorImpl.java:43)
	   java.lang.reflect.Method:invoke(Method.java:566)
	   org.ballerinalang.test.runtime.entity.TesterinaFunction:lambda$runOnSchedule$0(TesterinaFunction.java:108)
	   io.ballerina.runtime.internal.scheduling.SchedulerItem:execute(Scheduler.java:603)
	   io.ballerina.runtime.internal.scheduling.Scheduler:run(Scheduler.java:328)
	   io.ballerina.runtime.internal.scheduling.Scheduler:runSafely(Scheduler.java:296)
	   java.lang.Thread:run(Thread.java:834)

```

**Affected Versions:**
SL Beta.3-SNAPSHOT

**Comment by Dilhasha** [comment] 2021-07-28 11:41
@warunalakshitha 
This happens due to this code block. 
https://github.com/ballerina-platform/nballerina/blob/main/compiler/tests/testSuite.bal#L68

**Comment by warunalakshitha** [comment] 2021-07-28 13:15
@Dilhasha We will check

**Comment by HindujaB** [comment] 2021-07-30 07:37
can be reproduced with this code

```ballerina
public function main() returns error? {
    string[] e = from var entry in "test"
        where check checkError(entry)
        select entry;
}

function checkError(string a) returns boolean|error {
    return a == "s";
}
```
Could be related to https://github.com/ballerina-platform/ballerina-lang/issues/31008

**Comment by HindujaB** [comment] 2021-08-02 04:50
This happens due to a spec change on query expressions [#871](https://github.com/ballerina-platform/ballerina-spec/issues/871) where we wrap the check expressions inside the clauses to return an error value. 

This contradicts with the filter funtions as they are not defined to return error values. 
```ballerina
function createFilterFunction(function(_Frame _frame) returns boolean filterFunc) {
...
}
```
Modifying the reurn value of the filter function will fix the issue. 

And we need to check the other clauses for a similar scenario as well. ( eg. limit function etc.)

**Comment by gimantha** [comment] 2021-08-05 04:34
> This happens due to a spec change on query expressions [#871](https://github.com/ballerina-platform/ballerina-spec/issues/871) where we wrap the check expressions inside the clauses to return an error value.
> 
> This contradicts with the filter funtions as they are not defined to return error values.
> 
> ```ballerina
> function createFilterFunction(function(_Frame _frame) returns boolean filterFunc) {
> ...
> }
> ```
> 
> Modifying the reurn value of the filter function will fix the issue.
> 
> And we need to check the other clauses for a similar scenario as well. ( eg. limit function etc.)

Thank you for the analysis. Will have a look

**Comment by gimantha** [comment] 2021-08-17 05:57
closing this issue, as it has been fixed in the latest master. Please reopen if necessary

**Closed by gimantha** 2021-08-17 05:57 UTC
Labels: Type/Bug, Priority/Blocker, Team/CompilerFE, Points/3, NBalNeeds
