### ISSUE TITLE
hello_world_service.bal UTF-8 error

### ISSUE THREAD

**Issue by paundo** [ballerina-platform/ballerina-lang#19036] opened 2019-09-13 12:55 UTC
There is problem when using hello_world_service.bal sample with UTF-8 characters.

**Comment by parkavi11** [comment] 2020-01-29 08:30
Can you provide any sample to reproduce?

**Comment by parkavi11** [comment] 2020-02-12 05:40
Since there is no samples provided, closing the issue. Please do not hesitate to reopen the issue along with a sample to reproduce, if you still have the problem.

**Closed** 2020-02-12 05:50 UTC
Labels: Area/BuildTools, Priority/High, Type/Bug
