### ISSUE TITLE
Indexing should work on sequences (string and xml)

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-lang#28312] opened 2021-01-31 02:21 UTC
v[i] on a string or xml value should give the singleton item at index i, but it doesn't work for either string or xml.

If I do this in the shell

```
"abc"[0]
```

I get a compile-error. Similarly for

```
xml`abc`[0]
```

(which should result in xml`abc`). It also doesn't work if I assign to variables first.

Iteration (with `foreach`) does work: this should be consistent with iteration.

**Comment by kdsuneraavinash** [comment] 2021-01-31 07:46
Reproducible outside the shell as well,
```ballerina
import ballerina/io;

public function main() {
    io:println("abc"[0]);
}
```
Gives
```
ERROR [sad.bal:(4:16,4:21)] invalid expression: 'abc' does not support index access
```

**Comment by lasinicl** [comment] 2021-02-23 10:00
Partially fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28833

**Comment by rdhananjaya** [comment] 2021-02-25 10:30
XML case should be fixed in https://github.com/ballerina-platform/ballerina-lang/pull/28556

**Comment by lasinicl** [comment] 2021-03-10 14:10
Closing this since both the PRs have been merged.

**Closed by lasinicl** 2021-03-10 14:10 UTC
Labels: Area/TypeChecker, CompilerSLDump, Lang/Strings, Lang/XML, Priority/High, Team/CompilerFE, Type/SpecDeviation
