### ISSUE TITLE
No module suggestion for modules in the same project

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#28095] opened 2021-01-22 01:30 UTC
**Description:**
When trying to use the records of a module say a from another module say b of the same project without importing a in b first, then there's no suggestion to import module a. We get suggestions to import ballerina inbuilt modules, but not for modules in the same project.

**Comment by nadeeshaan** [comment] 2021-01-26 07:49
Duplicate of #28191. Hence closing the issue

**Closed by nadeeshaan** 2021-01-26 07:49 UTC
Labels: Area/LanguageServer, Resolution/Duplicate, Team/Tooling
