### ISSUE TITLE
[Bug]:Load test throughput is lower in 2201.9.0 RC1 compare to test pack

### ISSUE THREAD

**Issue by prakanth97** [ballerina-platform/ballerina-lang#42606] opened 2024-04-22 09:15 UTC
### Description

For the below service
```
import ballerina/http;
import ballerina/lang.value;

service /wso2 on new http:Listener(9092) {
    resource function post stringDataDataBind(http:Request req) returns json|error? {
        // Get string get xml payload, then to record type and return record value.
        string xmlStr = check req.getTextPayload();
        record {|json...;|} val = check value:fromJsonStringWithType(xmlStr);
        return val;
    }
}
```
Test pack 

Users | 20 | time (sec) | 300 |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Label | # Samples | Average | Median | 90% Line | 95% Line | 99% Line | Min | Max | Error % | Throughput | Received KB/sec | Std. Dev.
HTTP Request | 278902 | 18 | 3 | 22 | 48 | 252 | 2 | 9214 | 0.00% | 929.7 | 58215.3 | 119.75
TOTAL | 278902 | 18 | 3 | 22 | 48 | 252 | 2 | 9214 | 0.00% | 929.7 | 58215.3 | 119.75

RC 1 Pack

Users | 20 | time (sec) | 300 |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Label | # Samples | Average | Median | 90% Line | 95% Line | 99% Line | Min | Max | Error % | Throughput | Received KB/sec | Std. Dev.
HTTP Request | 204930 | 24 | 5 | 12 | 26 | 246 | 4 | 46923 | 0.00% | 683.1 | 42773.9 | 349.59
TOTAL | 204930 | 24 | 5 | 12 | 26 | 246 | 4 | 46923 | 0.00% | 683.1 | 42773.9 | 349.59

2201.8.6
Users | 20 | time (sec) | 300 |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Label | # Samples | Average | Median | 90% Line | 95% Line | 99% Line | Min | Max | Error % | Throughput | Received KB/sec | Std. Dev.
HTTP Request | 131029 | 38 | 9 | 14 | 38 | 193 | 7 | 60010 | 0.01% | 436.8 | 27346.7 | 842.17
TOTAL | 131029 | 38 | 9 | 14 | 38 | 193 | 7 | 60010 | 0.01% | 436.8 | 27346.7 | 842.17

JSON Payload : 
[large_data.json](https://github.com/ballerina-platform/ballerina-lang/files/15060654/large_data.json)

### Affected Version(s)

2201.9.0 RC1

### Related area

-> Runtime

**Comment by gabilang** [comment] 2024-05-02 08:15
It seems the above mentioned issue is not reproducible when comparing the results of 2201.9.0 RC2 and the earliest test pack. Actually the results I obtained shows slight improvements. 

2201.9.0-RC2 Pack 

Users: 20, duration: 300 sec, ramp-up period: 100 sec  

Label | # Samples | Average | Median | 90% Line | 95% Line | 99% Line | Min | Max | Error % | Throughput | Received KB/sec | Std. Dev.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
HTTP Request | 274995 | 19 | 3 | 4 | 5 | 92 | 1 | 30020 | 0.00% | 916.70500 | 57386.31 | 
TOTAL | 274995 | 19 | 3 | 4 | 5 | 92 | 1 | 30020 | 0.00% | 916.70500 | 57386.31 | 


2201.9.0 test pack

Users: 20, duration: 300 sec, ramp-up period: 100 sec

Label | # Samples | Average | Median | 90% Line | 95% Line | 99% Line | Min | Max | Error % | Throughput | Received KB/sec | Std. Dev.
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
HTTP Request | 269431 | 18 | 3 | 4 | 5 | 114 | 1 | 30021 | 0.02% | 898.15423 | 56227.38 | 
TOTAL | 269431 | 18 | 3 | 4 | 5 | 114 | 1 | 30021 | 0.02% | 898.15423 | 56227.38 | 

@prakanth97 can you verify this again with RC2 or the latest RC pack?

**Comment by gabilang** [comment] 2024-05-06 04:34
The issue is not reproducible with the latest RC packs. But observed some cases where we can improve the logics for a better performance (Created an issue for that https://github.com/ballerina-platform/ballerina-lang/issues/42609). 
Since there are improvements observed in the load test with the latest update-9 pack, closing this issue. Feel free to reopen if you have any concerns.

**Closed by gabilang** 2024-05-06 04:34 UTC
Labels: Type/Bug, Team/jBallerina
