### ISSUE TITLE
jsonValue.detail().message is not in the suggestions

### ISSUE THREAD

**Issue by srsharon** [ballerina-platform/ballerina-lang#13746] opened 2019-02-21 08:56 UTC
**Description:**
When coding jsonValue.detail().message is not given in auto complete suggestions 

![image](https://user-images.githubusercontent.com/10986966/53156079-8283c480-35e4-11e9-96f9-21f2107aec9c.png)

**Comment by nadeeshaan** [comment] 2019-03-13 07:00
Duplicate of #13534

**Closed by nadeeshaan** 2019-03-13 07:00 UTC
Labels: Component/LanguageServer, Type/Bug
