### ISSUE TITLE
error: value not provided for required configurable variable '<name>'

### ISSUE THREAD

**Issue by maheeka** [ballerina-platform/ballerina-lang#30282] opened 2021-05-02 07:36 UTC
**Description:**
I have a ballerina project created with external configurations. When I use the same name for the config variable as the config record type, I observe the above-mentioned error.  

**Steps to reproduce:**
```
type MongoDbConfig record {|
    string host;
    int port;
    string username;
    string password;
    string authSource;
|};

configurable int port = ?;
configurable MongoDbConfig & readonly mongodbconfig = ?;

mongodb:ClientConfig mongoConfig = {
    host: mongodbconfig.host,
    port: mongodbconfig.port,
    username: mongodbconfig.username,
    password: mongodbconfig.password,
    options: {authSource: mongodbconfig.authSource, sslEnabled: false, serverSelectionTimeout: 5000}
};
```
![image](https://user-images.githubusercontent.com/1029806/116805863-a7810400-ab6c-11eb-878d-df64c7b36701.png)

The same code executed with a different name for configuration works without an issue (see below)
```
type MongoDbConfig record {|
    string host;
    int port;
    string username;
    string password;
    string authSource;
|};

configurable int port = ?;
configurable MongoDbConfig & readonly mongodb = ?;

mongodb:ClientConfig mongoConfig = {
    host: mongodb.host,
    port: mongodb.port,
    username: mongodb.username,
    password: mongodb.password,
    options: {authSource: mongodb.authSource, sslEnabled: false, serverSelectionTimeout: 5000}
};
```

**Affected Versions:** Swan Lake Alpha v4

**OS, DB, other environment details and versions:**
OSX

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by HindujaB** [comment] 2021-05-04 10:24
@maheeka may I know the content of the `Config.toml` and the project details (packag name)?

**Comment by HindujaB** [comment] 2021-05-05 04:03
I tested with a module `mongoConfig`, 
```
.
├── Ballerina.toml
├── Config.toml
├── Dependencies.toml
└── main.bal
```
With the below in `main.bal`
```ballerina
import ballerinax/mongodb;
import ballerina/io;

type MongoDbConfig record {|
    string host;
    int port;
    string username;
    string password;
    string authSource;
|};

configurable int port = ?;
configurable MongoDbConfig & readonly mongodbconfig = ?;

mongodb:ClientConfig mongoConfig = {
    host: mongodbconfig.host,
    port: mongodbconfig.port,
    username: mongodbconfig.username,
    password: mongodbconfig.password,
    options: {
        authSource: mongodbconfig.authSource,
        sslEnabled: false,
        serverSelectionTimeout: 5000
    }
};

public function main() {
    io:println(mongodbconfig);
    io:println(port);
}
```
In Config.toml
```toml
port = 9090

[mongodbconfig]
host="localhost"
port=9091
username="hinduja"
password="1234"
authSource="abc"
```
It didn't give the error
![Screenshot from 2021-05-05 09-31-27](https://user-images.githubusercontent.com/28644893/117095781-eab5bf80-ad84-11eb-8346-911acbae68ef.png)

**Comment by maheeka** [comment] 2021-05-05 11:34
Hi @HindujaB this is my Config.toml
```
[developer_service]
port = 8085

[developer_service.dbservice.mongodb]
host = "localhost"
port = 27017
username = "api_user"
password = "api1234"
authSource = "developer_db"
```

**Comment by HindujaB** [comment] 2021-05-06 04:27
@maheeka With the `Config.toml` provided, Imay I know which we are specifying by  `dbservice` in line `4`?
If we have the configurable variable(with name `mongodbconfig`)  in module `developer_service` , the header can be,
```toml
[developer_service.mongodbconfig]
host = "localhost"
port = 27017
username = "api_user"
password = "api1234"
authSource = "developer_db"
```
Otherwise, the TOML table part `dbservice` will be considered as an unused toml value. 
Could you try with this toml ?

**Comment by maheeka** [comment] 2021-05-12 21:00
Hi @HindujaB ,

I am having  dbservice in  the config because I am using this  configuration inside a bal  file in a package. If I remove the dbservice, it fails with the following  error.

`error: [Config.toml:(1:1,11:26)] invalid module structure found for module 'developer_service.dbservice'. Please provide the module name as '[developer_service.dbservice]'`

**Comment by HindujaB** [comment] 2021-06-25 10:27
I still couldn't reproduce this scenario. 
Is this error still valid with `Swan Lake - beta1`?
@maheeka Can you pls provide me with a sample package?

**Comment by HindujaB** [comment] 2021-07-22 06:58
Closing the issue, as this error could not be reproduced in `Swan Lake - beta2` with the given context, .

**Closed by HindujaB** 2021-07-22 06:58 UTC
Labels: Team/jBallerina, Type/Bug
