### ISSUE TITLE
Import non-Ballerina IDL as a module that defines a client 

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#36996] opened 2022-07-14 09:10 UTC
Please refer to: https://github.com/ballerina-platform/ballerina-lang/issues/36835

**Comment by MaryamZi** [comment] 2022-07-14 09:32
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/36835.

**Closed by MaryamZi** 2022-07-14 09:32 UTC
Labels: Type/NewFeature, Team/CompilerFE
