### ISSUE TITLE
NullPointerException when building a project with test cases

### ISSUE THREAD

**Issue by praveennadarajah** [ballerina-platform/ballerina-lang#18986] opened 2019-09-10 04:43 UTC
**Description:**
I am migrating Twilio connector[1] to Ballerina 1.0.0. When I build the module with the command `ballerina build -a -- --b7a.config.file=src/twilio/ballerina.conf`, it ended up with following error

```
Praveen-WSO2:module-twilio praveen$ ballerina build -a -- --b7a.config.file=src/twilio/ballerina.conf --skip-tests
Compiling source
        wso2/twilio:0.8.31

Creating balos
        target/balo/twilio-2019r3-any-0.8.31.balo

Running tests
    wso2/twilio:0.8.31
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```

The ballerina-internal.log has the following NullPointerException.

```
[2019-09-10 09:50:35,715] SEVERE {b7a.log.crash} - org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException 
org.ballerinalang.util.exceptions.BallerinaException: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.BTestRunner.formatErrorMessage(BTestRunner.java:819)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$34(BTestRunner.java:664)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:638)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:160)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:132)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:81)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)
Caused by: org.ballerinalang.util.exceptions.BallerinaException: java.lang.NullPointerException
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:146)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.invoke(TesterinaFunction.java:66)
	at org.ballerinalang.testerina.core.entity.TestSuite.start(TestSuite.java:308)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$34(BTestRunner.java:660)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.ballerinalang.jvm.MapUtils.handleMapStore(MapUtils.java:49)
	at wso2.twilio.twilio.wso2_twilio_0_8_31__testinit_(twilio:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:130)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
	at java.lang.Thread.run(Thread.java:748)
```
 

- This behaviour is not observable when I build the module without test cases.
   `ballerina build -a --skip-tests`

- This could be resolved with the following workaround

**Workaround:** Adding a dummy function to twilio_endpoint.bal class

>     # Dummy function to pass the test cases
>     function dummyFunction() returns @tainted () {}

[1] https://github.com/wso2-ballerina/module-twilio

**Comment by pubudu91** [comment] 2019-09-10 05:27
Duplicate of #18431. Hence closing this. A fix for this is provided by PR #18985

**Closed by pubudu91** 2019-09-10 05:27 UTC
Labels: Area/JBallerina, Type/Bug
