### ISSUE TITLE
Invalid "invalid cyclic type reference" error 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35204] opened 2022-02-23 11:50 UTC
**Description:**
```bal
import ballerina/io;
type F function() returns function?;
// I should be able to write: type F function() returns F?;
// Even type F function() returns F


function f(int i) returns F? {
    if i == 10 {
        io:println(i);
        return ();
    }
    return f(i+1);
}

public function main() {
    F? k = f(0);
}
```
I think this should be possible.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment] 2022-02-23 15:15
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/32735.

**Closed by MaryamZi** 2022-02-23 15:15 UTC
Labels: Type/Bug, Status/Duplicate, Team/CompilerFE, Spec/Different

**Comment by rdhananjaya** [comment] 2022-02-23 15:17
Ohh my bad
