### ISSUE TITLE
Need to add variable evaluation features : debugger 

### ISSUE THREAD

**Issue by vishmika531** [ballerina-platform/ballerina-lang#10156] opened 2018-08-22 13:15 UTC
Add variable evaluation feature in the Ballerina debugger so that users can evaluate and see a variable's value while debugging.

**Comment by SupunS** [comment] 2018-08-29 06:05
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/10090

**Closed by SupunS** 2018-08-29 06:05 UTC
Labels: Component/Debugger, Type/Improvement
