### ISSUE TITLE
Restriction on annotation values to anydata

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22428] opened 2020-04-02 10:41 UTC
Assign : Rukshan

**Comment by KRVPerera** [comment] 2020-04-02 10:46
Related to spec: https://github.com/ballerina-platform/ballerina-spec/issues/70

**Comment by pubudu91** [comment] 2020-04-30 08:48
Closing since this is a duplicate of #15533

**Closed by pubudu91** 2020-04-30 08:48 UTC
Labels: Area/Language, Type/NewFeature, Type/SpecDeviation
