### ISSUE TITLE
[Bug]: Compiler cannot determine whether all possible cases have been covered in a match statement

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#39093] opened 2022-12-16 07:54 UTC
### Description

Consider the following scneario:
```ballerina
enum TimeSpan {
    DAILY, WEEKLY, MONTHLY
}

function timespanToFunction(TimeSpan span) returns string {
    match span {
        DAILY => {
            return "startofday";
        }
        WEEKLY => {
            return "startofweek";
        }
        MONTHLY => {
            return "startofmonth";
        }
    }
    // <1> complains about function not returning a result.
}
```
Shouldn't the compiler be able to detect that the flow will never reach point `<1>`? 

### Affected Version(s)

2201.2.3

### Related area

-> Compilation

**Comment by MaryamZi** [comment] 2022-12-18 14:12
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/28869.

**Closed by MaryamZi** 2022-12-18 14:12 UTC
Labels: Type/Bug, Team/CompilerFE, Reason/Invalid, needTriage, userCategory/Compilation
