### ISSUE TITLE
Address TODO's in the BallerinaParser

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#25151] opened 2020-08-06 06:12 UTC
**Description:**

$subject.

Related Issue: #25148

**Comment by lochana-chathura** [comment] 2020-12-08 11:51
Related issues: 
There's a TODO for the root cause of #26654

**Comment by hasithaa** [comment] 2023-02-17 11:06
This issue has been marked as "Deferred" and will be revisited in the future when resources are available.

**Closed by hasithaa** 2023-02-17 11:06 UTC
Labels: Type/Task, Priority/High, Team/CompilerFE, Area/Parser, Deferred
