### ISSUE TITLE
Documentation information is null for the listener symbols

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#27667] opened 2021-01-05 11:08 UTC
**Description:**
$subject for the following,

```
# Test Listener
public listener module1:Listener lst = new module1:Listener(23);
```

for the variable symbol `lst`, the description information is missing

**Comment by MaryamZi** [comment] 2022-02-23 15:12
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/30770. Fixed in https://github.com/ballerina-platform/ballerina-lang/pull/31274 for Swan Lake Beta3.

**Closed by MaryamZi** 2022-02-23 15:12 UTC
Labels: Type/Bug, Status/Duplicate, Area/Compiler, Priority/Blocker, Team/CompilerFE, Points/2, SwanLakeDump
