### ISSUE TITLE
json.convert does not work properly

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-lang#13420] opened 2019-01-31 03:22 UTC
After json.convert converts a string to the json. The created json value can't be used to access it's members. It's full content can just be printed with io:println. "internal:parseJson" works properly though. The following code snippet shows the issue:-

```ballerina
import ballerina/io;
import ballerina/internal;

public function main() {
    string x = "{\"X\":50}";
    var j = internal:parseJson(x);
    if (j is json) {
        io:println("A: ", j.X);
    }
    json j2 = json.convert(x);
    io:println("B: ", j2);
    io:println("C: ", j2.X);
}
```

**Comment by hasithaa** [comment] 2019-01-31 04:38
JSON is a union. Calling convert on a union type seems not correct. This functionality has to be a utility function. But the internal package is not the correct place.

**Comment by SupunS** [comment] 2019-01-31 04:59
This can be achieved via the io lib. eg:
```ballerina
io:StringReader reader = new("{'foo':'bar'}");
json|error result = reader.readJson();
```

Need to clean up the internal package.

**Comment by warunalakshitha** [comment] 2019-01-31 04:59
json can hold any value type value and currently json.convert(<any value type value>) will directly assign to value to json type variable. It will not do any parsing. We can fix that. But the problem is calling convert method to parse a string is correct? As hasitha mentioned calling convert on union type seems incorrect for me.

**Comment by Shan1024** [comment] 2019-01-31 05:01
The string can be anything, so I also don't think parsing by default is a good option.

**Comment by lafernando** [comment] 2019-01-31 16:49
Yes, thank you for the clarification guys. And yes, we shouldn't be parsing
this, since any given string itself is a valid json.

**Closed** 2019-02-01 03:09 UTC
Labels: Component/Compiler, Severity/Blocker
