### ISSUE TITLE
[Bug]: Bad sad error when the `ballerina/test` import is below the import of a module of the mocked object

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#42037] opened 2024-01-24 07:10 UTC
### Description

Say we have 2 modules `db` and `user`. `db` has a db client and it is being mocked in the tests of `user`. When the import of `ballerina/test` module is above the import of `db`, there is a bad sad error.

``` ballerina
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-01-24 12:07:24,404] SEVERE {b7a.log.crash} - Cannot invoke "io.ballerina.runtime.internal.values.MapValue.containsKey(Object)" because "globalAnnotMap" is null 
java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.internal.values.MapValue.containsKey(Object)" because "globalAnnotMap" is null
        at io.ballerina.runtime.internal.AnnotationUtils.processFPValueAnnotations(AnnotationUtils.java:126)
        at gayaldassanayake.choreo_issue$0046A$test.0.tests.a_test.getMockClient(tests/a_test.bal:10)
        at gayaldassanayake.choreo_issue$0046db.0.db.getClient(db.bal)
        at gayaldassanayake.choreo_issue$0046db.0.$_init.$gen$$0046$0060init$0062(choreo_issue.db:4)
        at gayaldassanayake.choreo_issue$0046A$test.0.$_init.$moduleInit(choreo_issue.A)
        at gayaldassanayake.choreo_issue$0046A$test.0.$_init.$moduleExecute(choreo_issue.A)
        at gayaldassanayake.choreo_issue$0046A$test.0.$_init.$lambda$$moduleExecute$(choreo_issue.A)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to Reproduce

modules/db/db.bal
``` ballerina
import ballerina/sql;
import ballerinax/mssql;

mssql:Client dbClient = check getClient();

function getClient() returns mssql:Client|error {
    return new (
        "localhost",
        "config:database.user",
        "config:database.password",
        "billing_db",
        1443
    );
}

public function getValue() returns int {
    sql:ParameterizedQuery query = `INSERT INTO users (name, age) VALUES ("Nimal", 23)`;
    [return](sql:ExecutionResult|sql:Error) value = dbClient->execute(query);
    if (value is sql:ExecutionResult) {
        return 1;
    }
    return 0;
}
```

modules/user/test/testUser.bal
``` ballerina
import choreo_issue.db as _;
import ballerina/test;
import ballerinax/mssql;

@test:Mock {
    moduleName: "choreo_issue.db",
    functionName: "getClient"
}
function getMockClient() returns mssql:Client|error {
    return test:mock(mssql:Client);
}

// Tests. removed for brevity

```

If we change the order of imports in `testUser.bal`, i.e.
``` ballerina
import ballerina/test;
import choreo_issue.db as _;
import ballerinax/mssql;
```
then the error is not there.

An explanation for this issue is given in https://github.com/wso2-enterprise/internal-support-ballerina/issues/504#issuecomment-1809568898

### Related area

-> Test Framework

### Related issue(s) (optional)

https://github.com/wso2-enterprise/internal-support-ballerina/issues/567
https://github.com/wso2-enterprise/internal-support-ballerina/issues/504

**Comment by gayaldassanayake** [comment] 2024-01-24 07:40
The same issue is reported with https://github.com/ballerina-platform/ballerina-lang/issues/41706

**Comment by ShammiL** [comment] 2024-01-31 09:12
This failure is caused because the `moduleInit` execution order depends on the module imports order. Unless there are any dependencies between module imports the import order remains unchanged from the user defined order. 

Hence in this case, when the package module `db` is imported before the `ballerina/test`,  \`db` source module `init` is loaded before loading the test module `init`. Calling `test:mock(mssql:Client)` insinde the `db` module requires a global annotation map from the test module to be initiated but due to the order of `init` loading a null value is accessed instead, causing the noticed NPE. 
When the import order is changed, this failure won't be noticed as the `init` loading happens for the test module first.

While this is the expected behaviour for `moduleInit` execution and cannot be considered a bug, we are working on finding a way to perform the mocking while mitigating the mentioned issue.

**Comment by ShammiL** [comment] 2024-02-22 08:36
Closing this as a workaround was provided till the new mock interface in implemented.
The progress of the mock interface design can be tracked in #42193

**Closed by ShammiL** 2024-02-22 08:36 UTC
Labels: Type/Bug, Team/DevTools, Area/TestFramework
