### ISSUE TITLE
Sticky error in annotation tag

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#36343] opened 2022-05-27 13:30 UTC
The following is my scenario:

- There's a simple package with 3 public annotations in it.
- I built and pushed this package to the local repository.
- Then I created a new project and tried to use the previous package within it.

When trying to use one of those annotations, I'm getting an error highlighted for the annotation tag and it doesn't go away even though the program is valid.

![image](https://user-images.githubusercontent.com/6260009/170709004-4a4fea22-3fd2-4292-bdd3-6ad3a9d380ec.png)

**Comment by IMS94** [comment] 2022-06-15 11:17
The above diagnostic is coming when we don't have the annotation name specified
```
import ballerina/http;
import imesha/sample;

@sample:<cursor>
function addHeader(http:Request request) {
    
}
```
And when we type the name of the annotation, the diagnostic goes away (when I tried). Probably in the reported case, something else might have crashed the compiler and not recovering after text edits has caused this.

**Comment by IMS94** [comment] 2022-06-16 08:23
Closing this since it's not reproducible in both 2201.1.0 and 2201.0.3.

**Closed by IMS94** 2022-06-16 08:23 UTC
Labels: Type/Bug, Team/LanguageServer, Area/SyntaxHighlighting, Points/2, Reason/Invalid
