### ISSUE TITLE
Fit to screen doesn't work

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#18273] opened 2019-08-28 09:40 UTC
**Description:**
See below.

![aaa-1](https://user-images.githubusercontent.com/6178058/63844378-c3023780-c9a5-11e9-8685-943893f779f3.gif)

**Comment by roonyh** [comment] 2019-08-29 05:08
This is because fit to screen actually works as fit to width. And its already fit to width. This is a duplicate of #17787. Closing since we are tracking it there.

**Closed by roonyh** 2019-08-29 05:08 UTC
Labels: Area/Tooling, Component/Diagram, Priority/Blocker, Type/Bug
