### ISSUE TITLE
[Composer] Shutting down of the Composer closes the entire browser window

### ISSUE THREAD

**Issue by Gathika94** [ballerina-platform/ballerina-lang#9567] opened 2018-07-10 09:10 UTC
**Description:**
When a browser window instance is automatically started as a result of starting the composer, shutting down of the composer closes that entire window. It is inconvenient as all the tabs which were opened in that browser window get closed. However, this issue cannot be seen if there is an already opened browser window instance when the composer is started. 

**Steps to reproduce:**
1. Make sure there is no running instance of the default browser.
2. Run the composer using the terminal.
3. Go to the browser window which will be automatically opened by the composer and open new tabs within that window.
4. Shut down the composer (Ctrl+C in the terminal).

**Affected Versions:**
 0.975.1

**OS, DB, other environment details and versions:**
OS - Ubuntu 17.10, Ubuntu 18.04
Browser - Mozilla Firefox, Google Chrome

**Suggested Labels (optional):**
Bug

**Comment by DimalChandrasiri** [comment] 2018-07-16 06:51
@Gathika94 Could you mention the browser versions which this occurred?

**Comment by menuka94** [comment] 2018-07-16 11:56
Experienced the mentioned issue in Chrome Version 67.0.3396.99 (Official Build) (64-bit) @DimalChandrasiri

**Comment by Gathika94** [comment] 2018-07-16 12:34
@DimalChandrasiri  The browser version is Mozilla Firefox Quantum 61.0 (64-bit).

**Comment by DimalChandrasiri** [comment] 2018-07-20 09:00
Was able to reproduce this issue in ubuntu 18.04. Since the composer is moving to a standalone application IMO this wouldn't be a problem in the future. As for a suggestion, could you try opening up the composer using the `nohup` command? 

`nohup sh composer`

**Comment by Gathika94** [comment] 2018-07-22 06:08
@DimalChandrasiri  I tried with `nohup composer` command, but this issue was still there. If we have an already opened instance of the default browser when the composer is started,  shutting down of the composer does not close the browser window. When there is no running instance of default browser  at the time of starting the composer,  even if the composer is started using `nohup composer` command, shutting down of composer closes the entire browser window. Agree that this would not be a problem if composer is moving to a standalone application.

**Comment by DimalChandrasiri** [comment] 2018-07-23 08:19
@Gathika94 please try with the version 0.980 latest release? if not could u try with `nohup composer &` to separate the browser from the console.

**Comment by Manuri** [comment] 2018-08-20 09:39
@Gathika94 Were you able to try out @DimalChandrasiri 's suggestion. Please note that 0.981.0 is released therefore you can try on that.

**Comment by Gathika94** [comment] 2018-08-22 11:46
@Manuri - Yeah, I tried with 0.981.0. The ballerina composer started as a standalone application. Therefore, I believe this issue is resolved.

**Comment by Manuri** [comment] 2018-08-22 11:59
Thanks @Gathika94. Closing the issue based on your feedback.

**Closed by Manuri** 2018-08-22 11:59 UTC
Labels: Component/Composer, Type/Bug
