### ISSUE TITLE
Need Ballerina support for Microgateway Secure API Listener supported for HTTP/2.0

### ISSUE THREAD

**Issue by Varuni-Punchihewa** [ballerina-platform/ballerina-lang#10934] opened 2018-10-22 05:09 UTC
**Description:**
When you send an HTTP1.1 request via curl to the Microgateway secure API listener whose highest httpVersion supported is set to HTTP/2.0 , the ballerina runtime gives a null reference exception as follows.

error: ballerina/runtime:NullReferenceException
	at src:0.0.0:WorldBank_1_0_0.get_cf1a0a7a_801b_412a_9a14_28e231c9af1b(WorldBank_1_0_0.bal:100)

**Affected Versions:**
 ballerina platform version = 0.981.1

**OS, DB, other environment details and versions:**
Ubuntu 18.04.1 LTS
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment] 2018-10-22 08:41
This is a duplicate of #10936. Hence closing the issue.

**Comment by chamil321** [comment] 2018-10-22 08:42
This is a duplicate of #10936. Hence closing the issue.

**Closed by chamil321** 2018-10-22 08:41 UTC

**Comment by chamil321** [comment] 2018-10-22 08:43
This is a duplicate of #10936. Hence closing the issue.
