### ISSUE TITLE
java.lang.Exception: Couldn't find the invocation symbol!

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#29524] opened 2021-03-23 18:27 UTC
**Description:**
Following error was observed when the cursor was at position as seen in the image.

<img width="811" alt="Screenshot 2021-03-23 at 23 55 03" src="https://user-images.githubusercontent.com/690559/112198731-6de6e000-8c33-11eb-934d-b063d595807d.png">

Error
```
[Error - 11:54:52 PM] Operation 'text/signature' failed! {uri: '/Users/kishanthan/WSO2/work/projects/ballerina-projects/test_hackathon/msmp_with_nats/publisher.bal', [9:9], error: 'Couldn't find the invocation symbol!'}
java.lang.Exception: Couldn't find the invocation symbol!
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$signatureHelp$2(BallerinaTextDocumentService.java:210)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by nadeeshaan** [comment] 2021-03-24 04:31
Duplicate of #29549. Hence closing the issue.

**Closed by nadeeshaan** 2021-03-24 04:31 UTC
Labels: Status/Duplicate, SwanLakeDump, Team/LanguageServer, Type/Bug, Version/SLAlpha3
