### ISSUE TITLE
Incorrect behavior of `lang.int:abs` function

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#32590] opened 2021-09-06 16:22 UTC
**Description:**
$title

**Steps to reproduce:**
```ballerina
import ballerina/io;
public function main() {
    int a1 = -9223372036854775807 - 1;
    int b1 = a1.abs(); // should panic

    io:println(b1); 
}
```
```ballerina
import ballerina/io;
public function main() {
    int a1 = (-9223372036854775807 - 1).abs(); // should panic
    io:println(a1);
}
```
These print `-9223372036854775808`, but should panic at runtime since `9223372036854775808` would overflow

**Affected Versions:**
slbeta2

**Comment by HindujaB** [comment] 2021-11-08 11:29
The spec on `int` type says, 
> The int type consists of integers between -9,223,372,036,854,775,808 and 9,223,372,036,854,775,807 

Which indicates the int range to be (`-2^63`  to `2^63 - 1`). 
Note that, here the value `-2^63 - 1` would overflow. 
The compiler validation for `int` is also complies to this range. 
![Screenshot from 2021-11-08 16-51-36](https://user-images.githubusercontent.com/28644893/140733495-fb0b72ba-1f92-444e-b35b-8c01b393fdb9.png)

But the langlib says that value  `-9,223,372,036,854,775,808` would overflow
https://github.com/ballerina-platform/ballerina-spec/blob/11277d73b77f5f0c2871c7e7f04cc803ca9f31b2/lang/lib/int.bal#L57

Due to this inconsistency between the langlib spec and the lang spec, we need to confirm the expected behavior.

**Comment by HindujaB** [comment] 2021-11-09 09:06
We have behavior inconsistensies for the int value `-9,223,372,036,854,775,808`.
Eventhough the `lang.int` specifies that the value will overflow for  `-9,223,372,036,854,775,808`,
https://github.com/ballerina-platform/ballerina-spec/blob/11277d73b77f5f0c2871c7e7f04cc803ca9f31b2/lang/lib/int.bal#L57
It is not restricted in compiler. 
![Screenshot from 2021-11-08 16-51-36](https://user-images.githubusercontent.com/28644893/140894019-4ab765c7-8f77-4974-ad05-fb6f13a02c1a.png)

And the arithmetic operations that results in `-9,223,372,036,854,775,808` are also not panicking for overflow. 
```ballerina
public function main() {
    int a = -9223372036854775806 - 2; // does not panic
    int b = -9223372036854775807 - 2; // panics
}
```
So, it would be an inconsistency if we panic only for `int:abs()`. 
What should be the expected behavior? 
Do we need to panic for all the above cases? @hasithaa

**Comment by hasithaa** [comment] 2021-11-09 10:01
The expression `-9,223,372,036,854,775,808` will overflow, But not the value `-9,223,372,036,854,775,808`. 

This is how the evaluation of the expression will overflow. The said Expression is an unary expression of operator `-` and literal value of `9,223,372,036,854,775,808`. But literal `9,223,372,036,854,775,808` is larger than `int:MAX_VALUE`. So when evaluating it, it will overflow. Theoretically, we can't write the expression `-9,223,372,036,854,775,808`, that is why it is written in different way here.  https://github.com/ballerina-platform/ballerina-spec/blob/11277d73b77f5f0c2871c7e7f04cc803ca9f31b2/lang/lib/int.bal#L57

But in JBallerina we are doing constant folding, at the compile time. So `-9,223,372,036,854,775,808` is parsed as `int:MIN_VALUE`, That is why it is not overflowing.

**Comment by HindujaB** [comment] 2021-11-16 08:56
Fix merged to beta4. Hence, closing this.

**Closed by HindujaB** 2021-11-16 08:56 UTC
Labels: Type/SpecDeviation, Team/jBallerina, Lang/LangLib, Points/1.5, Error/TypeA
