### ISSUE TITLE
Content Length Header mismatch

### ISSUE THREAD

**Issue by jaddjennings** [ballerina-platform/ballerina-lang#19621] opened 2019-10-28 17:18 UTC
**Description:**
When setting the payload of an http request using setBinaryPayload(), the content length header is automatically set to an amount that does not equal the length of the byte array when reading all bytes from the readable byte channel. The content length header is set in the transport layer, so I don't know of a way to get the value besides by http logging. My workaround is using setFileAsPayload(), when I use that function, the content lengths match up. Also, this only occurs with a file that has about 300 bytes.

**Steps to reproduce:**

create http client

1. create http client
2. set payload using setBinaryPayload with content below that is within quotations
3. Observe http log, content-length should be 259 but it gets changed to 316
4. set payload using setFileAsPayload and observe how content-length is the correct 259

payload content:
_"teststring objectName = "README1.md";
string objectName = "README1.md";
string objectName = "README1.md";
string objectName = "README1.md";

string objectName = "README1.md";

string objectName = "README1.md";

vstring objectName = "README1.md";

Zd
v
D
v
Dv
"_
**Affected Versions:**
1+
**OS, DB, other environment details and versions:**
Mac OS
**Related Issues (optional):**

**Suggested Labels (optional):**
Area/Language

**Suggested Assignees (optional):**

**Comment by chamil321** [comment] 2019-11-07 14:18
The issue is not reproducible.

```ballerina
import ballerina/http;
import ballerina/log;
import ballerina/io;

http:Client clientEP = new("http://localhost:9092/backend");
service passthrough on new http:Listener(9090) {
    @http:ResourceConfig {
        path: "/"
    }
    resource function passthrough(http:Caller caller, http:Request req) returns error? {
        http:Request request = new;
        string srcPath = "/path/to/file";
        io:ReadableByteChannel srcCh = check io:openReadableFile(srcPath);
        byte[] body = check srcCh.read(1000);
        request.setBinaryPayload(<@untainted> body);
        http:Response clientResponse = check clientEP->post("/", request);

        var result = caller->respond(clientResponse);
        if (result is error) {
            log:printError("Error sending response", err = result);
        }
    }
}
```
Outbound network tracelog

```
POST /hello/ HTTP/1.1
content-type: application/octet-stream
host: localhost:9092
user-agent: ballerina/1.0.3
connection: keep-alive
content-length: 259  
[2019-11-07 19:41:53,693] TRACE {http.tracelog.upstream} - [id: 0x4f98f351, correlatedSource: 0xf63afa28, host:/127.0.0.1:59622 - remote:localhost/127.0.0.1:9092] OUTBOUND: DefaultLastHttpContent(data: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 259, cap: 8192), decoderResult: success), 259B
teststring objectName = "README1.md";
string objectName = "README1.md";
string objectName = "README1.md";
string objectName = "README1.md";

string objectName = "README1.md";

string objectName = "README1.md";

vstring objectName = "README1.md";

Zd
v
D
v
Dv
```
We cannot experience any content length difference.
@jaddjennings Will you be able to provide your source code to understand the aforementioned behavior?

**Comment by jaddjennings** [comment] 2019-11-13 14:51
My issue occurred with version 1.01, I need to re-verify for 1.03

**Comment by chamil321** [comment] 2020-02-17 04:43
Issue is not reproducible in ballerina/1.0.3 and tested well, Hence closing the issue.

**Closed by chamil321** 2020-02-17 04:43 UTC
Labels: Area/StandardLibs, Component/HTTP, Resolution/Cannot Reproduce, Type/Bug
