### ISSUE TITLE
Bad. Sad. when there's a JDBC init issue.

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#17828] opened 2019-08-16 03:00 UTC
**Description:**
$subject. For example, when there's a `Failed to initialize pool`, `No permission for user:` issue with JDBC init, that ends up in a Bad. Sad.

```
PS C:\Users\ballerina-dev\Desktop\Hackathon\wum-server> ballerina run .\target\bin\update_service-executable.jar
error: {ballerinax/java.jdbc}ApplicationError message=Error in sql connector configuration: Failed to initialize pool: The server time zone value 'GMT Summer Time' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.:The server time zone value 'GMT Summer Time' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support. cause=null
        at ballerinax.java_jdbc:createClient(jdbc_client.bal:88)
           ballerinax.java_jdbc.$value$Client:__init(client_endpoint.bal:27)
ballerina: Oh no, something really went wrong. Bad. Sad.
...
```

**Steps to reproduce:**
Try to init jdbc client with a user/pass of a user without required permissions.

**Affected Versions:**
1.0.0-beta testing

**OS, DB, other environment details and versions:**
Windows, VS Code, 1.0.0-beta

**Comment by Manuri** [comment] 2019-08-19 10:07
This should be due to https://github.com/ballerina-platform/ballerina-lang/issues/17774

Once https://github.com/ballerina-platform/ballerina-lang/issues/17774 is fixed, will verify this and close.

**Comment by Manuri** [comment] 2019-08-26 13:19
Didn't get reproduced after #17774 was resolved. Hence closing.

**Closed by Manuri** 2019-08-26 13:19 UTC
Labels: Area/StandardLibs, BetaTesting, Component/Data, Type/Bug
