### ISSUE TITLE
[Improvement]: Project API improvements for client declaraion feature

### ISSUE THREAD

**Issue by malinthar** [ballerina-platform/ballerina-lang#37734] opened 2022-09-14 08:34 UTC
### Description

Consider the following project structure. Note that I have generated the module corresponding to the client declaration.

Improvement 1 : When I reload the project the diagnostic is still there
![image](https://user-images.githubusercontent.com/35211477/190103191-b2d1ce7d-193f-4e05-b7d1-ffb7d5f7e434.png)

Improvement 2: `ProjectPaths.packageRoot() ` for a the file uril of the newly generated module's file returns a incorrect path for package root. Due to this the modules in the generated directory are considered as separate  projects, 

```Ballerina
import ballerina/io;

client "https://postman-echo.com/get?name=projectapiclientplugin" as myapi;

public function main() {
    // myapi:client x;
    // myapi:ClientConfiguration config;
    
    io:println("Hello, World!");
}
```

**Comment by gayalkuruppu** [comment] 2022-09-26 12:04
1. Module level completions are not working with this NPE

steps to reproduce: 
```
client "https://postman-echo.com/get?name=projectapiclientplugin" as myapi; 
<cur>
```
```
[Error - 5:20:32 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/gayal/Documents/learnBal/client_decl_test/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
	at io.ballerina.projects.ModuleContext.resolveDependencies(ModuleContext.java:348)
	at io.ballerina.projects.PackageContext.resolveModuleDependencies(PackageContext.java:317)
	at io.ballerina.projects.PackageContext.resolveDependencies(PackageContext.java:305)
	at io.ballerina.projects.PackageResolution.resolveDependencies(PackageResolution.java:472)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:111)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:116)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:251)
	at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:66)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:93)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:223)
	at io.ballerina.projects.Package.getCompilation(Package.java:150)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:272)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:241)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:236)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.handleReferences(SemanticTokensVisitor.java:668)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.addSemanticToken(SemanticTokensVisitor.java:654)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:134)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.accept(FunctionDefinitionNode.java:66)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:870)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:107)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$16(BallerinaTextDocumentService.java:652)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

2. When the generated client is changed (steps to reproduce: when adding a new remote method), that change is not updated until we do a reload. 

```
public type ClientConfiguration record {
    string specVersion;
};

public isolated client class 'client {
    public final string specVersion;

    public function init(*ClientConfiguration config) {
        self.specVersion = config.specVersion;
    }

    remote function getSpecVersion() returns string {
        lock {
            return self.specVersion;
        }
    }
    
    remote function name() { // new method
        
    }
}
```
```
client "https://postman-echo.com/get?name=projectapiclientplugin" as myapi; 


public function main() {
    myapi:ClientConfiguration config = {specVersion : "3.0.0"};
    myapi:client cl = new (config);
    string specVersion = cl-><cur>; // try completions here after the update
    
}
```

**Comment by gayalkuruppu** [comment] 2022-10-03 02:15
> @azinneera
> 
> 1. Module level completions are not working with this NPE
> 
> steps to reproduce:
> 
> ```
> client "https://postman-echo.com/get?name=projectapiclientplugin" as myapi; 
> <cur>
> ```
> 
> ```
> [Error - 5:20:32 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/gayal/Documents/learnBal/client_decl_test/main.bal', error: 'java.lang.NullPointerException'}
> java.lang.NullPointerException
> 	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
> 	at io.ballerina.projects.ModuleContext.resolveDependencies(ModuleContext.java:348)
> 	at io.ballerina.projects.PackageContext.resolveModuleDependencies(PackageContext.java:317)
> 	at io.ballerina.projects.PackageContext.resolveDependencies(PackageContext.java:305)
> 	at io.ballerina.projects.PackageResolution.resolveDependencies(PackageResolution.java:472)
> 	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:111)
> 	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:116)
> 	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:251)
> 	at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:66)
> 	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:93)
> 	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:223)
> 	at io.ballerina.projects.Package.getCompilation(Package.java:150)
> 	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:272)
> 	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:241)
> 	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:236)
> 	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.handleReferences(SemanticTokensVisitor.java:668)
> 	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.addSemanticToken(SemanticTokensVisitor.java:654)
> 	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:134)
> 	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.accept(FunctionDefinitionNode.java:66)
> 	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:870)
> 	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:107)
> 	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
> 	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$16(BallerinaTextDocumentService.java:652)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> ```
> 
> 2. When the generated client is changed (steps to reproduce: when adding a new remote method), that change is not updated until we do a reload.
> 
> ```
> public type ClientConfiguration record {
>     string specVersion;
> };
> 
> public isolated client class 'client {
>     public final string specVersion;
> 
>     public function init(*ClientConfiguration config) {
>         self.specVersion = config.specVersion;
>     }
> 
>     remote function getSpecVersion() returns string {
>         lock {
>             return self.specVersion;
>         }
>     }
>     
>     remote function name() { // new method
>         
>     }
> }
> ```
> 
> ```
> client "https://postman-echo.com/get?name=projectapiclientplugin" as myapi; 
> 
> 
> public function main() {
>     myapi:ClientConfiguration config = {specVersion : "3.0.0"};
>     myapi:client cl = new (config);
>     string specVersion = cl-><cur>; // try completions here after the update
>     
> }
> ```

Part 1 is resolved and part 2 is tracked under https://github.com/ballerina-platform/ballerina-lang/issues/38017

**Comment by azinneera** [comment] 2022-10-03 07:15
Closing since the Project API fixes are done.

**Closed by azinneera** 2022-10-03 07:15 UTC
Labels: Type/Improvement, Priority/Blocker, Team/DevTools, Area/ProjectAPI
