### ISSUE TITLE
ClientInitializationFailureTest.testClientEndpointFailureInResource test fails intermittently

### ISSUE THREAD

**Issue by vinok88** [ballerina-platform/ballerina-lang#13487] opened 2019-02-06 09:56 UTC
**Description:**
This is disabled at the moment.

Please find the build error below.

java.lang.AssertionError: expected object to not be null at org.ballerinalang.test.service.websocket.ClientInitializationFailureTest.testClientEndpointFailureInResource(ClientInitializationFailureTest.java:54)

**Comment by NatashaWso2** [comment] 2019-02-06 17:24
This is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/13338, hence closing this issue.

**Closed by NatashaWso2** 2019-02-06 17:24 UTC
Labels: Component/WebSocket, Severity/Critical, Type/Test Failure
