### ISSUE TITLE
Memory leackage in BLock

### ISSUE THREAD

**Issue by tharmini** [ballerina-platform/ballerina-lang#20660] opened 2020-01-17 09:44 UTC
**Description:**
Memory leakage is found when calling a lock.  When doing memory analyzing it is found that it takes more memory in the org.ballerinalang.jvm.BLock . The heap_dump file and jar file [attached](https://drive.google.com/drive/folders/1zUL1eOFmZ9k0lRLJ8SZvAwdsRHqU9Nae?usp=sharing)

**Affected Versions:**
1.1.0

**Comment by warunalakshitha** [comment] 2021-06-25 09:53
Can you please attach a sample ballerina program to reproduce this issue?  Any other appropriate steps would be appreciated.

**Comment by warunalakshitha** [comment] 2021-06-29 06:56
I am closing this issue since the it seems to be outdated with the latest code base. Please reopen this if you observe the issue again.

**Closed by warunalakshitha** 2021-06-29 06:56 UTC
Labels: Lang/Concurrency, Priority/High, SwanLakeDump, Team/jBallerina, Type/Bug
