### ISSUE TITLE
check expression with custom native function is throwing error

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-lang#14626] opened 2019-03-22 05:43 UTC
**Description:**
I have a native function implementation as below which returns record array or an error:
```ballerina
public extern function readSwaggerFile(string swaggerFilePath) returns (ApiDefinition[]|error);
```
When I try to invoke the function with as below compilation fails.
```ballerina
import celleryio/cellery;

cellery:ApiDefinition[] employeeAPIdefn = check cellery:readSwaggerFile("./resources/employee.swagger.json");

public function main(string... args) {
 }
```
Error message is as below:
```
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
```
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2995123/ballerina-internal.log)

**Steps to reproduce:**
1. Create a native function returning an error and try to access as described above.

**Affected Versions:** 0.990.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment] 2019-04-01 12:47
This issue is reproducible when using `check` at module level even with a non-native function call or some other expression. Closing this issue since #12663 is already created to track the same.

**Closed by MaryamZi** 2019-04-01 12:47 UTC
Labels: Component/Compiler, Resolution/Duplicate, Type/Bug
