### ISSUE TITLE
Clarification regarding the order of let and where clauses in query expression

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#23498] opened 2020-05-26 07:32 UTC
**Description:**
When `where` clause uses a symbol definition given in the `let` clause, the `where` clause is required to come after the `let` clause. Otherwise, it would give a compilation error with `undefined symbol`. But according to the current implementation, if the `where` clause doesn't use such definitions, the order of the `let` and `where` clauses doesn't matter. We need to discuss whether we need to explicitly provide an order for the clauses. 

**Sample:**
```
Person[] outputPersonList =
            from var { firstName: nm1, lastName: nm2, deptAccess: d } in personList
            where nm1 == filterName
            let string filterName = "Alex"
            select {
                   firstName: nm1,
                   lastName: nm2,
                   deptAccess: "Operations"
            };
```
Error
`undefined symbol 'filterName'`

**Comment by mohanvive** [comment] 2020-05-28 06:18
It is expected behavior since let clause is defined after the where clause. Hence, closing the issue.

**Closed by mohanvive** 2020-05-28 06:18 UTC
Labels: Area/Language
