### ISSUE TITLE
[Bug]: XML attribute access with qualified identifier is incorrect

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#38973] opened 2022-12-06 09:12 UTC
### Description

Consider the following example:

`mod1` has:
```ballerina
public const string KEY = "{http://ballerina.com/ns0}key";
```

Default module has:
```ballerina
xmlns "http://ballerina.com/ns0" as ns0;

public function main() returns error? {
    xml x2 = xml `<foo ns0:key="1">hello</foo>`;
    string id2 = check x2.mod1:KEY;
}
```
When run using `bal run`, following error is shown:
```
error: {ballerina/lang.xml}XMLOperationError {"message":"attribute '{http://ballerina.com/ns0}KEY' not found"}
```

However, as per the spec, 
```
It is also allowed for the xml-attribute-name to be specified as a qualified-identifier, in which the prefix is a module-prefix declared using an import-decl. In this case the qualified-identifier must refer to a module-const-decl of type string, and the attribute name string is the value of the referenced constant. This allows e.g. xml:lang to work. 
```
the value of the constant is considered as the attribute name. But seems like the name of the constant is considered as the name of the attribute.

### Affected Version(s)
2203.3.0

### Related area

-> Compilation

**Comment by MaryamZi** [comment] 2022-12-07 03:41
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/32624.

**Closed by MaryamZi** 2022-12-07 03:41 UTC
Labels: Type/Bug, Status/Duplicate, Team/CompilerFE, Reason/Invalid
