### ISSUE TITLE
Return value from select query if passed to jsonutils causes null pointer

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-lang#19802] opened 2019-11-06 11:11 UTC
**Description:**
The select query on a `jdbc:Client` returns a table event if the result of the query is a table of subrecord type and returned value is a super record type. In this case (result is empty) if the table returned is called with the `jsonutils:fromTable(tableVal)` then a null pointer appears in ballerina-internal.log

```
[2019-11-06 15:14:12,892] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.jvm.JSONUtils.toJSON(JSONUtils.java:577)
	at org.ballerinalang.stdlib.jsonutils.FromTable.fromTable(FromTable.java:46)
	at ballerina.jsonutils.jsonutils.fromTable(jsonutils.bal:37)
	at choreo.api.$value$ApplicationService__service_1.findApplicationByCriteria(application_service.bal:63)
	at choreo.api.$value$ApplicationService__service_1.call(application_service.bal)
	at org.ballerinalang.jvm.values.connector.Executor.lambda$submit$0(Executor.java:76)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:411)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:202)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:175)
	at java.lang.Thread.run(Thread.java:748)
 
```
**Steps to reproduce:**
Select query that returns table of Application :
```
function getResult() returns table<domain:Application> {
    table<domain:ApplicationResponse> result = check connection->select(QUERY_SELECT_ALL_APPLICATIONS, domain:ApplicationResponse,  userId);
    return result;
}
```

The function returns a table of `Application` that is a supertype of `ApplicationResponse`

Pass the result(table of `Application`) to jsonUtils:
`jsonutils:fromTable(result)`

```
public type Application record {|
    string id;
    string name;
    string description;
    string user_id;
|};
```
```
public type ApplicationResponse record {|
    string id;
    string name;
    string description;
|};
```

**Affected Versions:**
1.0.2
**OS, DB, other environment details and versions:**
Mysql 8.0.17

**Comment by wggihan** [comment] 2019-11-08 11:20
Can you please share the reproducible code?

**Comment by riyafa** [comment] 2019-11-08 14:25
This is an issue discussed with @anupama-pathirage

**Comment by anupama-pathirage** [comment] 2019-11-13 04:51
Sample code to reproduce the issue

```ballerina
import ballerinax/java.jdbc;
import ballerina/io;
import ballerina/jsonutils;

jdbc:Client testDB = new ({
    url: "jdbc:h2:file:./testissue/testdb",
    username: "test",
    password: "test",
    poolOptions: { maximumPoolSize: 5 }
});

public type Application record {|
    string id;
    string name;
    string description;
    string user_id;
|};

public type ApplicationResponse record {|
    string id;
    string name;
    string description;
|};

public function main() returns error? {
    populateData();
    table<Application> t = check getResult();
    io:println("table:", t);
    json j = jsonutils:fromTable(t);
    clearData();
}

function populateData() {
    var ret = testDB->update("CREATE TABLE APPLICATION (id VARCHAR(30), name VARCHAR(30), description VARCHAR(30), userid  VARCHAR(30))");
    io:println(ret);

    ret = testDB->update("INSERT INTO APPLICATION(id,name,description, userid) VALUES ('AAA', 'app1', 'app1-desc', '1')");
    io:println(ret);
}

function clearData() {
    var ret = testDB->update("DROP TABLE APPLICATION");
    io:println(ret);
}

function getResult() returns  @tainted table<Application>|error {
    table<ApplicationResponse> result =  check testDB->select("Select id, name, description from APPLICATION where userid = ?", ApplicationResponse,  "1");
    return result;
}
```

**Comment by riyafa** [comment] 2019-11-13 09:27
Thank you!

Without the println in the following code also the error was noticed if I am not mistaken:
```
public function main() returns error? {
    populateData();
    table<Application> t = check getResult();
    io:println("table:", t);
    json j = jsonutils:fromTable(t);
    clearData();
}
```

**Comment by SupunS** [comment] 2019-11-19 06:20
I think the following should fail at compile time:

```ballerina
function getResult() returns  @tainted table<Application>|error {
    table<ApplicationResponse> result =  check testDB->select("Select id, name, description from APPLICATION where userid = ?", ApplicationResponse,  "1");
    return result;
}
```

Here we have allowed assigning a super-type `table<ApplicationResponse>` to a subtype `table<Application>`. A simple sample is bellow:
```ballerina
table<ApplicationResponse> appResp =  checkpanic testDB->select("Select id, name, description from APPLICATION where userid = ?", ApplicationResponse,  "1");
table<Application> app = appResp;
```

But this is not correct IMHO since it violates the sub-typing. ` table<Application>` can be assigned to `table<ApplicationResponse>`, but not the other-way around.

@hasithaa Thoughts?

**Comment by SupunS** [comment] 2019-11-19 09:37
@riyafa Despite the type validation issue, seems like you are trying to get a result with 3 columns, and pass it to someone who expect a result with 5 columns.. Thats doesn't seems correct to me. Is that a valid use-case?

**Comment by riyafa** [comment] 2019-11-19 09:44
This is not a valid usecase. It doesn't give me a pointer to why this is not valid. It gives a null pointer later on in the processing step. I fixed it by changing the return value:

```
function getResult() returns table<domain:ApplicationResponse> {
    table<domain:ApplicationResponse> result = check connection->select(QUERY_SELECT_ALL_APPLICATIONS, domain:ApplicationResponse,  userId);
    return result;
}
```

**Comment by SupunS** [comment] 2019-11-19 10:10
Ack. Thanks for the update.

So the root cause/issue is the table type validations are being not properly implemented, and as a result it doesn't give a proper error at compile-time/runtime. This is a spec deviation in the implementation. I have created a separate issue https://github.com/ballerina-platform/ballerina-lang/issues/19970 for tracking.

Im closing this one, since the specific use-case is resolved. Feel free to reopen if you need further assistant with this.

**Closed by SupunS** 2019-11-19 10:10 UTC
Labels: Area/jBallerina, Points/2, Priority/High, Type/Bug
