### ISSUE TITLE
[Native Functions] Need a default way to handle/log run-time errors 

### ISSUE THREAD

**Issue by mohanvive** [ballerina-platform/ballerina-lang#8552] opened 2018-05-14 12:13 UTC
**Description:**
At the moment, there is no any default mechanism to handle/log the runtime errors that caused when calling native function. 

Let's say, there is a native function defined but function definition does not explicitly says there is a possibility of an error can be thrown. In this situation, if there is any runtime exception thrown by the native function then the respective error trace is logged anywhere.

**Steps to reproduce:**
- Create a native function without specifying error as possible return type. 
- Throw an exception from the native function implementation.

**Comment by hasithaa** [comment] 2019-08-01 14:37
@SupunS This seems to be fixed with JBallerina. When panic happens original error is included in the stack trace. For others, developers can use runtime API to attache the cause to Ballerina error value.  Can you verify?

**Comment by vinok88** [comment] 2019-08-12 10:04
This can be achieved using BallerinaErrors class in runtime.

**Closed by vinok88** 2019-08-12 10:04 UTC
Labels: Area/JBallerina, Component/BVM, Type/Bug
