### ISSUE TITLE
Building a project which uses JDBC crashes the runtime when running tests

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#17375] opened 2019-08-02 12:30 UTC
The above mentioned issue seems to be due to the error value being wrapped in the wrong type of exception.
https://github.com/ballerina-platform/ballerina-lang/blob/6881b7afb01a2b98e2dac09681ef44ea8d8cb989/misc/testerina/modules/testerina-core/src/main/java/org/ballerinalang/testerina/core/entity/TesterinaFunction.java#L171

```
[2019-08-02 17:46:33,063] ERROR {org.ballerinalang.tool.Main} - error {ballerinax/java.jdbc}ApplicationError message=Error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/StudentDetailsDB:No suitable driver cause=null 
org.ballerinalang.util.exceptions.BallerinaException: error {ballerinax/java.jdbc}ApplicationError message=Error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/StudentDetailsDB:No suitable driver cause=null
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:171)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.invoke(TesterinaFunction.java:90)
	at org.ballerinalang.testerina.core.BTestRunner.lambda$execute$33(BTestRunner.java:589)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ballerinalang.testerina.core.BTestRunner.execute(BTestRunner.java:571)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:127)
	at org.ballerinalang.testerina.util.TesterinaUtils.executeTests(TesterinaUtils.java:204)
	at org.ballerinalang.packerina.task.RunTestsTask.execute(RunTestsTask.java:64)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:197)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: error {ballerinax/java.jdbc}ApplicationError message=Error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/StudentDetailsDB:No suitable driver cause=null
	at org.ballerinalang.jvm.BallerinaErrors.createError(BallerinaErrors.java:67)
	at org.ballerinax.jdbc.exceptions.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:72)
	at org.ballerinax.jdbc.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:255)
	at org.ballerinax.jdbc.datasource.SQLDatasource.init(SQLDatasource.java:57)
	at org.ballerinax.jdbc.datasource.PoolOptionsWrapper.createAndInitDatasource(PoolOptionsWrapper.java:75)
	at org.ballerinax.jdbc.datasource.PoolOptionsWrapper.lambda$retrieveDatasource$1(PoolOptionsWrapper.java:68)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.ballerinax.jdbc.datasource.PoolOptionsWrapper.retrieveDatasource(PoolOptionsWrapper.java:67)
	at org.ballerinax.jdbc.functions.CreateClient.createSQLDBClient(CreateClient.java:75)
	at org.ballerinax.jdbc.functions.CreateClient.createClient(CreateClient.java:48)
	at ballerinax.java_jdbc.jdbc_client.createClient(jdbc_client.bal:88)
	at ballerinax.java_jdbc.Client.__init(client_endpoint.bal:27)
	at ballerinax.java_jdbc.Client.call(client_endpoint.bal)
	at pubudu.transform.___init.pubudu_transform_0_1_0__init_(transform:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ballerinalang.testerina.core.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:157)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:414)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:198)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:169)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by warunalakshitha** [comment] 2020-02-14 05:40
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/19069

**Closed by warunalakshitha** 2020-02-14 05:40 UTC
Labels: Area/TestFramework, Component/Testerina, Type/Bug
