### ISSUE TITLE
Bal run crashes when running inside a directory with a space separated name

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-lang#32863] opened 2021-09-22 14:59 UTC
**Description:**
$subject

**Steps to reproduce:**
1. Create a directory with a space-separated name (eg: "Hello World").
2. Go inside that directory and create a ball file with the main function.
3. Run the sample bal file.

The application crashes with this error:
```
Error: Could not find or load main class World
Caused by: java.lang.ClassNotFoundException: World
```

**Affected Versions:**
SLBeta3 RC3

**OS, DB, other environment details and versions:**
MacOS

**Comment by HindujaB** [comment] 2021-12-01 08:49
This happens in our `bal` script execution even before we launch the `cli` commands. This is because we use  `pwd` command in out scripts to pass the path arguments where it does not escape the space character in the path.
This needs to be fixed from the `bal` script level.

**Comment by HindujaB** [comment] 2021-12-02 09:04
duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/32740.
Hence, closing this.

**Closed** 2021-12-02 09:05 UTC
Labels: Type/Bug, Team/jBallerina
