### ISSUE TITLE
[Export] Text not properly aligned in the exported .svg format

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/ballerina-lang#6412] opened 2018-04-03 10:46 UTC
<a href="https://github.com/erandidesilva"><img src="https://avatars1.githubusercontent.com/u/15624590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erandidesilva](https://github.com/erandidesilva)**
_Thursday Nov 23, 2017 at 12:09 GMT_
_Originally opened as https://github.com/ballerina-lang/composer/issues/4712_

----

Please see the attached diagram, the text inside the boxes are not properly aligned.

[image.zip](https://github.com/ballerinalang/composer/files/1498956/image.zip)

**Comment by uthaiyashankar** [comment] 2018-04-03 10:46
<a href="https://github.com/NipunaMarcus"><img src="https://avatars0.githubusercontent.com/u/9109762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NipunaMarcus](https://github.com/NipunaMarcus)**
_Friday Nov 24, 2017 at 09:54 GMT_

----

This is because of the limitations of image viewers to render dominant-baseline css property. I'm working on changing these property to supporting property

**Comment by hevayo** [comment] 2018-06-11 05:08
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/6280

**Closed by hevayo** 2018-06-11 05:08 UTC
Labels: Imported, Priority/Normal, Type/Bug, component/Composer
