### ISSUE TITLE
Misleading parser error message

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-lang#30030] opened 2021-04-17 01:17 UTC
**Description:**
If I write a simple Ballerina code like below, with a missing semi-colon, the parser error message should be a"missing semi colon`. Instead, I'm getting the below error message. Shouldn't the error message indicate the quickest way to recover?

```ballerina
type R record {| int x; |};

public function main() {
    R a = {x: 3} // MISSING ;
    R|error b = a;
}
```

```
java.lang.IllegalStateException: There were compilation errors: 
ERROR [stream-test.bal:(3:10,4:5)] operator '+' not defined for 'record {| int x; |}' and 'typedesc<R>'
ERROR [stream-test.bal:(4:0,4:0)] missing plus token
ERROR [stream-test.bal:(4:6,4:17)] undefined error type descriptor 'b'
ERROR [stream-test.bal:(4:14,4:14)] missing identifier
ERROR [stream-test.bal:(4:14,4:14)] missing open parenthesis token
ERROR [stream-test.bal:(4:14,4:17)] missing positional arg in error constructor
ERROR [stream-test.bal:(4:17,4:17)] missing close parenthesis token
    at org.ballerinalang.test.BRunUtil.getInvokedFunction(BRunUtil.java:1240)
    at org.ballerinalang.test.BRunUtil.invokeFunction(BRunUtil.java:1259)
    at org.ballerinalang.test.BRunUtil.invoke(BRunUtil.java:199)
    at org.ballerinalang.test.types.stream.SandboxTest.testGlobalStreamConstruct(SandboxTest.java:43)
```

**Comment by rdulmina** [comment] 2021-04-20 03:53
Closing due to duplicate of #25317. Please feel free to reopen if needed.

**Closed by rdulmina** 2021-04-20 03:53 UTC
Labels: Area/Parser, Team/CompilerFE, Type/Bug, Type/Improvement
