### ISSUE TITLE
Highlight/show TODO’s as info diagnostics

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#36220] opened 2022-05-19 10:45 UTC
**Description:**
Developers use `TODOs` to keep track of future work within the projects. In IntelliJ IDEA, there's a separate panel to view TODOs. But due to the limitations in language server protocol, we cannot give a similar experience. 

But looking at the RedHat java plugin, it shows TODOs as info diagnostics under the problems tab. This is a good way for the users to keep track of TODOs and if we can implement the same for Ballerina, it will be helpful.

**Describe your problem(s)**
See description

**Describe your solution(s)**
We need to analyze the documentation nodes in a separate compiler plugin and publish INFO diagnostics for TODOs we find.

**Comment by KavinduZoysa** [comment] 2024-09-17 19:49
Duplicate of #36137

**Closed by KavinduZoysa** 2024-09-17 19:49 UTC
Labels: Type/Improvement, Priority/Low, Team/LanguageServer, Area/Diagnostics
