### ISSUE TITLE
Auto completion for function arguments within doc comments

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#21116] opened 2020-02-17 09:51 UTC
**Description:**
Add auto-completion for the function arguments within the doc comments.

**Comment by mohanvive** [comment] 2021-03-30 09:46
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/25575 .

**Closed by mohanvive** 2021-03-30 09:46 UTC
Labels: Team/LanguageServer, Type/NewFeature
