### ISSUE TITLE
Unexpected/inconsistent behavior of JSON to record conversion

### ISSUE THREAD

**Issue by jgeofil** [ballerina-platform/ballerina-lang#12935] opened 2018-12-27 20:27 UTC
**Description:**
Conversion from JSON to record returns error when when optional or defaultable record fields are missing in the JSON. However, conversion is successful when JSON contains additional fields not present in the record definition.

**Steps to reproduce:**
```ballerina
type Person1 record {
    string fname;
    string lname = "";
};

type Person2 record {
    string fname;
    string? lname;
};

public function main () returns error?{

    json fn = {fname: "John"};
    json fnlnag = {fname: "John", lname: "Doe", age:30};

    any|error p = Person1.convert(fn);
    io:println(p); // ERROR

    p = Person1.convert(fnlnag);
    io:println(p); // OK

    p = Person2.convert(fn);
    io:println(p); // ERROR

    p = Person2.convert(fnlnag);
    io:println(p); // OK
}
```
**Affected Versions:**
0.990.1
**OS, DB, other environment details and versions:**
Ubuntu 18.10, VSCode

**Comment by pubudu91** [comment] 2018-12-31 20:51
This is actually the expected behaviour. When you call convert(), internally what happens is the value is cloned and then its storage type changed to the type upon which you called convert() (i.e., call stamp()) which, in this case, happens to be `Person1`. 

When stamping, it checks if the value "is-like" the target type. In this case, the value is not like `Person1` since it's missing the required field `lname`. If you are wondering why not add that field since it has a default value, when converting, we don't mutate the value itself. Hence `lname` being defaultable is irrelevant. 

The third conversion, you seem to have gotten nil-able fields and optional fields mixed up. In previous releases, nil-able fields were how we made fields seem optional. However, now, optional have its own syntax and semantics. For example, if what you intended was for `lname` to be optional, the record type descriptor for Person2 should've been as follows:
```ballerina
type Person2 record {
    string fname;
    string lname?;
};
```
Note the placement of `?` in the above descriptor. A `?` following the identifier of the field marks the field as an optional field, while a `?` following the type of the field simply makes the type of the field nil-able. It's still a required field. For example, if you tried to create a Person2 record using the literal `{fname: "John"}` would result in a compile error saying the `lname` field is missing. Make the `lname` an optional field, and the 3rd conversion above would work. 

Hope this clears things up. :)

**Comment by pubudu91** [comment] 2019-01-07 05:19
Closing this since this is not a bug. Do let us know if you have any further queries regarding this.

**Closed by pubudu91** 2019-01-07 05:19 UTC
Labels: Component/BVM, Resolution/Not a bug
