### ISSUE TITLE
Type of `readonly` record field not updated to the immutable type when recompiled

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-lang#37053] opened 2022-07-19 04:04 UTC
**Description:**
Consider the following:
```ballerina
public type GraphqlServiceConfig record {|
    int maxQueryDepth?;
    readonly (readonly & Interceptor)[] interceptors = [];
|};

public type Interceptor distinct service object {
    isolated remote function execute(Context ctx, Field 'field) returns anydata|error;
};

public type Context record {
    int a;
};

public type Field record {
    int n;
};

isolated function getServiceInterceptors(GraphqlServiceConfig? serviceConfig) returns readonly & (readonly & Interceptor)[] {
    if serviceConfig is GraphqlServiceConfig {
        return serviceConfig.interceptors;
    }
    return [];
}
```

Ballerina GraphQL module uses a function similar to the above `getServiceInterceptors()` and returns the following error.
```
incompatible types: expected '(ballerina/graphql:1.3.3:Interceptor & readonly)[] & readonly', found '(ballerina/graphql:1.3.3:Interceptor & readonly)[]'
error: compilation contains errors
```

After removing the brackets in `interceptors` field in `GraphqlServiceConfig`, the function works fine.
```ballerina
public type GraphqlServiceConfig record {|
    int maxQueryDepth?;
    readonly readonly & Interceptor[] interceptors = [];
|};
```

**Comment by MaryamZi** [comment] 2022-07-19 04:13
On the surface

(1)
```ballerina
public type GraphqlServiceConfig record {|
    int maxQueryDepth?;
    readonly (readonly & Interceptor)[] interceptors = [];
|};
```

and

(2)
```ballerina
public type GraphqlServiceConfig record {|
    int maxQueryDepth?;
    readonly readonly & Interceptor[] interceptors = [];
|};
```

are not the same.

If we forget they are `readonly` fields, the type of `interceptors` in (1) is a **mutable** array of immutable `Interceptor`s whereas in (2) it is an **immutable** array with immutable `Interceptor`s. But since the type of a field `readonly T x;` is effectively `readonly & T`, both should end up being immutable arrays.

This works for normal code, but seems like it doesn't work when there's a plugin that result in recompiling the source. Could be that readonly-ness is not propagated on the subsequent compilation.

**Comment by MaryamZi** [comment] 2022-10-11 03:37
Can't seem to reproduce this on the current master and some earlier versions too. 

@DimuthuMadushan confirmed that this isn't reproducible now too.

Will check and add a test anyway.

**Comment by MaryamZi** [comment] 2022-10-11 04:51
> Can't seem to reproduce this on the current master and some earlier versions too.
> 
> @DimuthuMadushan confirmed that this isn't reproducible now too.
> 
> Will check and add a test anyway.

Update: not reproducible on the current master, but reproducible with the GraphQL build when using lang v2201.2.0.

**Comment by MaryamZi** [comment] 2022-10-13 04:15
Closing this issue since it is not reproducible on Update 3 SNAPSHOT and the current master. Added a test in https://github.com/ballerina-platform/ballerina-lang/pull/38143.

**Closed by MaryamZi** 2022-10-13 04:15 UTC
Labels: Type/Bug, Status/CannotReproduce, Team/CompilerFE, Points/3
