### ISSUE TITLE
Refactor jvm codegen

### ISSUE THREAD

**Issue by lankavitharana** [ballerina-platform/ballerina-lang#20250] opened 2019-12-06 10:48 UTC
**Description:**
Current jvm code gen is a big program without proper organizing, we can organize the code by breaking everything to proper phases. (like compiler front end)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment] 2019-12-09 05:00
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/19027

**Closed by SupunS** 2019-12-09 05:00 UTC
Labels: Area/jBallerina, Points/7, Type/Improvement
