### ISSUE TITLE
Cannot assign explicitly providing variable type

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/ballerina-lang#27010] opened 2020-11-19 06:21 UTC
**Description:**
In the following code snippet the line having the variable inResHotel2 throws compilation error.

```
        map<json> outReqPayloadHotel = outReqPayload.clone();
        outReqPayloadHotel["Preference"] = <json>hotelPreference;

        var inResHotel = hotelReservationEP->post("/reserve", <@untainted>outReqPayloadHotel);

        http:Response|error inResHotel2 = hotelReservationEP->post("/reserve", <@untainted>outReqPayloadHotel);

        if (!(inResHotel is http:Response)) {
            return;
        }

        http:Response inResHotelFiltered = <http:Response> inResHotel;
```
The error we get is as follows.

```
incompatible types: expected '(ballerina/http:1.0.1:Response|error)', found '(ballerina/http:1.0.1:Response|string|xml|json|map<json>|byte[]|ballerina/http:1.0.1:CustomRecordType|ballerina/http:1.0.1:CustomRecordType[]|ballerina/http:1.0.1:FailoverAllEndpointsFailedError|ballerina/http:1.0.1:FailoverActionFailedError|ballerina/http:1.0.1:UpstreamServiceUnavailableError|ballerina/http:1.0.1:AllLoadBalanceEndpointsFailedError|ballerina/http:1.0.1:AllRetryAttemptsFailed|ballerina/http:1.0.1:IdleTimeoutError|ballerina/http:1.0.1:AuthenticationError|ballerina/http:1.0.1:AuthorizationError|ballerina/http:1.0.1:InitializingOutboundRequestError|ballerina/http:1.0.1:WritingOutboundRequestHeadersError|ballerina/http:1.0.1:WritingOutboundRequestBodyError|ballerina/http:1.0.1:InitializingInboundResponseError|ballerina/http:1.0.1:ReadingInboundResponseHeadersError|ballerina/http:1.0.1:ReadingInboundResponseBodyError|ballerina/http:1.0.1:UnsupportedActionError|ballerina/http:1.0.1:Http2ClientError|ballerina/http:1.0.1:MaximumWaitTimeExceededError|ballerina/http:1.0.1:SslError|ballerina/http:1.0.1:GenericClientError|ballerina/http:1.0.1:CookieHandlingError|ballerina/http:1.0.1:RemoteServerError|ballerina/http:1.0.1:ClientRequestError|ballerina/http:1.0.1:IllegalDataBindingStateError)
```

However, if we comment out the line having inResHotel2, the code compiles as expected.

**Steps to reproduce:**
See the above description.

**Affected Versions:**
This issue was found in Ballerina slp5 release

**OS, DB, other environment details and versions:**
Ubuntu 18.04, Ballerina slp5

**Related Issues (optional):**
N/A

**Suggested Labels (optional):**
N/A

**Suggested Assignees (optional):**
N/A

**Comment by rdhananjaya** [comment] 2020-11-19 06:33
Closing as this is not a bug, but an API change

**Closed by rdhananjaya** 2020-11-19 06:33 UTC

**Comment by chamil321** [comment] 2020-11-19 06:34
For more info, check https://ballerina.io/swan-lake/learn/api-docs/ballerina/http/clients/Client.html#post
