### ISSUE TITLE
On building the repo - Task :ballerina-bindgen:test FAILED

### ISSUE THREAD

**Issue by HarveyEllis** [ballerina-platform/ballerina-lang#25530] opened 2020-08-30 14:00 UTC
**Description:**
When I clone the ballerina repo and try to build it I get an error, to do with the bindgen test. I have tried this for the tip of the master branch, and also for the 1.2.8 release. 

Stack trace:
```
ballerina-bindgen-test-suit > ballerina-bindgen-tests > org.ballerinalang.bindgen.MavenSupportTest > testBindgenMvnToml FAILED
    java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertTrue(Assert.java:44)
        at org.testng.Assert.assertTrue(Assert.java:54)
        at org.ballerinalang.bindgen.MavenSupportTest.testBindgenMvnToml(MavenSupportTest.java:92)

1 test completed, 1 failed
```

Please excuse my ignorance as I am newly looking at this project. 

I fairly sure this is just something silly to do with my environment, but I don't really know what. 

**Steps to reproduce:**
I run `./gradlew build` or run the build task from within Intellij. 

**Affected Versions:**
The github repo. Master branch and release tag 1.2.8.

**OS, DB, other environment details and versions:**
MacOS Catalina 10.15.6
AdoptopenJDK 1.8.0_242
Node, v8.9.4
Npm v5.6.0
Gradle v5.4
Python, v2.7.16 (available)
Maven, v3.6.2

**Related Issues (optional):**

Can't find any other issues where this test task is failing.

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Dilhasha** [comment] 2020-08-31 07:21
Hi @HarveyEllis,
I tried running this particular test using "./gradlew :ballerina-bindgen:test" on master branch.
But, I was unable to reproduce the mentioned issue, the test passed fine for me.

This test case is comparing the content in the Ballerina.toml at the test project against a Ballerina.toml file in test resources, to see whether the toml has updated correctly.
I would suggest that you reset any changes in the repo and try "./gradlew :ballerina-bindgen:test" again.

**Comment by keizer619** [comment] 2020-08-31 07:46
@HarveyEllis 
is it possible for you to try rebuilding bindgen module (<repo location>/misc/ballerina-bindgen) to verify its an intermittent failure or not?

This particular test is resolving artifacts from maven repository and i am suspecting some network issue has caused this failure.

**Comment by HarveyEllis** [comment] 2020-09-01 16:15
Hi both, 

Thanks for your responses. I'm pretty sure @keizer619 - that it will be some sort of network issue. This is because I am behind a corporate proxy on this current machine. Not sure why my proxy would not be working though... I'm futher confident because its taking >1m to download whatever it is trying to download on a 1gbps connection.

It is still not working now - but I'm pretty sure this is due to my machine's local config. 

I will try on my windows/linux machine and see if that works instead. 

Thanks both for your help - I suspected it'd be something to do with my setup.

**Comment by Dilhasha** [comment] 2020-09-02 04:59
@HarveyEllis Thanks for your response. I will close this issue based on your comment. Please reopen if you need any further assistance.

**Closed by Dilhasha** 2020-09-02 04:59 UTC
Labels: Area/Build
