### ISSUE TITLE
[New Feature]: Optimize `f(...arr)`

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#40040] opened 2023-03-30 06:20 UTC
In nBallerina we often have code that looks like `myList.push(...myCalcArr(1, 5))`. As far as I am aware this produces code that creates a new array to be passed into the `myList.push` (please close this issue if my assumption is wrong). Since `myCalcArr` is already returning and array, we should directly pass it in to `myList.push`.

**Comment by HindujaB** [comment] 2023-04-03 03:47
This seems to be the expected behavior. 
As per the spec, the value assigned for the `rest-parameter` is described below.
```
If there is a rest-param, then that is initialized to a newly created list containing the remaining arguments in the argument list;
the inherent type of this list will be T[] where T is the type of the rest-param.
The conformance of the argument list ensures that the members of this list will belong to type T.
 ```
The compiler creates a new list with the provided values in the function body.  Therefore, the compiler validates whether the arguments passed are of type `T` and not `T[]`. 
 
Further, as we are trying to pass an array `T[]` from the `myCalcArr()` function, it is expected to use the `rest-arg` as it considers each array member as a single argument.

```
  rest-arg := ... expression

The static type of the expression in a rest-arg must be either a list type or a mapping type. 
If it is a list type, then the rest-arg is equivalent to specifying each member of the list as a positional arg. 
```

**Comment by manuranga** [comment] 2023-04-03 05:04
We will not be able to do this in the general case.
Eg: `foo(x, ...x);` can't be optimized.


But it should be possible to do when passed in spred arg is the last and only reference the given list.

**Comment by HindujaB** [comment] 2023-04-03 11:33
The `rest-arg` call is handled from the compiler desugaring phase to create a new array of parameter values before calling the method. 
We need to revamp this from the desugaring if we are to optimize this. 
@gimantha @hasithaa WDYT?

**Comment by MaryamZi** [comment] 2023-04-04 04:53
Based on the following example, it seems like we are not always creating a new list? IMO, we need to create a new list always (also in-line with the spec) because it can result in unintentional updates like in the example.

E.g.,
```ballerina
import ballerina/io;

int[] arr = [1, 2];

public function main() {
    fn(...getArr());
    io:println(arr); // updated to [1,2,4] on 2201.4.0
}

function getArr() returns int[] => arr;

function fn(int... x) {
    x.push(4);
}
```

Btw, just to add, the rest argument doesn't have to be just for the rest param, it can provide arguments for other params also.

```ballerina
[int, int...] arr = [1, 2];

public function main() {
    fn(...getArr()); // valid
}

function getArr() returns [int, int...] => arr;

function fn(int a, int... x) {
}
```

**Comment by MaryamZi** [comment] 2024-08-29 07:31
Created https://github.com/ballerina-platform/ballerina-lang/issues/43338 to track fixing not always creating a new list.

Closing this issue since creating a new list seems to be the correct thing to do anyway.

**Closed by MaryamZi** 2024-08-29 07:31 UTC
Labels: Type/NewFeature, Area/Compiler, Team/CompilerFE, userCategory/Compilation
