### ISSUE TITLE
Terminating debug session in VSCode doesn't kill listener process on MacOS

### ISSUE THREAD

**Issue by bvandehey** [ballerina-platform/ballerina-lang#16734] opened 2019-07-15 16:08 UTC
In debugging a Ballerina listener within VSCode, the listener process doesn't get killed. In reviewing the following code:

https://github.com/ballerina-platform/ballerina-lang/blob/308b6054c669cd5179ee33638f45ca4754216db9/tool-plugins/vscode/src/debugger/session.ts#L445

The problem is on MacOS, the ps-node package uses "ps -lx" which doesn't return the complete command line that contains the "org.ballerinalang.launcher.Main" string that the lookup function is looking for. Here is sample output from my Mac:
```
$ ps -lx | grep ballerinalang
229480683 55270 55263     4004   0  31  0 10136712 391860 -      S                   0 ??         0:13.77 /Library/Ballerina/ballerina-0.991.0/bre/lib/jdk8u202-b08-jre/bin/java -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Library/Ballerina/ballerina-0.991.0/language-server-heap-dump.hprof -Dballerina.home=/Library/Ballerina/ballerina-0.991.0 -Dballerina.debugLog= -Dexperimental=false -cp ::/Library/Ballerina/ballerina-0.991.0/bre/lib/*:/Library/Ballerina/ballerina-0.991.0/lib/tools/lang-server/lib/* org.ballerinalang.langserver.launchers.stdio.Main
```

You will notice the string "org.ballerinalang.launcher.Main" is not contained in that list. My recommendation is to change the string to org.ballerinalang.langserver.launchers at least for Mac's

**Comment by pahans** [comment] 2019-07-16 15:09
@bvandehey Hi,
`org.ballerinalang.langserver.launchers.stdio.Main` is a background process we start to provide auto completions etc... for ballerina extension. This is a separate process from launcher.

**Comment by pahans** [comment] 2019-08-27 18:12
Closing this as per the above comment.

**Comment by bvandehey** [comment] 2019-08-30 00:00
You mentioned "org.ballerinalang.langserver.launchers.stdio.Main" in your comment but I mentioned "org.ballerinalang.launcher.Main" which is different. This is still an issue.

**Comment by pahans** [comment] 2019-09-17 08:43
Hi @bvandehey, 
We did a major revamp for debugger during 1.0.0 release and moved to a debugger adapter while implementing [debugger adapter protocol](https://microsoft.github.io/debug-adapter-protocol/). We no longer use ps-node to find the process.

**Comment by pahans** [comment] 2019-10-03 05:07
I tried to reproduce this on mac with the latest ballerina(1.0.1) could not reproduce the issue.

**Closed by pahans** 2019-10-03 05:07 UTC
Labels: Area/Tooling, Component/VScodePlugin, Resolution/Cannot Reproduce, Type/Bug
