### ISSUE TITLE
Compiler error when compile the calculator package

### ISSUE THREAD

**Issue by jayamaljayamaha** [ballerina-platform/ballerina-lang#9544] opened 2018-07-09 18:24 UTC
**Description:**
When compiling the calculator package, that means when running the ballerina 'run calculator' command in terminal it gives this error

ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.

lib.bal and main.bal files are OK, no errors in that files. I attached the log file along with this
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/2177533/ballerina-internal.log)

**Steps to reproduce:**
Delete the created lib.bal and main.bal files and create again that files and copy the code. Then it will compile successfully.  

**Affected Versions:**
0.970.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by jayamaljayamaha** [comment] 2018-07-09 20:47
this is a screenshot of that error
![error](https://user-images.githubusercontent.com/24557887/42475154-720dceca-83e7-11e8-837e-6ed42bd5e92b.PNG)

**Comment by pankaja92** [comment] 2018-07-11 04:10
Having the same issue. Deleting and recreating them doesn't work either.

**Comment by vinok88** [comment] 2018-07-11 04:30
This looks like an error in the compiler. Can you let us know the exact calculator package you used? If it is from ballerina Central what is the organization?
We need above info in order to reproduce the issue.

**Comment by pankaja92** [comment] 2018-07-11 04:40
I got this when I'm following [Ballerina Quick Tour](https://ballerina.io/community-program/#create-a-new-package) guide.

**Comment by pankaja92** [comment] 2018-07-11 07:15
For my case it wasn't an error or a bug. I tried running  `ballerina run calculator` for a project (outside a project). But it was supposed to run inside a project for a package. Followed those steps and it worked.

**Comment by pubudu91** [comment] 2018-07-11 10:13
Is this issue reproducible? What were the exact steps you were following? I tried out the quickstart and the behaviour was as intended

**Comment by HishanIndrajith** [comment] 2018-07-11 16:15
This is a duplicate of 
Running ballerina build with the 'absolute directory containing space' results in Bad, Sad #9369

**Comment by jayamaljayamaha** [comment] 2018-07-11 18:09
Yes Hishan you are right same error came up when we give a name to the folder with spaces but I got that error in different situation. I got tat error when compiling not when building

I don't know the reason but delete both files and recreate them worked for me

**Comment by ldclakmal** [comment] 2018-07-31 07:34
@jayamaljayamaha I followed steps of [Ballerina Quick Tour – Community Engagement](https://ballerina.io/community-program/) and the behaviour was as expected.
Can you list the steps you were following? so that we can figure out what's the issue.

**Comment by anupama-pathirage** [comment] 2018-08-02 06:12
@jayamaljayamaha Closing this issue as it cannot be reproduced with the 0.981.0 release. Feel free to reopen with more details if the issue still exists.

**Closed by anupama-pathirage** 2018-08-02 06:12 UTC
Labels: Component/Compiler, Type/Bug

**Comment by hemikak** [comment] 2018-08-02 08:37
I think the mentioned issue is when trying to build a bal file/package by giving the full path and when there are spaces in the path. This was fixed by https://github.com/ballerina-platform/ballerina-lang/pull/9377.
