### ISSUE TITLE
`NoSuchElementException` when attempting to get completions for a record var

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#29531] opened 2021-03-23 18:37 UTC
Consider the following syntactically invalid code snippet:
```ballerina
function mapToBook(record {int book_id; string title; string first_name; string last_name;} book) returns Book => {
    id: book.book_id;
    name: book.title;
    author: book.first_name + " " + book.
};
```
Getting the following exception as soon as `.` is typed after `book`.
```
[Error - 12:05:56 AM] Operation 'text/completion' failed! {uri: '/c%3A/Users/Pubudu/Projects/openapi/bookstore/data_mappers.bal', [4:42], error: 'No value present'}
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:382)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.getSymbolByName(FieldAccessCompletionResolver.java:166)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.transform(FieldAccessCompletionResolver.java:73)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.transform(FieldAccessCompletionResolver.java:62)
	at io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode.apply(SimpleNameReferenceNode.java:46)
	at org.ballerinalang.langserver.completions.util.FieldAccessCompletionResolver.getVisibleEntries(FieldAccessCompletionResolver.java:159)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessContext.getEntries(FieldAccessContext.java:54)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:42)
	at org.ballerinalang.langserver.completions.providers.context.FieldAccessExpressionNodeContext.getCompletions(FieldAccessExpressionNodeContext.java:32)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.route(CompletionUtil.java:99)
	at org.ballerinalang.langserver.completions.util.CompletionUtil.getCompletionItems(CompletionUtil.java:56)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:51)
	at org.ballerinalang.langserver.completions.BallerinaCompletionExtension.execute(BallerinaCompletionExtension.java:37)
	at org.ballerinalang.langserver.LangExtensionDelegator.completion(LangExtensionDelegator.java:92)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$completion$0(BallerinaTextDocumentService.java:139)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by nadeeshaan** [comment] 2021-03-24 03:13
The provided source snippet is invalid. The record fields are being separated by `;` instead of `,` within the mapping. Hence, the parser's resolution logic leads to, that the semantic analyzer cannot identify the `book` variable as a visible symbol, which leads to this particular error, which is acceptable when the symbol cannot find. 

This is working when the source is corrected as 
<img width="1095" alt="Screenshot 2021-03-24 at 08 42 31" src="https://user-images.githubusercontent.com/1329674/112248955-e625c380-8c7c-11eb-9119-396d429afcf7.png">

I believe we can close this @pubudu91

**Comment by nadeeshaan** [comment] 2021-04-06 05:18
Closing this, since the issue is with the code snippet and the parser's as well as completion engine's behaviour is expected.

**Closed by nadeeshaan** 2021-04-06 05:18 UTC
Labels: Area/Completion, SwanLakeDump, Team/LanguageServer, Type/Bug, Version/SLAlpha3
