### ISSUE TITLE
outer cannot be used as a field identifier inside a record

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#31311] opened 2021-06-21 06:54 UTC
```
type LoopContext record {|
    LoopContext? outer;
    string str;
|};

public function main() {
    LoopContext ctx = {outer: (), str: "ABC"};
}

```
Compiling the above code will give the following errors

```
    ERROR [test.bal:(2:18,2:18)] missing identifier
    ERROR [test.bal:(2:23,2:24)] invalid token 'outer'
    ERROR [test.bal:(7:23,7:46)] missing non-defaultable required record field '$missingNode$_0'
    ERROR [test.bal:(7:24,7:24)] missing identifier
    ERROR [test.bal:(7:24,7:24)] undefined field '$missingNode$_1' in record 'LoopContext'
    ERROR [test.bal:(7:29,7:30)] invalid token 'outer'
```

**Comment by rdulmina** [comment] 2021-08-09 04:41
Duplicate of #32061

**Closed by rdulmina** 2021-08-09 04:41 UTC
Labels: Type/Bug, Team/CompilerFE, Points/1, Area/Parser, NBalNeeds
