### ISSUE TITLE
Error message shown for duplicate resource methods in a service isn't informative

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#29061] opened 2021-03-08 12:51 UTC
**Description:**
When we have two resource methods with the same signature in a given service, the error message shown (ex: `redeclared symbol '$anonType$_1.$get$path'`) is not informative and contains ambiguous (for end users) `anonType...` etc.

![Screenshot from 2021-03-08 18-15-29](https://user-images.githubusercontent.com/11285165/110323461-a636cd80-803a-11eb-8a9e-fb68e9dc7ebe.png)

The error message should be more informative since services are one of the main features in Ballerina.

**Steps to reproduce:**
See above screenshot

**Affected Versions:**
SLA 2

**Comment by lochana-chathura** [comment] 2021-06-30 19:31
Duplicate of #28440

**Closed by lochana-chathura** 2021-06-30 19:31 UTC
Labels: Area/Diagnostics, Priority/High, Team/CompilerFE, Type/Bug, Type/Improvement
