### ISSUE TITLE
Completions not working for a package pushed to the local repo

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#36342] opened 2022-05-27 13:23 UTC
The following is my scenario:
- There's a simple package with 3 public annotations in it.
- I built and pushed this package to the local repository.
- Then I created a new project and tried to use the previous package within it.

But the completions are not working for it. 
![Screencast from 05-27-2022 06_50_39 PM](https://user-images.githubusercontent.com/6260009/170707688-a690c9c7-03f6-4512-9636-1ed43506dc11.gif)

**Comment by IMS94** [comment] 2022-06-23 08:07
@pubudu91 Can you share the source of the 3 annotations you have in this other package? Because LS validates the attachment point of annotations before suggesting. Just want to know if there are annotations with the attachment point set to `function`s.

**Comment by pubudu91** [comment] 2022-06-23 08:10
These are the annotations:
```ballerina
public const annotation InFlow on source function;
public const annotation OutFlow on source function;
public const annotation FaultFlow on source function;
```

**Comment by IMS94** [comment] 2022-06-30 04:30
Tried the same scenario locally with 2201.1.0, 2201.0.3 and 2201.1.1 (RC). Couldn't reproduce this. Closing.

**Closed by IMS94** 2022-06-30 04:30 UTC
Labels: Type/Bug, Priority/High, Team/LanguageServer, Points/3, Area/Completion
