### ISSUE TITLE
Debugger doesn't show some variables

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-lang#29477] opened 2021-03-23 11:22 UTC
**Description:**

As seen here; `segmentDelimeter` and `segments` variables are not shown under local variables section in debugger.

<img width="1505" alt="Screenshot 2021-03-23 at 4 47 50 PM" src="https://user-images.githubusercontent.com/1448489/112138823-f9428000-8bf7-11eb-959a-75cb9f7659d1.png">

**Steps to reproduce:**

**Affected Versions:**
2.0.0-SLA3

**Comment by NipunaRanasinghe** [comment] 2021-03-25 04:27
@rasika Will you be able to provide the complete code snippet so that we can reproduce this behaviour?

**Comment by praveennadarajah** [comment] 2021-06-22 05:52
**Steps to reproduce**

Consider the below code segment:
```
import ballerina/regex;

class Message {
    string msg;
    function init() {
        self.msg = "Hello Praveen!!!";
    } 
}

public class EDIParser {
    Message message;

    public function init() {
        self.message = new Message();
    }
    public function parse(string message) {
        self.init();
        string parseText = message;
        string segmentDelimeter = self.getSegmentDelimeter(message); // Add a debug point here.
        string[] segments = regex:split(message, segmentDelimeter);
        self.parseSegments(segments);
    }

    public function getSegmentDelimeter(string message) returns string {
        return "/";
    }

    public function parseSegments(string[] message) {
        string[] segMessage = message;
    }
}

public function main() {
    string simpleMessage = "This/is/a/simple/message";
    EDIParser parser = new EDIParser();
    parser.parse(simpleMessage);

}
```
- Add a debug point inside `parse()` function of `EDIParser` class as shown above in the code segment.
- Start the program in debug mode.
- Once the debug point gets hit, execute `STEP_OVER` operation. We could able to observe that `segmentDelimeter` and `segments` variables are not visible.

**Comment by praveennadarajah** [comment] 2021-06-23 06:02
The above issue is due to function returned values and their assigned variables are not visible in the debugger view, and it should be fixed with https://github.com/ballerina-platform/ballerina-lang/issues/31385.

**Comment by praveennadarajah** [comment] 2021-06-23 06:03
Closing this issue as this is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/31385

**Closed by praveennadarajah** 2021-06-23 06:03 UTC
Labels: Area/Debugger, Team/DevTools, Type/Bug, Version/SLAlpha3
