### ISSUE TITLE
Empty tuple declaration is not allowed

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#35029] opened 2022-02-11 07:16 UTC
**Description:**

I think the following should be allowed.
```
type T [];
```

```
tuple-type-descriptor :=
   [ tuple-member-type-descriptors ]
tuple-member-type-descriptors :=
   member-type-descriptor (, member-type-descriptor)* [, tuple-rest-descriptor]
   | [ tuple-rest-descriptor ]
member-type-descriptor := type-descriptor
tuple-rest-descriptor := type-descriptor ...
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by MaryamZi** [comment] 2022-02-11 07:25
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/26191?

**Closed** 2022-02-11 07:27 UTC
Labels: Type/Bug, Type/SpecDeviation, Team/CompilerFE, Area/Parser
