### ISSUE TITLE
Issue in stack frame manipulation in JBallerina

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#16092] opened 2019-06-28 07:09 UTC
**Description:**
Observed the following exception on travis when running database tests. Could not reproduce locally.
Seems like this tries to cast a stack frame of a function to a different function frame.

```ballerina

> Task :ballerina-h2:test

ballerina-test-suite > ballerina-lang-test-suite > org.ballerinalang.stdlib.database.sql.SQLConnectionPoolTest > testGlobalConnectionPoolSingleDestinationConcurrent FAILED
    org.ballerinalang.util.exceptions.BLangRuntimeException: Error while invoking function 'testGlobalConnectionPoolSingleDestinationConcurrent'
        at org.ballerinalang.test.util.BRunUtil.invoke(BRunUtil.java:407)
        at org.ballerinalang.test.util.BRunUtil.invokeOnJBallerina(BRunUtil.java:286)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1048)
        at org.ballerinalang.test.util.BRunUtil.invokeFunction(BRunUtil.java:1073)
        at org.ballerinalang.stdlib.database.sql.SQLConnectionPoolTest.testGlobalConnectionPoolSingleDestinationConcurrent(SQLConnectionPoolTest.java:105)

        Caused by:
        java.lang.RuntimeException: Error while invoking function 'testGlobalConnectionPoolSingleDestinationConcurrent'

            Caused by:
            java.lang.reflect.InvocationTargetException

                Caused by:
                java.lang.ClassCastException: testGlobalConnectionPoolSingleDestinationConcurrentFrame cannot be cast to testGlobalConnectionPoolConcurrentHelper2Frame
```

**Comment by SupunS** [comment] 2019-07-18 05:26
Possible root cause: https://github.com/ballerina-platform/ballerina-lang/issues/15593

However, this occurs if theres an actual issues in the generated classes. If this is not reproducing locally, then the reason for the issue in generated classes could be a caching issue.

**Comment by SupunS** [comment] 2019-07-19 05:03
Closing this issues, since the same issue is tracked via #15593.

**Closed by SupunS** 2019-07-19 05:03 UTC
Labels: Area/Language, Component/jBallerina, Type/Bug
