### ISSUE TITLE
[CLI] bal push command has invalid instruction

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#29376] opened 2021-03-22 08:53 UTC
Steps to reproduce. 

1. Delete the `target` dir from your project. 
2. run `bal push`
```
D:\test\alpha3\factorial>bal push
ballerina: cannot find bala file for the package: factorial. Run 'bal build' to compile and generate the bala.
```
3. It says to run `bal build` But it should be `bal build -c`
```
D:\test\alpha3\factorial>bal build

Compiling source
        hasitha/factorial:0.1.5

Generating executable
        target\bin\factorial.jar
```

4. Run `bal push` again. You get the same error message.
```
D:\test\alpha3\factorial>bal push
ballerina: cannot find bala file for the package: factorial. Run 'bal build' to compile and generate the bala.
```

**Comment by azinneera** [comment] 2021-03-22 19:08
Duplicate of #29347

**Closed by azinneera** 2021-03-22 19:08 UTC
Labels: Area/CLI, SwanLakeDump, Team/DevTools, Type/Improvement
