### ISSUE TITLE
[HTTP][CircuitBreaker] Make continuous no. of failures a threshold

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#4461] opened 2018-01-18 12:12 UTC
**Description:**
Need to make the number of successive failures a threshold as well.

**Suggested Labels (optional):**
Type/Improvement

**Comment by VijithaEkanayake** [comment] 2018-04-25 14:47
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/4634

**Closed by VijithaEkanayake** 2018-04-25 14:47 UTC
Labels: HTTP, Type/Improvement, component/stdlib
