### ISSUE TITLE
[Bug]: Runtime errors are not displayed within workers

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-lang#41776] opened 2023-11-28 05:57 UTC
### Description

When a runtime error is generated within a worker, it is not presented to the user. Consequently, the user is unable to determine if the worker has completed the work successfully.

### Steps to Reproduce

Execute the following code with `bal run`. 

```ballerina
public function main() {
    worker A {
        _ = 1 / 0;
    }
}
```

Ideally, it should generate the message `error: {ballerina}DivisionByZero {"message":"/ by zero"}`, which is not produced when erroneous code is within a worker.

### Affected Version(s)

Ballerina 2201.8.0 (Swan Lake Update 8)

### OS, DB, other environment details and versions

OS: macOS 14.1.1 23B81
JDK: openjdk 17.0.8 2023-07-18

### Related area

-> Compilation

**Comment by Nadeeshan96** [comment] 2023-12-07 08:57
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/36077.

The reason is described in https://github.com/ballerina-platform/ballerina-lang/issues/36077#issuecomment-1149773181 and also noted in https://stackoverflow.com/collectives/wso2/articles/76718960/ballerina-program-execution-flow#heading-ballerina-program-termination.

If you wait for the worker, it shows the error.
```bal
public function main() {
    worker A {
        _ = 1 / 0;
    }

    wait A;
}
```
gives
```
Running executable

error: {ballerina}DivisionByZero {"message":" / by zero"}
        at issue:$lambda$_0(issue.bal:3)
```

**Closed by Nadeeshan96** 2023-12-07 08:57 UTC
Labels: Type/Bug, Status/Duplicate, Team/jBallerina, Reason/Invalid
