### ISSUE TITLE
Tooling functionality does not work for the given project

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#31030] opened 2021-06-08 05:23 UTC
**Description:**
I am working on the below project. I do not get any tooling functionality via VSCode for this project.

https://github.com/ballerina-platform/module-ballerina-websubhub/tree/my-websubhub-samples/websubhub-examples/kafka-hub/hub-impl

**Comment by nadeeshaan** [comment] 2021-06-08 06:50
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/30973

**Comment by nadeeshaan** [comment] 2021-07-20 08:26
Tested in the latest master build and cannot reproduce the issue. Hence closing the issue. If the issue still persists, please reopen.

**Closed by nadeeshaan** 2021-07-20 08:26 UTC
Labels: Priority/High, Team/LanguageServer, Type/Bug
