### ISSUE TITLE
Incorrect error message for negative array sizes

### ISSUE THREAD

**Issue by SandaruJayawardana** [ballerina-platform/ballerina-lang#32073] opened 2021-08-09 10:26 UTC
**Description:**
Compiler gives incorrect error message for following code.
```ballerina
    int[-1] v;
```
Compiler output:
```
ERROR [a.bal:(1:1,1:11)] invalid list binding pattern: expected an array or a tuple, but found 'int'
ERROR [a.bal:(1:5,1:5)] missing close bracket token
ERROR [a.bal:(1:5,1:5)] missing comma token
ERROR [a.bal:(1:5,1:5)] missing equal token
ERROR [a.bal:(1:5,1:5)] missing identifier
ERROR [a.bal:(1:5,1:5)] missing identifier
ERROR [a.bal:(1:7,1:8)] invalid token ']'
ERROR [a.bal:(1:9,1:10)] invalid token 'v'
error: compilation contains errors
```
TestParser Output:
```
int[ MISSING[] MISSING[,] MISSING[] MISSING[]] MISSING[=]-1 INVALID[]]  INVALID[v];
```

**Comment by rdulmina** [comment] 2021-08-30 08:30
Duplicate of #32394

**Closed by rdulmina** 2021-08-30 08:30 UTC
Labels: Type/Improvement, Priority/High, Team/CompilerFE, Area/Parser
