### ISSUE TITLE
CORS - sending disallowed methods as well in response header

### ISSUE THREAD

**Issue by kavishkafernando** [ballerina-platform/ballerina-lang#14703] opened 2019-03-26 09:31 UTC
**Description:**
After applying CORS to an API and invoking an API through the browser a set of methods that are not allowed also can be seen in the response header.
<img width="597" alt="Screen Shot 2019-03-26 at 2 49 31 PM" src="https://user-images.githubusercontent.com/19324135/54985462-db28f180-4fd6-11e9-8e95-685820b18940.png">

**Steps to reproduce:**
Created an API in APIM
Applied CORS to the API (Allowed only OPTIONS)
Invoke API (PUT request)
A set of methods that are not allowed also can be seen in the response header.
![Screen Shot 2019-03-26 at 5 43 11 PM](https://user-images.githubusercontent.com/8381003/55058928-87301280-5093-11e9-96ff-e0dcb7f77c16.png)

**Affected Versions:**
Ballerina 990.3

**Comment by chamil321** [comment] 2019-03-26 09:36
@kavishkafernando Can you please attach the generated bal file with all the resources to reproduce the issue?

**Comment by kavishkafernando** [comment] 2019-03-26 09:50
@chamil321 attached the resources.
[Resources.zip](https://github.com/ballerina-platform/ballerina-lang/files/3007516/Resources.zip)

**Comment by chamil321** [comment] 2019-03-27 08:01
@kavishkafernando This is not an issue/bug of HTTP Cors behavior. 

Summery of the scenario
User does an ajax call locally using PUT method by setting the Origin header. Browser identify the cors requirement and do a preflight. 
Since the call has not been performed on a host, browser has failed to set the Origin header in the preflight request. Ballerina service does not treat any of the request as cors unless it includes Origin header. 
Therfore preflight request has been treated as a typical OPTIONS request and has sent the response along with the allow header which is expected.
If this was treated according to cors , `Access-Control-Allow-Methods` header must be available in the response. 

hence closing the issue!

**Closed by chamil321** 2019-03-27 08:01 UTC
Labels: Component/HTTP, Component/stdlib, Type/Bug
