### ISSUE TITLE
No Errors are shown for invalid object constructor

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#17352] opened 2019-08-02 09:51 UTC
**Description:**
Source code:
![image](https://user-images.githubusercontent.com/7834839/62361602-fbdef600-b538-11e9-8ae0-5af1a2c175ef.png)

No errors are shown in the vs code.

How ever, if you try to compile the same file with the CLI, following errors are shown:
```
error: .::Untitled-1.bal:5:61: cannot refer to non public parameter 'config' of 'new(http://localhost:9092, config= {circuitBreaker:  {timeoutMillis: 2000}})()' as a named arg
error: .::Untitled-1.bal:6:25: invalid literal for type 'ballerina/http:CircuitBreakerConfig?'
```

**Affected Versions:**
1.0-alpha

**OS, DB, other environment details and versions:**
Mac OS - High Sierra

**Comment by nadeeshaan** [comment] 2019-08-08 12:54
Check in the latest master and could not reproduce the error. Hence closing the issue

**Closed by nadeeshaan** 2019-08-08 12:54 UTC
Labels: Area/Tooling, Component/LanguageServer, Component/VScodePlugin, Type/Bug
