### ISSUE TITLE
NATS does not work in Windows

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-lang#17792] opened 2019-08-15 12:16 UTC
**Description:**
I followed [Basic Streaming Publisher and Subscriber BBE ](https://v1-0-0-alpha.ballerina.io/learn/by-example/nats-streaming-client.html). There first i started consumer and it got connected successfully. Then i start producer it get connected but timeout occurs when publishing the message as in following log.

```
PS C:\Users\wso2\Desktop\beta-test\guaranteed-gateway> java -jar target\bin\gateway-executable.jar
Subject : demo
[ballerina/nats] Connection established with server nats://localhost:4222
error: {ballerina/nats}Error message=stan: connect request timeout
        at ballerina.nats:createStreamingConnection(streaming/producer.bal:66)
           ballerina.nats.$value$StreamingProducer:__init(streaming/producer.bal:23)
           wso2.gateway:main(main.bal:13)
```

Same scenario i tried in a Macos and it worked perfectly.

**Comment by daneshk** [comment] 2019-08-16 07:57
Tested in both remote windows instance and local windows machine and both nats and nats streaming client. Couldn't reproduce the issue.

I am closing the issue since we cannot reproduce the issue. Please reopen if you encounter this issue again in windows environment.

**Closed by daneshk** 2019-08-16 07:57 UTC
Labels: Area/StandardLibs, BetaTesting, OS/Windows, Priority/Blocker
