### ISSUE TITLE
Improve diagnostic Message

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#30686] opened 2021-05-20 07:05 UTC
**Description:**
Consider the following screen capture, where the diagnostic message contains `$anonType$_34` which does not make sense.

<img width="660" alt="Screenshot 2021-05-20 at 12 27 20" src="https://user-images.githubusercontent.com/1329674/118934135-a4a55200-b967-11eb-8173-52b0dbca039a.png">

**Affected Versions:**
ls-beta1-SNAPSHOT at least

**Comment by dulajdilshan** [comment] 2021-11-19 13:14
I was not able to reproduce this. @nadeeshaan Is this fixed?

**Comment by nadeeshaan** [comment] 2021-11-19 17:27
It seems this has been fixed now. Couldn't reproduce.

**Comment by MaryamZi** [comment] 2022-03-01 04:53
Fixed in slbeta2.

**Closed by MaryamZi** 2022-03-01 04:53 UTC
Labels: Type/Bug, Priority/High, Team/CompilerFE, Area/Diagnostics, Reason/EngineeringMistake
