### ISSUE TITLE
[Bug]: No compilation error when ignoring the value of the error cause using `_` in error binding pattern

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-lang#39042] opened 2022-12-14 05:38 UTC
### Description

$title. and this leads to an NPE at the desugar.

### Steps to Reproduce

```ballerina
type SampleErrorData record {|
    int code;
    string reason;
|};

type SampleError error<SampleErrorData>;

public function main() {
    SampleError sampleErr = error("Transaction Failure", error("Database Error"), code = 20,
                            reason = "deadlock condition");

    var error(message, _, code = code, reason = reason) = sampleErr; // should be a compilation error for `_` since the error cause is of type `error?`.
}
```
error log
```
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1468)
        at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:54)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1607)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:50)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8880)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8886)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1601)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:65)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8880)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1593)
        at org.wso2.ballerinalang.compiler.tree.BLangErrorVariable.accept(BLangErrorVariable.java:78)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1711)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangErrorVariableDef.accept(BLangErrorVariableDef.java:46)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8880)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:8886)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1374)
        at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:60)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1420)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:76)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:826)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:8842)
        at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:469)
        at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:216)
        at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:152)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:451)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:385)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:170)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:139)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:117)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:170)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:116)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:165)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:213)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

### Affected Version(s)

2201.3.0

### Related area

-> Compilation

**Comment by MaryamZi** [comment] 2023-02-28 04:12
Duplicate of the first example in https://github.com/ballerina-platform/ballerina-lang/issues/33544 (https://github.com/ballerina-platform/ballerina-lang/issues/33544#issue-1040822577).

**Closed** 2023-03-02 05:16 UTC
Labels: Type/Bug, Team/CompilerFE, Points/3, Area/TypeChecker, Reason/EngineeringMistake
