### ISSUE TITLE
Can't use `OrderedType` as sort callback's return type

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#32481] opened 2021-08-31 07:04 UTC
```ballerina
isolated function o(string v) returns array:OrderedType {
    ...
}
public function main() returns error? {
   ...
   var sorted = numberedIndex.sort(array:ASCENDING, o);
}
```

I get 
```
invalid sort key function return type: 'ballerina/lang.array:1.1.0:OrderedType' is not an ordered type
```

**Comment by MaryamZi** [comment] 2022-03-03 04:01
IMO, it is correct for this to result in an error. If `ballerina/lang.array:OrderedType` was allowed as the sort function's return type, we could return values of different ordered types, for which together ordering is not defined.

For example 

```ballerina
import ballerina/lang.array;

isolated function o(string v) returns array:OrderedType {
    return v == "" ? 0 : v;
}

public function main() {
   int[] numberedIndex = [];
   var _ = numberedIndex.sort(array:ASCENDING, o);
}
```

This is like allowing `int|string` as the return type, and `int|string` is not an ordered type. WDYT?

cc @lasinicl

**Comment by MaryamZi** [comment] 2023-06-21 04:48
Also see https://github.com/ballerina-platform/ballerina-spec/issues/787#issuecomment-808035151.

**Comment by MaryamZi** [comment] 2024-07-16 08:46
Closing this since the current behaviour is the expected behaviour.

**Closed by MaryamZi** 2024-07-16 08:46 UTC
Labels: Type/Bug, Team/CompilerFE, Lang/LangLib, Reason/Invalid
