### ISSUE TITLE
[Bug]: The mocking function can't read configurable values from Config.toml file

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#41793] opened 2023-11-29 08:44 UTC
### Description

The Ballerina project contains the `initializeClient` function which is used to initialize MySQL client.
```ballerina
final db:Client dbClient = check initializeClient();

function initializeClient() returns db:Client|error {
   return new ();
}
```
To initialize the client, we need to set the following set of configurable,
```toml
[mock_with_h2.db]
hostname = "localhost"
port1 = 3307
username = ""
pwd = ""
db = "hospitaldb"
```

In the test cases, when we try to mock the `initializeClient` and mock the MySQL client with the H2 client like below,
```
@test:Mock {functionName: "initializeClient"}
isolated function getMockClient() returns db:Client|error {
    return test:mock(db:Client, check new Client(url, user, password, options = {}));         
}
```

For the H2 client, we are setting the following values in the `Config.toml` file,
```toml
url = "jdbc:h2:./test"
user = "sa"
password = ""
```

but when we do bal build, it failed with the below error,
```
error: java.lang.NullPointerException {"message":"Cannot invoke "io.ballerina.runtime.api.values.BString.getValue()" because "str" is null"}
        at ballerina.lang.string.0:startsWith(string.bal:210)
           ballerinax.java.jdbc.1.Client:init(client.bal:36)
           danesh.mock_with_h2$test.0.Client:init(tests/persist_client.bal:37)
           danesh.mock_with_h2$test.0.tests.main_test:getMockClient(tests/main_test.bal:9)
```

### Steps to Reproduce

Project source: https://github.com/daneshk/persist-test-samples/blob/main/mock_with_h2/tests/Config.toml

### Affected Version(s)
Swan Lake

**Comment by Thevakumar-Luheerathan** [comment] 2023-12-11 09:11
I was able to reproduce the issue with following code.
`main.bal`
```ballerina
import ballerina/http;
import ballerina/io;

final Client dbClient = check initializeClient();

// public configurable string urlConfig = "http://localhost:9090";

function initializeClient() returns Client|error {
    return new ("");
}

public client class Client {
    private final http:Client httpClient;

    function init(string url) returns error? {
        self.httpClient = check new (url);
    }

    resource function get [string path]() returns string|error {
        return check self.httpClient->/[path];
    }
}

service / on new http:Listener(9091) {

    resource function get greeting() returns string|error {
        return "serv1";

    }
}

public function main() {
    io:println("Hello, World!");
}
```

`test.bal`
```ballerina
import ballerina/http;
import ballerina/test;

string urlConfig = "http://localhost:9090";

public client class Client2 {
    private final http:Client httpClient;

    function init(string url) returns error? {
        self.httpClient = check new (url);
    }

    resource function get [string path]() returns string|error {
        return check self.httpClient->/[path];
    }
}

@test:Mock {functionName: "initializeClient"}
function getMockClient() returns Client|error {
    Client2 client2 = check new Client2(urlConfig);

    Client cl = test:mock(Client, client2);
    return cl;
}

```
Issue can be reproduced not only with configurable in the test file, but also with global variables in the test file. When I use a public global variable(`urlConfig`) defined in the `main.bal`. This issue does not occur. 

Reason for the issue could be that mock function is started when initialising the final client. But, In that time, necessary global variables defined in the test file are not initialised.

**Comment by HindujaB** [comment] 2023-12-12 05:20
The cause of this issue is because of the test execution order at runtime. Currently, we call the init of the test module after we call the init of its source module. In this case, the client initialization in the source module calls a mock function that has a dependency in the test module (`urlConfig`). This needs test module init execution which has not started. As the test global variables are not initialized for the mock function, it gives an NPE.
The order of execution : 
- init source module
          - `initializeClient()`
          - `getMockClient`  -> needs global variable `urlConfig` from the test module *Fails*
- init test module
          -  initialize global vars in the test module

The cause is similar to what we discussed in https://github.com/ballerina-platform/ballerina-lang/issues/41330

@Dilhasha Are there any workarounds other than moving the mock function dependent global vars into the source module?

**Comment by Dilhasha** [comment] 2023-12-12 08:53
> The cause of this issue is because of the test execution order at runtime. Currently, we call the init of the test module after we call the init of its source module. In this case, the client initialization in the source module calls a mock function that has a dependency in the test module (`urlConfig`). This needs test module init execution which has not started. As the test global variables are not initialized for the mock function, it gives an NPE. The order of execution :
> 
> * init source module
>   - `initializeClient()`
>   - `getMockClient`  -> needs global variable `urlConfig` from the test module _Fails_
> * init test module
>   -  initialize global vars in the test module
> 
> The cause is similar to what we discussed in #41330
> 
> @Dilhasha Are there any workarounds other than moving the mock function dependent global vars into the source module?

Agreed with Hinduja on this. 
The only way to overcome the issue is to move the mock function dependent global vars into the source module.

**Comment by Thevakumar-Luheerathan** [comment] 2023-12-20 09:14
We are closing this issue as this behaviour is expected.

**Closed by Thevakumar-Luheerathan** 2023-12-20 09:14 UTC
Labels: Type/Bug, Area/TestFramework
