### ISSUE TITLE
The compilation of `OAuth2` module build is failing intermittently

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#30347] opened 2021-05-04 14:57 UTC
**Description:**
The compilation of [OAuth2 module](https://github.com/ballerina-platform/module-ballerina-oauth2) build is failing intermittently with the lang version `Ballerina Lang : 2.0.0-beta.1-20210504-152000-4d5f126d`. This happens in both Windows and Ubuntu builds.

```
Compiling source
	ballerina/oauth2:1.1.0-beta.1
ERROR [listener_oauth2_provider.bal:(105:9,105:19)] unknown type 'ClientAuth'
ERROR [listener_oauth2_provider.bal:(105:28,105:66)] invalid operation: type 'ballerina/oauth2:1.1.0-beta.1:ClientConfiguration' does not support optional field access for field 'auth'
ERROR [listener_oauth2_provider.bal:(106:21,106:31)] unknown type 'ClientAuth'

ERROR [oauth2_commons.bal:(31:5,31:15)] unknown type 'ClientAuth'
> Task :oauth2-ballerina:ballerinaBuild FAILED
error: compilation contains errors
```

The type which says as unknown type is defined as `public type ClientAuth ClientCredentialsGrantConfig|PasswordGrantConfig|RefreshTokenGrantConfig;` It is a union of records.

This is the PR, that the build is failing. 1 build has failed out of 4. That can be changed when retriggering, since this is intermittent.
https://github.com/ballerina-platform/module-ballerina-oauth2/pull/172

**Affected Versions:**
Ballerina Lang : 2.0.0-beta.1-20210504-152000-4d5f126d

**Comment by MaryamZi** [comment] 2021-05-04 15:07
Reproducible intermittently with the following files in a project.

proj/client_oauth2_provider.bal
```ballerina
public type ClientCredentialsGrantConfig record {|
    string tokenUrl;
    string clientId;
    string clientSecret;
    CredentialBearer credentialBearer = AUTH_HEADER_BEARER;
    ClientConfiguration clientConfig = {};
|};

public type PasswordGrantConfig record {|
    string tokenUrl;
    string username;
    string password;
    string clientId?;
    string clientSecret?;
    CredentialBearer credentialBearer = AUTH_HEADER_BEARER;
    ClientConfiguration clientConfig = {};
|};

public type RefreshTokenGrantConfig record {|
    string refreshUrl;
    string refreshToken;
    string clientId;
    string clientSecret;
    CredentialBearer credentialBearer = AUTH_HEADER_BEARER;
    ClientConfiguration clientConfig = {};
|};
```

proj/listener_oauth2_provider.bal
```ballerina
public type IntrospectionConfig record {
    ClientConfiguration clientConfig = {};
};

public class ListenerOAuth2Provider {

    public isolated function init(IntrospectionConfig introspectionConfig) {
        ClientAuth? auth = introspectionConfig.clientConfig?.auth;
        if (auth is ClientAuth) {
        }
    }
}
```

proj/oauth2_commons.bal
```ballerina
public type ClientConfiguration record {|
    HttpVersion httpVersion = HTTP_1_1;
    map<string> customHeaders?;
    string customPayload?;
    ClientAuth auth?;
    SecureSocket secureSocket?;
|};

public type ClientAuth ClientCredentialsGrantConfig|PasswordGrantConfig|RefreshTokenGrantConfig;

public enum HttpVersion {
    HTTP_1_1,
    HTTP_2
}

public type SecureSocket record {|
    boolean disable = false;
    string cert;
    string key?;
|};

public enum CredentialBearer {
    AUTH_HEADER_BEARER,
    POST_BODY_BEARER
}
```

**Comment by MaryamZi** [comment] 2021-05-04 15:27
Also with

proj/client_oauth2_provider.bal
```ballerina
public type ClientCredentialsGrantConfig record {|
    string tokenUrl;
    ClientConfiguration clientConfig = {};
|};
```

proj/oauth2_commons.bal
```ballerina
public type ClientConfiguration record {|
    ClientAuth auth?;
|};

public type ClientAuth ClientCredentialsGrantConfig;
```

**Comment by KRVPerera** [comment] 2021-05-05 04:19
Issue is fixed by reverting the code causing the issue..
https://github.com/ballerina-platform/ballerina-lang/pull/30348

**Comment by MaryamZi** [comment] 2021-05-05 04:29
Let's keep this issue open since we need to verify this scenario when reintroducing the fix. Removing the milestone since we've fixed this for RC1.

**Comment by MaryamZi** [comment] 2021-06-16 16:15
@KRVPerera, can we close this now?

**Comment by KRVPerera** [comment] 2021-06-16 18:07
Closing as already fixed by PR https://github.com/ballerina-platform/ballerina-lang/pull/30352

**Closed by KRVPerera** 2021-06-16 18:07 UTC
Labels: Priority/Blocker, Team/CompilerFE, Type/Bug
