### ISSUE TITLE
Match pattern with wso2/soap in the tests throws a BallerinaException

### ISSUE THREAD

**Issue by Seralahthan** [ballerina-platform/ballerina-lang#9905] opened 2018-08-04 12:25 UTC
**Description:**
Getting a ballerina build failure with 
> Compiling tests
    code_test:0.0.0
    soap_consumer_client:0.0.0
    tests:0.0.0
error:tests:0.0.0/soap_consumer_client_test.bal:44:5: A matching pattern cannot be guaranteed for types '[wso2/soap:0.3.8:SoapResponse]'
error:tests:0.0.0/soap_consumer_client_test.bal:45:9: pattern will not be matched
ballerina: Oh no, something really went wrong. Bad. Sad.

**ballerina-internal.log** files have the following ballerina exception with compilation failed message

`ERROR {org.ballerinalang.launcher.Main} - error : compilation failed 
org.ballerinalang.util.exceptions.BallerinaException: error : compilation failed
	at org.ballerinalang.testerina.core.BTestRunner.lambda$compileAndBuildSuites$7(BTestRunner.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.ballerinalang.testerina.core.BTestRunner.compileAndBuildSuites(BTestRunner.java:155)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:97)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:82)
	at org.ballerinalang.testerina.core.BTestRunner.runTest(BTestRunner.java:71)
	at org.ballerinalang.testerina.core.TestCmd.execute(TestCmd.java:160)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)`

**Steps to reproduce:**
Run the following test using 0.980.1

     `import ballerina/io;
      import ballerina/test;
      import soap_consumer_client;
      import wso2/soap;

      @test:Config
      function testSoapConsumerClient() {
         io:println("Starting the test for Soap Consumer Client...");
         xml soapResp1 = xml `<book>
                    <name>Sherlock Holmes</name>
                    <author>Sir Arthur Conan Doyle</author>
                    
                  </book>`;

    var resp1 = soap_consumer_client:unsecureSoapConsumerClient();
    
    io:println("Running the test for Unsecure Soap Consumer Client");
    match resp1 {
        soap:SoapResponse soapResponse => test:assertEquals(soapResp1, soapResponse);
        soap:SoapError soapError => test:assertFail(msg = "Failed to retrieve data from the Soap end point");
        
    }

}`

**Affected Versions:**
Running the code on Ballerina-0.980.1.
VS Code Plugin 0.980.1.vsix

**OS, DB, other environment details and versions:**
Ubuntu:16.04

**Related Issues (optional):**

**Suggested Labels (optional):**
Component/Compiler, Severity/Blocker

**Suggested Assignees (optional):**

**Comment by VijithaEkanayake** [comment] 2018-08-06 12:54
@Seralahthan,

I've investigated the code you have shared offline. The reason for this issue seems to be the incorrect restructuring of the folder hierarchy. Created a project with the correct structure. Please find the attached project [Consuming-A-SOAP-Service.zip](https://github.com/ballerina-platform/ballerina-lang/files/2262592/Consuming-A-SOAP-Service.zip)

**Comment by VijithaEkanayake** [comment] 2018-08-07 12:18
Closing the issue is not related to match and created the issue[1] to track testerina issue.
[1]. https://github.com/ballerina-platform/ballerina-lang/issues/9936

**Closed by VijithaEkanayake** 2018-08-07 12:18 UTC
Labels: Component/Testerina
