### ISSUE TITLE
build fails on empty package-lock.json

### ISSUE THREAD

**Issue by pmhofman** [ballerina-platform/ballerina-lang#9188] opened 2018-06-20 19:41 UTC
**Description:**
Build fails with error from npm: "Unexpected end of JSON input"
It can happen, that when a build fails during npm install (maven goal :ballerina-composer-web), that the package-lock.json is empty. I have not quite figured out how this happens, but it did happened a few times already.
An empty json file is not valid json. It should contain at least 
`{}
`
In case of an error, package-lock.json should be always be restored from package-lock.json.bak.
Apparently, that is not happening. Maybe the npm-preinstall.js and npm-postinstall.js scripts in composer/modules/scripts should do the backup/restore in a safer way. I think no backup should be done when package-lock.json is an empty file and if a backup file is still existing.

**Steps to reproduce:**
1) empty composer/modules/web/package-lock.json
2) run the build

`mvn clean install 
`

3) In the output the following appears:

`main:
[INFO] Executed tasks
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:exec (backup-package-lock) @ ballerina-composer-web ---
Note: package-lock.json won't be updated during the build
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:parse-version (parse-version) @ ballerina-composer-web ---
[INFO] 
[INFO] --- replacer:1.5.3:replace (replace-versions) @ ballerina-composer-web ---
[INFO] Replacement run on 3 files.
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:exec (npm install (initialize)) @ ballerina-composer-web ---
npm ERR! Unexpected end of JSON input

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pmhofman/.npm/_logs/2018-06-20T19_04_02_558Z-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
`

**Workaround**
as work around, before restarting the build at :ballerina-composer-web restore package-lock.json file from git:
`git checkout -- composer/modules/web/package-lock.json
`
`mvn clean install -rf :ballerina-composer-web
`

**Affected Versions:**
0.975.1

**OS, DB, other environment details and versions:**
CentOS 7

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pmhofman** [comment] 2018-06-20 20:08
update: a better solution than creating a backup may be copying packages-lock.json to npm-shrinkwrap.json in npm-preinstall.js, and deleting npm-shrinkwrap.json in npm-postinstall.js.
[https://docs.npmjs.com/files/shrinkwrap.json](https://docs.npmjs.com/files/shrinkwrap.json)

**Comment by pmhofman** [comment] 2018-06-20 20:41
not figured out quite yet how shrinkwrap works, but I am diving into this, so don't change anything yet

**Comment by pmhofman** [comment] 2018-06-21 13:19
shrinkwrap is not the way to go.
If you don't want an update of package-lock.json, then you should run npm install with option "--no-save".
This means that backing up and restoring package-lock.json would not be necessary.

**Comment by pmhofman** [comment] 2018-06-21 13:22
tonight (at home) I will test this with modification of pom.xml to include --no-save option in npm install

**Comment by pmhofman** [comment] 2018-06-21 19:53
tested with the backup and restore of package-lock.json executions disabled, 
and extra argument --no-save in the npm install execution. 
AFAICC that works without updating package-lock.json.

**Comment by hevayo** [comment] 2018-06-22 04:23
@pmhofman Can you let us know the node and npm version you are using. Usually, we recommend node 8.9.1 LTS. see https://github.com/ballerina-platform/ballerina-lang/tree/master/composer

**Comment by roonyh** [comment] 2018-06-22 14:43
@pmhofman Thanks for the info. `--no-save` is for asking npm to not add the installing module to dependencies section of the `package.json` file. I don't think it affects the `package-lock.json`.

`package-lock.json` being empty is a bit unusual case. It can't happen due to `npm install` crashing. But it could happen if the postinstall script crashes. In that case it should print an error to the console. If you managed to reproduce this issue could you look for such an error printed to the console?

**Comment by pmhofman** [comment] 2018-06-22 21:04
I am using npm 5.6.0 and node v8.11.3

on package-lock.json:
https://docs.npmjs.com/cli/install states:

> Further, if you have an npm-shrinkwrap.json or package-lock.json then it will be updated as well.

Maybe my conclusion might be wrong that --no-save will prevent updates not only on package.json but also on npm-shrinkwrap.json and package-lock.json 
I have asked support@npmjs.com to clarify this.
I do not expect a reply before next monday.

**Comment by pmhofman** [comment] 2018-06-23 08:57
Here is a copy of my question to npm, with the response:
	
CJ Joulain (npm)
Jun 22, 14:24 PDT

Hi Peter,

Thanks for reaching out!

Yes, the npm install option --no-save command should prevent updates on npm-shrinkwrap.json and package-lock.json?

Alternately, you can also try --no-package-lock to prevent it from being written to the package-lock, but still update the package.json.

Best wishes,
CJ


Peter Hofman
Jun 22, 14:02 PDT

Hi,

quick question that I could not answer from the documentation, since it is not clearly stated:

does npm install option --no-save prevent updates on npm-shrinkwrap.json and package-lock.json?

Best regards,

Peter Hofman

**Comment by roonyh** [comment] 2018-06-25 05:13
@pmhofman `--no-save` is used when installing a specific module to avoid adding it to `package.json`. eg: `npm install --no-save react` will install the react package but an entry to the [dependencies section](https://docs.npmjs.com/files/package.json#dependencies) of package.json won't be added for react. As opposed to running `npm install react` which will add react as an dependency to this section. As package json is not updated package-lock too will not be updated. But when running just `npm install` this option has no effect.

We considered `--no-package-lock` but didn't used it for two reasons.

1) It doesn't even read the packge-lock file. What we want is the build to read package-lock and install modules accordingly but not write to it. The writing may change the existing content of package-lock file because of inconsistencies in different npm (5.x.x) versions. We noticed that our developers have different npm versions and un intended changes happen to package-lock file in some commits

2) It was introduced in some 5.x.x version of npm and older npm versions will give an error if used.

So the option that we had is to preserve the content of package-lock file when running *`mvn install`*. By backing it up before the build and then wrtitng it back after the build. The javascript developers still should be able to allow necessary changes to package-lock by running `npm install`.

The other option is to make sure that everyone is using a newer npm version by detecting its version and showing and error for older ones but we preferred the above.

**Comment by pmhofman** [comment] 2018-06-29 10:32
Developers can easily install multiple versions of `node` and `npm` and switch between them with `nvm`. You could even build that into the `pom.xml`, making `node` and `npm` dependencies of the project. Then everyone building ballerina will use the same `node` and `npm` version.

Anyways, I figured out I may have caused the error myself, which means this is not really a problem.

**Comment by roonyh** [comment] 2018-06-29 11:12
Yeah. We need to figure out something that works for both the JS and non-JS developers.
We are considering mandating a certain node and npm version and showing an error if the versions are too old.
I'll close this issue for now since the build is working now. If the issue comes up again please reopen.
Thanks a lot for the report.

**Closed by roonyh** 2018-06-29 11:12 UTC
Labels: Component/Composer, Type/Bug
