### ISSUE TITLE
Node Transformer fails incomplete source

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#24944] opened 2020-07-26 16:19 UTC
**Description:**
Consider the following source 

```
import ballerina/auth;
import ballerina/http;

auth:OutboundBasicAuthProvider basicAuthProvider = new({ username: "postman", password: "password" });
http:BasicAuthHandler basicAuthHandler = new(basicAuthProvider);

http:ClientConfiguration conf = {
//    url: "https://postman-echo.com/basic-auth",
   auth: {
       authHandler: basicAuthHandler
   }
};

function testFunction () {
    http:Client httpClient = new ("http://localhost:8080", config = conf );
    _ = httpClient->
}
```

For the above incomplete source, following exception is thrown,

```
Caused by: java.lang.ClassCastException: org.wso2.ballerinalang.compiler.tree.statements.BLangWorkerSend cannot be cast to org.wso2.ballerinalang.compiler.tree.expressions.BLangExpression
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createExpression(BLangNodeTransformer.java:3771)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:2284)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.AssignmentStatementNode.apply(AssignmentStatementNode.java:58)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.generateAndAddBLangStatements(BLangNodeTransformer.java:3682)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1325)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.FunctionBodyBlockNode.apply(FunctionBodyBlockNode.java:59)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.createFunctionNode(BLangNodeTransformer.java:1206)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:1163)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.FunctionDefinitionNode.apply(FunctionDefinitionNode.java:71)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:505)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:418)
	at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
	at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:443)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:144)
	at org.wso2.ballerinalang.compiler.parser.Parser.parseNew(Parser.java:117)
	at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:500)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:380)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:137)
	at org.ballerinalang.langserver.compiler.LSModuleCompiler.compilePackagesSafe(LSModuleCompiler.java:291)
	... 11 more

```

**Comment by SupunS** [comment] 2020-07-30 04:09
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/24944?

**Comment by MaryamZi** [comment] 2020-08-14 09:40
Related to #24849.

**Closed** 2021-03-10 09:41 UTC
Labels: Area/AST, Area/Compiler, CompilerSLDump, Priority/Blocker, SwanLakeDump, Team/CompilerFE, Type/Bug
