### ISSUE TITLE
[Composer] Design view is not getting loaded when trying out with "try catch block"

### ISSUE THREAD

**Issue by chalitha87** [ballerina-platform/ballerina-lang#8086] opened 2018-04-25 16:32 UTC
**Description:**
Design view is not getting showed when we try out with try catch block

**Steps to reproduce:**
Open the blob type .bal file
Add a try catch block in the design view.
Then design is disappeared and below error showed in the UI.
(attached a screenshot)

**Affected Versions:**
ballerina-tools-0.970.0-beta15-SNAPSHOT.

**OS, DB, other environment details and versions:**
macOS High Sierra
ballerina-tools-0.970.0-beta15-SNAPSHOT
JDK 1.8.0_152

**Suggested Labels (optional):**
Type/Bug
Severity/Blocker
Priority/High
Affected/ballerina-tools-0.970.0-beta15-SNAPSHOT

<img width="832" alt="screen shot 2018-04-25 at 10 01 06 pm" src="https://user-images.githubusercontent.com/14923354/39259511-35d92650-48d4-11e8-9519-f6d555fb9bfc.png">

**Comment by dilinisg** [comment] 2018-04-25 16:35
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/8058

**Closed by dilinisg** 2018-04-25 16:35 UTC
Labels: component/Composer
