### ISSUE TITLE
Compilation failed with error: failed to load the module 'ballerina/task:2.0.0-beta.2' from its BIR

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-lang#31592] opened 2021-07-06 06:32 UTC
**Steps to reproduce:**

We can reproduce with below code.

```ballerina
import ballerinax/mysql as _;
import ballerina/http as _;
```

**Affected Versions:**
slbeta2

**Comment by azinneera** [comment] 2021-07-06 06:50
**Condition:**
The beta2 version of mysql is not pushed to central yet and thus it pulls the mysql `beta1.1` by default.

**Cause:**
When resolving transitive dependencies, the build fails with the following error which is caused by the `time` package.
`error: failed to load the module 'ballerina/task:2.0.0-beta.2' from its BIR`

In this scenario, `http` depends on `time-2.0.0-beta.1` whereas `mysql` depends on `time-2.0.0-beta.2`. When resolving transitive dependencies in the dependency graph, intermittenty the `time-2.0.0-beta.1` is picked.

https://github.com/ballerina-platform/ballerina-lang/blob/a1691ea0a24d1f66db5f5e3f1b67202d38128d4a/compiler/ballerina-lang/src/main/java/io/ballerina/projects/internal/PackageDependencyGraphBuilder.java#L238-L239

Here, if the older version of the dependency is first resolved, when the new version is checked, the condition evaluates to false.  This is because the key of the `vertices` map does not consider the version. It only contains the org name and the package name.

**Comment by tennengabr** [comment] 2021-07-07 05:07
Same is happening with error: failed to load the module 'ballerina/auth:1.1.0-beta.1' from its BIR

**Comment by azinneera** [comment] 2021-07-08 07:46
@tennengabr the root cause is the same for both. We will fix it for the next release.

**Comment by azinneera** [comment] 2021-09-08 18:42
This is fixed with the package resolution refactor.

**Closed by azinneera** 2021-09-08 18:42 UTC
Labels: Type/Bug, Priority/Blocker, Team/DevTools, Points/0.5, Area/ProjectAPI
