### ISSUE TITLE
Compiler crash for invalid code

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#25871] opened 2020-09-17 08:23 UTC
**Description:**
```ballerina
public function x() {

    var func = () => { a.getI(); };
    int i = func();
    assertEquality(1, i);
}
```

```
 jballerina-test > org.ballerinalang.test.expressions.lambda.FunctionPointersTest > setup FAILED
    java.lang.ClassCastException: io.ballerinalang.compiler.syntax.tree.ListBindingPatternNode cannot be cast to io.ballerinalang.compiler.syntax.tree.CaptureBindingPatternNode
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:545)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:435)
        at io.ballerinalang.compiler.syntax.tree.ModuleVariableDeclarationNode.apply(ModuleVariableDeclarationNode.java:67)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:530)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.transform(BLangNodeTransformer.java:435)
        at io.ballerinalang.compiler.syntax.tree.ModulePartNode.apply(ModulePartNode.java:54)
        at org.wso2.ballerinalang.compiler.parser.BLangNodeTransformer.accept(BLangNodeTransformer.java:460)
        at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnitNew(Parser.java:126)
        at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:99)
        at org.wso2.ballerinalang.compiler.PackageLoader.parse(PackageLoader.java:490)
        at org.wso2.ballerinalang.compiler.PackageLoader.loadEntryPackage(PackageLoader.java:377)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:156)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:508)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:495)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:712)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:611)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:599)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:592)
        at org.ballerinalang.test.util.BCompileUtil.compileOnJBallerina(BCompileUtil.java:677)
        at org.ballerinalang.test.util.BCompileUtil.compile(BCompileUtil.java:109)
        at org.ballerinalang.test.expressions.lambda.FunctionPointersTest.setup(FunctionPointersTest.java:42)
```

**Steps to reproduce:**

Current master (as of commit id: 691b6d5)
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by mohanvive** [comment] 2021-01-27 04:10
Closing the issue because above issue is not reproducible in the master.

**Closed by mohanvive** 2021-01-27 04:10 UTC
Labels: Area/AST, Area/Parser, CompilerSwanLakeDump, Team/CompilerFE, Type/Bug
