### ISSUE TITLE
[Bug]: Bad sad error occurs when the CompilerPlugin.toml is empty

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-lang#42120] opened 2024-02-06 11:32 UTC
### Description

Steps to reproduce

```
Create a Ballerina project that contains both Ballerina and native packages with a `CompilerPlugin.toml`.
Commented the content in the `CompilerPlugin.toml`
Then build the project using `./gradlew clean build`
```

Bad sad error is

```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2024-02-06 16:51:51,836] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at io.ballerina.projects.JBallerinaBalaWriter.addCompilerPlugin(JBallerinaBalaWriter.java:121)
        at io.ballerina.projects.BalaWriter.populateBalaArchive(BalaWriter.java:135)
        at io.ballerina.projects.BalaWriter.write(BalaWriter.java:108)
        at io.ballerina.projects.JBallerinaBackend.emitBala(JBallerinaBackend.java:244)
        at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:221)
        at io.ballerina.cli.task.CreateBalaTask.execute(CreateBalaTask.java:79)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.PackCommand.execute(PackCommand.java:256)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
 


```

### Related area

-> Compilation

**Comment by Shadow-Devil** [comment] 2024-10-03 14:45
Hi, I already added a PR for a duplicate of this issue.
PR: #43426 
Duplicate: #41418

Could you please assign this issue to me and does this still count towards the Hacktoberfest?
Thank you :)

**Comment by azinneera** [comment] 2024-10-04 18:41
> Hi, I already added a PR for a duplicate of this issue. PR: #43426 Duplicate: #41418
> 
> Could you please assign this issue to me and does this still count towards the Hacktoberfest? Thank you :)

Hi @Shadow-Devil 

Yes we can apply it for Hacktoberfest :)

**Comment by gimantha** [comment] 2024-10-10 05:14
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/43426

**Closed by gimantha** 2024-10-10 05:14 UTC
Labels: Type/Bug, Team/DevTools, Fix/Crash, Area/CLI-BuildTools, Hacktoberfest, Credits/30
