### ISSUE TITLE
On fail variable reference is seen as undefined when debugged

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-lang#28190] opened 2021-01-25 09:03 UTC
**Description:**

![image](https://user-images.githubusercontent.com/15815199/105671958-9a1f0280-5f09-11eb-9aea-1e1042854c5f.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pcnfernando** [comment] 2021-01-25 09:49
Noticed that if you do not use the variable within the on fail clause, when debugged, we can evaluate the reference successfully.
![onFailVarVisible](https://user-images.githubusercontent.com/15815199/105689312-96e34100-5f20-11eb-9ec3-a78487d7422d.gif)

**Comment by NipunaRanasinghe** [comment] 2021-01-25 09:59
@pcnfernando Thanks for reporting and we'll look into this. In the meantime, it would be great if you can attach the reproducible  source code snippet.

**Comment by praveennadarajah** [comment] 2021-07-05 05:31
@lafernando The above reported issue not reproducible in the latest master. We have tested this scenario in the `slbeta2 RC4` pack.
```
Ballerina Swan Lake Beta 2
Language specification 2021R1
Update Tool 1.3.5
```

Tested code sample:
```
import ballerina/io;

public function main() returns error? {
    int i = 0;
    retry {
        io:println("Retrying...");
        i += 1;
        fail error error:Retriable("Execution Error");
    } on fail error e {
        io:println("Error caught: ", e.message());
    }
}
```

<img width="1112" alt="Screen Shot 2021-07-05 at 10 45 36 AM" src="https://user-images.githubusercontent.com/11292766/124421700-a5f7d600-dd7f-11eb-9c8d-b3d93eee656b.png">

Since the issue is not reproducible, we are closing this issue. Feel free to reopen this issue if you have any queries.

**Closed by praveennadarajah** 2021-07-05 05:31 UTC
Labels: Area/Debugger, SwanLakeDump, Team/DevTools, Type/Bug
