### ISSUE TITLE
NPE when referencing an abstract object type from a different package, without the package name prefix

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#11651] opened 2018-11-22 10:46 UTC
**Description:**
$Subject. This happens when the package of the referenced type has been missed. Ideally there should have been a compilation error instead of an NPE.

eg:
NPE scenario
```ballerina
public type Client client object {
    *AbstractSQLClient;
```
Working scenario
```ballerina
public type Client client object {
    *sql:AbstractSQLClient;
```

The exception
```bash
[WARNING] 
java.lang.NullPointerException
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit (SemanticAnalyzer.java:430)
    at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept (BLangSimpleVariable.java:54)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode (SemanticAnalyzer.java:1580)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode (SemanticAnalyzer.java:1547)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef (SemanticAnalyzer.java:1539)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$13 (SemanticAnalyzer.java:349)
    at java.util.ArrayList.forEach (ArrayList.java:1257)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit (SemanticAnalyzer.java:349)
    at org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode.accept (BLangObjectTypeNode.java:70)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode (SemanticAnalyzer.java:1580)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode (SemanticAnalyzer.java:1547)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef (SemanticAnalyzer.java:1539)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit (SemanticAnalyzer.java:337)
    at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept (BLangTypeDefinition.java:122)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode (SemanticAnalyzer.java:1580)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode (SemanticAnalyzer.java:1547)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef (SemanticAnalyzer.java:1539)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$4 (SemanticAnalyzer.java:257)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:418)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit (SemanticAnalyzer.java:257)
    at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept (BLangPackage.java:159)
    at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze (SemanticAnalyzer.java:237)
    at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck (CompilerDriver.java:183)
    at org.wso2.ballerinalang.compiler.CompilerDriver.compile (CompilerDriver.java:140)
    at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol (CompilerDriver.java:132)
    at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage (CompilerDriver.java:101)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:418)
    at org.wso2.ballerinalang.compiler.Compiler.compilePackages (Compiler.java:161)
    at org.wso2.ballerinalang.compiler.Compiler.compilePackages (Compiler.java:171)
    at org.wso2.ballerinalang.compiler.Compiler.build (Compiler.java:92)
    at org.ballerinalang.stdlib.utils.GenerateBalo.genBalo (GenerateBalo.java:102)
    at org.ballerinalang.stdlib.utils.GenerateBalo.main (GenerateBalo.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)

```

**Comment by SupunS** [comment] 2018-11-27 05:48
I could not reproduce the exact issue. However fixed the related test cases and added some more tests.

**Comment by SupunS** [comment] 2018-11-27 08:34
Closing the issue, since it is fixed. Please reopen if you encounter the issue again.

**Closed by SupunS** 2018-11-27 08:34 UTC
Labels: Component/Compiler, L1/L2 for December, Type/Bug
