### ISSUE TITLE
The HTTP service snippet creates a listener with port 0

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#35123] opened 2022-02-18 12:32 UTC
Refer to the following. The generated code generates a listener with `0` as the port. Shouldn't this port be set to something like `8080` or `9090`?

https://user-images.githubusercontent.com/6260009/154683419-8d30eb98-0119-4ce1-83b4-0a0684107d27.mov

**Comment by nadeeshaan** [comment] 2022-02-21 01:52
Duplicate of #34724. Hence closing.

**Closed by nadeeshaan** 2022-02-21 01:52 UTC
Labels: Type/Improvement, Status/Duplicate, Team/LanguageServer
