### ISSUE TITLE
[Improvement]: Support parallel test execution for testerina

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/ballerina-lang#39814] opened 2023-03-07 10:58 UTC
### Description

Currently the Testerina supports the test execution in a sequential manner. Executing tests in a parallel manner reduce the time requirement. 

### Related area

-> Test Framework

**Comment by azinneera** [comment] 2023-03-13 12:29
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/24643

**Closed by azinneera** 2023-03-13 12:29 UTC
Labels: Type/Improvement, Team/DevTools, Area/TestFramework
