### ISSUE TITLE
Code snippets style is differentiated in the suggestion help and hover support.

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#29553] opened 2021-03-24 03:24 UTC
**Description:**
Please refer to the following

<img width="713" alt="Screenshot 2021-03-23 at 11 12 11 PM" src="https://user-images.githubusercontent.com/12771261/112249755-4d904300-8c7e-11eb-9f4f-a2f47798e528.png">

**Affected Versions:**
SLAlpha3

**Comment by nadeeshaan** [comment] 2021-04-06 07:02
Duplicate of #29547. Hence closing the issue.

**Closed by nadeeshaan** 2021-04-06 07:02 UTC
Labels: Area/Parser, Status/Duplicate, Team/CompilerFE, Type/Bug
