### ISSUE TITLE
[LS] Go to definitions/rename doesn't work for user defined error types

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-lang#29276] opened 2021-03-17 09:21 UTC
**Description:**
When we have a user defined error type and it is being used in several locations, `goto definition`, `find all references` and `rename` doesn't work for them.

**Steps to reproduce:**
Create any user defined error type and return an instance of that in any method. Try finding occurrences or renaming that error type. 

**Affected Versions:**
SLA 2

**Suggested Labels (optional):**
Language server, Semantic API, Tooling

**Comment by IMS94** [comment] 2021-05-20 09:04
Blocked by #30688

**Comment by IMS94** [comment] 2021-05-25 08:33
Relates to #29232

**Comment by pubudu91** [comment] 2021-10-29 19:25
Checked with Chiran's PR for the following sample:
```ballerina
type MyError error;

function foo() returns MyError|int|() {
    return error MyError("ERROR");
}
```
Find all refs and renaming worked. But goto def didn't. Tried with the code snippet in #29232 as well. Goto def worked with distinct error, but not for cases like the above.

**Comment by IMS94** [comment] 2021-11-01 04:23
@pubudu91 That means, can we consider this has been unblocked?

**Comment by pubudu91** [comment] 2021-11-01 06:49
> @pubudu91 That means, can we consider this has been unblocked?

Once Chiran's PR is merged, yes.

**Comment by IMS94** [comment] 2021-11-01 07:29
@pubudu91 Thanks! Can you mention that PR here as well?

**Comment by nadeeshaan** [comment] 2021-11-23 11:37
After merging #31845 renaming is working. Goto definition is still not working.

**Comment by pubudu91** [comment] 2021-11-23 13:29
> After merging #31845 renaming is working. Goto definition is still not working.

Is that an issue in Semantic API side or LS side?

**Comment by nadeeshaan** [comment] 2021-12-01 04:51
> > After merging #31845 renaming is working. Goto definition is still not working.
> 
> Is that an issue in Semantic API side or LS side?

Basically the issue is because of https://github.com/ballerina-platform/ballerina-lang/issues/30688

**Comment by pubudu91** [comment] 2022-02-10 08:24
> ```ballerina
> type MyError error;
> 
> function foo() returns MyError|int|() {
>     return error MyError("ERROR");
> }
> ```

The above case also works on 2201.0.0. Hence closing this.

**Closed by pubudu91** 2022-02-10 08:24 UTC
Labels: Type/Bug, Priority/High, Status/Blocked, Team/LanguageServer, Team/CompilerFETools, Area/SemanticAPI, SwanLakeDump, Area/Rename
