### ISSUE TITLE
[Bug]: The `Create variable with type` code action fails to import the relevant modules

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#42482] opened 2024-04-05 05:34 UTC
### Description

Check the video.

https://github.com/ballerina-platform/ballerina-lang/assets/6178058/85add4fc-2628-44fb-8a5c-d6c4be2a5e67

### Related area

-> Compilation

**Comment by nipunayf** [comment] 2024-04-05 05:48
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/41460, and the fix is added to U9.

However, the create variable CA does not yet support module imports, so this feature has yet to be implemented.

**Closed** 2024-04-26 07:02 UTC
Labels: Type/Bug, Priority/High, Team/LanguageServer, Area/CodeAction
