### ISSUE TITLE
Getting incorrect package during the compilation

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-lang#32076] opened 2021-08-09 14:09 UTC
**Description:**
When building the MySQL ballerina project with the latest distribution pack(SL-beta3-SNAPSHOT), getting the following error:

```
ERROR [ballerina/sql/0.6.0-beta.2::client.bal:(75:49,75:63)] incompatible types: expected '(record {| record {| anydata...; |} value; |}|ballerina/sql:0.6.0-beta.2:Error)', found '(record {| record {| anydata...; |} value; |}|ballerina/sql:0.6.0-beta.2:Error)?'
```
Dependency.toml has Mysql-0.7.0-beta.2 and  sql-0.6.0-beta.2. The sql-0.6.0-beta.2 doesn't support nil but it takes value with nil completion during the compilation because of [the latest SQL API changes](https://github.com/ballerina-platform/module-ballerina-sql/pull/315) in the distribution SQL package. Therefore this project compiles with a distribution SQL pack.

**Steps to reproduce:**
Build the following project with SL-beta.2, which will succeed because this pack has sql-beta.2. Then, 
build this project again with the latest ballerina package which is getting from the distribution(SL-beta3-SNAPSHOT).

Ballerina project:  https://drive.google.com/file/d/1dNnCg7j7tW8eAEj_crcmpjd6h5KQFal_/view?usp=sharing

**Affected Versions:**
SL-beta3-SNAPSHOT

**Comment by MaryamZi** [comment] 2021-09-09 04:00
IIUC, you're trying to build a project with beta2 dependencies using beta3.

This particular error seems to occur at https://github.com/ballerina-platform/module-ballerina-sql/blob/v0.6.0-beta.2/sql-ballerina/client.bal#L75.

```ballerina
stream<record {}, Error> errorStream = new (resultIterator);
```

Where `resultIterator` is an object value created using the [`ResultIterator`](https://github.com/ballerina-platform/module-ballerina-sql/blob/6f2a1fe9e6a2685d1b94c19fc4be1a15d95b2729/ballerina/types.bal#L1315) class, in which the `next` method has the following signature.

```ballerina
    public isolated function next() returns record {|record {} value;|}|Error?
```

Since the `next` method's return type is `record {|record {} value;|}|Error?`, the type of stream this creates is `stream<record {}, Error?>`.

So `stream<record {}, Error> errorStream = new (resultIterator);` should result in a compilation error. There was [bug](https://github.com/ballerina-platform/ballerina-lang/issues/31464) up to beta2 where this did not result in a compilation error. This has been fixed for beta3 (without the fix it could crash at runtime). So any dependency/code that relied on the incorrect behaviour will now fail on beta3. IMO, the behaviour you are observing is expected.

**Comment by azinneera** [comment] 2021-09-09 05:03
Closing this is the expected behavior. @kalaiyarasiganeshalingam please re-open if needed.

**Closed by azinneera** 2021-09-09 05:03 UTC
Labels: Type/Bug, Points/1, Area/ProjectAPI
